### ISSUE TITLE
Intra-group regular segmented scans crash the code generator

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1007]
Of course, this is hard to test for since #697 is still outstanding...

The root problem is simple enough: we wish to treat the regular segmented scan as an ordinary scan with a different operator that is segment-aware, but we can't just index the multi-dimensional output array as if it were single-dimensional (or at least, we have to flatten the index functions first).

**Comment by Munksgaard** [comment]
Do you have a test case?

**Comment by athas** [comment]
`map (map (scan (+) 0))`
