### ISSUE TITLE
An attribute for warning on safety checks

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1023]
We need an attribute that you can put on an expression, which will make the compiler issue a warning if it is unable to remove all safety checks inside it.  What's a good name for it?  `#[warn_on_checks]`?

**Comment by Munksgaard** [comment]
I like it, although I think `#[warn_on_safety_checks]` would be a bit more descriptive.

**Comment by athas** [comment]
What about `#[warn(safety_checks)]`?  I can imagine that we'll eventually want other kinds of opt-in warnings.

**Comment by Munksgaard** [comment]
:+1:
