### ISSUE TITLE
Internal compiler error while building futracer

### ISSUE THREAD

**Issue by gabriel-fallen** [diku-dk/futhark#1025]
Hello! I'm trying to build https://github.com/nqpz/futracer (actually my fork https://github.com/gabriel-fallen/futracer because I had to replace `unsafe` with `#[unsafe]`).

I'm running `make` and getting this message:

```
futhark pyopencl --library futracerlib.fut
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'extract kernels':
In function render_triangles_raw
When checking function body
In expression of statement {[w_7044][h_7045]i32 res_7530}
In expression of statement {[w_7044][h_7045]i32 res_8511}
In expression of statement {[w_7044][h_7045]i32 res_8516}
In expression of statement {[n_total_8515][lifted_0_rect_pixel_indices_arg_8841]i32 res_8848,
 [n_total_8515][lifted_0_rect_pixel_indices_arg_8841]i32 res_8849}
In expression of statement {[n_total_8515][lifted_0_rect_pixel_indices_arg_8841]i32 res_14208}
In expression of statement {[lifted_0_rect_pixel_indices_arg_8841]i32 res_14234}
In subexp res_9261
Use of unknown variable res_9261.
Makefile:6: recipe for target 'futracerlib.py' failed
make: *** [futracerlib.py] Error 2
```

I'm not familiar with Futhark internals at all, so I have no idea what it means and why it occurs, but hopefully you can fix it or send me into direction of a workaround.

I'm using Futhark freshly pulled and built from source with `stack install`.

**Comment by Munksgaard** [comment]
Hi @gabriel-fallen, thank you for your bug report. 

I believe I've narrowed the problem down to commit 6161f1c14c9ee6fece610a09cd49bae2d71a36ec. I will try to investigate further.

**Comment by athas** [comment]
Thanks, I can reproduce.  This is almost certainly related to the recent switch to the new flattening algorithm.

**Comment by athas** [comment]
This is due to a change to `leavingNesting`, which used to have some fairly gross hacks to handle irregular nested parallelism.  They were removed because I thought they were no longer necessary (and none of our tests appeared to hit them).

**Comment by gabriel-fallen** [comment]
If you could direct me in a way of a fix or workaround I would try to "modernize" futracer (though there are kinda lots of pretty involved code from my perspective of just starting with Futhark :smiley: ).

**Comment by gabriel-fallen** [comment]
Though Futhark compiler not crashing and giving a bit more informative error message would be nice to have anyway... :)

**Comment by gabriel-fallen** [comment]
And while I'm talking to you I'll take an opportunity to say how much I admire Futhark. I think it's a brilliant language from the language design perspective. And I'm deeply impressed with the level of compiler optimizations and the resulting code performance.

My humble opinion. :smiley:

**Comment by athas** [comment]
Futracer is fine and should not need modification (well, you can argue that its fundamental algorithmic approach is a bad idea, but it's a valid Futhark program).  The error message here is bad because it's an internal compiler bug - those are *our* fault, and by definition not user-oriented.  It told you to report the bug, and you did, so it served its purpose!

And thanks for your kind words!

**Comment by gabriel-fallen** [comment]
I had to update futracer anyway to use `#[unsafe]` attribute instead of `unsafe` keyword which was deprecated and apparently removed (you should probably reflect that in documentation BTW :wink: ). So I thought this internal error might be triggered by some implementation-reliant "hacks" that need to be reworked. If that's not the case I'll just relax and wait while you fix the bug in the compiler. :smiley:

**Comment by gabriel-fallen** [comment]
WOW, that was fast! :smiley: 

I can confirm, the bug is gone. Thanks a lot!
