### ISSUE TITLE
Optimising scalar computation interspersed between GPU operations

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1045]
Consider an implementation of Gaussian elimination:

```futhark
  let gauss_jordan [m] [n] (A:[m][n]t) =
    loop A for i < i32.min m n do
    -- Find nonzero value.
    let j = A[i:,i] |> map T.abs |> argmax |> (.1) |> (+i)
    let f = T.((i32 1-A[i,i]) / A[j,i])
    let irow = map2 (T.fma f) A[j] A[i]
    in tabulate m (\j ->
                     let f = T.negate A[j,i]
                     in map2 (\x y -> if j == i then x else T.fma f x y)
                             irow A[j])
```

`argmax` is a reduction.  The problem here is that we copy the scalar `j` from the GPU to the host just to compute the scalar `f` (which also involves copying twice from `A` to the host!), which is then immediately used in more GPU operations.  This is wasteful.  Indeed, most of this program's runtime is spent copying those scalars around.  It would be much better if we just did those operations on the GPU instead.  I can think of two ways of accomplishing this.

### 1. Extending SegRed with a postlude operator

When the SegRed that implements `argmax` writes the final result, it does in principle have the opportunity to do an arbitrary amount of scalar computation before actually writing it.  We could extend SegReds with a "postlude operator" that is applied to the final result(s) before they are written.  A bottom-up compiler pass would then identify SegRed results that are used in subsequent arithmetic operations and do a kind of backward fusion to move it into this postlude operator.  SegReds already return their results as single-element arrays (that is, GPU-resident), so this would fairly elegantly reduce the amount of needed CPU-GPU communication.  This could also be added to SegScan, giving us the ability to fuse `scan` into `map`.

### 2. Adding a "device code" block construct

We could extend the Kernels IR with a construct that contains a Body and indicates that this Body should be run as a single-thread GPU kernel.  This would allow us to fairly easily migrate code to the GPU to cut down on communication costs.

**Comment by PhilipBorgesen** [comment]
For the record I have begun looking into this issue and intend to develop a patch over the next months.
