### ISSUE TITLE
Inconsistent c-types for tuples with type synonyms

### ISSUE THREAD

**Issue by FluxusMagna** [diku-dk/futhark#1047]
Take for example

```
type pair = (i32, i32)

entry fromPairs (ps:[]pair) = unzip ps
entry toPairs (as:[]i32) (bs:[]i32) : []pair = zip as bs
```
When compiled to a library it produces the entries
```
int futhark_entry_toPairs(struct futhark_context *ctx,
                          struct futhark_opaque_4ba7e2ad **out0, const
                          struct futhark_i32_1d *in0, const
                          struct futhark_i32_1d *in1);
int futhark_entry_fromPairs(struct futhark_context *ctx,
                            struct futhark_i32_1d **out0,
                            struct futhark_i32_1d **out1, const
                            struct futhark_opaque_arr_pair_1d *in0);

```
For the case where tuple is taken as input, the name of the type is given by the type synonym, but when returned it takes the seemingly random name as regular tuples do. 

Note that the compiler does not complain about opaque types in this case, as it would if an unusable type is introduced normally. Without casting, there is no way to use either pointer.

I think the preferable solution to this would be to use any explicit type signatures to determine the type name, and make sure that each type in the c-code is usable. Based on the observed behavior, I assume that it currently compares the Futhark representations which would be the same for both, despite the different types in the c-header.

**Comment by Munksgaard** [comment]
How did you compile this, and with what version? Using the latest master and compiling with `futhark opencl --library pair.fut`, I get the following code in my header file:

``` c
int futhark_entry_fromPairs(struct futhark_context *ctx,
                            struct futhark_i32_1d **out0,
                            struct futhark_i32_1d **out1, const
                            struct futhark_opaque_arr_pair_1d *in0);
int futhark_entry_toPairs(struct futhark_context *ctx,
                          struct futhark_opaque_arr_pair_1d **out0, const
                          struct futhark_i32_1d *in0, const
                          struct futhark_i32_1d *in1);
```

Which does what you want, right?

**Comment by Munksgaard** [comment]
Ah, but the structs are still opaque, I guess.

**Comment by athas** [comment]
Like @Munksgaard, I also get consistent types for the two entry points, both when using the latest release and the nightly version.

**Comment by FluxusMagna** [comment]
My bad, I used 0.15.3. Nice to hear it's been fixed already.

**Comment by athas** [comment]
Good to hear!
