### ISSUE TITLE
Compiler error while running fulthark test

### ISSUE THREAD

**Issue by n-hansen** [diku-dk/futhark#1053]
Hello,

I get the following failure when running a test via `fulthark test`
```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'Inline functions':
In function test_single_step_trail
Type error:
trail_map_10778 was invalidly consumed.
Nothing can be consumed here.
```

The triggering test is [here](https://github.com/n-hansen/slime-mold/blob/1bc72863fe53d2a94d9d396984697b07d905c0dc/slime_test.fut#L61-L81); module being tested is in the same repo. I'm not sure I understand Futhark's type system well enough to say with certainty if this is me sneaking an unsound program past the typechecker or a bug in the compiler, but the function does seem to execute as expected at the REPL, for what it's worth.

Apologies for the messy code/example, I'll see if I can get down to a cleaner reproduction tomorrow.

**Comment by athas** [comment]
No, your program is fine.  The compiler screws up something in inlining, which is far too late for any source-program defects to still be around.

**Comment by athas** [comment]
Oh, wait, actually there might be a bug in the type checker.  I don't think your `reduce_by_index` should be allowed, since the `env` value is not passed as a unique parameter.  Something in the type checker may be turning something more unique than it is supposed to be.

**Comment by athas** [comment]
You'll need to `copy` the first argument to `reduce_by_index`.  I'll tighten up the type checker.
