### ISSUE TITLE
OpenCL backend miscompilation

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1054]
```futhark
-- ==
-- input { [0x2b28ab09u32, 0x7eaef7cfu32, 0x15d2154fu32, 0x16a6883cu32] }
-- auto output

let blk_transpose (block: [4]u32) : [4]u32 = #[sequential] map (\i ->
    let offset = u32.i32 (3-i)<<3
    in    (((block[0] >> offset) & 0xFF) << 24)
        | (((block[1] >> offset) & 0xFF) << 16)
        | (((block[2] >> offset) & 0xFF) << 8)
        | ((block[3] >> offset) & 0xFF)) (iota 4)

let main (key: [4]u32) : [11][4]u32 =
  map blk_transpose (loop w = [key] for _i < 10i32 do (w ++ [key])) :> [11][4]u32
```

**Comment by athas** [comment]
Looks like it's the size ascription (and the Reshape it gives rise to) that produces a bad index function for the result.

**Comment by michael-elkh** [comment]
The issue seems to come from the sequential attribute. The issue goes away when I remove it.

**Comment by athas** [comment]
It's actually linked to any kind of size coercion of a column-major array (and Futhark stores the result of the `map` in column-major when the innermost `map` is sequential, to optimise the memory access pattern).  This is the simplest case that reproduces the problem, in all backends:

```
let main [n] [m] (xss: [n][m]i32) =
  transpose xss :> [2][3]i32
```

I think I have a fix for it, but I'll need to run some thorough tests, as I am super paranoid about all change we make to the array representation level.
