### ISSUE TITLE
Bad results with byte rotation on u32

### ISSUE THREAD

**Issue by michael-elkh** [diku-dk/futhark#1056]
Hi,
I tried to do a byte rotation on a u32, but I get a bad result with a vector member, but if a use a constant instead, I get the right result.

Some example (I tried to remove the bloat): https://github.com/michael-elkh/futhark_issue_vector
With a rotation of 0 byte to the left, I get the following result : 
```
0x32_88_31_e0
0x32_88_31_e0
0xff_ff_ff_ff
0xff_ff_ff_ff
```
All lines should be the same.
A partial part of the futhark code : 
```
....
let rot_word (word: u32) (n: u32) : u32 = (word << (n<<3)) | (word >> ((4-n)<<3)) -- Rotate left
....
let s0 : u32 = rot_word 0x32_88_31_e0 0 -- Rotate the constant of 0 byte to the left
let s1 : u32 = vec4.get 0 s -- Get the value for example, same as constant
let s2 : u32 = rot_word (vec4.get 0 s) 0 -- Rotate the value of 0 to the left -- should be the same as s0
let s3 : u32 = ((vec4.get 0 s) << 0) | ((vec4.get 0 s) >> (4<<3)) -- Same but without a function
```
I'm on 0.16.1 btw.
Thank you

**Comment by athas** [comment]
I get an interesting warning when I run the generated code:

```
f_example.c:683:14: runtime error: shift exponent 32 is too large for 32-bit type 'unsigned int'
```

Futhark is intentionally/unfortunately a bit loose with the semantics of some arithmetic operations, and bitshifts in particular do whatever the target platform does.  In C, shifts larger than the number of bits in the type is undefined behaviour.

**Comment by athas** [comment]
Correction: it's shifts *equal to* or larger that are undefined, and this program right-shifts 32-bit integers 32 bits.  On x86, shifts are done modulo 32, so this will have no effect.  I wouldn't be surprised if many GPUs do the same thing.

**Comment by michael-elkh** [comment]
I see, I updated my code, to stay in [0;32[, and it works.
Thanks

**Comment by athas** [comment]
I'll document this issue.  It's quite a wart on an otherwise supposedly-safe language, but I think the overhead of imposing stricter semantics (or raising run-time errors) might be unacceptably high, because bit shifts tend to occur most frequently in the innermost parts of well tuned algorithms.
