### ISSUE TITLE
Incorrect NaN comparisons in interpreter

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1070]
```futhark
> f32.nan == f32.nan
false
```

Looks like this is because we are using Haskell-derived comparison operators, which do the wrong thing.

**Comment by FluxusMagna** [comment]
> ```futhark
> > f32.nan == f32.nan
> false
> ```
> 
This is actually correct behaviour, the problem is with `<=` and `>=`. Presumably because they use an implementation based on `(!).(>)` and `(!).(<)` respectively. Any comparison with `nan` should always return `false` except for `!=` which should always return `true`.

**Comment by athas** [comment]
Oh right, my example was wrong.  Here's the right one:

```futhark
> f32.nan >= f32.nan
true
```

But the problem is still related to the use of a Haskell-generated `Ord` instance, I'm pretty sure.

**Comment by FluxusMagna** [comment]
Yes, I believe so too. Given a minimal complete definition - which works for basically anything but `nan` (and `inf`?), it would produce incorrect instances.
