### ISSUE TITLE
Cuda thread storage :  CUcontext needs first, to be bound to a thread, before using it in the thread.

### ISSUE THREAD

**Issue by michael-elkh** [diku-dk/futhark#1077]
If we want to call futhark functions with the Cuda backend on multiple threads, the context needs to be bound first to each calling thread.
The solution might be in the functions `CUresult cuCtxSetCurrent(CUcontext ctx)` or `CUresult cuCtxPushCurrent(CUcontext ctx)`.

**Comment by athas** [comment]
We should look into doing this, but I am unnerved that CUDA does not do it automatically.  Perhaps the overhead is significant?

**Comment by athas** [comment]
I wrote a test program that reproduces this, and I am working on fixing it.  I'll have to see whether it causes any regressions, though.
