### ISSUE TITLE
CUDA  Failed with error code 999 

### ISSUE THREAD

**Issue by luxint** [diku-dk/futhark#1117]
Hi,

My program compiles and runs fine  when I compile to C, it also compiles fine when i compile to CUDA, but when i'm trying to run it i get : 
_/collatz2: collatz2.c:3592: CUDA call
  cuInit(0)
failed with error code 999 (unknown error)_

My program : 
```
let collatz (x: i64) : i64 =
  let i = 0
  let (_, i) = loop (x, i) while  x != 1 do
    if (x & 1) == 0 then
      (x / 2, i + 1)  
     else
     ((3 * x + 1 ) / 2, i + 2)
  in i

let main (end:i64) :[][]i64 =
  let batch = i32.i64 end
  let ind = iota(batch)
  let mc = map (\x -> collatz (i64.i32 (x+1))) ind
  let ms = [0] ++ init (scan (i64.max) 0 mc)
  let mf = filter (\(x,y,_) -> x > y) (zip3 mc (ms :> [batch]i64) ind)  
  in  map (\(x,_,i) -> [i64.i32 i+1,x]) mf  

```

**Comment by athas** [comment]
Can you run other CUDA programs?  This looks like a system that doesn't have the CUDA kernel module loaded.

**Comment by luxint** [comment]
I have, see below, and i actually have compiled a previous version of this program and it worked great  with CUDA.  I'm on UBUNTU 20.04 and i'm now thinking the automatic upgrades may have something to do with it.
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

nvidia-smi
Mon Sep  7 19:51:04 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 206...  Off  | 00000000:07:00.0  On |                  N/A |
|  0%   41C    P8    13W / 175W |    251MiB /  7981MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     41150      G   /usr/lib/xorg/Xorg                            84MiB |
|    0     42232      G   /usr/bin/gnome-shell                          51MiB |
|    0     42763      G   ...uest-channel-token=16222174509180663045   106MiB |
|    0     44605      G   /usr/lib/firefox/firefox                       5MiB |
+-----------------------------------------------------------------------------+

```

**Comment by athas** [comment]
Try running `ldd` on your program, and compare with `ldd` on `nvidia-smi`.  Maybe Futhark is linking with a version of the CUDA library that is incompatible with your driver version?  The call to `cuInit()` happens before any Futhark-specific logic or code runs, so I have a hard time seeing what could be wrong.

**Comment by luxint** [comment]
ok, this from my program:

ldd collatz2
        linux-vdso.so.1 (0x00007ffdd23c4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdfc1942000)
        libcuda.so.1 => /lib/x86_64-linux-gnu/libcuda.so.1 (0x00007fdfc0721000)
        libcudart.so.10.1 => /lib/x86_64-linux-gnu/libcudart.so.10.1 (0x00007fdfc04a5000)
        libnvrtc.so.10.1 => /lib/x86_64-linux-gnu/libnvrtc.so.10.1 (0x00007fdfbed35000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdfbeb43000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdfc1adc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdfbeb3d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdfbeb18000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdfbeb0d000)

and i have compiled a hello.cu program with nvcc (and that works) and with ldd it looks like this:

ldd hello
        linux-vdso.so.1 (0x00007ffc0d7ae000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff72e9f3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff72e9d0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff72e9ca000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff72e7e9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff72e69a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff72e67f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff72e48b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff72ea92000)

**Comment by athas** [comment]
`nvcc`-built executables don't dynamically link to libcuda?  Huh.

I find it slightly suspicious that `collatz2` is linked against CUDA libraries located in `/lib/x86_64-linux-gpu`.  Isn't CUDA normally installed in `/usr/local`?  Is there anything in your `dmesg`?  Sometimes version incompatibilities are reported there.

Do programs compiled with `futhark opencl` run succesfully?

**Comment by luxint** [comment]
Ok, i have rebooted and now it works!? (thought that was only necessary on windows..)

Anyway, thanks a lot for your replies and for futhark! My example program calculates all the 'running maxima' of the collatz sequences and it is crazy fast! About 1 second up to 200_000_000, i also made a comparable program in Nim, multithreaded (my computer has 16 cores/threads) and it took 5 seconds. The only thing is that above 250_000_000 it runs out of memory so  i'm trying to run the futhark program in sequential 'batches'.

**Comment by athas** [comment]
It is likely that your system upgrade updated the userspace CUDA libraries, while keeping the old version of the kernel module loaded.  That can cause weird issues, but is fixed by rebooting (which loads the new kernel module).

I'm glad to hear you enjoy the language!  Futhark sadly doesn't do anything clever about oversize memory requirements yet, so some kind of external chunking or batching is unfortunately necessary.
