### ISSUE TITLE
ICE when futhark binary is not in $PATH

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#1133]
I was trying to run a benchmark on a remote machine. Here's a stripped-down version of the benchmark:
```
-- ==
-- entry: a
-- compiled random input { 0u8 }
entry a (b: u8) = 0
```
Since this was a new machine, I didn't have Futhark installed. So I downloaded a nightly release, extracted it, and tried to benchmark:
```
$ futhark-nightly-linux-x86_64/bin/futhark bench a.fut
Compiling a.fut...
Reporting average runtime of 10 runs for each dataset.

Results for a.fut:a:
0u8: [          ] 0/10 Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
futhark: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
Long story short, it seems like the reference dataset fails to generate since `futhark` isn't in `$PATH`. Also, the same error occurs even if I use `--futhark` to pass the path to `futhark`.

**Comment by athas** [comment]
That's odd; it should pick up the executable from `argv[0]`.

**Comment by athas** [comment]
Apparently it picks up the position correctly for compiling, but not when trying to run `futhark dataset`.  Must be a simple oversight that is easy to fix.
