### ISSUE TITLE
Bug in coverage checking for some record patterns

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1134]
```futhark
type r = {f0: bool, f1: bool}

let f (x: r) =
  match x
  case {f0=false, f1=false} -> 0
  case {f0=true, f1=true} -> 0
```

This does not give an error in the type checker, but it should.

What do you say @zfnmxt, up for a break from CUDA?

**Comment by athas** [comment]
Seems unrelated to records; this also is not detected:

```
let f (x: (bool, bool)) =
  match x
  case (false, false) -> 0
  case (true, true) -> 0
```

**Comment by athas** [comment]
Also not `bool`-specific:

```futhark
let f (x: (i32, i32)) =
  match x
  case (0, _) -> 0
  case (_, 1) -> 0
```

**Comment by athas** [comment]
I think this is specifically a bug in the coverage checking of tuples (and records) where we do not consider group patterns in subsequent columns the way we do for constructors.

**Comment by athas** [comment]
Oh no, this tuple-free program is also incorrectly accepted:

```futhark
type tuple = #tuple bool bool

let f (x: tuple) =
  match x
  case #tuple false false -> 0
  case #tuple true true -> 0
```

**Comment by zfnmxt** [comment]
I missed your original @, I'll look into it!
