### ISSUE TITLE
Command line arguments for compiled programs fails with zsh on Mac OS

### ISSUE THREAD

**Issue by YmiYugy** [diku-dk/futhark#1140]
When running the first example `echo [2,2,3] [4,5,6] | ./dotprod` I get `./dotprod: Cannot read input #0 of type []i32 (errno: Undefined error: 0)`

**Comment by athas** [comment]
What happens if you quote the input?  I.e:

```
echo '[2,2,3] [4,5,6]' | ./dotprod
```

**Comment by YmiYugy** [comment]
Thanks that worked. I tried double quotations before and it didn't.
I still find it a bit strange that arguments are passed in as one string.

**Comment by athas** [comment]
It's not really a "string" as such; it's just that the program reads the contents of stdin.  You could also put the data in a file and then use `./dotprod < input.txt`.
