### ISSUE TITLE
Should Futhark respect CC/CFLAGS/LDFLAGS when compiling?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1147]
The C-based backends hardcode compiler command lines when compiling.  Should we instead respect the environment variables `CC`, `CFLAGS`, and `LDFLAGS`, if set?  And if so, should we assume that they are *complete*, or automatically add things like `-lOpenCL` that we assume will be necessary?

This only matters when users are *not* using `--library`, as in that case the user will be doing all the C compiler stuff manually.  But I'm considering improving the non-library use of Futhark as a basis for better tooling anyway, where this might help.

**Comment by Munksgaard** [comment]
Seems reasonable enough? But no, I wouldn't expect the flags to be complete. Would it makes sense to add eg. LDFLAGS _after_ our own flags? That way, users can use flags to negate and change the stuff we wrote?

How do other people do it?

**Comment by athas** [comment]
Most compilers add a bunch of compiler options that get passed on to the C compiler, linker, or whatever other tools they build upon.  But I don't like compilers with many options.

I also don't normally like hidden configuration, which is what environment variables really are, but we already implicitly depend on things like `CPATH`, so I guess this is just more of the same.
