### ISSUE TITLE
Provide latest stable release

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1149]
Is there a way to automatically download the latest _stable_ release? Currently, nightly is available at eg. https://futhark-lang.org/releases/, but there's no easy way to get the latest stable release (ie. currently 0.17.3)

The latest stable release should probably also be referenced here, instead of the latest nightly:
https://futhark.readthedocs.io/en/stable/installation.html#installing-from-a-precompiled-snapshot

**Comment by Munksgaard** [comment]
By the way, feel free to disagree that this is even something we want. I thought it would be nifty for automatically testing external libraries (eg. sorts, segmented) using the latest _released_ version of futhark instead of just nightly, cf. your comment here: https://github.com/diku-dk/segmented/pull/5#issuecomment-705379793

**Comment by athas** [comment]
This makes some sense.  What is a good way to do this?

I prefer testing libraries against the nightly version, as it has proven useful for catching regressions.  In the future, incompatible changes to the language should be rare.

An argument could be made that if you want to use the newest Futhark, you should just install it from Nix, Homebrew, or Linuxbrew in your CI script.  Particularly the two latter are rarely more than a day or two behind each release.

**Comment by Munksgaard** [comment]
I'm not quite sure. I've done it in a naive way in #1150, but perhaps it's not necessary.

Taking inspiration from outside, it doesn't look like Rust has a "latest stable" binary release. I think they manually update their release links whenever a new release is added: https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers

Given your comment, let's close this for now, we can always take it up again in the future if it seems useful.
