### ISSUE TITLE
Cannot instantiate "tΓéü" with type i32

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#1153]
I tried to compile this program on Windows, but the compiler produces a confusing error message:

```
let example a b = a + b

let example2 a = example a 1.0
```

```
Error at example.fut:4:28-30:
Cannot apply "example" to "1.0" (invalid type).
Expected: i32
Actual:   tΓéü

Cannot instantiate "tΓéü" with type
  i32
as "tΓéü" must be one of f32, f64 due to float literal at example.fut:4:28-30.
```

But it compiles successfully when I use an integer instead of a floating-point number:
```
let example a b = a + b

let example2 a = example a 1
```

Why does the Futhark compiler produce this error message?

**Comment by athas** [comment]
The confusing message is because the Futhark compiler outputs UTF-8 and your terminal expects something else.  It's supposed to be a subscripted type variable like `t₁`.

The problem is that your `example` function is type checked to completion on its own, and since the `+` operator is overloaded, the compiler arbitrarily decides that `a` and `b` must be of type `i32`.  You'd normally get a warning about this, except that warnings are not reported when the program has a type error.  I think we should fix that.

**Comment by jarble** [comment]
In this case, I expected the compiler to choose a default type (either `f32` or `f64`) instead of producing an error message.

**Comment by athas** [comment]
The type checker only looks at single top-level definitions at a time when doing type inference.  By the time it starts looking at `example2`, the type of `example` is clad in stone (and chosen to operate on `i32` by the defaulting rules).  The idea behind this inflexibility is to make it easier to provide easy-to-understand type errors, but in this case it does the opposite.

**Comment by jarble** [comment]
I tried to work around this problem using type parameters, but this example also does not compile:

```
-- Can this function be overloaded?
let example 't (a:t) (b:t):t = a + b

let example1 a =
	example a 1.0
	
let example2 a =
	example a 1.0
```

**Comment by athas** [comment]
Futhark does not have ad hoc polymorphism. You'll need two different monomorphic functions. Use parametric modules for more complex cases.

**Comment by jarble** [comment]
It's also possible to work around this problem by inlining the `example` function, though this requires some code duplication.
This program compiles with no errors:
```
let example a b = a + b

let example1 a =
	(\a b -> a+b) a 1.0

let example2 a =
	(\a b -> a+b) a 1
```
