### ISSUE TITLE
Replacing fields in records: compiler error

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#1159]
I tried to replace a field in a record using the syntax described [here](https://futhark-lang.org/blog/2017-03-06-futhark-record-system.html), but I see a compiler error:

```
let incr_x (p: {x:f64,y:f64}) =
  {p, x = #x p + 1.0}
```

```
Error at example.fut:2:11-14:
Cannot apply "+" to "#x p" (invalid type).
Expected: tΓéÇ
Actual:   tΓéü

Type constrained to one of i8, i16, i32, i64, u8, u16, u32, u64, f32,
                           f64, but also inferred to be sum type due to use of
constructor at example.fut:2:11-14.
```

Does Futhark still have a similar feature to allow fields in a record to be replaced?
I want to replace a single field in a record without listing all of its fields:

```
let example =
  let vars = {a=1,b=2,c=3} in
  let vars = {a=vars.a,b=vars.b+1,c=vars.a} in
  vars.a + vars.b
```

**Comment by athas** [comment]
Old blog posts are not documentation.  The blog post in question uses the old field projection syntax, [which was replaced three years ago](https://futhark-lang.org/blog/2017-11-11-dot-notation-for-records.html).  Now you write it like this:

```
let incr_x (p: {x:f64,y:f64}) =
  {p, x = p.x + 1.0}
```
