### ISSUE TITLE
Consider WebAssembly support

### ISSUE THREAD

**Issue by workingjubilee** [diku-dk/futhark#1167]
It is considered fashionable nowadays to provide a high level of WebAssembly (wasm) support. Futhark already compiles to C, and from C it can be compiled to wasm, though this would probably be relatively crude. However, more important for Futhark's particular goals, WebAssembly offers a generic SIMD API nowadays that can be implemented by a runtime and would allow Futhark to make maximal usage of parallelization. Also, a lot of VMs seem to be integrating with wasm support so it would provide an easy way for people to import Futhark code into their language of choice while minimizing additional maintenance overhead.

**Comment by athas** [comment]
We have a project coming up this winter that is exactly this.  It's in very early stages, so we don't yet know exactly how it will be done or how far it will get.  For example, we need to decide whether to generate WASM directly, or generate C and then compile to WASM from there.  Generating C would mean we have to maintain much less backend code, and would also let us write supporting runtime code in C.

Also, while we eventually wish to generate WebGPU for sure, maybe parallel CPU execution is easier to do first.

**Comment by jarble** [comment]
Since Futhark already has a sequential C code generator, it may be possible to compile the generated C code to WebAssembly using [Emscripten](https://emscripten.org/).

**Comment by athas** [comment]
Definitely.  The question is then how to handle WebGPU, but perhaps that can be done by having stub functions that we then hook up to JavaScript that calls WebGPU.

**Comment by athas** [comment]
Implemented by #1199 (WIP).

**Comment by athas** [comment]
Implemented in ef35628f5fcc04391fd344e23f5e9ba75bbe72e0.
