### ISSUE TITLE
[C API] Thread safety of futhark_context_clear_caches

### ISSUE THREAD

**Issue by dignifiedquire** [diku-dk/futhark#1169]
I have been running into some unfortunate memory panics when using `futhark_context_clear_caches`. Unfortuantely it is not entirely clear to me how the API is supposed to be safe when the context is shared across multiple threads.

My intuition after looking at the generated C code is that the lock needs to be held inside of `clear_caches`. 

Example Backtrace of the issue is here: 

![Screenshot 2020-10-30 at 22 35 43](https://user-images.githubusercontent.com/790842/97764928-859cbb00-1b10-11eb-9b6e-59d0490aa99b.png)
![Screenshot 2020-10-29 at 14 09 57](https://user-images.githubusercontent.com/790842/97765054-ffcd3f80-1b10-11eb-83ab-bb1137282d1c.png)

**Comment by athas** [comment]
Indeed, this is an oversight.  Should be an easy fix.

**Comment by dignifiedquire** [comment]
Unfortunately when I patched in the lock calls into my code this issue still seems to happen. (I am on 0.16.2 and didn't want to upgrade to the unreleased version yet)

**Comment by athas** [comment]
Oh, looking more closely at the stack trace, it appears the problem is in the `free_opaque()` function (although `clear_caches()` was indeed also thread-unsafe).  And looking at code generation for opaque deallocation, it does indeed look like it is not done with the lock taken.
