### ISSUE TITLE
Record concatenation

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#1172]
I want to concatenate two records to create another record, but the array concatenation operator can't be used here: 

```
let example a b =
    let a1 = {a=1,b=2} in
    let b1 = {c=1,d=2} in
    a1++b1
```

Does Futhark have an operator to concatenate these records, so that the new record would be `{a=1,b=2,c=1,d=2}`?

**Comment by athas** [comment]
No, sorry, you have to manually construct the record.  We did use to support this, but it was too easy to do by mistake, and led to confusing errors.

**Comment by jarble** [comment]
I thought it might be possible to add these fields to the record using the `with` operator, but this does not work either:
```
let example =
    let a1 = {a=1,b=2} in
    let b1 = {c=1,d=2} in
    a1 with c=b1.c with b1.d
```

**Comment by athas** [comment]
That is also by design, as it requires row type variables to handle that, which the type system does not yet support.

**Comment by jarble** [comment]
It's possible to add a field to a record by manually typing all of its fields again, but this is less convenient:
```
let example =
    let a1 = {a = 1,b = 2} in
    {a = a1.a, b = a1.b, c = 1}
```
Is there any other way to add a new field to a record?

**Comment by athas** [comment]
No, that is the only way.
