### ISSUE TITLE
Uninitialized output in a variable length loop on Vega 56 GPU only with pyopencl backend

### ISSUE THREAD

**Issue by EvilMav** [diku-dk/futhark#1175]
I was not **yet** able to reduce it to a trivial example without the issue disappearing, so I've attached a test package below for starters. Sorry for that. 

If I run it on an NVIDIA at work - it yields consistent results, but on (rocm) opencl on a Vega 56 each time I run it, it looks like that:
```
maverick@MavsArch ~/Desktop/rcsj_issue_fut % ./test_it.py
/usr/lib/python3.8/site-packages/pyopencl/__init__.py:249: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'gfx900' on 'AMD Accelerated Parallel Processing' at 0x55b85177ccc0> succeeded, but said:

warning: argument unused during compilation: '-I /usr/lib/python3.8/site-packages/pyopencl/cl'
1 warning generated.

  warn(text, CompilerWarning)
[ 4.5638890e-41 -2.3555494e+38 -2.3555494e+38 -2.3555494e+38
 -2.3555494e+38]
[ 4.5638890e-41 -2.3555494e+38 -2.3555494e+38 -2.3555494e+38
 -2.3555494e+38]
On nvidia we had:
 [ 0.0000000e+00 -4.7007356e-07 -5.0692918e-08 -5.6012931e-07
 -4.0556117e-08]
Physics changed based on the GPU. Not good.
255 maverick@MavsArch ~/Desktop/rcsj_issue_fut % ./test_it.py
...
[ 1.40130e-45 -3.72549e-01 -3.72549e-01 -3.72549e-01 -3.72549e-01]
[ 1.40130e-45 -3.72549e-01 -3.72549e-01 -3.72549e-01 -3.72549e-01]
...
```

The interesting part:
```
let fp_ludwig_thread [m] (n: i64) (dtau: f32) (g0: f32) 
                            (irf: [m]f32) (wnd: [m]f32) (ibias: f32) : f32 =
    let steady = fp_steady n g0 ibias    
    let (_, _, uavg) = 
        loop (cs, iprev, usum) = (steady, ibias, 0f32) for i < m do  --<  HERE
            let inext = irf[i] + ibias
            let csnext = fp_step dtau g0 iprev inext cs
            let u = inext + 2 * f32.pi * (c64.im csnext[1])
            let usumnext = usum + u * wnd[i] 
            in (csnext, inext, usumnext) 
    in uavg  
```
`m` is dependant on input arrays for the kernel and is 1 for the test. **If I hardcode `i < 1`  instead of `i < m` in the loop, the bug disappears!**. I've tried replacing return value with `f32.i64` to verify `m` is actually 1 - it is. Furthermore, `fp_step()` ends with:
```
    let rhs = tridiag_matvecmul rexpl state 
    in thomas rimpl rhs 
```
If I replace `rhs` with, say, `state` argument, omitting `tridiag_matvecmul()`, the problem disappears. `tridiag_matvecmul` is however tested independently and works otherwise.

My best guess is that there is some local memory involved in parallelization which is or is not properly initialising depending on workgroup heuristics from kernel launch and only happens when nesting the loop and `tridiag_matvecmul`... 

Running arch linux, rocm-opencl-runtime 3.8.0-1 (from arch4edu), Vega 56. Current futhark master branch. Test package and my clinfo:
[rcsj_issue_fut.tar.gz](https://github.com/diku-dk/futhark/files/5471153/rcsj_issue_fut.tar.gz)
[rcsj_issue_fut_clinfo.txt](https://github.com/diku-dk/futhark/files/5471162/rcsj_issue_fut_clinfo.txt)

PS Short-therm workarounds ideas appreciated.

**Comment by athas** [comment]
Try using `#[unsafe]` to disable bounds checks.  [I recently found a ROCm code generation bug that shows up sometimes for the code that is generated by bounds checking](https://github.com/RadeonOpenCompute/ROCm/issues/1182).  This might not be the problem, but it's worth trying for a start.  Otherwise, missing local memory initialisation is a pretty good bet.

**Comment by athas** [comment]
On my Vega 64, if I put `#[unsafe]` in every entry point, I seem to at least get reliable and consistent results.  Your test script still complains because it doesn't match the NVIDIA results exactly, but they're close, so this might just be due to different implementations of floating-point (or in particular the `reduce` with strictly-speaking-nonassociative float addition):

```
[ 0.0000000e+00 -4.8428774e-07  2.9802322e-07  1.7881393e-07
 -1.1920929e-07]
[ 0.0000000e+00 -4.8428774e-07  2.9802322e-07  1.7881393e-07
 -1.1920929e-07]
[ 0.0000000e+00 -4.8428774e-07  2.9802322e-07  1.7881393e-07
 -1.1920929e-07]
On nvidia we had:
 [ 0.0000000e+00 -4.7007356e-07 -5.0692918e-08 -5.6012931e-07
 -4.0556117e-08]
Physics changed based on the GPU. Not good.
```

Oclgrind does complain about some writes of uninitialized *registers*, but it appears to be mistaken.  While Oclgrind's detection of races and general memory shenanigans is invaluable, I've never had it give useful results at the scalar level.  If disabling bounds checks doesn't resolve this for you, I'll take another look.

**Comment by athas** [comment]
Oh, and thanks for the extremely nice test script!  This is probably my favourite bug report yet.

**Comment by EvilMav** [comment]
Thank you for saying - I was feeling really guilty for throwing a whole source file at you ;)

Inserting `#[unsafe]` after equals sign of fp_ludwig (if this is where you meant?) did the trick, thank you a lot!! It finally works and at a fraction of the code of the OpenCL prototype! I'm starting to really like futhark =))

Something is weird about the workgroup heuristics though. The n parameter (which the discretization resolution) would in a sequential world increase computation time per thread linearly, while ibias size (~1024) is obvious top-level parallelism. Interestingly, with n=32 my test computes within 15 seconds while rocm-smi showing 100% GPU utilization, with n=16 the utilization drops to 6%, sometimes spiking, and the computation time goes into minutes.

PS Does your Vega also spin up the fan when computing and never going back even long after showing 27°C on rocm?

**Comment by athas** [comment]
Yes, that is where I suggest you put the `#[unsafe]`.  You can put it in a more precise place by trial-and-error to work around the bug, if you wish.  You can always use the `--safe` compiler option to enforce the checking when testing.

I don't know why you see such odd utilisation (but I'm also not sure what you mean by n=64 - 30).  I don't see anything particularly fishy in your code, except that the top-level parallelism (1024) is a bit on the small size.  I do see that if `n` is at least 32, then [incremental flattening](https://futhark-lang.org/blog/2019-02-18-futhark-at-ppopp.html) kicks in and used a version of your program where each `fp_ludwid_thread` function call is collectively executed by an entire GPU workgroup - this will be *much* faster than doing it sequentially per thread.  Normally you'd use [futhark-autotune](https://futhark.readthedocs.io/en/latest/man/futhark-autotune.html) to calibrate the thresholds used to pick the versions for a specific program, but we never got around to properly integrating it with the Python backend.  As an experiment, you can play around with passing a `default_threshold=K` keyword argument to the constructor of the Futhark object, where `K` should probably be more than 1024, but maybe not too much more.

PS: Yes, my Vega has extremely weird fan behaviour.  I often end up controlling it manually when I get too annoyed.

**Comment by EvilMav** [comment]
Thank you very much for taking the time! I will try that out. 
I can probably also do slightly better by employing in-place updates in thomas and matvecmul, not sure how much of effect it would have.

#1182 covers the original issue, so this can be closed.
