### ISSUE TITLE
Internal compiler error trying to implement PCR loop

### ISSUE THREAD

**Issue by EvilMav** [diku-dk/futhark#1177]
The code in the `.tar.gz` below produces an internal compiler error.
Full message:
<details>
``
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
After internalisation:
In function pcr_thomas_4674
When checking function body
When matching
   {i64 size_12695, i64 size_12696;
    [size_12695][size_12696]f32 parts_12697,
    [size_12695][size_12696]f32 parts_12698,
    [size_12695][size_12696]f32 parts_12699,
    [size_12695][size_12696]f32 parts_12700,
    [size_12695][size_12696]f32 parts_12701,
    [size_12695][size_12696]f32 parts_12702,
    [size_12695][size_12696]f32 parts_12703,
    [size_12695][size_12696]f32 parts_12704}
with
   loop {i64 loop₇_12706, i64 loop₈_12707;
         [loop₈_12707][loop₇_12706]f32 parts_12708,
         [loop₈_12707][loop₇_12706]f32 parts_12709,
         [loop₈_12707][loop₇_12706]f32 parts_12710,
         [loop₈_12707][loop₇_12706]f32 parts_12711,
         [loop₈_12707][loop₇_12706]f32 parts_12712,
         [loop₈_12707][loop₇_12706]f32 parts_12713,
         [loop₈_12707][loop₇_12706]f32 parts_12714,
         [loop₈_12707][loop₇_12706]f32 parts_12715} = {n_12674, 1i64,
                                                       loop_init_12687,
                                                       loop_init_12688,
                                                       loop_init_12689,
                                                       loop_init_12690,
                                                       loop_init_12691,
                                                       loop_init_12692,
                                                       loop_init_12693,
                                                       loop_init_12694}
   for i_12705:i64 < splits_12686 do {
     let {i64 y_12716} = add64(i_12705, 1i64)
     let {bool nonnegative_12717} = sle64(0i64, y_12716)
     let {cert nonzero_cert_12718} =
       assert(nonnegative_12717, "negative exponent",
              "tmpvua3c7ud.fut:71:33-44")
     let {i64 y_12719} =
       <nonzero_cert_12718>
       pow64(2i64, y_12716)
     let {bool zero_12720} = eq_i64(y_12719, 0i64)
     let {bool nonzero_12721} = not zero_12720
     let {cert nonzero_cert_12722} =
       assert(nonzero_12721, "division by zero", "tmpvua3c7ud.fut:71:28-45")
     let {i64 partsize_12723} =
       <nonzero_cert_12722>
       sdiv64(n_12674, y_12719)
     let {i64 partsize_12724} = partsize_12723
     let {i64 lifted_3_map_arg_12725, bool lifted_3_map_arg_12726,
          bool lifted_3_map_arg_12727} =
       pcr_step_4814(partsize_12724)
     let {i64 lifted_3_map_arg_12728, i64 lifted_3_map_arg_12729,
          i64 lifted_3_map_arg_12730} =
       map_4625(loop₇_12706, partsize_12724, 2i64)
     let {i64 lifted_4_map_arg_12731, i64 lifted_4_map_arg_12732,
          i64 lifted_4_map_arg_12733, bool lifted_4_map_arg_12734,
          bool lifted_4_map_arg_12735} =
       lifted_3_map_4815(lifted_3_map_arg_12728, lifted_3_map_arg_12729,
                         lifted_3_map_arg_12730, lifted_3_map_arg_12725,
                         lifted_3_map_arg_12726, lifted_3_map_arg_12727)
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12736,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12737,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12738,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12739,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12740,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12741,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12742,
          [loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12743} =
       lifted_4_map_4888(loop₈_12707, loop₇_12706, lifted_4_map_arg_12731,
                         lifted_4_map_arg_12732, lifted_4_map_arg_12733,
                         lifted_4_map_arg_12734, lifted_4_map_arg_12735,
                         parts_12708, parts_12709, parts_12710, parts_12711,
                         parts_12712, parts_12713, parts_12714, parts_12715)
     -- evens_odds_12744 aliases evens_odds_12736
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12744} =
       evens_odds_12736
     -- evens_odds_12745 aliases evens_odds_12737
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12745} =
       evens_odds_12737
     -- evens_odds_12746 aliases evens_odds_12738
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12746} =
       evens_odds_12738
     -- evens_odds_12747 aliases evens_odds_12739
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12747} =
       evens_odds_12739
     -- evens_odds_12748 aliases evens_odds_12740
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12748} =
       evens_odds_12740
     -- evens_odds_12749 aliases evens_odds_12741
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12749} =
       evens_odds_12741
     -- evens_odds_12750 aliases evens_odds_12742
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12750} =
       evens_odds_12742
     -- evens_odds_12751 aliases evens_odds_12743
     let {[loop₈_12707][lifted_4_map_arg_12732][lifted_4_map_arg_12731]f32 evens_odds_12751} =
       evens_odds_12743
     -- loopres_12753 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12754 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12755 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12756 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12757 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12758 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12759 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     -- loopres_12760 aliases evens_odds_12744, evens_odds_12745, evens_odds_12746, evens_odds_12747, evens_odds_12748, evens_odds_12749, evens_odds_12750, evens_odds_12751
     let {i64 size_12752;
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12753,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12754,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12755,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12756,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12757,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12758,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12759,
          [size_12752][lifted_4_map_arg_12731]f32 loopres_12760} =
       flatten_4657(loop₈_12707, lifted_4_map_arg_12732, lifted_4_map_arg_12731,
                    evens_odds_12744, evens_odds_12745, evens_odds_12746,
                    evens_odds_12747, evens_odds_12748, evens_odds_12749,
                    evens_odds_12750, evens_odds_12751)
     let {i64 ret₂₁_12761} = size_12752
     let {i64 d₂₂_12762} = lifted_4_map_arg_12731
     in {lifted_4_map_arg_12731, size_12752, loopres_12753, loopres_12754,
         loopres_12755, loopres_12756, loopres_12757, loopres_12758,
         loopres_12759, loopres_12760}
   }
Pattern {i64 size_12695, i64 size_12696;
 [size_12695][size_12696]f32 parts_12697,
 [size_12695][size_12696]f32 parts_12698,
 [size_12695][size_12696]f32 parts_12699,
 [size_12695][size_12696]f32 parts_12700,
 [size_12695][size_12696]f32 parts_12701,
 [size_12695][size_12696]f32 parts_12702,
 [size_12695][size_12696]f32 parts_12703,
 [size_12695][size_12696]f32 parts_12704} cannot match value of type {[?1][?0]f32, [?1][?0]f32, [?1][?0]f32, [?1][?0]f32, [?1][?0]f32, [?1][?0]f32,
 [?1][?0]f32, [?1][?0]f32}.
```
</details>

The code is quite an ugly draft, so a little explanation to make it at least readable. I'm trying to parallelize a tridiagonal solve. The matrix is represented as a tuple of complex diagonals (diags type), refered by argument `mat` in most cases. `ds` is a complex rhs vector, xs will be the output vector. `thomas()` solves the problem sequentially. To parallelize, `pcr_step()` is introduced: it uses parallel cyclic reduction approach to split the problem in two separate tridiagonal problems. To do so, it calculates aprimes, bprimes, cprimes etc and splits them in even and odd elements (by number). It returns a 2-element-list of tuples of new diagonals and accoding ds. Furher, `pcr_thomas()` contains two loops: first starts from a list with a single tuple [(mat, ds)] and repeatedly splits it into more tuples using `pcr_step()`, until 2-element problems are left (we assume it is always 2^n matrix). It then maps `thomas()` to find their solutions. Last loop is repeatedly reordering and flattening the solutions to bring them back into correct order, which can be returned as solution vector.

I'm not sure the approach is supposed to be legal at all, considering how the shape of the list changes in the loop. But I do not see any other way to implement without recursion... Note that problem sizes must be constrained to 2^N for this to have a chance.

[futhark_pcr_compiler_error.tar.gz](https://github.com/diku-dk/futhark/files/5503962/futhark_pcr_compiler_error.tar.gz)

**Comment by athas** [comment]
This looks like a fairly straightforward pertubation of some internal book-keeping in the compiler frontend.  Should not be difficult to fix.

**Comment by athas** [comment]
A minimal reproducible case:

```
let main n =
  loop acc = [([1], 1)] for i < n do
    replicate i (replicate (n-i) 1, i)
```

**Comment by athas** [comment]
I don't know whether your algorithm is the best way to do it in a data-parallel style, but it's legal code.  And more than just being legal, it's also something the compiler can handle!  The restriction on variant sizes only applies to the *bodies* of parallel operations, and is ultimately due to GPU hardware limitations (so the `multicore` backend has no such restriction).  This program has the variant loop at the top-level, in code that runs on the CPU, so it is fine to do what you are doing.
