### ISSUE TITLE
Generated OpenCL is not compatible with some versions of macOS

### ISSUE THREAD

**Issue by dignifiedquire** [diku-dk/futhark#1182]
Trying to invoke the OpenCL code on a mac, I am getting 

```
device: Device { brand: Apple, name: "AMD Radeon Pro Vega 20 Compute Engine", memory: 4278190080, bus_id: None, platform: Platform(PlatformId(0x7fff0000)), device: Device(DeviceId(0x1021d00)) }
Build log:
Error returned by cvms_element_build_from_source
(embedded Futhark): ./lib/a.c:2928: OpenCL call
  build_opencl_program(prog, device_option.device, compile_opts)
failed with error code -2 (Device not available)
```

After searching the interwebs, I found https://github.com/samr7/vanitygen/issues/39#issuecomment-249408067 which points to the fact that functions like `floorf` are not actually part of OpenCL 1.0 (neither of OpenCL 1.2) when I checked. 
When I removed `rintf`, `floorf` etc from the compiled OpenCL code, it started working. 

Reference: Math functions for OpenCL 1.2 https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/mathFunctions.html

**Comment by dignifiedquire** [comment]
Looks like I spoke too soon, removing them seems to get me further, but it will eventually just hang, not entirely sure what is happening there.

**Comment by athas** [comment]
Which version of macOS is this?

**Comment by dignifiedquire** [comment]
> Which version of macOS is this?

- 10.15.7
- gpus: 
  - Radeon Pro Vega 20 4 GB
  - Intel UHD Graphics 630 1536 MB

**Comment by athas** [comment]
That's odd, I have 10.15.6 with a Radeon Pro 555, and I'd be surprised if Apple touches their OpenCL compiler anymore...

**Comment by athas** [comment]
When you say you've removed `rintf` etc. from the generated OpenCL code, do you mean that you removed them from the `.c` file, or from the huge string literal that contains OpenCL code that is embedded in the `.c` file?

**Comment by dignifiedquire** [comment]
both

**Comment by dignifiedquire** [comment]
to be exact when I removed them only from the regular code things still produced this error, when I removed them from the string it „worked“ as no error just hanging.

**Comment by athas** [comment]
Hanging how?  If you just run a Futhark program as an executable, then it will wait for input from stdin, which might look like hanging.  Try entering some input or press CTRL-D to terminate the input.

Removing them from the string is the correct way, and we should indeed not be using the f-suffixes in OpenCL code, but only in the host code.  We will fix that.  Odd that it works on my macOS, though.

**Comment by dignifiedquire** [comment]
> Hanging how

I am launching the code through genfut -> rust, and it does work fine on linux with a gpu. 
It just runs at 100% CPU without any output, for > 30min after which I stopped it. Even if it is very slow it should finish faster. 

>  Odd that it works on my macOS, though.

No idea, opencl + macos is not a great combo :(

**Comment by athas** [comment]
Is the Futhark program very large?  I have noticed that the macOS OpenCL kernel compiler can be slow, but 30 minutes is over an order of magnitude longer than it's ever taken me.

Does the program also hang when compiled with `futhark opencl` and run directly (especially with the `-D` command line option)?

**Comment by dignifiedquire** [comment]
This is the code I am running: https://github.com/filecoin-project/neptune-triton/tree/1f0cb31f55e6a1b6d884281585527a51818802c8/library

Currently testing the generated code from `futhark opencl poseidon-test.fut`

**Comment by dignifiedquire** [comment]
I built the code with `clang -O3`, code just hangs at 0.6% cpu usage, without using the gpu, running like this: 

```
./poseidon-test --entry-point simple8_test -d "AMD Radeon Pro Vega 20 Compute Engine"
```

**Comment by dignifiedquire** [comment]
note: building with futhark@0.16.2

**Comment by athas** [comment]
Try adding `-D` to the command line options.  That'll make it print what it's doing so we can figure out where it hangs.

**Comment by dignifiedquire** [comment]
running
```
./a.out --entry-point simple8_test -d "AMD Radeon Pro Vega 20 Compute Engine" --debugging &> log.txt
```

gives this out put, and will hang there https://gist.github.com/dignifiedquire/16b01231e83a1ce2321ea359469c4d94

**Comment by athas** [comment]
Well, that's not so great.  It's running correctly for a while, launching many kernels, and then hanging in something unclear - possibly (CPU-side) runtime code.  This works on Linux you say?  Mysterious.

**Comment by athas** [comment]
Oh, that's just for initialisation.  It's hanging because it's waiting for input on stdin.  Try this:

```
echo 5 | ./a.out --entry-point simple8_test -d "AMD Radeon Pro Vega 20 Compute Engine" --debugging &> log.txt
```

**Comment by athas** [comment]
I'm going to assume this was actually a macOS OpenCL bug.
