### ISSUE TITLE
Futhark interpreter uses wrong types in while loops

### ISSUE THREAD

**Issue by SupernaviX** [diku-dk/futhark#1208]
Hi!

I was trying out Futhark for some programming problems, and ran into what looks like a bug in the repl.

A minimal reproduce:
```futhark
let main (target: u64) =
  loop x = 0u64 while x != (trace target) do x + 1
```
I have a less trivial repro [here](https://github.com/SupernaviX/AdventOfCode2020/blob/main/25/solution.fut) if it helps.

When compiled (`futhark c repro.fut && echo 10 | ./repro`) this returns `10u64` the way I'd expect. When run through the interpeter (`echo 10 | futhark run repro.fut`), it runs forever.

I think it's related to the type of `target` in that expression; when I add that trace, the interpreter repeatedly prints
```
Trace at repro.fut:2:29-40: 10i32
```
Since `x` is `u64` and `target` is `i32` (even though it shouldn't be, and the type system shouldn't allow it to be), the values are never equal and the program never terminates.

Version info (this was from the nightly linux build):
```
Futhark 0.19.0
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.      
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by athas** [comment]
This bug is because `futhark run` does not do any type-checking of its input, and a plain `10` is interpreted to be of type `i32`.  The following runs correctly:

```
$ echo 10u64 | futhark run repro.fut
```

I don't remember why I didn't fix this a long time ago (maybe because `futhark run` is rarely used), but it is time to fix it.  This is just a weird pitfall for no good reason.
