### ISSUE TITLE
FutharkScript

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1210]
I want a way to take commented Futhark programs written in [this style](https://github.com/diku-dk/futhark-website/blob/master/examples/dex-raytrace.fut) and turn them into Markdown files with visualisations (images/plots) of certain values.  The inspiration is [these reports produced by Dex](https://google-research.github.io/dex-lang/raytrace.html).

I don't think this would be particularly hard to implement.

**Comment by Munksgaard** [comment]
This is literal programming, right? An easy-ish way to achieve something equivalent would be to implement Futhark support for [org-mode's babel](https://orgmode.org/worg/org-contrib/babel/).

**Comment by athas** [comment]
I think that would be more work.  It's also important to me that the source programs are ordinary `.fut` files that the compiler can process without issue (it doesn't have to type-check the visualisation annotations).

I think Knuth would be sad if we called this literate programming.  It goes against one of his core goals, namely that physical declaration order does not have to be the same as the presentation order.

**Comment by kfl** [comment]
It looks like a job for pandoc, it's similar to inverted `.lhs`.

**Comment by kfl** [comment]
[The Padoc documentation](https://pandoc.org/using-the-pandoc-api.html) shows an example converting JSON to Word files.

**Comment by athas** [comment]
I think Pandoc is overkill.  (Or rather, it will eventually be used for converting the produced Markdown to HTML.)  The technical work that has to be done is to look through the program for comments with (strawman syntax):

```
-- %image main 250
```

We'd then inspect the type of `main` and figure out how to best convert that to an image, then compile the program, run it, pass the result into some kind of data-to-image converter, and spit out a Markdown file where those comments have been replaced with HTML containing the image as a data URL.

**Comment by kfl** [comment]
But that's what pandoc filters are made for? Or Am I misunderstanding you?

You want something similar to [pandoc-markdown-ghci-filter](https://hackage.haskell.org/package/pandoc-markdown-ghci-filter), but for futhark, right?

**Comment by athas** [comment]
It's possible, but actually using the interpreter will be far too slow.  We must compile the program using the ordinary compiler, and I'm not sure Pandoc filters are appropriate when we must have access to the original source file.  [Actually extracting the graphics directives is trivial](https://github.com/diku-dk/futhark-website/blob/c34c1954e24ec259522df2a9f29b21bbd03638d9/site.hs#L27-L46), so Pandoc seems a heavyweight way to solve the simplest problem.

**Comment by athas** [comment]
This depends on #1179.
