### ISSUE TITLE
Add a way of detecting with which backend a particular futhark program was created

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1216]
For scripting purposes, it would be nice to have a flag to compiled executables (perhaps just with C-like backends) that tells you the name of the backend. Perhaps just something as simple as:

```
$ futhark opencl foo.fut
$ ./foo --backend
opencl
```

**Comment by athas** [comment]
Sounds harmless, but when is it useful?

**Comment by Munksgaard** [comment]
I had a particular scripting situation where I could've used it, but I found a way around it. In particular, I wanted to be able to automatically benchmark using a few different backends, while comparing the output to the result of the C backend.

You may close this issue if you don't think it's worth it to add.

**Comment by athas** [comment]
This is already part of the C API, where it was quite useful.  If it also becomes useful for executables, then we can re-open this issue.
