### ISSUE TITLE
Expose floating-point operations with non-default rounding modes

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1217]
Futhark currently emits floating-point operations that don't specify any particular rounding mode.  This means that it will be round-to-even, which is generally fine.  But there is some code that benefits from other rounding modes.  We should expose specialised functions from the `f32` and `f64` modules that round differently.  These should at least include addition, multiplication, division, and reciprocal.

In the CUDA backend, these can be easily implemented by using intrinsic functions: https://docs.nvidia.com/cuda/floating-point/index.html#rounding-modes

On OpenCL, this pragma seems promising, but I have not experimented with it yet: https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/SELECT_ROUNDING_MODE.html

CPUs are the main challenge, since C uses a global rounding mode setting: https://www.gnu.org/software/libc/manual/html_node/Rounding.html

At least the setting is thread-local.  The only sensible implementation strategy is probably to switch to the desired rounding mode inside the specialised functions, then restore the default afterwards.  This is probably slow, but will only affect code that uses non-default rounding.  Hopefully there will not be too much of that.

**Comment by Oblomov** [comment]
Beware that the rounding mode selection pragma in OpenCL has been obsoleted and AFAIK is not supported by any implementation presently (its support is advertised via [the appropriate extension](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/cl_khr_select_fprounding_mode.html), but I don't know of implementations that support it).

**Comment by athas** [comment]
Well, that sucks.  At least we can implement it properly on CUDA.

**Comment by athas** [comment]
Realistically we will not do this.
