### ISSUE TITLE
_GNU_SOURCE ifdef

### ISSUE THREAD

**Issue by Snektron** [diku-dk/futhark#1228]
Compiling generated C code yields a warning about a redeclaration of _GNU_SOURCE, which is present in the generated header. I believe this can be solved simply by adding an ifndef around the generated code:
https://github.com/diku-dk/futhark/blob/f74515c57d7ded9db05fff2d92b7f8d9d0cbfe4f/src/Futhark/CodeGen/Backends/GenericC.hs#L1397

**Comment by athas** [comment]
I wonder why we require this ifdef anyway.  I think it's related to the multicore backend, but maybe we could be more precise.
