### ISSUE TITLE
Making generated headers compatible with C++

### ISSUE THREAD

**Issue by Snektron** [diku-dk/futhark#1229]
Currently, generated headers are only valid for C: When including them in a C++ project, a manual `extern "C"` block is required around the include directive. I think it is a good idea to also make these headers compatible with C++ by providing the `extern "C"` block in the generated header. This is usually done as follows:
```c++
// Include directives
#ifdef __cplusplus
extern "C" {
#endif
// Generated C code
#ifdef __cplusplus
}
#endif
```

**Comment by athas** [comment]
This seems harmless enough.
