### ISSUE TITLE
(pyOpenCL) Occasional NaN in certain thread numbers when using cpprandom (+ bonus Internal Compiler Error)

### ISSUE THREAD

**Issue by EvilMav** [diku-dk/futhark#1242]
A kernel of mine uses a split rng over parallel threads solving an SDE. After each execution the state is joined and returned to continue execution next time. I've noticed that with certain thread numbers one of the threads will yield a NaN, even though the conditions are identical and the rng is multiplied with 0.0. Unfortunately, I could not reproduce with a smaller example with rng alone, so I'm not sure if it's a cpprandom issue or compiler's flattening issue.

Running ` ./check_fail.py` in the directory attached below I get:
```
% ./check_fail.py
FUTHARK_INCREMENTAL_FLATTENING=1 futhark pyopencl --library fail.fut
Attempting with 256 biases
Attempting with 4096 biases
Encountered NaN in sample [[43]] in step 89
Attempting with 4097 biases
Attempting with 131072 biases
Encountered NaN in sample [[9540]] in step 83
./check_fail.py  4,89s user 0,13s system 99% cpu 5,056 total
```
The "Encountered NaN" issues should not happen and only appear with certain problem sizes.

Bonus: if I comment out "+ irf[step]" on line 17 of fail.fut, I get:
```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
BinderT.lookupType: unknown variable n_6943
CallStack (from HasCallStack):
  error, called at src/Futhark/Binder.hs:111:18 in futhark-0.19.0-2V6GCosZ0r28tYyck4f4gH:Futhark.Binder
```
Arch Linux, current futhark and cpprandom version from git, executing on an RTX3080.

Failing code: [futhark_nan.tar.gz](https://github.com/diku-dk/futhark/files/5898447/futhark_nan.tar.gz)

**Comment by athas** [comment]
Minimal case for the crash:

```
let hof [n] (f: i64 -> i64) (irf: [n]f32) (b: bool) = n

let main [n][m] (irf: [n]f32) (bs: [m]bool) =
  map (hof (+1) irf) bs
```

I have a suspicion the NaN issues are related.  Do you otherwise gets lot of infinities?

**Comment by EvilMav** [comment]
> I have a suspicion the NaN issues are related. Do you otherwise gets lot of infinities?

I'm now pretty positive this is an rng issue: changing seed in em_state_init from [0] to [1] did make these NaN disappear...

**Comment by athas** [comment]
That's certainly possible.  The seeding is pretty ad hoc, and it's likely it doesn't behave well with zero entropy (even though the documentation tries to claim otherwise).

**Comment by EvilMav** [comment]
>  it doesn't behave well with zero entropy 
Changed seed to [1, 2, 3]. NaNs are back in provided test case. So it is not only for 0. I bet split_rng produces unfavorable states for certain parent states and numbers.

**Comment by athas** [comment]
How could these NaNs occur, though?  Isn't the division by an integer the only place where they might arise?  This might be a compiler bug where the generated Python code doesn't unpack the size correctly and treats it as a zero...

**Comment by athas** [comment]
I'm pretty sure the NaNs are not a compiler bug, but rather a bug in [cpprandom](https://github.com/diku-dk/cpprandom).  It appears that it tries to take the logarithm of zero in the [normal deviation random number function](https://github.com/diku-dk/cpprandom/blob/50b258f6d6fbc9aa27fbacec03462141c40f199d/lib/github.com/diku-dk/cpprandom/random.fut#L538-L546).  I'll close this issue, but feel free to open a new one in the `cpprandom` repository.  I'm not promising I will know how to fix it, as I'm a lot better at compiler hacking than random number generation, but maybe I can find an algorithm somewhere I can copy.

**Comment by EvilMav** [comment]
> Do you otherwise gets lot of infinities

You were spot on from the start. Box-Muller transform converts 0 input to f32.inf. I was multiplying 0.0 with inf in my test case ending up with NaN. Returning an inf is something I did not consider as it is theoretically infinitely unlikely, unless I seed with so little enthropy that it becomes common with cpprandom I guess. Likely not a bug.

**Comment by athas** [comment]
It's almost certainly a bug in `cpprandom`, not in your code.  At least I don't think a function that supposedly returns a normally distributed number should ever return NaN.
