### ISSUE TITLE
IO exceptions from invalid/unexpected tuning file

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#1246]
With a minimal program `bug.fut`:
```futhark
-- ==
-- input {} output { 0 }
entry main = 0
```
And an invalid tuning file:
```sh
$ echo "x" > bug.fut.tuning
```

Both `futhark bench bug.fut` and `futhark bench --backend=opencl bug.fut` cause an IO exception. The former is because `--tuning` is an unknown option on the C backend and the latter is because the tuning file is invalid. Using `futhark test` prints the same errors, but there is no message about an unhandled IO exception.

**Comment by athas** [comment]
We must do two things:

* Make the `c` backend understand `--tuning` (even if no tuning option is actually going to be valid).
* Handle invalid tuning files in the tooling.  This is actually a more general problem, where `futhark test` and friends will freak out if there is an error during program server startup (such as initialisation errors).  We should do this better.
