### ISSUE TITLE
bench: auto output fails with opaque types

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#1251]
When trying to bench the following program (`bug.fut`):
```
-- ==
-- input {} auto output
entry main = [()]
```
The auto generated output `data/bug:main-#0_("").out` is:
```
#<opaque []()>
```
This causes an error:
```
Results for bug.fut:
#0 (""): [██████████] 10/10 futhark: user error (Cannot parse values from 'data/bug:main-#0_("").out')
```

**Comment by athas** [comment]
This shouldn't work (at least not with the interpreter), but it should fail in a better way.  I'm not sure where to check the result type of the entry point.
