### ISSUE TITLE
Possible regression

### ISSUE THREAD

**Issue by omalaspinas** [diku-dk/futhark#1252]
Hello,

when trying to compile my liibrary after updating to futhark 18.6 (it was working under 18.5) I get the following internal error:

```
$ futhark c liblbm_f32.fut 
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
BinderT.lookupType: unknown variable q_6891
CallStack (from HasCallStack):
  error, called at src/Futhark/Binder.hs:111:18 in futhark-0.18.6-HGknMLrgrqlA3ncCn4oC6i:Futhark.Binder
```

Steps to reproduce:

```bash
$ git clone https://githepia.hesge.ch/orestis.malaspin/palathark
$ cd palathark/src
$ futhark c liblbm_f32.fut
```

I do not really know what may be going on so I have difficulties reducing it. Sorry.

**Comment by athas** [comment]
It's certainly a regression, as the compiler should never crash.

**Comment by athas** [comment]
This commit is the problem: https://github.com/diku-dk/futhark/commit/68075f3c96ade967d07a4ca20d962b886b5f2def

I'll have to think a little bit about how to fix it, but I don't think it will take too long.
