### ISSUE TITLE
Any possibilities to show images at README.md benchmarking with other languages 

### ISSUE THREAD

**Issue by terremoth** [diku-dk/futhark#1257]
It would be nice to show comparison/tests like fibonacci, PI generation, processing a CSV file into an image, and place it at README.md, maybe this way can help attract more people;

Other way is to print/show at readme some little pieces of code doing something, this also helps attract people and help 😀

**Comment by athas** [comment]
Would it be enough to link to [the examples](https://futhark-lang.org/examples.html)?

**Comment by terremoth** [comment]
Idk, just to have visual representation, as our brain assimilates better;
It's nice to enter a not known programming language github and see how the lang is, even more for people in a hurry just passing his eyes on its README

:)
