### ISSUE TITLE
NumPy DeprecationWarnings in PyOpencl backend

### ISSUE THREAD

**Issue by EvilMav** [diku-dk/futhark#1281]
PyOpenCL modules use NumPy type aliases which are identical to using python types and are therefore deprecated: [Using the aliases of builtin types like np.int is deprecated](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations).

This results in hundreds of warnings like:
```
  .../emg-thz/emg/thz/futhark/rcsj_ocl.py:17977: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    byte_count=np.long((replicate_arg_24549 * np.int32(4))))

```

Very annoying but probably a trivial fix...

**Comment by EvilMav** [comment]
Warnings seem to come for two types: `np.bool` and `np.long`. The codebase can be greped for them. `np.bool` can be replaced with bool. I'm not sure it `np.long` should be replaced with generic `int` or fixed precision `np.int64`.

**Comment by athas** [comment]
Definitely `np.int64`.

**Comment by EvilMav** [comment]
> Definitely `np.int64`.

The old way was equivalent to `int` if I read the docs correctly though ;) Should I prepare a pull request or are you already on it? (On a side note - are there any beginner docs on how to run tests for the compiler? For those trying to make themselves at least somewhat useful but being lost on the unfamiliar haskell terrain ;) )

**Comment by athas** [comment]
It should be `np.int64`.  Probably it didn't make a difference in any of the spots where we were using `np.long`, but we try to avoid the builtin `int` as much as possible (although it makes no difference for the runtime system code, I suppose).

I'm not working on it, so feel free to give it a shot.  As far as tests go, see [this line in the CI setup](https://github.com/diku-dk/futhark/blob/2f3dd6c9fad887dfe610d3fd8fbacee6563678a7/.github/workflows/main.yml#L277).  If you also want to run the `pyopencl` backend tests, see [this line](https://github.com/diku-dk/futhark/blob/2f3dd6c9fad887dfe610d3fd8fbacee6563678a7/.github/workflows/main.yml#L328) (doesn't require a GPU; the test uses `oclgrind`).
