### ISSUE TITLE
Insufficient args crashes server

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/futhark#1299]
Simply starting a server and calling entry point foo like `call foo` will write the message `./binary-name-here: Insufficient command args.` and close the server with exit code 1.

I just downloaded `futhark` from `brew` a couple of days ago. Running `futhark -V` prints the version as `Futhark 0.20.0`, which is weird as well since as far as I can tell the current version is 0.19.4.

**Comment by athas** [comment]
It's expected that the server crashes in that case, since you also need to provide inputs and outputs for the entry point.  The server is not robust in the face of invalid commands.

The version number is a bit odder.  Are you sure you don't have another installation of Futhark earlier in your PATH?

**Comment by Unigurd** [comment]
Ah, I realize now that I had been too hasty when reading the server protocol. I was under the impression it would always respond with `%%% FAILURE`.

The output of `whereis futhark` is `futhark: /home/linuxbrew/.linuxbrew/bin/futhark`.

**Comment by athas** [comment]
Did you install with `--HEAD`?  As far as I can see, the Linuxbrew/Homebrew tarball has the right version number in the .cabal file.  A version number ending with .0 indicates a pre-release version.

**Comment by Unigurd** [comment]
Oh, I see. Yeah, brew reports the version as `futhark HEAD-d95ca1`. I installed with `--HEAD` about a year ago. I must've still had that lying around and just run `brew upgrade futhark` a couple of days ago.
