### ISSUE TITLE
Nix Documentation

### ISSUE THREAD

**Issue by baskaransri** [diku-dk/futhark#1307]
When using ```futhark opencl``` via nix-shell on MacOS X (Catalina) you need both ```nixpkgs.futhark``` and  ```nixpkgs.darwin.apple_sdk.frameworks.OpenCL```. @athas mentions that on NixOS, you need ```nixpkgs.opencl-headers``` (and possibly ```nixpkgs.ocl-icd```). I don't think this is clearly documented, and it would be nice if it were. Perhaps a section in the user's guide?

**Comment by athas** [comment]
I think [a subsection here](https://futhark.readthedocs.io/en/latest/installation.html#installing-futhark-on-linux) would be appropriate.  A little hidden, but hopefully the search engines will pick it up eventually.

**Comment by rowanG077** [comment]
I use Futhark with NixOS and it requires:

```
opencl-headers
opencl-icd
```

Compilation fails with missing headers errors if `opencl-headers` is missing and linking fails if `opencl-icd` is missing due to missing `-lOpenCL`.
