### ISSUE TITLE
Explicit existentials in the Futhark source language

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1308]
To follow up on #1301, I think it is time to support explicit binding of existentials in the source language.  For syntax, I suggest extending the syntax of types with the following:

```
type ::= ... | "?" "[" id "]" "." type
```

where `?` is my ASCII rendition of `∃`. Then we can write types such as

```
val filter [n] 'a : (a -> bool) -> [n]a -> ?[m].[m]a
```

and perhaps more interestingly

```
val some_square : i32 -> ?[n].[n][n]i32
```

This is mostly useful with abstract types and type abbreviations.

Existentials will still be implicitly opened, as @melsman recently formalised, so little will change in the language.  In particular, no variable will ever be bound to a type that has an outermost existential quantifier.  There are still questions to be answered.

1. It seems clear to me that `(i32,?[m].[m]bool)` and `?[m].(i32,[m]bool)` should be considered equivalent.  Does this have any pitfalls?

2. Should we allow types such as `?[n].[n]bool -> bool`, where in practice there would be no way to apply this function?

3. Should we allow types such as `?[n].([n]bool, [n]bool -> bool)`?

4. Do we need to extend the type checker's semantic representation of types to also include explicit quantification?  Currently it uses implicit existentials whose scope are the nearest enclosing arrow.  For example (using internal implicitly quantified syntax), `[?n]bool -> bool` is interpreted as `?[n].bool->bool`.  If the answer to point 3 above is "yes", then this is not good enough, as `([?n]bool, [?n]bool -> bool)` means `?[n].([n]bool, ?[n].[n]bool -> bool)`.  It's possible this could fixed by simply also looking below arrows when instantiating an existential type.  I guess this is more of an engineering question.

5. While I do not want variables bound to types with outermost existentials, I *do* want them to be supported in type abbreviations:
        
        type square = ?[n].[n][n]bool

    This is a natural thing to write, and a function

        let fun (x: square) = ...

    should also just do the right thing (in this case, implicitly instantiating the existential).  I think this will just work, but we should check the details.

Preemptive answers to two good questions:

## Why existentials with special/ad-hoc semantics such as implicit instantiation, rather than representing existentials like dependent products that must be explicitly opened?  Are you afraid of dependent types?

I am not afraid of dependent types!  Implementing it like that would not be a problem, because types would only still be dependent on very specific terms (those of type `i64`) and in very specific ways (they ultimately become array sizes).  It's purely about programming convenience, in that I want it to be possible to express pipelines such as

    xs |> filter p |> filter q |> ...

without having to worry about manually unpacking dependent products.  As always, Futhark is about focusing on a special case, and providing good ergonomics for that case.

## Why is the proposed syntax `?[n].[n]bool` rather than the more concise `?n.[n]bool`?

Two reasons:

1. Consistency.  Everywhere else in Futhark where "size parameters" are used, they are written enclosed in brackets.  For example, when applying a type that is parameterised on a size, we write `t [n]` not `t n`, even if `n` is an ordinary term variable.

2. Lexing issues.  Currently the lexer always parses `n.m` as a single token to handle qualified names, so `?n.t [n]` would not work.

I am still trying to work out whether (1) is just a rationalisation, while (2) is the real issue.

**Comment by athas** [comment]
Another reason for the syntax: it allows `?[n][m].([n]bool, [m]bool)` with the obvious meaning.

**Comment by athas** [comment]
I've made a first draft in #1318.  This was shockingly easy to get working.  The semantic representation of types still uses implicit quantification, which is not ideal, but it works.  I discovered one odd case, namely that this type checks:

```
let main [n] (xs: ?[n].[n]bool) (ys: [n]i32) = length (zip xs ys)
```

This is because when an existential quantifier is *not* to the right of a function arrow (as in the ascription for `xs`) it will "float" out as far as possible, which is to the definition of `f` itself, and then it will be *unified* with `n` because of the `zip`.  The type of `main` is then

```
main [n] : (xs: [n]bool) -> (ys: [n]i32) -> i64
```

This is not harmful, but perhaps a bit unexpected.  The root cause is that such "floating" existentials are instantiated with nonrigid size variables, rather than rigid ones (if you apply a function with an existential to the right of the arrow, you'll get a proper rigid size variable back, as you would expect).

**Comment by melsman** [comment]
fre. 16. apr. 2021 kl. 21.41 skrev Troels Henriksen <
***@***.***>:

> I've made a first draft in #1318
> <https://github.com/diku-dk/futhark/pull/1318>. This was shockingly easy
> to get working. The semantic representation of types still uses implicit
> quantification, which is not ideal, but it works. I discovered one odd
> case, namely that this type checks:
>
> let main [n] (xs: ?[n].[n]bool) (ys: [n]i32) = length (zip xs ys)
>
> This is because when an existential quantifier is *not* to the right of a
> function arrow (as in the ascription for xs) it will "float" out as far
> as possible, which is to the definition of f itself, and then it will be
> *unified* with n because of the zip.
>
Wouldn't it be more natural to disallow the unification. Then, the program
will become

let main [n] [m] (xs: [m]bool) (ys: [n]i32) = length (zip xs ys)

which does not type check...

The type of main is then

**Comment by athas** [comment]
But then what should this mean?

```
let main [n] (xs: []bool) (ys: [n]i32) = length (zip xs ys)
```

I think it is natural for this to mean the same thing as 

```
let main [n] (xs: ?[m].[m]bool) (ys: [n]i32) = length (zip xs ys)
```

but we really do want inference for "empty" dimensions.  I think there are many possible ways to define the rules here (it's all about how to interpret certain implicit shorthands), and we just need to pick whatever is the most useful most of the time.

**Comment by athas** [comment]
This is even more interesting than I thought.  Writing `te ⇒ t` for
the elaboration of a type expression `te` to a semantic type `t`, and
with free variables denoting (nonrigid) size variables subject to
unification, we wish to have

```
[]i32 ⇒  [n]i32
```

but

```
i32 -> []i32 ⇒  i32 -> ∃n.i32
```

and equivalently

```
i32 -> ?[n].[n]i32 ⇒  i32 -> ∃n.i32
```

But now things get interesting, as we want:

```
i32 -> []i32 -> []i32 ⇒  i32 -> [n]i32 -> ∃m.i32
```

Blank dimensions (`[]`) are always a shorthand for inserting an
existential binder *somewhere*, but it's actually a bit subtle where
we do it and what their scope is.  For example, interpreting

```
i32 -> []i32 -> []i32
```

as

```
i32 -> ∃n.([n]i32 -> ∃m.[m]i32)
```

is not useful, because there is no way to apply this function (an `n`
may exist, but you cannot know what it is!).  It's quite important
that it is interpreted as

```
∃n.i32 -> [n]i32 -> ∃m.[m]i32
```

where the outermost quantifier then evaporates into a nonrigid size
variable subject to further unification.  This means that the rule is
not as simple as "blank dimensions become existentially bound at the
nearest enclosing arrow".  I think the rule may be:

* Blank dimensions for types in *positive position* become
  existentially bound *outermost*.

* Blank dimensions for types in *negative position* become
  existentially bound at the nearest enclosing arrow.
