### ISSUE TITLE
ICE after unstream on opencl backend when map is nested inside loop

### ISSUE THREAD

**Issue by nhey** [diku-dk/futhark#1310]
I have run into internal compiler error(s) when doing in-place updates to loop variables with results of mapping operations.
I think I may be doing something illicit, but the program in question compiles and produces correct results using the C backend.

The ICE is:
```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'unstream':
In function mrecresid
When checking function body
In expression of statement
  {defunc_5_map_res_42563 : ({}, [m_42462][k_42461][k_42461]f64),
   defunc_5_map_res_42564 : ({}, [m_42462][k_42461]f64)}
in false branch
In expression of statement
  {defunc_3_map_res_r_55112 : ({}, [m_42462][k_42461][k_42461]f64)}
in false branch
In expression of statement
  {defunc_3_map_res_r_55176 : ({}, [m_42462][k_42461][k_42461]f64)}
Inside the loop body
In expression of statement
  {defunc_3_map_res_55209 : ({}, [m_42462][k_42461][k_42461]f64)}
in true branch
In expression of statement
  {defunc_3_map_res_55214 : ({}, [m_42462][k_42461][k_42461]f64)}
In expression of statement
  {defunc_0_f_res_55219 : ({}, [k_42461][k_42461]f64)}
Inside the loop body
Type error:
x_expanded_55215 was invalidly consumed.
Only mapout_78163 can be consumed here.
```
and was produced by`futhark opencl` using futhark v0.19.3.
Unfortunately, the program is convoluted for showcasing this and I was not able to reproduce the exact same error using a simple example. The code is [available here](https://github.com/nhey/recresid-roc/blob/b2ddd3e92234f0a1327fc671258d92caedb5aa5c/recresid.fut#L106). Line 172 alludes to where the error is introduced. I _think_ the error stems from the in-place update of `retrs` _and_ mapping over `X1s`/ `X1rs`. The sizes in the ICE correspond with `[m][k][k]` which is the size of `X1s` and `X1rs`. The size of `retrs` is `[m]`.

In a sort of related minimal example I am able to produce a different ICE using in-place updates combined with map results.
This should at least give an idea of the code I am trying to write:
```
let main [m][N][k] (X: [N][k]f64) (_: [m][N]f64) =
  let xs = replicate m X
  let x1s = map (\_ -> replicate (k*k) 0i32 |> unflatten k k) xs

  let (_, x1s) =
    loop (r, x1rs) = (k, x1s) while r < N do
      (r+1, x1rs)
  in x1s
```
The error:
```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'simplify':
In function main_3998
When checking function body
When matching declared return type to result of body
Type error:
Type annotation is
  {[m_4406][k_4405][k_4405]i32}
But result returns type
  {[m_4406][defunc_4_map_arg_4415][defunc_4_map_arg_4415]i32}
```
Although here, the error is produced for both the C and opencl backends and it is fixed by a type-cast:
```
  let x1s = map (\_ -> replicate (k*k) 0 |> unflatten k k) xs :> [m][k][k]f64
```

**Comment by nhey** [comment]
Also any pointers on how to avoid this error for the time being would be greatly appreciated. I can ask about this on the IRC if you prefer.

**Comment by athas** [comment]
What a cool problem!  It's failing because it's doing an optimisation that is theoretically possible (`copy`-elimination), but which happens rarely, and apparently sequentialisation cannot deal with the resulting code.  I can fix it, I think.

The workaround is to modify `ols.fut` and put `#[sequential]` in front of the call to `dotprod` in `back_substitution`.  That will prevent the loop interchange that eventually makes the compiler trip over its own feet.  (Although you're in for a bad time for other reasons, as this program has some subtle irregular parallelism that the allocator cannot handle.)

**Comment by nhey** [comment]
> (Although you're in for a bad time for other reasons, as this program has some subtle irregular parallelism that the allocator cannot handle.)

Oh right, I need to handle the check differently. Luckily I should be able to modify the algorithm to regularize it rather than fully flattening. Thanks for taking the time to inspect my code!
