### ISSUE TITLE
Add adhoc tests for autotune, imports and other random things

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1314]
As discussed in #1313, we need some way to test that eg. futhark autotune actually works on the different backends (at least that it is able to run, picks up size-comparisons, and outputs something reasonable). @athas suggests that we add a `test_adhoc` directory, which could contain arbitrary scripts running such tests.

**Comment by Munksgaard** [comment]
For testing the autotuner: How do we make sure that it actually works on CUDA and OpenCL? Unless I am mistaken, GA doesn't even have support for OpenCL, so any tests that actually run `futhark autotune --backend=opencl` (or even worse, uses the CUDA backend), would not be able to run on GA.

**Comment by Munksgaard** [comment]
b167c79b4a749e74e0f981b95a3feb7c7196cacf is an example of what it could look like. Of course, it's probably not going to work...

**Comment by athas** [comment]
We actually do test the OpenCL backend on GA, using `oclgrind`.  Constructing autotuner tests that do something interesting with such a slow OpenCL implementation may be an interesting challenge, but not impossible.

**Comment by athas** [comment]
Unfortunately not.
