### ISSUE TITLE
Type abbreviations of flat tuples not unpacked to separate return values in server mode

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/futhark#1319]
I am under the impression that [type abbreviations are entirely interchangable with the type they abbreviate](https://futhark.readthedocs.io/en/stable/language-reference.html#type-abbreviations), but interacting with the following program in the futhark server reveals that a type abbreviation of `(u8, u8)` is returned as a single value instead of two separate values, and when storing it in a file it has been cast to `(i8, i8)`. I am running Futhark 0.19.4 on Ubuntu 18.04.5 LTS.

Futhark program compiled either to C or OpenCL:
```
type tuple_abbrev        = (u8, u8)
entry foo : tuple_abbrev = (0, 0)
```

Server interaction:
```
%%% OK
call foo a b
runtime: 4
%%% OK
store out-a a
%%% OK
store out-b b
%%% FAILURE
Unknown variable: b
%%% OK
```
Hex contents of out-a:
```
6202 0020 2069 3800 6202 0020 2069 3800  b..  i8.b..  i8.
```
On a side note, when reading the server protocol, I did not found it obvious why an entry point would ever return multiple values, i.e. that flat tuples are returned as multiple values. I'm sure it is documented elsewhere, but a note on it there would have helped me. :)

**Comment by athas** [comment]
If you run the `outputs foo` command, you'll see that `foo` returns a single value, of type `tuple_abbrev`.  This means that the binary representation is undefined except that `restore` should work.  The whole notion of how Futhark types are mapped to types in the library API (which is what the server protocol ultimately exposes) is a bit fiddly, and sort of documented here: https://futhark.readthedocs.io/en/latest/usage.html#general-concerns

It doesn't seem to mention the behaviour for tuples, which is that the components are returned piecewise, *unless* a type annotation is used to hide the tuple.

The rule that type abbreviations are just shorthands is true within the language, but not when it comes to interacting with the outside world.  There they are used for naming.

**Comment by Unigurd** [comment]
Okay, fair. You write that `restore` should work for `tuple_abbrev`. Is writing the `u8` values as `i8` considered working?

**Comment by athas** [comment]
Yes, the deserialisation code opaques will (should...) handle that.
