### ISSUE TITLE
Machine epsilon for floating point types

### ISSUE THREAD

**Issue by nhey** [diku-dk/futhark#1320]
While the IEEE standard does not define "machine epsilon", most languages agree on the following definition [[C](https://www.cplusplus.com/reference/cfloat/); [Rust](https://doc.rust-lang.org/std/f64/constant.EPSILON.html); [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.finfo.html); [Mathematica](https://reference.wolfram.com/language/ref/$MachineEpsilon.html); [Mathworks](https://se.mathworks.com/help/matlab/ref/eps.html)]: _Machine epsilon is the difference between 1.0 and the next larger representable number._

I suspect you may have considered this already, but if you are open to including this for the `float` module type in `prelude/math.fut`, I will gladly open a PR.

My motivation is to access this information when defining tolerance values in parametric modules without requiring the user to extend built-in types `f32` and `f64`.

**Comment by athas** [comment]
Sure, sounds harmless enough.
