### ISSUE TITLE
Type error after fusion

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1322]
```
let resolve_fns [n] (a: [n]bool) (data: [n]i32) =
    let b = map (== 0) data
    let d =
        b
        |> map i32.bool
        |> scan (+) 0
        |> map (+ -1)
    let is = data |> map i64.i32
    let f = scatter (replicate n (-1i32)) is d
    let g =
        f
        |> map (!= -1)
        |> reduce (&&) true
    let new_data = scatter (copy data) is d
    in (g, new_data)

let resolve_vars [n] (a: [n]bool) =
    let valid = reduce (&&) true a
    let data = map i32.bool a
    in (valid, data)

entry oef [n] (a: [n]bool) =
    let (b, data) = resolve_vars a
    let (c, data) = resolve_fns a data
    in (b && c, data)
```

I don't think this is your fault @Munksgaard, so don't spend too long on it.  Looks vaguely related to seqstreams.

**Comment by Munksgaard** [comment]
Yeah, I have no idea what's going on inside that pass. I'll leave it to you, @athas.

**Comment by athas** [comment]
God damn do I hate debugging the fusion pass.  By far the worst code in the compiler.  The problem is that we insert a duplicate in the `outNames` field of the `FusedKer` when doing a producer-consumer fusion between a redomap and a sequential stream.
