### ISSUE TITLE
`futhark bench` doesn't play well with long lines

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1330]
[ocean-sim](https://github.com/diku-dk/futhark-benchmarks/blob/master/misc/ocean-sim/tke.fut) has a [test dataset](https://github.com/diku-dk/futhark-benchmarks/blob/master/misc/ocean-sim/tke.fut#L51) with a long name. When running `futhark bench`, it seems to break the ANSI control codes.

For instance, this is what it looks like on my machine:

![screenshot](https://user-images.githubusercontent.com/230613/117281821-591d7f00-ae64-11eb-9f75-99376eee48cc.png)

I think we need to detect how large the terminal is (perhaps using the method described [here](https://stackoverflow.com/questions/35688348/how-do-i-determine-size-of-ansi-terminal)) and then cut off excessively long dataset names.

**Comment by athas** [comment]
Yes.  This dataset name is ridiculous, but I guess users are liable to make bad choices.  There are other places where we just assume a maximum terminal width, and we could just do the same here.
