### ISSUE TITLE
Reactive benchmarking

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1335]
`futhark bench` currently uses a fixed number of runs.  This is in many cases inflexible.  It would be nice to support a reactive mode where the number of runs is based on how long a single run takes, and how quickly we establish confidence in the measurement results.  Probably we should look at what other tools like [criterion](http://www.serpentine.com/criterion/) do.

**Comment by Munksgaard** [comment]
That's a great idea, I think.

**Comment by kfl** [comment]
Note that `criterion` is doing some fancy statistics, that not all users might understand or even misinterpretate (even if they ought to know better). I know, I have misinterpretated `critetion` output myself.

Maybe take look at [`tasty-bench`](https://github.com/Bodigrim/tasty-bench)?

**Comment by athas** [comment]
Yes, I don't particularly like `criterion`s  default output.  I like `futhark bench`s very concise output format.  I just don't want to manually fiddle with the run count.
