### ISSUE TITLE
Comment parsing is broken

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1341]
This program fails to parse with the current master:

```futhark
let main (xs: []i32)  =
  xs
  -- |> map (+ 1)
```

The error is:

```
$ futhark opencl ~/tmp/ice.fut
Error at /home/munksgaard/tmp/ice.fut:4:1-1: unexpected end of file.

If you find this error message confusing, uninformative, or wrong, please open an issue at
https://github.com/diku-dk/futhark/issues.
```

Uncommenting the last line, or removing the comment, causes the program to work again.

**Comment by athas** [comment]
That's because `-- |` is a documentation comment, which is only allowed just before definitions.

**Comment by athas** [comment]
You can add an extra space and it'll work.  It would be nice if the parser provided a better error message in this case.  Maybe it could also simply be fixed to do the right thing, although I'm not sure how (skipping comments in the parser itself seems like a violation of the phase distinction).

**Comment by Munksgaard** [comment]
Thinking about it some more, I'm not sure I understand why it is the parsers job to handle doc comments? Shouldn't that be a job for a separate tool?

**Comment by athas** [comment]
That's what Haskell does, and it means that many Haskell programs end up mistakenly having doc comments in unexpected places, which then causes Haddock to fail.

**Comment by Munksgaard** [comment]
I guess one question we could ask ourselves is: Which is the bigger problem? Valid programs not compiling because of broken doc-comments, or invalid doc-comments causing `futhark doc` to fail? Which happens more often and which is most annoying to fix?

Personally, I don't think I've ever used `futhark doc`, but I (and my usage) might be an outlier. I can certainly see that having _some_ guarantees that `futhark doc` will work on otherwise healthy programs is a boon, eg. for generating documentation for https://futhark-lang.org/pkgs/.

**Comment by athas** [comment]
Yes, if the compiler doesn't fail on invalid doc comments, then it is unlikely that anyone will notice until `futhark-docbot` looks at them.  This happened many times in the Futhark compiler itself.

**Comment by Munksgaard** [comment]
In the case of the Futhark compiler, I feel like that could easily be fixed by adding a  `futhark doc --check` command and running it as part of the CI, or what?
