### ISSUE TITLE
Intra-group version (chosen per default) crahes with error code -5 (out of resources) 

### ISSUE THREAD

**Issue by mortvest** [diku-dk/futhark#1362]
This [program](https://gist.github.com/mortvest/39e5a93026264b220479de06a34228dc) (batched radix sort) crashes on 640 < n < 1001 on GPU04, GPU03 and GPU02. OpenCL backend only.

**Comment by athas** [comment]
Probably runs out of registers.  If so, we cannot fix it.

**Comment by mortvest** [comment]
If it is the case, why does it run fine with the cuda backend?

**Comment by athas** [comment]
Because NVIDIAs OpenCL compiler does register allocation with the assumption that kernels will never be launched with more than some number of threads (no idea about the specific number).  Their CUDA compiler does not make this assumption.  I have no idea why.

**Comment by mortvest** [comment]
Alright, makes sense

**Comment by mortvest** [comment]
If this number is known, however, can we make sure that the intra-group version is not chosen per default?

**Comment by athas** [comment]
I think this is fixed now, as we generate annotations in the kernels that indicate the group size.
