### ISSUE TITLE
futhark pkg sync fails on newly created repository

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1364]
To reproduce:

```
$ mkdir foo

$ cd foo

$ futhark pkg init .
Created directory lib/..
Wrote futhark.pkg.

$ futhark pkg add github.com/diku-dk/cpprandom
Added new required package github.com/diku-dk/cpprandom 1.3.0.
Remember to run 'futhark pkg sync'.

$ futhark pkg sync
futhark: lib~old/.: renameDirectory:renamePath:rename: resource busy (Device or resource busy)
```

**Comment by athas** [comment]
`.` is a really terrible name for a package path.  We should probably detect such cases and reject them in input validation.

**Comment by Munksgaard** [comment]
I guess the problem is, that it's not really clear that `futhark pkg init` shouldn't be used when you just want to _use_ packages, only when you want to _create_ a package. In hindsight, it is clear that my `init` is to blame, but the documentation output from `futhark pkg` and `futhark pkg init` doesn't really make that clear.

**Comment by Munksgaard** [comment]
Thanks!
