### ISSUE TITLE
Error in memory reuse

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1371]
tests/issue1328.fut fails because an allocation inside a SegThread-level op is moved into the enclosing SegGroup-level op.  Probably we should not merge memory blocks across nested SegThread ops (this is a bit too conservative perhaps, but we'd need to do a kind of expansion otherwise).

**Comment by athas** [comment]
Another way of looking at this bug is that it invalidly hoists memory allocations from nested SegThreads to the enclosing SegGroups.  This is never safe, and is the reason we have memory expansion in the first place.

**Comment by Munksgaard** [comment]
Yeah, I think the obvious fix is to disallow merging between memory blocks, as you say. Allowing that was not the purpose anyway.

**Comment by athas** [comment]
I suspect this is the bug that causes some of the AD code to not validate.  Do you think it will be easy to fix?
