### ISSUE TITLE
Rename some concepts to be more conventional or less unclear

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1378]
Some of our internal names were always dumb, and others have not kept up with the times and are now misleading.

* [ ] The `Binder` should be renamed `Builder` ("AST builder" is a relatively well known concept - and I think LLVM uses this term as well).
* [ ] The `Kernels` representation should be renamed `GPU`, and `KernelsMem` renamed `GPUMem`.
* [ ] Maybe "lore" should also be renamed to "representation" (and the type parameter `lore` to `rep`).

Others?

It's best to do these things when there are no large outstanding branches, which is the case now.

**Comment by Munksgaard** [comment]
Great idea. How about `Decorations` and the associated type parameter `dec`? I'm not sure what a better name would be though.

**Comment by athas** [comment]
Perhaps that is best, since `Decorations` is the name of the core type class that these things must implement.  But maybe we should change that to `Representation` or `Rep` instead?

**Comment by Munksgaard** [comment]
Wouldn't that clash with your suggested renaming of "lore"?

**Comment by athas** [comment]
I am renaming `Decorations` to `RepTypes`.

**Comment by athas** [comment]
Closed in #1379 - at least the big ones.  We can improve other things in the future.

**Comment by Munksgaard** [comment]
What about [`Wise`](https://hackage.haskell.org/package/futhark-0.19.6/docs/Futhark-Optimise-Simplify-Lore.html#t:Wise)?

**Comment by athas** [comment]
I considered that one too but couldn't come up with better names for its various types, so I left it for later.
