### ISSUE TITLE
Futhark -r gives strange timings

### ISSUE THREAD

**Issue by philass** [diku-dk/futhark#1380]
When testing on mandelbrot.fut from the futhark-benchmarks, and using the C library with the following dataset 
```bash
echo "4000 4000 -0.7f32 0f32 3.067f32 100 16f32" > data.in
```
And compiling with C backend
```bash
futhark c mandelbrot.fut
```
Running 
```bash
cat data.in | ./mandelbrot -t /dev/stdout -r3                                                                                ✔  at 19:25:00 
4292911
2083617
2090395
28u32
```
Where as running not with /dev/stdout gives
```bash
cat data.in | ./mandelbrot -t out.txt -r3 && cat out.txt
28u32
4273640
4316172
4283673
```
This difference in stdout from other files is replicable everytime I run the snippets. 

I am running on MacOS, and compiling with clang as default C compiler.

**Comment by philass** [comment]
Ok this one has really thrown me for a loop. Some more clues....

Running the following command
```bash
clang -O3 mandelbrot.c && echo 2000 2000 -0.7f32 0f32 3.067f32 100 16f32 | time ./a.out -t out.txt -r3 && cat out.txt
```

Gives the following
```
29u32
./a.out -t out.txt -r3  4.29s user 0.01s system 96% cpu 4.459 total
1072456
1073721
1072901
```
However when we add a useless print statement to the first line of the futhark_entry_main function
```C
...
int futhark_entry_main(struct futhark_context *ctx, uint32_t *out0, const
                       int32_t in0, const int32_t in1, const float in2, const
                       float in3, const float in4, const int32_t in5, const
                       float in6)
{
    printf("Random shit\n");
    int32_t screenX_11715;
...
```
And running the same command as before
```bash
gcc -O3 mandelbrot.c && echo 2000 2000 -0.7f32 0f32 3.067f32 100 16f32 | time ./a.out -t out.txt -r3 && cat out.txt
```
Gives the following
```
1 warning generated.
Random shit
Random shit
Random shit
Random shit
29u32
./a.out -t out.txt -r3  2.08s user 0.01s system 94% cpu 2.202 total
520762
518662
520557
```
So something about forcing a print to stdout, changes the speed up execution by 2x??? And its not a trivial amount of time either.

I don't know what to believe anymore. Are these issues replicable on a linux distro and with GCC?

**Comment by athas** [comment]
What happens if you do more runs than 3?  Which results are produced by `futhark bench`?

**Comment by philass** [comment]
Futhark bench gives the faster results

**Comment by philass** [comment]
When running with more than 3 (and in this case 8), I get the following,

```
clang -O3 lol.c && echo 2000 2000 -0.7f32 0f32 3.067f32 100 16f32 | time ./a.out -t out.txt -r8 && cat out.txt
29u32
./a.out -t out.txt -r8  9.57s user 0.02s system 98% cpu 9.699 total
1063008
1063465
1062404
1062008
1060015
1061143
1065100
1076470
```

and with the print statement
```
clang -O3 lol.c && echo 2000 2000 -0.7f32 0f32 3.067f32 100 16f32 | time ./a.out -t out.txt -r8 && cat out.txt

Random shit
Random shit
Random shit
Random shit
Random shit
Random shit
Random shit
Random shit
Random shit
29u32
./a.out -t out.txt -r8  4.67s user 0.01s system 96% cpu 4.869 total
521032
519684
520336
521905
521083
518632
521206
517147
```

**Comment by philass** [comment]
Yes will do! 

This is something I'll take a deep dive into once the thesis is submitted.

**Comment by philass** [comment]
Clearly not a Futhark issue, but something else going on. I'll close this. I updated my Mac and no longer an issue.
