### ISSUE TITLE
The API generated by the WASM backends is unsafe

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1402]
The API requires manual memory management, which is unavoidable because JavaScript does not support finalisers (wtf!).  However, if the user happens to use an object after it has been "freed", we will end up reading garbage memory (albeit still sandboxed), and this *is* avoidable.  The proxy classes FutharkArray and FutharkOpaque should contain a "valid" field that is set to false when they are freed, and which we check before using them.  This will allow us to throw an exception instead of corrupting memory.

**Comment by philass** [comment]
Can we close this or is there still more to do here?

**Comment by athas** [comment]
Closed in #1427.  Let's hope we don't have to reopen it.

**Comment by kfl** [comment]
@athas FYI JavaScript *does* support finalizers. The [ECMAScript spec for `FinalizationRegistry`](https://tc39.es/ecma262/multipage/managing-memory.html#sec-finalization-registry-objects) and the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry). And if it's really important to support old IE, I guess that you could roll your own with [`WeakMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap).
