### ISSUE TITLE
WebAssembly tests for the browser

### ISSUE THREAD

**Issue by philass** [diku-dk/futhark#1406]
Right now we currently only test the WebAssembly backends with Node locally.

It would make sense to also add some tests that run in the browser. We should look at headless Chrome and Firefox and see if there is a way we can use them for writing some tests that run with github actions.

**Comment by ruler501** [comment]
Testing with the worker environment would probably also be good. The webasm code I use in my projects is compiled aas either `ENVIRONMENT=node,worker` or `ENVIRONMENT=browser,worker`.

**Comment by philass** [comment]
There are still more tests to be added. But I am comfortable closing this as we now have an example test running the WASM/Javascript backend in the browser.
