### ISSUE TITLE
Benchmark not finishing (install issue?)

### ISSUE THREAD

**Issue by sebsheep** [diku-dk/futhark#1411]
Hello,

I'm trying futhark for the first time. I tried the following benchmark test https://futhark-lang.org/examples/benchmarking.html 

The first command (running tests on the CPU) is working.

The second command however hang for ever (even when I reduce the dataset to only have the `100` input). I suspect an installation issue.

My config:
* OS: Debian  4.19.194-1, 
* GPU:  Intel Corporation HD Graphics 620 (rev 02) 

For now I have installed the following Debian packages:
* beignet-opencl-icd
* ocl-icd-opencl-dev

What am I doing wrong?

**Comment by athas** [comment]
This is probably because something is wrong with the OpenCL setup.  Try compiling the program with `futhark opencl sumsquares.fut`, and then running it manually as

```
$ echo 1000i32 | ./sumsquares -D
```

It'll print a bunch of debugging information, which will let you pinpoint why it is freezing.  The most common cause is that Futhark picks a defective OpenCL backend.  Unless told otherwise, it will just pick the first one.  Some Linux systems have the Mesa OpenCL ICD installed, which is quite flaky.  I also remember that Intel has deprecated the Beignet ICD and replaced it with something that I think is called "compute-runtime" (I don't have an Intel GPU these days so I don't remember the specifics).  You can try that instead.  You can check the contents of `/etc/OpenCL/vendors` or run the `clinfo` tool to see which OpenCL backends are available.

**Comment by sebsheep** [comment]
Ok, thank you for your answer @athas. So I've installed `compute-runtime` following instructions from here: https://github.com/intel/compute-runtime/releases
(and removed the `beignet` thing)

Running `echo 1000i32 | ./sumsquare -D` outputs (and then freeze):
```
Using platform: Intel(R) CPU Runtime for OpenCL(TM) Applications
Using device: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
./sumsquare: sumsquare.c:4159: OpenCL call
  clCreateContext_error
failed with error code -2 (Device not available)
```

My `clinfo` gives that:
```
Number of platforms                               2
  Platform Name                                   Intel(R) CPU Runtime for OpenCL(TM) Applications
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.1 LINUX
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64 cl_khr_image2d_from_buffer cl_intel_vec_len_hint 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.1 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_depth_images cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_media_block_io cl_intel_driver_diagnostics cl_intel_device_side_avc_motion_estimation cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_khr_fp64 cl_khr_subgroups cl_khr_il_program cl_intel_spirv_device_side_avc_motion_estimation cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_intel_motion_estimation cl_intel_advanced_motion_estimation cl_intel_va_api_media_sharing 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             INTEL
```

so as you said, it looks like it picks up the first driver and ignore the second. How can I tell futhark using this second one?

**Comment by athas** [comment]
[Device selection is documented here.](https://futhark.readthedocs.io/en/latest/usage.html#opencl-specific-options).  In your case, you'd pass `-pGraphics` to the executable, or `--pass-option=-pGraphics` to `futhark bench`.

**Comment by athas** [comment]
Assuming this was a driver issue.
