### ISSUE TITLE
C clz implementation undefined behaviour

### ISSUE THREAD

**Issue by Snektron** [diku-dk/futhark#1415]
The current C implementation of clz functions check whether the most significant bit is set by checking whether the sign bit is set after a shift. When compiling with ubsan enabled, this creates an error, as signed overflow is undefined behaviour.

https://github.com/diku-dk/futhark/blob/d5c85bf96d0944ac5eb375b0fa9e998888f1877c/src/Futhark/CodeGen/Backends/SimpleRep.hs#L576-L585

The simplest way to fix it is to perform the shift on the unsigned version instead:
```c
x = (int64_t)(((uint64_t) x) << 1)
```

Alternatively, both gcc and clang implement (a variation of) this operation via __builtin_clz.

**Comment by athas** [comment]
The reason we don't use `__builtin_clz` is because it has undefined behaviour for an input of 0, and doesn't work for 64-bit numbers.  But maybe we can still build something on top of it.
