### ISSUE TITLE
Struggle compiling programs on Windows due to MSVC incompatability

### ISSUE THREAD

**Issue by pema99** [diku-dk/futhark#1447]
I'm trying to compile some Futhark programs on Windows using Futhark 0.20.0. I'm running into similar issues with both the Cuda and OpenCL backends.

Compiling the Futhark program works fine with the following `futhark cuda --library matmul.fut`.

When I try to compile the resulting C files, either using `nvcc` or `cl` directly, I get errors due to features being used in the output code which are not supported by MSVC.

For example, the following line:
```static void futhark_panic(int eval, const char *fmt, ...) __attribute__((noreturn));```
Causes an error `matmul.c(147): error C2061: syntax error: identifier '__attribute__'` because of the GCC style attribute.

Another example, variadic macros:
```#define CHECK_ERR(err, msg...) check_err(err, 0, __func__, __LINE__, msg)```
Causes `matmul.c(193): error C2010: '.': unexpected in macro parameter list` since MSVC uses `__VA_ARGS__` for this instead.

And a final example:
```  __uint128_t aa = a;```
Causes `matmul.c(1457): error C2065: '__uint128_t': undeclared identifier`

Is MSVC completely unsupported? Is there a way to force Futhark to compile in some sort of MSVC compatability mode?

**Comment by athas** [comment]
MSVC worked once, but since it is not tested in CI, it's a given that support bitrots rapidly.  At one point support was quite difficult because MSVC supported very little of C99, but the errors you list don't look too difficult to address.  I'm reluctant to try to fix something I cannot test myself, though.

I think most people who use Futhark on Windows just use WSL, which I understand even has GPU support nowadays.

**Comment by pema99** [comment]
> MSVC worked once, but since it is not tested in CI, it's a given that support bitrots rapidly. At one point support was quite difficult because MSVC supported very little of C99, but the errors you list don't look too difficult to address. I'm reluctant to try to fix something I cannot test myself, though.
> 
> I think most people who use Futhark on Windows just use WSL, which I understand even has GPU support nowadays.

Oh really? I would love to use WSL, but I was under the belief that it wouldn't let me use Cuda or OpenCL, defeating the point. Maybe this used to be case and isn't any longer?

**Comment by athas** [comment]
I have not tried it myself, but it was in the news some months ago, and seems well documented: https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by pema99** [comment]
> I have not tried it myself, but it was in the news some months ago, and seems well documented: https://docs.nvidia.com/cuda/wsl-user-guide/index.html

Thank you. I'll look into this. FWIW, those errors were the only ones preventing a build, though the test program was fairly tiny. I may do some more investigation into which other issues, if any, are blocking on larger programs.

**Comment by athas** [comment]
Closing this until someone specifically needs MSVC compatibility.
