### ISSUE TITLE
`evalPrimExp` gives wrong results

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1448]
```haskell
λ> evalPrimExp (\_ -> Nothing) (BinOpExp (Sub Int64 OverflowUndef) (ValueExp (IntValue (Int64Value 61))) (UnOpExp (Complement Int64) (UnOpExp (Complement Int64) (UnOpExp (Complement Int64) (ValueExp (IntValue (Int64Value 0)))))) :: PrimExp VName)
Just (IntValue (Int64Value 62))
```

I'm pretty sure `61 - (-(-(-(0))))` is supposed to give 61.

**Comment by Munksgaard** [comment]
Actually, this is much simpler:

```
evalPrimExp (\_ -> Nothing) (((UnOpExp (Complement Int64) (ValueExp (IntValue (Int64Value 0))))) :: PrimExp VName)
Just (IntValue (Int64Value (-1)))
```

`Futhark.IR.Primitive.doComplement uses [`complement`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Bits.html#v:complement), for which `complement 0 == -1`. Is that intended behavior? I notice that when I write `-(0)` in the futhark repl, I get 0 as expected.

**Comment by Munksgaard** [comment]
Or is it because unary `-` isn't actually `Complement` but is turned in to `0 - `? I'm guessing that's the case.

**Comment by athas** [comment]
To clarify: `Complement` is not arithmetic negation, it is bitwise negation.  There is no UnOp for arithmetic negation in the core language.

**Comment by Munksgaard** [comment]
> There is no UnOp for arithmetic negation in the core language.

This was the part that confused me. Thanks for clearing it up for me.
