### ISSUE TITLE
OpenCL error : Program uses double-precision floats

### ISSUE THREAD

**Issue by philass** [diku-dk/futhark#1449]
I was doing some benchmarks from `futhark-benchmarks`. And I ran into the following issue.

For the following program `scan.fut`

```
entry sum_iota_f64 n = i64.i32 n |> iota |> map f64.i64 |> scan (+) 0
```
I compile and run with
```
futhark opencl scan.fut 
./scan: Program uses double-precision floats, but this is not supported on the chosen device: Intel(R) UHD Graphics 630
```

I am running this on MacOS.

**Comment by philass** [comment]
Without specifying device
```
./scan --entry-point sum_iota_f64 
./scan: Program uses double-precision floats, but this is not supported on the chosen device: Intel(R) UHD Graphics 630
```
Specifying Intel
```
 ./scan --entry-point sum_iota_f64 -d Intel
10
./scan: scan.c:6333: OpenCL call
  clEnqueueNDRangeKernel(ctx->opencl.queue, ctx->sum_iota_f64ziscan_stage1_4829, 1, ((void*)0), global_work_sizze_4893, local_work_sizze_4897, 0, ((void*)0), ctx->profiling_paused || !ctx->profiling ? ((void*)0) : opencl_get_event(&ctx->opencl, &ctx->sum_iota_f64ziscan_stage1_4829_runs, &ctx->sum_iota_f64ziscan_stage1_4829_total_runtime))
failed with error code -54 (Invalid work group size)
```
Specifying Radeon
```
 ./scan --entry-point sum_iota_f64 -d Radeon
10
[0.000000f64, 1.000000f64, 3.000000f64, 6.000000f64, 10.000000f64, 15.000000f64, 21.000000f64, 28.000000f64, 36.000000f64, 45.000000f64]
```

**Comment by philass** [comment]
Ok so running the following program
```
#include "test.h"


int main() {
  struct futhark_context_config* cfg = futhark_context_config_new();
  futhark_context_config_list_devices(cfg);
}
```
gives

```
Platform: Apple
[0]: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
[1]: Intel(R) UHD Graphics 630
[2]: AMD Radeon Pro 555X Compute Engine
```
I guess device 0 is probably never meant to work. On my mac the device selection seems to default to the `Intel(R) UHD Graphics 630`. And it seems that it doesn't support double precision floats. So maybe a workaround is for the device to automatically select the Radeon, and not default to the Intel UHD.

I'm guessing there isn't really a way for the Intel GPU to ever properly handle `f64` programs if it doesn't support those instructions

**Comment by Munksgaard** [comment]
Which runtime are you using? I had similar errors on my Intel(R) Gen9 HD Graphics NEO when using beignet until i upgraded to intel-compute-runtime. Now I can use doubles just fine.

**Comment by Munksgaard** [comment]
> Ok so running the following program
> 
> ```
> 
> ```

And by the way, you can use the `--list-devices` flag to a futhark program compiled with opencl to get the same list.

**Comment by philass** [comment]
> Which runtime are you using? I had similar errors on my Intel(R) Gen9 HD Graphics NEO when using beignet until i upgraded to intel-compute-runtime. Now I can use doubles just fine.

I'm not sure how to see which Intel runtime I am using. I'll look into it and try and see if upgrading fixes the problem. Thanks for sharing.

> And by the way, you can use the --list-devices flag to a futhark program compiled with opencl to get the same list.

Thanks for that detail! Thats super useful.

I still think it makes sense to blacklist the Intel UHD GPU as I do in #1450 . From my few experiments the AMD GPU has 3x better performance. I think most people who stumble on Futhark and test their code won't realize that they are defaulting to the less performant GPU on their mac. And they can still set the device to the Intel GPU, if they so desire even if it is blacklisted.

**Comment by Munksgaard** [comment]
Surely it's a good fallback if there is no dedicated GPU available, as in my case?

**Comment by philass** [comment]
Thats a good point. I should probably change my PR such that it'll look for all other GPUs and fallback to the Intel if its the only viable option that exists.

**Comment by athas** [comment]
This is by design.  To avoid magic, Futhark always picks the first device (the blacklist is an unfortunate workaround of a uniquely dysfunctional device).  This shows up sufficiently rarely that I don't think further magic is justified.
