### ISSUE TITLE
futhark test reporting wrong result counts

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1452]
futhark test handles structure tests unintuitively. For instance, given the following file:

```futhark
-- ==
-- structure cpu { Alloc 42 }
-- structure gpu { Alloc 42 }

let main (x: i64) =
  x
```

I get the following result:

```
$ futhark test --backend=c  ~/tmp/foo.fut
/home/munksgaard/tmp/foo.fut:
Compiling with --backend=c:
Checking metrics:
Alloc should have occurred 42 times, but did not occur at all in optimised program.
┌──────────┬────────┬────────┬───────────┐
│          │ passed │ failed │ remaining │
├──────────┼────────┼────────┼───────────┤
│ programs │ 0      │ 1      │ 0/1       │
├──────────┼────────┼────────┼───────────┤
│ runs     │ 1      │ 1      │ 0/2       │
└──────────┴────────┴────────┴───────────┘
```

I would've expected two failing tests and zero passed tests, instead I get one of each?

Things get a little better when using `--no-terminal`:

```
$ futhark test --no-terminal --backend=c  ~/tmp/foo.fut
(0 failed, 0 passed, 1 to go).
Started testing /home/munksgaard/tmp/foo.fut (0 failed, 0 passed, 1 to go).

/home/munksgaard/tmp/foo.fut:
Compiling with --backend=c:
Checking metrics:
Alloc should have occurred 42 times, but did not occur at all in optimised program.
(1 failed, 0 passed, 0 to go).
```

But I would still expect two failures instead of one.

**Comment by Munksgaard** [comment]
Wait, this has nothing to do with structure tests, it's just weird reporting from futhark test overall.

This program exhibits the same thing:

```futhark
-- ==
-- input { 42i64 }
-- output { 43i64 }
-- input { 42i64 }
-- output { 43i64 }

let main (x: i64) =
  x
```

I would expect it to report two errors, or at least one failure and one test that hasn't been run.

**Comment by athas** [comment]
The `--no-terminal` summary just mentions how many files contained failing tests.  With respect to the counting of "runs", that's something @zfnmxt implemented years ago.
