### ISSUE TITLE
Add an online futhark "playground"

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1454]
Many languages have the ability to run in the browser, giving users a kind of "playground" for running small samples of code. It would be nice if we had something similar.

Examples:

 - https://play.flix.dev/
 - https://play.rust-lang.org/
 - https://play.golang.org/
 - https://elm-lang.org/try

**Comment by Munksgaard** [comment]
Extra points being usable for reporting ICEs. Eg. if I found a compiler bug, I would like to be able to save that as a playground link and post it here, with the correct error message being produced by the playground.

**Comment by Munksgaard** [comment]
Simplest possible design: A frontend that sends code stumps to a backend. The backend runs the code using the latest nightly and returns the result.

**Comment by Munksgaard** [comment]
However, it would be nice if we could also run literate programs, test datasets and so on.

**Comment by kfl** [comment]
Don't forget <http://try.mosml.org/> 😉 

(Alas, it does not support playground links and it seems that SSL certificate is outdated.)

**Comment by Munksgaard** [comment]
Perhaps something for @WilliamDue?

**Comment by WilliamDue** [comment]
> Perhaps something for @WilliamDue?

Could be fun, would Hakyll be used?

**Comment by athas** [comment]
Our new student programmer will be working on this.  The first design question is quite basic: where should the code run?  In the browser, or talk to some backend server?  I strongly suspect the latter is most feasible (although it has its own problems).  For a start, look at existing such playgrounds/REPLs and figure out how they are designed.  Where do *they* run the code?

**Comment by Munksgaard** [comment]
[Here](https://github.com/integer32llc/rust-playground#resource-limits) is some information about the limitations imposed on the [Rust playground](https://play.rust-lang.org). I'm not sure how that is enforced, but presumably one could glean that information from the repo somewhere.

**Comment by Munksgaard** [comment]
As compromise, would it make sense to _compile_ the program on our machines, but _run_ it in the browser, using e.g. our wasm backend? Would that even work?

**Comment by athas** [comment]
That sounds like the worst of all worlds.  I'd rather just have us sandbox the execution in a sensible way.  Futhark is a pure language so surely it can't be very difficult.

**Comment by dominicmkennedy** [comment]
Is there anyone currently working on this issue? If not I may begin prototyping some solutions for it. 
Additionally is the plan for the playground to exist on the [futhark-lang](futhark-lang.org) site or at a different location? 
Also are there any particular technologies/languages that are preferred for doing the plumbing between the compiler running on a server, and the UI in the frontend?

**Comment by athas** [comment]
Yes, it is actually here: http://playground.futhark-lang.org/

...except that the server seems to have crashed without anyone noticing.
