### ISSUE TITLE
Inconsistent definition of identifiers in the language reference

### ISSUE THREAD

**Issue by larshum** [diku-dk/futhark#1463]
The current version of the [language reference](https://github.com/diku-dk/futhark/blob/d29d21f747a7e9da4a5ddf057a7e4f709c5a6e6a/docs/language-reference.rst#identifiers-and-keywords) defines an identifier as
```
`letter` (`letter` | "_" | "'")* | "_" `id`
```

However, the current definition of an identifier in the [lexer](https://github.com/diku-dk/futhark/blob/d29d21f747a7e9da4a5ddf057a7e4f709c5a6e6a/src/Language/Futhark/Parser/Lexer.x#L51) is
```
[a-zA-Z] [a-zA-Z0-9_']* | "_" [a-zA-Z0-9] [a-zA-Z0-9_']*
```
which accepts digits.

**Comment by athas** [comment]
Good catch, I will fix the reference.
