### ISSUE TITLE
Segfault w/ non-associative scan in multicore backend

### ISSUE THREAD

**Issue by maedoc** [diku-dk/futhark#1468]
with the following program,
```futhark
type scan_state [n] = { iter: i64, large: [n]f32, small: f32 }

let scanner [n] (l:scan_state[n]) (r:scan_state[n]): scan_state[n] = 
    let new_large = map (+1f32) l.large
    let new_small = r.small * (reduce (+) 0f32 new_large)
    in
    {iter=l.iter, large=new_large, small=new_small}

-- input { 50000i64 }
let main (iters: i64): []f32 =
    let init_large = tabulate 400000 f32.i64
    let ne = {iter=0i64, large=init_large, small=0f32}
    let as = tabulate iters (\i -> {iter=i, large=init_large, small=0f32})
    let results = scan scanner ne as
    in -- results is big, whereas we just wanted to accumulate the .small field
    map (\state -> state.small) results
```
the multicore backend segfaults while the c backend doesn't,
```
~/src/futhark futhark multicore scanq.fut
~/src/futhark echo 50000i64 | ./scanq | cut -f1 -d,
~/src/futhark echo 50000i64 | ./scanq
Segmentation fault
~/src/futhark futhark c scanq.fut
~/src/futhark echo 50000i64 | ./scanq | cut -f1 -d,
[0.000000f32
```
As pointed out in the gitter channel, the function `scanner` is not associative.

**Comment by maedoc** [comment]
I just reread from the prelude docs,

> The function op must be associative. If it is not, the return value is unspecified

so I guess this segfault is not really a big deal, and the program doesn't do want I want it to.  Feel free to close.

**Comment by athas** [comment]
"Unspecified" does not mean "segfault".  This isn't C++!

**Comment by athas** [comment]
This program is trying to create a 75GiB array.  Maybe it just runs out of memory?

**Comment by athas** [comment]
With the `c` backend, the compiler (correctly) deduces that the only possible result is an array of zeroes, so it doesn't manifest the large array.  This does not happen with the `multicore` backend.  I think the root problem here is just running out of memory, which on Linux often manifests as a segmentation fault.

It's a good question whether we should handle OOM more gracefully, of course, but I'm not sure how we could.

**Comment by maedoc** [comment]
True, choosing problems sizes such that `results` fits in memory, it runs without segfaulting.   Thanks for the answer about the c backend, that's pretty cool.

> whether we should handle OOM more gracefully, of course, but I'm not sure how we could.

a panic with a message would be a nicer alternative

**Comment by maedoc** [comment]
> With the c backend, the compiler (correctly) deduces that the only possible result is an array of zeroes

is there a flag to pass during compilation to check if this happens? or you have to know the compiler?

**Comment by athas** [comment]
> a panic with a message would be a nicer alternative

The problem is that Linux uses [overcommit](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting), so it's not straightforward to know when you run out of memory.  To be completely robust you need to install a signal handler, which is not viable for Futhark.

> is there a flag to pass during compilation to check if this happens? or you have to know the compiler?

I checked the compiler output.  It's not some particularly clever analysis, just a consequence of dead code elimination, so it's not really clear to me what the compiler should report.  It doesn't know whether it is deleting more code than "expected".  In this case the root cause is (I think) that `small` is initially zero, and is then multiplied with every new value for `small`, always yielding zero.

**Comment by maedoc** [comment]
ok thanks, makes sense on both points.  again, feel free to close

**Comment by athas** [comment]
We'll probably need to think a bit about OOM at some point in the future.  It works on the GPU backends (which don't use overcommit), so it shouldn't be too hard to make it work on the multicore backend as well.
