### ISSUE TITLE
Dumping OpenCL source requires compiler

### ISSUE THREAD

**Issue by maedoc** [diku-dk/futhark#1474]
I'm trying to use an external CL compiler (with `--dump-opencl` and `--load-opencl-binary`), but a small challenge came up:
```
$ ./futhark-nightly-linux-x86_64/bin/futhark opencl  mapreduce.fut
$ ./mapreduce --dump-opencl=mapreduce.cl
./mapreduce: mapreduce.c:4730: OpenCL call
  clBuildProgram_error
failed with error code -3 (Compiler not available)
```
of course I dump the source on a different machine and then upload, so it's not a blocker.

**Comment by athas** [comment]
Are  you sure the dumping didn't succeed anyway?

We probably should not even bother compiling in these cases, of course.

**Comment by maedoc** [comment]
Ah indeed dumping succeeded.  I guess this can be closed.

**Comment by athas** [comment]
This is fixable but slightly annoying to do, so I'll close it until someone really cares about it.
