### ISSUE TITLE
Add an option to load test blocks from another file(s)

### ISSUE THREAD

**Issue by mortvest** [diku-dk/futhark#1488]
Currently, test blocks for a Futhark program should be placed in the same file as the program. Can we add a option for `futhark bench`, `futhark test` and `futhark autotune` to load the test blocks from another file(s)?

Something like `futhark autotune --test-data=foo1.test --test-data=foo2.test foo.fut`

**Comment by mortvest** [comment]
It sounds like the most straightforward approach

**Comment by athas** [comment]
@mortvest I have not tested the `autotune` part of this very well.  Let me know if you need further changes.
