### ISSUE TITLE
Internal compile error.

### ISSUE THREAD

**Issue by ianmbloom** [diku-dk/futhark#1490]
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'simplify':
In function searchUvTree_6393
When checking function body
In expression of statement
  {defunc_1_map_res_43130 : ({}, [s_39965]f32),
   defunc_1_map_res_43131 : ({}, [s_39965]f32),
   defunc_1_map_res_43132 : ({}, [s_39965]f32),
   defunc_1_map_res_43133 : ({}, [s_39965]f32),
   defunc_1_map_res_43134 : ({}, [s_39965]f32),
   defunc_1_map_res_43135 : ({}, [s_39965]f32)}
In expression of statement
  {rootStack_res_43157 : ({}, i64),
   rootStack_res_43158 : ({}, [x_44340]i64)}
Use of unknown variable rootStack_arg_43156.

This occurs when I'm compiling this repository: https://github.com/ianmbloom/futharkTreeExample

**Comment by ianmbloom** [comment]
It looks like I solved this by making the originating vector of the uniqueness type have a set size so the line:
`let newStack   't (i:t) (lg:i64):(i64,[]t) = (0,replicate (lg+1) i)`
became:
`let newStack   't (i:t) (lg:i64):(i64,[lg]t) = (0,replicate lg i)`

**Comment by athas** [comment]
OK, it's a little about uniqueness, but not because you are doing anything wrong.
