### ISSUE TITLE
futhark ad: scatter not supported, filter does not compile

### ISSUE THREAD

**Issue by coancea** [diku-dk/futhark#1496]
1. Filter does not compile with reverse mode, unsupported scanomap case:
   (the problem seems to be the map-scan fusion; if I break that in customised code, it works)

```
let objFun [n] (pivot: f32) (arr: [n]f32) =
    let tmp = filter (>pivot) arr
            |> opaque
    in  f32.sum tmp

let main [n] (pivot: f32) (arr: [n]f32) =
    vjp (objFun pivot) arr 1.0
```

2. scatter is not yet supported, so I cannot compile the elman-batch (which I recently added to futhark-ad).
    It is also needed for sparse-kmeans.
    Should I add it locally on my branch? (it is quite nicely implemented in troels-ad branch, if I may say so).

**Comment by athas** [comment]
`scatter` is supported now.
