### ISSUE TITLE
Repeated opens of parametric module causes ICE

### ISSUE THREAD

**Issue by Programmerino** [diku-dk/futhark#1518]
I tested this bug on versions `0.20.3` and the latest git master `6387144466b5ed59188f9a9a4eb3fb953c4f9f5f` on a Linux x86-64 machine and reproduced it both times. The error occurs on all backends

Failing code:
```futhark
module type ModuleType = {
    val someVal: i32
}

module moduleinst: ModuleType = {
    let someVal = 0i32
}

module ModuleTypeOps (x: ModuleType) = {
    let mySomeVal = x.someVal
}

open ModuleTypeOps moduleinst
open ModuleTypeOps moduleinst

entry main = mySomeVal
```
Compiler error:
```
[  +0.000029] Reading and type-checking source program
[  +0.305221] Defunctorising
[  +0.000988] Monomorphising
[  +0.026944] Lifting lambdas
[  +0.006342] Defunctionalising
[  +0.000167] Converting to core IR
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
BuilderT.lookupType: unknown variable someVal_4476
CallStack (from HasCallStack):
  error, called at src/Futhark/Builder.hs:107:18 in futhark-0.21.0-E97DCIOoGw91VG1PpMePDI:Futhark.Builder
```

I provided the most minimal case I could find, albeit unrealistic, but consider the more complicated case of:
```futhark
module type dummy = {}
module dummyinst: dummy = {}

module type ModuleType = {
    val someVal: i32
}

module moduleinst: ModuleType = {
    let someVal = 0i32
}

module ModuleTypeOps (x: ModuleType) = {
    let valGetter = x.someVal
}

module HigherModule (unused: dummy) = {
    open ModuleTypeOps moduleinst
    let myGet = valGetter
}

open ModuleTypeOps moduleinst

module test = HigherModule dummyinst -- if this is placed before the open, no errors

entry main = test.myGet
```
which causes the same issue, but looks a lot more sane for somebody to actually write

**Comment by athas** [comment]
Static evaluation of modules has got to be the few hundred lines in the compiler with the highest defect density.  Those substitution maps are so impenetrable that a lot of the code was written without a completely firm understanding of all cases.

How come you're using the module system more than it has apparently been pushed before?  Usually people who really like modules go for SML or OCaml.

**Comment by Programmerino** [comment]
I'm having a competition with my friends to see who can write the best chess engine, and my first step has been porting [Gigantua](https://github.com/Gigantua/Gigantua) (a really fast chess move generator) to Futhark which makes heavy use of templates. I figured that the module system should get me close enough, and hopefully with the same performance optimizations that templates have (correct me if I'm wrong).

**Comment by athas** [comment]
Sounds about right; templates are also implemented by static evaluation.
