### ISSUE TITLE
Provide a mechanism to exclude/include certain inputs in a `futhark-test` test case.

### ISSUE THREAD

**Issue by zfnmxt** [diku-dk/futhark#1526]
At the moment, there isn't a nice way to, e.g., only run inputs `a` and `b` or run all inputs but input `c` in the example below.
```
-- ==
-- entry: my_rad_function
-- input a
-- input b
-- input c
-- input d
```

**Comment by athas** [comment]
We sort of did that here: https://github.com/diku-dk/futhark/issues/1488

**Comment by athas** [comment]
I'm going to assume the #1488 solution is good enough.
