### ISSUE TITLE
f**.max and f**.min functions and NaN values in the interpreter

### ISSUE THREAD

**Issue by mortvest** [diku-dk/futhark#1528]
Currently, the futhark interpreter evaluates `f**.min 1f** f**.nan` to `f**.nan`, while `f**.min f**.nan 1f**` is evaluated to `1f**`. The same holds for the `f**.max` (with operands swapped).

In both C and all the GPU backends, the snippet would be compiled to a call to the `fmax()` [function](https://en.cppreference.com/w/c/numeric/math/fmax), which returns the non-NaN operand, unless both of them are NaN.

**Comment by athas** [comment]
`fmax()` does that?  I had no idea.  Bizarre.

**Comment by mortvest** [comment]
Yep, it is one of the few floating point functions that does not propagate the NaNs. Some advanced math libraries such as Python's numpy have multiple versions of the max/min functions. One that propagates and one that does something akin to fmax().
