### ISSUE TITLE
Reverse AD should support the entire IR.

### ISSUE THREAD

**Issue by zfnmxt** [diku-dk/futhark#1530]
As per Cosmin's awake-for-the-last-30-hours insight, we should be able to handle differentiation of `UpdateAcc`.

**Comment by coancea** [comment]
The citation is wrong. Fritz has paternity of that idea -- I have heard 
it from him, but did not quite understood it when he ennounced it (it 
was entirely my fault he said it quite clearly).

Cosmin

**Comment by athas** [comment]
Any updates on this @zfnmxt?

**Comment by zfnmxt** [comment]
I'm working on it now; should be fixed soon.
