### ISSUE TITLE
Allow `futhark bench`, `test`, and `literate` to place generated files in directories

### ISSUE THREAD

**Issue by Snektron** [diku-dk/futhark#1543]
Running `futhark bench`, `test`, or `literate` currently places all generated source files and executables next to the source file being tested, benchmarked or literated. It is kinda annoying to remove all those files if they are inside the source tree, and i don't think that gitignores are quite the right solution here either. It would be useful to be able to place them in a different directory, like how `futhark c -o a/b` will generate `a/b.c` and `a/b`. 

For `futhark bench` and `futhark test`, i think the best way to implement that is to simply add a `-o` flag to set the output basename or output directory.

In the case of `futhark literate`, the basename is also already used to generate a directory name for images (which does support placing the output in a different directory), and so i think the best way to implement it there is to generate executable- and source file names from that basename as well.

**Comment by athas** [comment]
What would happen to the `data` directories generated by `futhark bench` and `futhark test` for `random` input blocks?

Why is it not a sufficient workaround to `cp` the source files elsewhere before using them?

My main concern is that such a feature is probably a bountiful source of bugs, as it is likely it would not be well tested.

**Comment by athas** [comment]
I am closing this because `cp` seems like a sufficient workaround, and we've had plenty of bugs related to file lookup already.
