### ISSUE TITLE
Wrong ambiguous type

### ISSUE THREAD

**Issue by leonardschneider** [diku-dk/futhark#1552]
The following should not raise an ambiguous type error, IMHO, as the compiler should infer that the type a is indeed i64.

```
[0]> type T 'a = i64
[1]> let f 'a (x: T a): T a = x
[2]> f
Error at [2]> :1:1-1:
Type of expression is ambiguous.
Add a type annotation to disambiguate the type.

For more information, see:
  https://futhark.readthedocs.io/en/latest/error-index.html#ambiguous-type
[3]>
```
I'm using the higher-kinded type T as f is declared in a module. T a can degenerate into a normal type.

BTW, in the above example, I've found to way to disambiguate the expression. It seems the compiler reduces T a too early to i64 and therefore cannot infer that a is i64.

**Comment by athas** [comment]
I agree, something is fishy here.  But `T` *really* should be discarded early; that's in the nature of type abbreviations and structural typing.  I guess this is a corner case when using phantom type parameters.

**Comment by leonardschneider** [comment]
Actually my first description is wrong. Any type `a` can work. Would it as simple as picking type () in the case a generic type is not actually used in a declaration?

**Comment by athas** [comment]
Yes, that might be the right thing.  The type checker knows that this type is not at all constrained, so picking anything should work (as the type cannot possibly be used for anything, not even let-generalisation).

**Comment by athas** [comment]
Another solution might be to... not signal an error at all.  This type variable will certainly not appear as the type of anything in the checked AST, so it really does not matter.

**Comment by athas** [comment]
I prefer just picking `()`.  I think if you have a polymorphic function and a dead binding, then it the type variable might occur.   I can't really figure out the consequences of that.  Defaulting to `()` is more obviously safe.

**Comment by leonardschneider** [comment]
Indeed.

**Comment by leonardschneider** [comment]
Thanks so much for the quick turnaround. I have recompiled with your commit and it's all good.
