### ISSUE TITLE
In-place update of array within record

### ISSUE THREAD

**Issue by Programmerino** [diku-dk/futhark#1560]
Hello! I'm hitting a snag when it comes to updating a field array in a unique record, and am not sure how to get around it without using copy. My assumption is that the following examples shouldn't actually be problematic in terms of memory aliasing issues, but cannot be compiled because they trigger the use-after-consume error. Is there any language feature or alternative way to do this I'm missing?

```futhark
type Rec = {
    a: [5]i64,
    b: i64
}

def recUpdate (rec: *Rec) = 
    rec with a = (rec.a with [0] = 1)

def recUpdate' (rec: *Rec) = 
    {a = (rec.a with [0] = 1), b = rec.b}
```

**Comment by athas** [comment]
This is unfortunately a little awkward because consumption is tracked at the name level, and we cannot express notions such as "`rec.a` is consumed but the rest of `rec` is fine".  These are some possible workarounds:

```
def recUpdate (rec: *Rec) =
  let b = rec.b
  let a = (rec.a with [0] = 1)
  in {a,b}

def recUpdate' ({a,b}: *Rec) = 
    {a = (a with [0] = 1), b}
```

**Comment by Programmerino** [comment]
Those work great, thank you!
