### ISSUE TITLE
Provably Space-Efficient Parallel Functional Programming

### ISSUE THREAD

**Issue by flip111** [diku-dk/futhark#1566]
Hey i found this blog post and thought it might be interested for people looking into futhark

https://blog.sigplan.org/2022/01/13/provably-space-efficient-parallel-functional-programming/

close the issue when you like

**Comment by athas** [comment]
It's a nice post, but we're already aware of MPL.  [I even contributed a benchmark once!](https://github.com/MPLLang/mpl/pull/108)
