### ISSUE TITLE
Expose structure of opaque records in C API

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1568]
Currently, a Futhark entry point that accepts or returns records (including the special case of tuples) will result in an opaque type at the C level.  The only exception is that if a function returns a tuple immediately, it will be interpreted as multiple return values.  Opaque types are a necessity in general, but for those that correspond to records, it would be useful to provide C functions for constructing or destructing them.  Consider this program:

```Futhark
type r = {x: f32, y: bool}
entry f ({x,y}: r): r = {x=x+1,y=not y}
```

That results in this API:

```C
struct futhark_opaque_r;
int futhark_entry_f(struct futhark_context *ctx, struct futhark_opaque_r **out0,
                    const struct futhark_opaque_r *in0);
```

What I propose is that since `r` is really a record, we also provide the following functions:

```C
struct futhark_opaque_r* futhark_new_record_r(struct futhark_context *ctx, float x, bool y);
float futhark_project_r_x(struct futhark_context *ctx, const struct futhark_opaque_r*);
bool futhark_project_r_y(struct futhark_context *ctx, const struct futhark_opaque_r*);
```

Here the "new" function takes the record fields in lexicographic order.  The manifest file would contain information about these functions as well, to allow FFI generators to make use of them.  Any objects you get back from projection are "fresh" just like if they were returned from an entry point, which means they must be freed using the appropriate function (not applicable here since primitive types do not need to be freed).

Some open questions:

* What do we do about field names that are not valid C identifiers (e.g. contain `'`).  I suggest we reject them.  I think that's what we do for entry points with such names.
* Is this API sufficient?  It's not very important that it is concise for manual usage, since I think it will mostly be used by FFI tools, but it has to support everything we need.

**Comment by athas** [comment]
Note that this design is backwards-compatible in the sense that you can just ignore the new/project functions if you don't care about them.

**Comment by FluxusMagna** [comment]
To me it seems complete in terms of the API, but the format in the manifest also needs to be considered.

**Comment by FluxusMagna** [comment]
Additionally, how does this handle nested records, like when the returned type is opaque?

**Comment by FluxusMagna** [comment]
I think some would like to access elements in arrays of structs too, but it seems unnecessary to me. Array handling does need to be considered though, but I think it should be analogue to the element construction and deconstruction, just with arrays.

**Comment by athas** [comment]
> Additionally, how does this handle nested records, like when the returned type is opaque?

Ideally, the type of each record field will also be exposed, possibly involving creating yet another opaque C type, which will have its own projection functions if it happens to be a record.  It may be tricky to maintain the original type names of those fields, though, because the type checker tries to throw away the abbreviation names as quickly as possible.  Perhaps a first version of this will only allow projection of "top level" records, and the rest may be implemented later.

> I guess this will include a record with e.g. arrays as an element?

Yes.

> Secondly, it may be handy to update/set fields vs extracting everything and creating a new one.

This is something that can be implemented in terms of the provided API.  I don't think it needs to be part of the compiler.

> I think some would like to access elements in arrays of structs too, but it seems unnecessary to me.

Yeah, but that's a different feature!

> This needs to be able to exit with failure though, if non matching sizes are encountered for example.

Such checking is done in the entry points themselves.  The justification is that we need to check in the entry points *anyway*, so we might as well check *only* in the entry points.  This does mean that if you have a type

```
type t = {x: [10]bool}
```

then the construction function will let you pass in an array that is not actually of size `10`, and then any attempt to actually pass the resulting object to an entry point will fail.  This is not ideal, but I worry addressing it creates unnecessary complexity.  The workaround is to not actually define `t` as a record but to make it a unary sum type

```
type t = #t {x: [10]bool}
```

and then write your own constructor entry point that does the size checking.  I'm open to disagreement, though.  I don't think there are any *technical* hindrances to putting size checks in constructors.

**Comment by FluxusMagna** [comment]
Regarding size errors, I think the ideal would be to get the error from the offending function, if only for debugging purposes, but sufficiently descriptive error messages would g a long way too. In `futhask` I would probably implement a size check where possible if it's not in the futhark code. This would to an extent require size information in the manifest though, unless it's just `zip`ing some arrays.

**Comment by athas** [comment]
I have a pretty decent prototype of this.  There is one issue that'll be a bit tricky to fix.  Consider this program.

```
type t0 [n] = ([n]u32,bool)
type t1 [n] = (t0 [n],[3]f32)

entry main0 [n] (p: *t1 [n]): t1 [] = p

entry main1 [n] (y: t0 [n]) : t0 [] = y
```

This results in *three* opaque types being identified:

```
types {
  type "([]u32, bool)" = record {
    0: unsigned []i32
    1: signed bool
  }
  type "t0" = record {
    0: unsigned []i32
    1: signed bool
  }
  type "t1" = record {
    0: opaque "([]u32, bool)"
    1: signed []f32
  }
}
```

The reason is that when the compiler looks at whether the return type of `main1` is a record, it looks at the *expanded* type, where the use of the `t0` name has been replaced by its definition.  Fixing this is not impossible, but somewhat annoying, as it would require keeping a different kind of information around - not un-elaborated types, but also not fully elaborated.

An alternative would be to no longer treat records as opaque at all, which would lead to the following types:

```
types {
  type "([]u32, bool)" = record {
    0: unsigned []i32
    1: signed bool
  }
  type "(([]u32,bool), []f32)" = record {
    0: opaque "([]u32, bool)"
    1: signed []f32
  }
}
```

This has two downsides:

1. It's a compatibility break at the C API level, which is generally very stable.
2. The C type name for these types will be ugly, as their name is not a valid C identifier (it becomes a hash).  The manifest file maps the original type name to the name of the C type, so it's not a problem for wrappers, but direct use of the API becomes uglier.

Note that it is always possible to make the type distinct from a record (so nothing of this will affect you) by making it a single-constructor sum type (or completely abstract through the module system).  I think that might be a fine rule of thumb for when you want a specific C type name.  But again, it's a compatibility break.

**Comment by athas** [comment]
I found a way to handle while maintaining backwards compatibility and producing these types:

```
types {
  type "t0" = record {
    0: unsigned []i32
    1: signed bool
  }
  type "t1" = record {
    0: opaque "t0"
    1: signed []f32
  }
}
```

It depends on slightly ad-hoc analysis of the original program, but it'll probably work in all cases where the programmer doesn't go out of their way to do something complicated.

**Comment by athas** [comment]
The C API for this is pretty good now.
