### ISSUE TITLE
Better handling of out-of-memory on GPU backends

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1570]
By "better handling" I don't mean anything more fancy than explicitly saying that's the problem, what the memory consumption is of the failing program, and the size of the failed allocation.

(This only goes for device OOM; `malloc()` failures cannot be handled sanely by Futhark I think.)

**Comment by FluxusMagna** [comment]
Would this just be in the error message or also the error code? I think having it in the code would be convenient for logic in wrappers.

**Comment by athas** [comment]
Certainly the former.  Maybe also the latter, but I have no idea what our error code hygiene is like in the generated code.

**Comment by FluxusMagna** [comment]
I'm not sure what is common practice, but for Futhark I think out of memory errors is probably the class of errors that would be most useful to have a separate error code for. Doesn't Futhark use `1` for all errors currently? Hopefully  a change to the error code should not break much, since (at least to me) the sensible way to naively handle errors is to test if they are equal to zero, not to test for any particular non-zero value. In C-code any non-zero value should evaluate as `true` anyway, right?

**Comment by athas** [comment]
Sure, my concern is mostly that there might be various places in the generated code where any non-zero code is coerced to zero, and tracking them all down would be a manual process.  But we can give it a go.  Eventually we can also give program errors (e.g. out-of-bounds) their own error code.

**Comment by athas** [comment]
From the point of view of an FFI, `#define`d error codes are less practical than `static const int` ones, right?

**Comment by FluxusMagna** [comment]
I think so. Error code handling would most likely be hard coded (but of course polymorphic where possible), so just having a set of static codes corresponding to error classes that can be handled in a particular way would be nice.

**Comment by FluxusMagna** [comment]
Adding to that, I think more specifics in the error messages would be good, if possible. A simple code for handling and an expressive message for debugging.

**Comment by athas** [comment]
Sure, we'll keep (and improve) the error message text, but it'll always be human-readable text that a program would have to parse in order to extract specifics.  Producing structured errors is very difficult and I think always beyond the effort we can afford.

I think I will make the error codes `#define`s because that seems to be the most common, but I will document the actual numbers.

**Comment by FluxusMagna** [comment]
As long as the numbers are documented and static, I see no issue with that.
