### ISSUE TITLE
Whitespace dependence in return types with size parameters

### ISSUE THREAD

**Issue by FluxusMagna** [diku-dk/futhark#1573]
This compiles:

    type a [n] = [n]f32
    let f (a:a []) : a [] = a

This fails with `unexpected RBRACKET Expected one of the following: id intlit`:

    type a [n] = [n]f32
    let f (a:a []) : a[] = a

The only difference is the lack of whitespace between `a`and `[]` in the return type.

**Comment by FluxusMagna** [comment]
it also fails in the argument definition, when there is no white space.

**Comment by athas** [comment]
How weird, it works if the size is not blank.
