### ISSUE TITLE
Strange "Irregular nested operations" error with #[sequential inner] attribute

### ISSUE THREAD

**Issue by mortvest** [diku-dk/futhark#1579]
This [code](https://gist.github.com/mortvest/b6216c5b1b30a1057e404c1bca872f91) produces a following error for all gpu backends:
```
Known compiler limitation encountered.  Sorry.
Revise your program or try a different Futhark compiler.
Cannot handle un-sliceable allocation size: (((thread; #groups=num_groups_top_18368; groupsize=group_size_18365; full []),
  [gid_flat_18369, ltid_flat_19157]), bytes_19483,)
Likely cause: irregular nested operations inside parallel constructs.
```

**Comment by athas** [comment]
It's a known limitation, not a bug.  Do you think it's wrong about it?

**Comment by mortvest** [comment]
Why is it produced? There is no irregular nested parallelism. The same library compiles fine as a part of a bigger program, or if I remove the #[sequential_inner] attribute.
