### ISSUE TITLE
Raise a warning when a tuning file extension is specified but a tuning file cannot be found.

### ISSUE THREAD

**Issue by zfnmxt** [diku-dk/futhark#1581]
If a tuning file for a file `foo.fut` is specified via `--tuning=EXTENSION` and the file `foo.futEXTENSION` doesn't exist, the user is not explicitly notified (at least with `futhark bench`).

**Comment by athas** [comment]
This would result in an incredible amount of warnings, since most programs do not have tuning files.

**Comment by zfnmxt** [comment]
Why not have an option to specify an exact tuning file (instead of just an extension) to avoid that?

**Comment by athas** [comment]
Because `futhark bench` is built around the general case: benchmarking multiple programs not a single one.

**Comment by zfnmxt** [comment]
But (as far as I can tell) `futhark bench` is also the only practical way to benchmark single programs on multiple datasets.

**Comment by athas** [comment]
Yes, that is a special case of the general case.  There is no functionality missing.

**Comment by zfnmxt** [comment]
> There is no functionality missing.

Strictly speaking, no. But I'm arguing that there may be utility in having an option `--tuningfile=FILE` (in addition to the existing `--tuning` option).
