### ISSUE TITLE
Entry points that consume their input have unexpected runtime impact in futhark bench

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1582]
`futhark bench` re-initialises consumed entry point arguments (as it should), but for some reason there can be significant performance impact.  NW is affected.  We need to figure out what is going on, as this affects @Munksgaard's work in particular.

**Comment by athas** [comment]
It's some NVIDIA thing.  Who knows, maybe it demand-pages the memory onto the device during the first execution.  This does cool my desire to work on it somewhat.

**Comment by coancea** [comment]
Lazy models are a nuisance
________________________________

**Comment by athas** [comment]
I don't think this is really about Futhark.
