### ISSUE TITLE
bit-shifting edge case bug

### ISSUE THREAD

**Issue by WalterResNiel** [diku-dk/futhark#1583]
Interesting bug found while coding the DPP project (or possibly just under-specified bit-shifting functions)

"
➜  futhark_stuff futhark c test.fut
➜  futhark_stuff ./test <<< [1,2,3,4]
[0u32, 0u32, 0u32, 0u32]
➜  futhark_stuff futhark opencl test.fut
➜  futhark_stuff ./test <<< [1,2,3,4]
[2u32, 4u32, 6u32, 8u32]
➜  futhark_stuff futhark repl test.fut <<< [1,2,3,4]
|// |\    |   |\  |\   /
|/  | \   |\  |\  |/  /
|   |  \  |/  |   |\  \
|   |   \ |   |   | \  \
Version 0.21.5.
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.

Run :help for a list of commands.

[0]> [1i32, 2i32, 3i32, 4i32]
[1]> Quit REPL? (y/n) Leaving 'futhark repl'.
➜  futhark_stuff futhark --v
Futhark 0.21.5
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
➜  futhark_stuff cat test.fut

entry main [n] (A : [n]u32)  : [n]u32 =
  map (\a ->  (a u32.<< 0) + (a u32.>>> 32)) A

"

**Comment by athas** [comment]
[Not a bug](https://futhark.readthedocs.io/en/latest/language-reference.html#x-binop-y), but rather the only instance of undefined behaviour in the language.  You get the same behaviour in e.g. C.  Some day we should probably measure whether assigning a defined behaviour to this would have any negative performance impact in practice.
