### ISSUE TITLE
Parsing inconsistency

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1595]
I just noticed this seeming inconsistency.

```
[0]> #foo : #foo
#foo
[1]> #foo #bar : #foo #bar
#foo (#bar)
[2]> #foo #bar #baz : #foo #bar #baz
Error at [2]> :1:1-31:
Expression does not have expected type from explicit ascription.
Expected: #foo (#bar (#baz))
Actual:   t₀

Cannot unify constructor "foo".
```

Is that on purpose?

The following works, which indicates to me that there is some inconsistency in the associativity rules.

```futhark
#foo (#bar #baz) : #foo #bar #baz
```

**Comment by Munksgaard** [comment]
Upon further thought, this is the same behavior as in other languages like Haskell. Sorry for the confusion.

**Comment by Munksgaard** [comment]
Perhaps, but what should it mean?

**Comment by athas** [comment]
It could evaluate to `#foo #bar #baz`.  After all, these are type *expressions*.  But I'm uncertain that it would be useful.
