### ISSUE TITLE
Reverse-mode AD of this function fails

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1604]
```Futhark
def f [n] (xs: [n]i32) =
  loop (A,B) = (xs,xs) for i < n do (map (*2) A, map (+1) B)
```

The problem is that when generating the adjoint loop, we assume that the original initial values of the loop parameters are distinct (and in particular, that their cotangents are, and if not we consume them multiple times).

**Comment by zfnmxt** [comment]
On it.

**Comment by athas** [comment]
What is the status of this?

**Comment by zfnmxt** [comment]
Actually in the process of fixing it now, looks like a simple fix.
