### ISSUE TITLE
Parse error for top-level tuple pattern

### ISSUE THREAD

**Issue by PhilipBorgesen** [diku-dk/futhark#1607]
I stumbled over the following, which I wonder about.
This is accepted by the compiler (v0.21.7):
```
let tmp = (0i32, 1i32)

def main : i32 =
  let (a, b) = tmp
   in a + b
```
But this
```
let (a, b) = (0i32, 1i32)

def main : i32 =
  a + b
```
gives the error:
```
Error at top-level.fut:1:12-12: unexpected EQU
Expected one of the following: '*' '-' '<' '^' '|' '+...' '-...' '*...' '/...' '%...' '//...' '%%...' '==...' '!=...' '<...' '>...' '<=...' '>=...' '**...' '<<...' '>>...' '|>...' '<|...' '|...' '&...' '^...' '||...' '&&...' '`'


If you find this error message confusing, uninformative, or wrong, please open an issue:
  https://github.com/diku-dk/futhark/issues
```
If I have understood [the language reference](https://futhark.readthedocs.io/en/latest/language-reference.html#declaring-functions-and-values) correctly then either should be valid.

**Comment by athas** [comment]
You misread the grammar: the `pat`s are for the *parameters*.  Top level definitions cannot be patterns, only single names.

(There is no extremely deep reason for this, but it's how the language is currently specified.)
