### ISSUE TITLE
Compatibility with CUDA compute capability < 3.5

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1624]
Running any futhark-cuda-compiled program, I get a number of errors of the shape
```
futhark-cuda(2063): error: no instance of overloaded function "atomicMax" matches the argument list
            argument types are: (int64_t *, int64_t)
```
For atomic operators `max`,`min`,`and`,`or` and `xor`, which are apparently only available for int64's on GPUs of compute capability >= 3.5. Is there a way to parametrize or hack a program in order to run it with a compute capability 3.0 GPU?

**Comment by athas** [comment]
CC 3.0 is really old... as in, older than any of the GPUs we had available for testing when we first built Futhark.  I didn't think CUDA even supported those anymore.  I doubt there is a reasonable way to modify a program to run.  You could [comment out the relevant parts of the RTS and recompile the compiler](https://github.com/diku-dk/futhark/blob/master/rts/c/atomics.h#L197-L395), but I have no recollection of whether we are using 64-bit atomics for bookkeeping somewhere.

**Comment by nbos** [comment]
It does work with the operators commented out. Perhaps unrelated, I find my code running ~80% slower on CUDA vs. OpenCL so I'll stick with the latter. Thank you!

**Comment by athas** [comment]
Glad I could help!

**Comment by athas** [comment]
Glad I could help!
