### ISSUE TITLE
Unpacked tuple containing sizes goes out of scope

### ISSUE THREAD

**Issue by Alexnortung** [diku-dk/futhark#1646]
I am trying to make a program that should store the output sizes and I would like to do this with tuples/records.
The problem is that when unpacking a tuple in the function definiton and using that variable as a return size, the variable has gone out of scope. However this does not happen if you are using separate arguments instead of tuples/records.

The following is a working test example

<details>
  <summary>working code example</summary>

```
-- ==
-- entry: a
-- input {[
--    [0.0, 0.0, 0.0, 0.0],
--    [0.0, 0.0, 0.0, 0.0],
--    [0.0, 0.0, 0.0, 0.0],
--    [0.0, 0.0, 0.0, 0.0]
--    ]
--
--    2i64
--    2i64
-- }
-- output {[
--    [0.0, 0.0],
--    [0.0, 0.0]
-- ]}
entry a [m] [n] (input: [m][n]f64) (output_m: i64) (output_n: i64) : [output_m][output_n]f64 =
  let w = m / output_m
  let h = n / output_n
  let xs = map (\x -> x * w) (iota output_n)
  let ys = map (\y -> y * h) (iota output_m)
  in map (\y ->
    map (\x ->
      input[y, x]
    ) xs
  ) ys
```

</details>

The following uses tuple unpacking, but gives a compilation error since `output_m` and `output_m` has gone out of scope.

<details>
  <summary>Code with compilation error</summary>

```
-- ==
-- entry: b_entry
-- input {[
--    [0.0, 0.0, 0.0, 0.0],
--    [0.0, 0.0, 0.0, 0.0],
--    [0.0, 0.0, 0.0, 0.0],
--    [0.0, 0.0, 0.0, 0.0]
--    ]
--
--    2i64
--    2i64
-- }
-- output {[
--    [0.0, 0.0],
--    [0.0, 0.0]
-- ]}
def b [m] [n] (input: [m][n]f64) ((output_m, output_n): (i64, i64)) : [output_m][output_n]f64 =
  let w = m / output_m
  let h = n / output_n
  let xs = map (\x -> x * w) (iota output_n)
  let ys = map (\y -> y * h) (iota output_m)
  in map (\y ->
    map (\x ->
      input[y, x]
    ) xs
  ) ys

entry b_entry [m] [n] (input: [m][n]f64) (output_m: i64) (output_n: i64) : [output_m][output_n]f64 =
  b input (output_m, output_n)
```

</details>

I think this problem feels very odd since the two functions are almost identical.

**Comment by athas** [comment]
Remove the sizes from the return type of `b`.  The problem is that the current type of `b` cannot be expressed as a function type, since `output_m` and `output_n` are not names of parameters (which they are for `b_entry`).

Generally, sizes present in the return type can only refer to parameter names.

**Comment by athas** [comment]
Not a bug.
