### ISSUE TITLE
size-lifting in module types

### ISSUE THREAD

**Issue by melsman** [diku-dk/futhark#1651]
The following module type declarations are accepted by Futhark:

```futhark
module type A = {
  type t
  val x : t
}

module type B = {
  type~ s
  include A with t = s
}
```

It seems unclear, however, what semantic module type `B` elaborates to... The module type `A` can legally be used as follows:

```futhark
module a : A = {
  type t = [2]f64
  def x : t = [4,3]
}
```
However, the following code is rejected:

```futhark
module b : B = {
  type~ s = ?[n].[n]f64
  type~ t = s
  def x : t = [4,3]
}
```
Here is the error message:
```
Module defines
  type~ t = ?[n].[n]f64
but module type requires a non-lifted type.
```

It would be great if we could allow flexible refinements wrt type-liftedness in module types, but it requires that type `t` in module type `B` above is refined to become lifted (due to the `with` constraint). 

Notice also that the following code is accepted by Futhark:
```futhark
module b : B = {
  type s = [2]f64
  type t = s
  def x : t = [4,3]
}
```

The suggested feature stems from a use case where the programmer would like to specify a generic module type that can be instantiated with a module declaring an existentially-sized type and another module declaring a regular-sized type.

**Comment by athas** [comment]
I don't think this is safe, or would at least add a lot of extra constraints to refinement.  Consider

```Futhark
module type A = {
  type t
  val f : t -> []t
}
```

We don't want to allow a refinement that would make `t` size-lifted here.  While it's perhaps possible to check the entire module type for whether it is safe to loosen the requirements of a type in a module type, is the utility significant enough to merit the additional complexity?

**Comment by melsman** [comment]
... You're probably right. SML has a notion of "maximising equality", but it works only on type specifications...
