### ISSUE TITLE
Allow arbitrary expressions in sizes

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1659]
I had a conversation with Martin today where we concluded that it may be possible to allow arbitrary expressions to be used as sizes as long as

* they have type `i64`.
* they consume nothing.

This would allow us to give types to functions such as `concat`:

```Futhark
val concat [n] [m] 't : [n]t -> [m]t -> [n+m]t
```

We have discussed this many times, but were reluctant to add it because in general it needs us to compute the inverse of arbitrary functions:

```Futhark
def length [n] (x: [f n]t) = n
```

Given some `x`, how do we find `n`?  We say that an array `x` *witnesses* `n` if we can extract the value of `n` from the run-time shape of `x`.  The trick we believe may work is to require that whenever you bind a size parameter, *you must have at least one array using that as the size of a dimension*.  This array will then *witness* the actual size, but you can still use it in "non-witness" ways in other arrays.  One motivating example is triangular matrices:

```Futhark
type triangular [n] = {data: [n*n/2]t, size: [0][n]()}
```

Note the `size` field above - this is required already, for the same reason.  We just hadn't realised that this allows us to safely make the type system even more expressive.

## What this does not handle

This does not address the question of how we can make equality of expressions more flexible.  We will not be able to infer that `x++y` and `y++x` have the same shape.  This is left for future work; perhaps infinitely far in the future.

**Comment by catvayor** [comment]
Why expect i64 instead of u64 as sizes should be non-negative ?

**Comment by athas** [comment]
Unsigned integers should not be used to encode "this value cannot be negative", but only as bit vectors.
