### ISSUE TITLE
Allow strings in test input as syntactic sugar for []u8

### ISSUE THREAD

**Issue by canadaduane** [diku-dk/futhark#1663]
I'm writing a CRC-16 function and many of my test inputs are strings, e.g. from a C library I'm converting:

```
/* Test vectors used in RFC 1321 */
static char rfc_1321_vectors[NUMVECTORS][MAXVECTORLEN] = {
   "",
   "a",
   "abc",
   "message digest",
   "abcdefghijklmnopqrstuvwxyz",
   "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
   "1234567890123456789012345678901234567890123456789012345678901234"
   "5678901234567890"
};
```

It would be nice to see these strings in the input rather than convert them to, e.g. `[ 97u8, 98u8, 99u8 ]` etc.

**Comment by athas** [comment]
This should be easy enough to implement, at least without escape sequences.

**Comment by athas** [comment]
With 44472e66ef723eb207f57ed5d4466676aa72ea8d, you can use `script input { "foo" }`.  Is that good enough?  It's simpler than extending the textual data format.

**Comment by canadaduane** [comment]
Thanks!

I'm not yet familiar with the `script` side of things. I assume this has to do with running a futhark program in [server mode](https://futhark-lang.org/blog/2021-01-18-futharkscript.html)?

Does anything need to change in the way I test? (I'm currently using `futhark test crc16.fut`, for example).

**Comment by canadaduane** [comment]
Thanks!
