### ISSUE TITLE
futhark_new_*_1d and futhark_values_*_1d are not asynchronous

### ISSUE THREAD

**Issue by PhilipBorgesen** [diku-dk/futhark#1664]
[The Futhark User's Guide](https://futhark.readthedocs.io/_/downloads/en/v0.21.10/pdf/#page=56) describes the `futhark_new_i32_1d` and `futhark_values_i32_1d` C API functions as being asynchronous:
> `struct futhark_i32_1d *futhark_new_i32_1d(struct futhark_context *ctx, int32_t *data, int64_t dim0)`
> Asynchronously create a new array based on the given data. The dimensions express the number of elements. The
> data is copied into the new value. It is the caller’s responsibility to eventually call futhark_free_i32_1d().
> Multi-dimensional arrays are assumed to be in row-major form. Returns NULL on failure.
>
> `int futhark_values_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr, int32_t *data)`
> Asynchronously copy data from the value into data, which must be of sufficient size. Multi-dimensional arrays
> are written in row-major form.

The implementations I get by executing `futhark opencl --library` or `futhark cuda --library` however perform synchronous memory transfers. `futhark_values_i32_1d` can even block for the entire pipeline of scheduled work to finish, to ensure no kernel assertions have failed.

**Comment by athas** [comment]
It's more that they are *possibly* asynchronous, meaning that a `futhark_context_sync()` *must* be performed before it can be certain that they are finished.  Is your issue that, as an optimisation, they could be even more asynchronous than is currently the case?

**Comment by PhilipBorgesen** [comment]
It _would_ be better if they were asynchronous as documented but I don't have a use case that requires either behavior.

My issue is that the behavior I expected from reading the documentation did not match the implemented behavior.
If it is not a bug with the implementation, then I would consider this a bug with the documentation. Stating that the asynchronicity is an undefined implementation detail or simply describing the constraint ("must call `futhark_context_sync()` before use of result") could be a solution.

I created the issue as I did not know whether the mismatch was a documentation issue or due to a regression.

**Comment by athas** [comment]
Documentation should not reflect the implementation, but the implementation *specification*.  It is user documentation, not implementation documentation.

**Comment by athas** [comment]
I suspect the synchronous here came as a side effect of when we implemented on-GPU bounds checking, as the same code generation functions are used.  This could be loosened, I suppose.

**Comment by PhilipBorgesen** [comment]
> Documentation should not reflect the implementation, but the implementation _specification_. It is user documentation, not implementation documentation.

Yes, I agree. The documentation states constraints for the calling code and what the function will do in return. In my view the implementation does not satisfy the specification.

To me it is as if the function was annotated with one big-O operation complexity but exhibited another. It is not relevant for what the function does but it is relevant for how one may use it (effectively).

If you don’t want to provide an asynchronous implementation but want the freedom to make the implementation asynchronous later, then the contract should require callers to call `futhark_context_sync()` before using results but not promise how the operation will be performed.
