### ISSUE TITLE
futhark-doc: included local module types are not shown

### ISSUE THREAD

**Issue by melsman** [diku-dk/futhark#1666]
Problem appears, for instance, on the documentation page

https://futhark-lang.org/pkgs/github.com/diku-dk/sparse/0.0.7/doc/lib/github.com/diku-dk/sparse/sparse.html

Here the module types `matrix` and `matrix_regular` are not shown...

**Comment by athas** [comment]
What should happen here?  `local` means (among other things) "don't put it in the documentation".  The solution is to not declare them local.

**Comment by melsman** [comment]
... somehow the local module type `sparse` *is* shown...

**Comment by athas** [comment]
You're right.  Perhaps I'm misremembering what the logic is in `futhark doc`.  It's not code we touch all that often, after all.
