### ISSUE TITLE
Traces not visible when running `futhark literate`

### ISSUE THREAD

**Issue by FluxusMagna** [diku-dk/futhark#1678]
This is inconvenient when debugging. Perhaps they could be enabled with a `--trace` option or similar.

**Comment by athas** [comment]
I don't like adding a new option, but we can show them always or when `-v` is passed.  Which would be preferable?  I lean towards the former.

**Comment by FluxusMagna** [comment]
Using `-v` makes sense. I just like that the default is 'clean'.

**Comment by athas** [comment]
I also believe that silence is golden by default.  On the other hand, `trace` is something that the programmer puts in *intentionally*.

**Comment by FluxusMagna** [comment]
That is true, and I'd be okay either way. Sometimes I find that leaving debug statements in the code can be practical in a development stage, even though one isn't always interested in them. I suppose always showing them discourages people from being lazy and never cleaning up after debugging though.

**Comment by athas** [comment]
An argument for requiring `-v` is also that we might then print *all* ancillary logging output (which matters if the executable uses `-L` or `-D`).  That's probably necessary anyway, since the tracing prints are part of the same output stream.
