### ISSUE TITLE
Simple sphere function works for `i32` but not `f32`

### ISSUE THREAD

**Issue by luleyleo** [diku-dk/futhark#1679]
I played around a bit with futhark and ran into an issue. The following code does not work:

`experiment.fut`:
```futhark
def sphere (x: []f32): f32 =
    reduce (+) 0 (map2 (*) x x)
```

`main.c`:
```c
#include <stdio.h>

#include "experiment.h"

void run_sphere(struct futhark_context *ctx)
{
    printf("Running: sphere\n");

    float x[] = {1, 2, 3, 4};
    struct futhark_f32_1d *x_arr = futhark_new_f32_1d(ctx, x, 4);

    float res;
    futhark_entry_sphere(ctx, &res, x_arr);
    futhark_context_sync(ctx);

    printf("Result: %d\n", res);

    futhark_free_f32_1d(ctx, x_arr);
}

int main()
{
    struct futhark_context_config *cfg = futhark_context_config_new();
    struct futhark_context *ctx = futhark_context_new(cfg);

    run_sphere(ctx);

    futhark_context_free(ctx);
    futhark_context_config_free(cfg);
}
```

With the `c` backend the result is always `0`, with the `opencl` backend it's random. If I replace `float` with `int` and `f32` with `i32` it works for both.

(I'm using the latest Futhark release 0.21.11)

**Comment by athas** [comment]
You need to declare the `sphere` function with `entry`, not `def`, if you want to call it from the outside world.  Does this C code actually compile?

You also need to use `%f` to print floats.

With that fixed it works for me.

**Comment by luleyleo** [comment]
> You also need to use `%f` to print floats.

Ouch, I got pampered by Rust for too long, it seems. Thanks!

> You need to declare the sphere function with `entry`, not `def`, if you want to call it from the outside world. Does this C code actually compile?

I  used `--entry-point`, but `entry` is much more convenient!

Thanks for your help, and sorry for the confusion :)

**Comment by athas** [comment]
If you like Rust, [consider genfut](https://github.com/Erk-/genfut).
