### ISSUE TITLE
Internal compiler error when supplying incorrct array size when using `futhark run`

### ISSUE THREAD

**Issue by Alexnortung** [diku-dk/futhark#1682]
I have the following program [here](https://github.com/Alexnortung/futhark-nn/blob/ef87201d5eb29cee1945c9c87322d2bc261f3c3f/layers/convolutional.fut#L255-L259). When running the following command I get an internal compiler error

```
echo "[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]]
[2.0, 3.0]
[[[10.0, 2.0],[-1.0, -2.0]],[[20.0, 4.0], [-3.0, -4.0]]]
" | futhark run layers/convolutional.fut -e conv_layer_channels
```

The error I get is

```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
src/Language/Futhark/Interpreter.hs:1918:13-63: Non-exhaustive patterns in (ShapeDim n
                                                         (ShapeDim m shape),
                                                xs')
```

In the previous command I use a 3 dimensional array, but the program expects a 4 dimensional array, so the following command works

```
echo "[[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]]]
[2.0, 3.0]
[[[10.0, 2.0],[-1.0, -2.0]],[[20.0, 4.0], [-3.0, -4.0]]]
" | futhark run layers/convolutional.fut -e conv_layer_channels
```

**Comment by athas** [comment]
There is actually [a FIXME in the source code](https://github.com/diku-dk/futhark/blob/27fbc2964b79b194c8acadd480f730e666608a7f/src/Language/Futhark/Interpreter.hs#L2028) for this one.  I don't remember if I was just too lazy to fix it, or if it was just annoying and assumed to be a very rare situation, but having an issue for it can't hurt.
