### ISSUE TITLE
Error: Using variable "+", but this was consumed

### ISSUE THREAD

**Issue by luleyleo** [diku-dk/futhark#1711]
I'm currently struggling with an odd compilation error. This is a simple example which causes it:
```futhark
def test =
    let x = [1, 2, 3, 4, 5] in
    let y = x |> map (\x -> x + x) with [0] = 10 in
    y |> i64.sum |> (+ 10)
```
For some reason, the `with` consumes the `+` operator. When removing either the `with [0] = 10`, the `x+x` or the `+ 10` at the end it works.

As stated in the title, the error I get is
```
Using variable "+", but this was consumed at 170:13-48.  (Possibly through aliasing.)
```

**Comment by athas** [comment]
This looks like a bug in alias tracking for the built-in overloaded operators.  Basically, when you use `+` in the lambda it's not yet sure which number type you'll be using, so it's assigning `+` a magical "overloaded" function type, and in principle such an unknown function can return a result that aliases its arguments.  Of course, this is not actually possible here for multiple reasons; with the most obvious one being that all the overloaded functions return primitives, which can `never` have aliases.

I'll fix it, and as a workaround you can make sure `+` knows from the start what its argument type should be; for example by adding a `:[]i64` ascription to the binding of `x`.

**Comment by luleyleo** [comment]
Oh, I see. Thanks for fixing it so quickly! :)
