### ISSUE TITLE
OpenCL backend: smalloc(): unaligned fastbin chunk detected

### ISSUE THREAD

**Issue by luleyleo** [diku-dk/futhark#1716]
Since the upgrade to Furhark `0.21.13` / `0.21.14` I get the following error when using the OpenCL backend:
```
smalloc(): unaligned fastbin chunk detected
```
This does not happen when using OpenCL on `0.21.12` or when using any other backend.

**Comment by athas** [comment]
Does it also happen with master?  https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz

Which OpenCL platform/driver are you using?  Do you get this error with all programs?

**Comment by luleyleo** [comment]
I tested it with `master`, `0.21.14`, `0.21.13` and `0.21.12`, with only `0.21.12` working as expected.

The same error appears on both my desktop (Nvidia drivers) and laptop (Intel drivers).

I tried some other examples, futball and " Ray Tracing in One Weekend in Futhark", and both seem to be working. Maybe I'm doing something wrong? But it's odd that other targets appear to work just fine, even though they share the same code. I'll keep investigating, perhaps I can isolate the error somehow.

**Comment by athas** [comment]
What does your program do?

**Comment by luleyleo** [comment]
Alright, I managed to find the culprit accidentally. I forgot to call `futhark_context_sync` after a call to `futhark_values_f64_1d` and that was causing the smalloc error. Now that I've added the sync call, it works again. Apparently, version `0.21.13` changed sync behavior of the OpenCL backend a bit, and made this silent-so-far mistake visible. Sorry for the inconvenience.

**Comment by athas** [comment]
I had to fix that exact same bug in lots of my own code, so don't feel too bad!  The symptoms can be really weird too.  I wonder what kind of virtual memory tricks the OpenCL driver is doing behind the scenes when performing asynchronous copies.
