### ISSUE TITLE
ocaml-futhark example

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [diku-dk/futhark#1717]
https://github.com/ArulselvanMadhavan/ocaml_gpu_wordcount

Hi, I have been learning Futhark and finding it really cool. I managed to put together a working example of consuming the futhark generated C and OpenCL code from OCaml. Would it be helpful to link this in the docs somewhere? If so, I can clean it up and make it more presentable.

Thanks

**Comment by zshipko** [comment]
Hi @ArulselvanMadhavan, I've also been working on a Futhark binding generator that supports OCaml: https://github.com/zshipko/futhark-bindgen :smile_cat:

**Comment by ArulselvanMadhavan** [comment]
Hi @zshipko, 

That looks cool. Looking forward to seeing it get mature. Appreciate the heads up!

**Comment by athas** [comment]
Cool!  I'm an adherent of the Big Tent philosophy of documentation where maximising references and examples is worthwhile by itself.  We don't have an obvious spot for such things right now, but I've added a new category [to the examples page on the website](https://futhark-lang.org/examples.html).

I also [added futhark-bindgen here](https://futhark-lang.org/docs.html).
