### ISSUE TITLE
Should we get rid of streaming SOACs?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1718]
Streaming SOACs (`map_stream` and `reduce_stream`) are an exotic feature that is little used in actual Futhark programs.  In our benchmark suite, only OptionPricing makes use of it.  I doubt anyone else has used them.  They are difficult to use correctly and require a lot of special-purpose machinery in the compiler (mostly flattening and the GPU representation) that is not needed for the more well-behaved other SOACs.  The non-commutative case for `map_stream` is currently implemented with multi-LMAD index functions, which I'd like to get rid of.

Current OptionPricing performance on A100:

```
OptionPricing-data/small.in:         794μs (95% CI: [     793.6,      794.9])
OptionPricing-data/medium.in:       1308μs (95% CI: [    1307.6,     1309.3])
OptionPricing-data/large.in:       23087μs (95% CI: [   23072.9,    23097.6])
```

Without using `map_stream`:

```
OptionPricing-data/small.in:         736μs (95% CI: [     734.4,      739.5])
OptionPricing-data/medium.in:       1172μs (95% CI: [    1171.1,     1173.2])
OptionPricing-data/large.in:       21708μs (95% CI: [   21693.0,    21724.5])
```

It appears that even for our original motivation, streaming SOACs are no longer worthwhile.

**Comment by athas** [comment]
`map_stream` has (small) advantages when generating sequential non-GPU code, but as it seems to be actively detrimental on the GPU for the only use case we have, I think we should still ditch it.

**Comment by Munksgaard** [comment]
If this is the only use-case for streaming, and it even seems to hamper performance, I'm all for cutting ut.

**Comment by athas** [comment]
*Sequential* streams are still useful as part of the fusion algebra.  I'm mostly concerned with parallel streams here.
