### ISSUE TITLE
OpenCL backend: race condition in memory transfers

### ISSUE THREAD

**Issue by mkm** [diku-dk/futhark#1731]
Consider the following simple program:
`entry main : [1]f64 = [42]`

On my system (Linux, Intel UHD Graphics 620) using the opencl backend this program prints `[0i32]`. On other backends (c, pyopencl) it prints `[42i32]` as expected.

Programs that output larger arrays are non-deterministic. Typically an initial segment of the output array is garbage and the rest contains the expected values. Sometimes it crashes with a heap corruption error.

Bisection reveals that this problem was first introduced in commit 3d6f2c383a0fc67381c1febd30734fcd7ff3d2da, which moves towards using more asynchronous memory transfers.

**Comment by athas** [comment]
Must be an issue with the executable frontend, since it works fine in daemon mode.
