### ISSUE TITLE
Fusion regression in sequential backend

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1733]
The following code used to be fusable in the sequential (CPU) backend:

```futhark
let main [n] (i: i64) (ns: [n]i32) (mss: [n][n]i32): [n][n]i32 =
  let t1 = map (map (+ 1)) mss

  let k = 1
  let t0 = map (+ k) ns

  let t1[i] = t0
  in t1
```

Running `futhark-0.21.2 dev --seq-mem foo.fut` results in just a single loop, whereas the latest master produces two loops.

**Comment by athas** [comment]
This is unrelated to the backend; we use the same fusion algorithm in all pipelines.

**Comment by athas** [comment]
I actually vaguely remember that this is intentional.  We changed the fusion algorithm to only perform horizontal fusion on SOACs that have overlapping inputs.

**Comment by athas** [comment]
Yes, fixing it is straightforward.  We'd just change the `filter` here:

https://github.com/diku-dk/futhark/blob/8f427635cba973516a0d76285a61741b8aa5f759/src/Futhark/Optimise/Fusion.hs#L121

But is that what we want?

**Comment by athas** [comment]
We discussed this yesterday and decided that the new fusion strategy is superior to the old overly-aggressive one.
