### ISSUE TITLE
Please add support for windows and macOS

### ISSUE THREAD

**Issue by fenginsc** [diku-dk/futhark#1734]
Please add support for windows and macOS

**Comment by Munksgaard** [comment]
You should be able to install Futhark on MacOS using [homebrew](https://futhark.readthedocs.io/en/stable/installation.html#installing-futhark-on-macos).

Windows is not officially supported, but you should be able to get it to work through [WSL](https://futhark.readthedocs.io/en/stable/installation.html#setting-up-futhark-on-windows).

What problems have you run into when trying to use either method?

**Comment by fenginsc** [comment]
> You should be able to install Futhark on macOS using [homebrew](https://futhark.readthedocs.io/en/stable/installation.html#installing-futhark-on-macos).
> 
> Windows is not officially supported, but you should be able to get it to work through [WSL](https://futhark.readthedocs.io/en/stable/installation.html#setting-up-futhark-on-windows).
> 
> What problems have you encountered when trying to use either method?

Thanks for the reply, I just wish macOS had a separate binary installer, and official support for windows instead of WSL.

**Comment by haoranpb** [comment]
@athas Just a minor thing, this doesn't work on macOS, specifically the `-D`

https://github.com/diku-dk/futhark/blob/ec3c95be352fd3993ed7a5566747b1fbb66832da/Makefile#L26

**Comment by jmhimara** [comment]
I would also like to add that while the WSL option works, there's currently no OpenCL support there. So a windows port would be nice, although I understand why this is not a priority. 

I was able to compile it natively on windows (since haskell is available), but every time I run it I keep getting the error: `Unknown` import "/prelude/prelude"`  Maybe the haskell code is not able to find certain libraries?

**Comment by athas** [comment]
I think NVIDIA supports CUDA (and maybe also OpenCL) under WSL.  Not sure about AMD.

The `import` error is unfortunate and is related to differences in pathname representation (Windows uses backslashes).  I remember fixing that bug many times, and it's not surprising that it has snuck back in.  I'll see if I can dig up a Windows system and fix it again.

**Comment by jmhimara** [comment]
@athas Yes, I think Cuda works but I haven't seen any reference to OpenCL working in WSL. I only have an AMD card at my disposal right now. Perhaps I can try again once I get my hands on an nvidia system.

**Comment by athas** [comment]
I fixed the bug that prevented anything from working.  I'll merge it once #1760 passes CI.  Windows is still poorly tested, so I have no idea how well it works, but it should at least be able to compile programs.

**Comment by jmhimara** [comment]
@athas Thanks! 

I can probably find the time to do some more tests on Windows, see what works and what doesn't. At the very least you'll have a record for future reference.
