### ISSUE TITLE
Idempotency of futhark pkg upgrade.

### ISSUE THREAD

**Issue by Ulrik-dk** [diku-dk/futhark#1743]
The timestamp generated in the `futhark.pkg` file by `futhark pkg upgrade` seems to be the time of the call, and not the time of the referenced commitment.

Is this an oversight, or intentional?

**Comment by Ulrik-dk** [comment]
The timestamp is not documented, as far as I can see.

https://futhark.readthedocs.io/en/latest/package-management.html

**Comment by athas** [comment]
[It's an implementation defect](https://github.com/diku-dk/futhark/blob/3bc414b0a0722e0b6867d78ba2bafe825ad2d0c6/src/Futhark/Pkg/Info.hs#L243), IIRC because it wasn't obvious how to find the date corresponding to a commit.

**Comment by Ulrik-dk** [comment]
It causes some noise when including a `futhark.pkg` in a git repo. A workaround is to only check it in when a change has happened, and otherwise git reset it.

**Comment by athas** [comment]
It only happens when using unreleased versions, right?  This is why fixing it has not been much of a priority.

**Comment by Ulrik-dk** [comment]
`futhark -V`
```
Futhark 0.22.2
git: 9550f97925171f7e89ea02048bd1e377114c87d0
...
```
Which is the same commit-id as in the released 0.22.2 tar here: https://futhark-lang.org/releases/

**Comment by athas** [comment]
Unreleased *package* versions in futhark.pkg.

**Comment by Ulrik-dk** [comment]
Right. I've added a version tag to the respective package, and now it works. Thanks!
