### ISSUE TITLE
Discrepancy between `futhark repl` and `futhark test` in `segmented_scan_add`

### ISSUE THREAD

**Issue by einar-triton** [diku-dk/futhark#1745]
I experience a discrepancy between what the `futhark repl` and `futhark test` computes.

You can see a not-so-minimal example [here][1]: 

```
git clone git@github.com:einar-triton/segmented_scan_add_issue.git
cd segmented_scan_add_issue
make
```

I should mention that I am new to size types, so maybe the issue is related to that.

[1]: https://github.com/einar-triton/segmented_scan_add_issue

**Comment by athas** [comment]
[This is not a neutral element for addition.](https://github.com/einar-triton/segmented_scan_add_issue/blob/master/demo.fut#L32)

**Comment by einar-triton** [comment]
Thanks, my bad.  I mistakenly thought of it as simply an accumulator.
