### ISSUE TITLE
Type abbreviations treated as opaque by futhark literate

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1750]
When using futhark literate, type abbreviations are treated as opaque. This is unexpected, since the futhark book explicitly states that [Type abbreviations are purely a syntactic convenience — the type complex is fully interchangeable with the type (f64, f64):](https://futhark-book.readthedocs.io/en/latest/language.html#type-abbreviations).

The result is that the following can be run with `futhark literate`:

```futhark
def moving_point (x: i64, y: i64) : ([][]u32, (i64, i64)) =
  let canvas = replicate 128 (replicate 128 0) with [y, x] = 255
  in (canvas, (x + 1, y+1))

-- > :video (moving_point, (10i64, 10i64), 50i64);
-- fps: 1
-- format: gif
```

while this cannot:

```futhark
type vec2 = (i64, i64)

def moving_point (x: i64, y: i64) : ([][]u32, vec2) =
  let canvas = replicate 128 (replicate 128 0) with [y, x] = 255
  in (canvas, (x + 1, y+1))

-- > :video (moving_point, (10i64, 10i64), 50i64);
-- fps: 1
-- format: gif
```

**Comment by athas** [comment]
This is sort of by design (the Futhark book is descriptive, not normative): https://futhark.readthedocs.io/en/latest/usage.html#value-mapping

But we might be able to handle this, as we know that `vec2` is actually a tuple, and this is also visible at the C API level.
