### ISSUE TITLE
More efficient function calls

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1756]
Currently the code generation backends assume that all function calls can fail.  In practice, we might often generate many small functions that cannot possibly fail.  These should be generated with a `void` return type.  This is probably most important for GPU and ISPC backends, because these are hurt by the control flow of checking for failures.

To implement this, first write a function for computing a call graph on ImpCode, then a function for classifying ImpCode procedures as safe or unsafe.  A safe procedure contains only safe operations and only calls to safe procedures.

**Comment by FluxusMagna** [comment]
I assume this only refers to internal function calls, and not the C-api?
