### ISSUE TITLE
native Windows support

### ISSUE THREAD

**Issue by 89z** [diku-dk/futhark#1761]
it seems currently, Windows support is only available via WSL:

https://github.com/diku-dk/futhark/blob/master/docs/installation.rst#setting-up-futhark-on-windows

which is essentially a Linux emulator. Is Windows native support planned?

**Comment by julian-goldsmith** [comment]
It's a little different than using Windows APIs directly, but MinGW is meant for exactly this.  Cygwin woupd work too, but it is less Windowsy.

**Comment by 89z** [comment]
> Cygwin woupd work too, but it is less Windowsy.

no, it wouldn't. Cygwin is essentially a Linux emulator, just like WSL. Before anyone argues: no, they aren't exactly the same, but WSL emulates and Linux environment, and Cygwin translates Unix syscalls into Windows syscalls. Either way, both options take a huge performance hit over Windows APIs. So please avoid those type suggestions in this thread, as those aren't "native" as mentioned in the title.

**Comment by athas** [comment]
It's unsupported mostly due to lack of testing resources. The next release (coming later today) works on Windows as far as I can determine, but we're still reluctant to make guarantees that we cannot keep.

**Comment by athas** [comment]
Precompiled snapshots for Windows are available again, and hopefully work to some extent.  I'm not sure MSVC supports enough of the C language to handle the generated code, but GCC and Clang should work on Windows.
