### ISSUE TITLE
Short-circuiting should also make scalar maps in-place when possible

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1765]
The `map`s in these functions should be in-place (the key thing is the uniqueness):

```
def f (xs: *[]i32) = map (+2) xs
def g (xs: *[]i32) (ys: []i32) = map2 (+) xs ys
```

I told @Munksgaard how to go about it while mildly inebriated yesterday night, so he should know how to do it.

**Comment by Munksgaard** [comment]
On it
