### ISSUE TITLE
Misleading warning

### ISSUE THREAD

**Issue by nqpz** [diku-dk/futhark#1776]
This program compiles:

```futhark
module type sub = {
  type a
}

module type a = {
  type a

  module sub: {
    include sub
  }
}
````

However, it also gives this warning:

```
Warning at badwarning.fut:9:5-15:
  Inclusion shadows type "a" .
```

I think the warning message is wrong here.

**Comment by athas** [comment]
It does shadow `a` and it happens silently.  The intent it to catch cases like


```
module type a = {
  type a
  val x : a
  module sub: {
    include sub
    val y : a -- now a different a!
  }
}
```

What do you think the rule should be?

**Comment by nqpz** [comment]
Oops, that makes sense. I probably got confused because this other piece of code doesn't give a warning, but does produce the same module type:

```futhark
module type sub = {
  type a
}

module type a = {
  type a

  module sub: sub
}
```
But I see how the difference is that this approach is more limited, since you can't extend `a.sub`, so none of its contents can cause confusion.

Closing this issue!
