### ISSUE TITLE
Unsigned Ints with sign in REPL

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1779]
The literal `-10u32` and the cast `u32.i64 (-10)` both evaluate to `-10` in the REPL.
Shouldn't it raise an error like you get when evaluating `-10 : u32`?

**Comment by athas** [comment]
This is by design, although the design can always be changed.  The reason this doesn't fail is that it's unambiguous what the user intended, which is not the case when type inference ends up inferring a type too small for the constant.

**Comment by athas** [comment]
That used to be different, so this is a bug.  Easy to fix, fortunately.
