### ISSUE TITLE
Compiler fails on mistyped match statement

### ISSUE THREAD

**Issue by poeface** [diku-dk/futhark#1783]
My colleague and I just getting started on using futhark (and we really like it!), but we've found a compiler bug that I want to report. I looked through the other issues with the bug tag and didn't see this one.

The code below generates an unhandled exception in the compiler when compiled (we've only tried compiling multicore, but it appears on both linux and mac).

Here's a summary of the problem.
When we define a tagged union type like this
```
type surface = #asphere {curvature: f64}
             | #sphere  {curvature: f64}
```
If try to pattern match against it, but mistakenly leave out the record terms (`{curvature}`):
```
let sag (surf: surface) : f64 =
    match surf 
      case #asphere ->
        1
      case #sphere ->
        2
```

It will cause the compiler to error out with the following message:

> Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
Prelude.!!: index too large

I hope this information is enough to work with. Thanks!

**Comment by athas** [comment]
I can reproduce.  Truly mysterious that something this simple fails.
