### ISSUE TITLE
IR parser can't parse pattern names with `%` 

### ISSUE THREAD

**Issue by zfnmxt** [diku-dk/futhark#1785]
Looks like this is because the IR parser uses the `constituent` function:

https://github.com/diku-dk/futhark/blob/3c74d10b11bc6b07616c1ec4a7520e7d9726494a/src/Futhark/IR/Parse.hs#L54-L63

https://github.com/diku-dk/futhark/blob/3c74d10b11bc6b07616c1ec4a7520e7d9726494a/src/Language/Futhark/Primitive/Parse.hs#L26-L28

**Comment by athas** [comment]
Adding `%` to the mix should be harmless.
