### ISSUE TITLE
Missing type check before internaliser?

### ISSUE THREAD

**Issue by nqpz** [diku-dk/futhark#1787]
Hi, I need a program that takes two integers and gives back the first one, like so:

```futhark
entry main: i32 -> i32 -> i32 =
  ((true, (.0)), (false, (.1)))
  |> (\p -> if p.0.0 then p.0 else p.1)
  |> (.1)
  |> curry
```

When I try to compile this program with `futhark` from master, I get this error:

```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
internaliseTypeM: cannot handle function type: (i32, i32) -> i32
CallStack (from HasCallStack):
  error, called at src/Futhark/Internalise/TypesValues.hs:165:7 in futhark-0.23.0-inplace:Futhark.Internalise.TypesValues
```

However, I think my program is actually invalid, since it's returning a function as part of the result tuple in the branch, so the above error is probably a symptom of a hole in the type checker rather than a hole in the internaliser (I guess).

If I change my program to be slightly less elegant:

```futhark
entry main: i32 -> i32 -> i32 =
  ((true, (.0)), (false, (.1)))
  |> (\p -> if p.0.0 then p.0.1 else p.1.1)
  |> curry
```

then the compiler correctly complains that the type of the branch return values is "found to be functional", and refuses to handle the program. I would expect the same type error for my original program.

**Comment by athas** [comment]
The probable error is that we don't know exactly what `p` is when we type-check the lambda, but we correctly note that its components may not be functions.  Then we neglect to check that constraint when they are later linked.

**Comment by athas** [comment]
No, the problem is that we do not track liftedness for unknown records or sum types.
