### ISSUE TITLE
multicore backend seems to miscompile some code

### ISSUE THREAD

**Issue by GoldsteinE** [diku-dk/futhark#1800]
Hi! I’ve stumbled upon this accidentally. I don’t usually use Futhark, so the code sample to reproduce the problem is certainly not minimal.

This code:
https://github.com/GoldsteinE/aoc2022/blob/c8d6c49d2e1ba6035002fc1f590758265951ae07/day15/code/futhark.pkg
https://github.com/GoldsteinE/aoc2022/blob/c8d6c49d2e1ba6035002fc1f590758265951ae07/day15/code/main.fut

With this C code to start it:
https://github.com/GoldsteinE/aoc2022/blob/c8d6c49d2e1ba6035002fc1f590758265951ae07/day15/code/wrapper.c

Produces these results with freshly-built Futhark from commit 625f4ec23f4f591ce1a1270770224d6b22a11e3a (and just ICEs Futhark v0.20.5, which might be or not be related):
```shell
$ bin/futhark multicore --lib main.fut
$ gcc -lpthread -O3 main.c wrapper.c -o wrapper
$ ./wrapper part 2 < ~/pets/aoc2022/day15/in/part2.txt
0
$ bin/futhark c --lib main.fut 
$ gcc -lpthread -O3 main.c wrapper.c -o wrapper
$ ./wrapper part 2 < ~/pets/aoc2022/day15/in/part2.txt
12274327017867
```

(where `part2.txt` is https://github.com/GoldsteinE/aoc2022/blob/c8d6c49d2e1ba6035002fc1f590758265951ae07/day15/in/part2.txt)

As this code doesn’t use any unsafe, I presume that there’s some problem with `multicore` backend. I may be mistaken tho.

**Comment by athas** [comment]
I can reproduce.

**Comment by athas** [comment]
It works with 1 thread.  My hunch is that it is related to the filter.

**Comment by GoldsteinE** [comment]
It's entirely possible that this problem is result of a my misunderstanding about how some of the constructs work in parallel mode.

**Comment by athas** [comment]
Looks fine to me.  There are not that many ways to get them wrong (mostly passing non-associative functions to reductions) and that is not happening here.

**Comment by GoldsteinE** [comment]
I'll try to minimize this later

**Comment by athas** [comment]
I've managed to shrink it myself.  Very mysterious; nothing really unusual is going on here.

**Comment by athas** [comment]
Oh cool, this looks like it's due to load-balancing of reductions.  We have quite few unbalanced programs in our test and benchmark suites, so I guess that code path is not well exercised.

**Comment by athas** [comment]
Small example:

```
def main n = i64.sum (map (\i -> loop i = i+1 while i < 1000 do i * 3) (iota n))
```

Our detection of load-imbalanced code is very crude, and basically boils down to having a `while` loop.

**Comment by athas** [comment]
I realise this didn't show off Futhark in a very good light, but consider also checking out [my solution for day 15](https://github.com/athas/aoc22/blob/main/15.fut).

**Comment by GoldsteinE** [comment]
Thanks, I had in plans checking out your solution

**Comment by GoldsteinE** [comment]
It’s interesting that `multicore` now works, but makes my code slower. I assume that’s a problem in my code, not Futhark so.
