### ISSUE TITLE
Nothing compiles [ARCH]

### ISSUE THREAD

**Issue by Retkid** [diku-dk/futhark#1818]
source: https://futhark-lang.org/examples/3d-vectors.fut

command ... any. For example: futhark c 3d-vectors.fut: 

Error: Error at fact.fut:78:12-12: Parse error

**Comment by athas** [comment]
Are you using a very old version of the compiler?

**Comment by Retkid** [comment]
Futhark 0.19.7

...

Yes. I have had some trouble getting it to compile on arch because of dependency issues

**Comment by Retkid** [comment]
im going to update the aur package now

**Comment by athas** [comment]
I don't know anything about Arch packaging, but the binary Linux tarballs that are published here on GitHub are statically linked and will run anywhere.

**Comment by Retkid** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=futhark-bin

it graves the futhark version statically, and it hasn't been updated since 2021, and probably had some weird linking issue since nothing works on it.

I'm not sure how arch packaging works, ideally it would just get /latest. I dont think I can do any deterministic webscraping in PKGBuilds and I don't have a sever to automate the updating of the version, if i were to acquire the package.

Is there anyway you can figure a github /latest/ where, it builds to /latest and the packages don't need to be maintained as much?
