### ISSUE TITLE
Request: add log1p in math prelude

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1820]
`log1p(x)` computes accurately `log(1 + x)` even when `x` is very small. 

It looks like OpenCL and CUDA have it as primitives, although I can't find reference to a 16-bit CUDA `log1p`.

I can give it a go if it turns out just to require appending definitions to the prelude.

**Comment by athas** [comment]
Sure, have at it. The main challenge is getting it done for all the backends, but if you add a test to tests/primitive, CI will tell you the ones you missed. For the 16 bit version, I would just use 32 bit arithmetic - we do that with many others. Let me know if you need more pointers.

**Comment by nbos** [comment]
How bad is it if results vary by 1 or 2 ULPs between backends? E.g. Haskell's `log1p 2.0` gives `1.0986122886681096` to the interpreter while my implementation for ISPC gives `1.0986122886681098`. Do I just omit those cases in tests?

**Comment by athas** [comment]
The testing tool uses a fairly generous tolerance when comparing.
