### ISSUE TITLE
REPL parsing error on floating point numbers with exponent

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1822]
Entering `1e12f32` in the REPL is answered with
```
Unknown name "e12f32"
```
This is fairly recent since it worked fine on a build from a little over 2 weeks ago.

**Comment by athas** [comment]
This is probably due to the lexer changes I made recently.  I'll cook up a fix.

**Comment by athas** [comment]
Wait, it only fails in the REPL?  That is truly mysterious.  They use the same lexer and parser.
