### ISSUE TITLE
Operator grammar mismatch with docs

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1824]
The language reference says that binary operators must start with one of
```
opstartchar ::=  "+" | "-" | "*" | "/" | "%" | "=" | "!" | ">" | "<" | "|" | "&" | "^"
```
but I get `Unexpected token` on identifiers starting with any number of "!" (e.g. `(!)`, `(!!)`) and also those starting with a single "=" (e.g. `(=+)`, but `(===)` works).

**Comment by athas** [comment]
Curious.  This is the definition of `opchar` in the lexer:

```
$opchar = [\+\-\*\/\%\=\!\>\<\|\&\^\.]
```

Seems correct to me.  The problem must be in the rules that use it.  A binary operator token is this:


```
@binop = ($opchar # \.) $opchar*
```

It looks like both `+=` and `!!` are lexed correctly, so the problem must be in the parser.

**Comment by athas** [comment]
With the bugs you're finding in dusty corners, you must be writing some really funky code.  This one has been in the compiler for a while.

**Comment by nbos** [comment]
Here I was just writing an indexing operator; it wasn't letting me and I got digging.
I regularly find myself writing gathers like `map (\i -> xs[i]) is`.

**Comment by nbos** [comment]
`(!!)` is fixed, but `(!)` and `(=+)` still don't parse.

**Comment by athas** [comment]
Fixed the `=+` bug.  It is intentional and documented (somewhere in the reference) that `(!)` cannot be redefined, as it is a prefix operator.

**Comment by nbos** [comment]
Great, thanks!
