### ISSUE TITLE
Internal compiler error: Scope.lookupInfo: Name color_7283 not found in type environment

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1838]
Compiling the program
```
entry main [n] (xs: [n]i64) =
  tabulate n
  (\_ ->
     let xs = loop xs = copy xs for i < 3
	      do scatter (copy xs) (scan (+) 0 xs) xs
     let xs = xs with [0] = n
     in spread xs[0] 0 xs xs :> [n]i64)
```
with backend `opencl` results in the error
```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
Scope.lookupInfo: Name color_7283 not found in type environment.
CallStack (from HasCallStack):
  error, called at src/Futhark/IR/Prop/Scope.hs:84:9 in futhark-0.23.0-inplace:Futhark.IR.Prop.Scope
```

**Comment by Munksgaard** [comment]
That looks like one of mine...

**Comment by Munksgaard** [comment]
Apparently not, the same thing happens with `futhark dev --gpu -a -e --cse -e --expand-allocations`! The generated code also looks pretty harmless.

**Comment by athas** [comment]
Yeah, I'm not quite sure why this one is a problem, although I'm guessing it's related to the irregularity.  I don't think the slicing of allocation sizes is a very well tested code path.  I'm recompiling with profiling to get a better lead.
