### ISSUE TITLE
Internal Compiler Error: Simplification fails

### ISSUE THREAD

**Issue by poeface** [diku-dk/futhark#1851]
I found this bug yesterday but it took me until now to be able to isolate it down to a (somewhat) concise test program. I really don't have much insight into the cause because it's occurring during the simplification pass--multiple different lines of code appear to be involved.

Here is the error it reports:
```
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'simplify':
In function entry_main
When checking function body
In expression of statement
  {transpose_res_9137 : ({concat_rep_9184}, [25i64][50i64]f64)}
The permutation (1, 0) is not valid for array concat_rep_9184 of rank 1.
```

running this version of futhark:
```
Futhark 0.23.0 (prerelease - include info below when reporting bugs)
git: f597d8d (Wed Jan 18 12:27:57 2023 +0100)
```

And here is the test program: [simplify_bug.zip](https://github.com/diku-dk/futhark/files/10458719/simplify_bug.zip)

Sorry to keep you so busy with these new bugs! I promise I'm not actively trying to find them haha. I guess it's something about the way we engineers are using your language.

**Comment by athas** [comment]
No worries!  If we didn't want bug reports, we would not have put bugs in the compiler.
