### ISSUE TITLE
Parsing error on sum type with a vector payload?

### ISSUE THREAD

**Issue by poeface** [diku-dk/futhark#1853]
The following code fails parsing:

    type Thing = #this [2]f64 | #that [3]f64

saying

```
Unexpected token: '['
Expected one of the following: 

```

with no suggested token provided. Is this a parsing bug? I have been trying to figure out if this could be an intentional limitation on sum types, but I can't find anything in the documentation that would suggest it. If it is intentional, I apologize for filing an unnecessary issue!

**Comment by athas** [comment]
Due to embarrassing parser restrictions, you have to parenthesize those:

```
type Thing = #this ([2]f64) | #that ([3]f64)
```

**Comment by athas** [comment]
Actually, the parser technology in my head may have matured to the point that this can be fixed.  The fix will make certain currently working (but confusing) syntax invalid, though.  From the test suite, `[]#foo | #bar` can now longer be used to indicate an array of an anonymous sum type, and `[t] mpr_net [n]` will not work for an array of elements of type `mpr_net [n]`.  In both cases, the solution is to add parentheses.

**Comment by athas** [comment]
Oh, apparently breaking that is not actually required.  We might consider it some other time, though...  I am horrified that we allow that.

**Comment by poeface** [comment]
> you have to parenthesize those

ah that makes sense--that's no problem to use. Thanks for a fix all the same!
