### ISSUE TITLE
Internal Compiler Error: After internalization, lambda return is wrong

### ISSUE THREAD

**Issue by poeface** [diku-dk/futhark#1855]
In the process of developing a solver I found this new error:

```
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
After internalisation:
In function lifted_lambda_6629
When checking the body aliases: [[mode_7261, mode_7262], [mode_7261, mode_7262]]
A unique tuple element of return value of function lifted_lambda_6629 is aliased to some other tuple component.
```

my futhark version is hot off the press:

```
Futhark 0.23.0 (prerelease - include info below when reporting bugs)
git: cb9d1c1 (Sat Jan 21 16:40:39 2023 +0100)
```

Here is code that generates the bug: [internalization_bug.zip](https://github.com/diku-dk/futhark/files/10472907/internalization_bug.zip)

The bug arises from somewhere in the block from line 42 to 47.

Hope that helps!

**Comment by athas** [comment]
Smaller case:

```Futhark
type t [n] = #foo [n](i32,i32) | #bar

def main (x: t []) =
  (\x -> match x
         case #foo arr -> take 2 arr
         case _ -> [(0,1)]) x
```

Looks like lambda lifting is inferring the wrong uniqueness of a return type.  Should not be too difficult to fix.  Futhark 0.21.1 also has this bug, so it is not new.

**Comment by athas** [comment]
Actually, this is a problem in type checking, where we don't propagate aliases when we pattern match on an incompletely known sum type.

In the long run I think we should move all alias/consumption checking to a second type checking phase, where we know completely the type structure, but I think I can patch this for now.
