### ISSUE TITLE
Internal error in interpreter for input with empty arrays

### ISSUE THREAD

**Issue by mkm** [diku-dk/futhark#1863]
Consider the following program:

    let main (foo: [1][0]i32): [1]i32  =
        map2 (\_ _ -> 0) [0] foo

Running it with `futhark run` using input `empty([1][0]i32)` it crashes with the following error message:

    Internal compiler error (unhandled IO exception).
    Please report this at https://github.com/diku-dk/futhark/issues
    "b" is not bound to a value.
    CallStack (from HasCallStack):
      error, called at src/Language/Futhark/Interpreter.hs:591:10 in futhark-0.23.0-inplace:Language.Futhark.Interpreter

The compiled version correctly produces the output `[0]`.

**Comment by athas** [comment]
@zfnmxt Do you really want to work on this one?  I don't think it's your fault, and the type/size-passing machinery in the interpreter is somewhat unpleasant.

**Comment by athas** [comment]
This works:

```Futhark
let main x : [1]i32  =
  let (foo: [1][]i32) = [[]]
  in map2 (\_ _ -> x) [0] foo
```

So I actually think it's a fairly boring bug in the value parser, which probably constructs the empty array value as an empty list, while our canonical representation is a singleton list containing an empty array.

**Comment by athas** [comment]
[Almost certainly the problem is here.](https://github.com/diku-dk/futhark/blob/master/src/Language/Futhark/Interpreter/Values.hs#L224-L238)
