### ISSUE TITLE
CudaText (free editor) now supports Futhark lexer

### ISSUE THREAD

**Issue by Alexey-T** [diku-dk/futhark#1881]
To install the lexer: "Plugins / Addons Manager / Install", find 'Futhark' item, ENTER to install.

Example
![Screenshot from 2023-02-26 11-25-51](https://user-images.githubusercontent.com/4154978/221400077-f2dc57a9-e5c2-4481-a365-1993bdc246d5.png)

![Screenshot from 2023-02-26 11-28-29](https://user-images.githubusercontent.com/4154978/221400187-6fc3eb6d-fe0a-46ce-be85-83878f5da423.png)

Lexer supports code-tree.
you may report your wishes about lexer.

**Comment by athas** [comment]
Cool!  I installed CudaText on my NixOS machine and installing the lexer works fine.  I have no particular wishes.
