### ISSUE TITLE
syntax file for Sublime Text 3: issues

### ISSUE THREAD

**Issue by Alexey-T** [diku-dk/futhark#1882]
1. syntax file https://github.com/titouanc/sublime-futhark/ is NOT listed in https://packagecontrol.io site
2. I found issues in syntax file, can someone fix them? https://github.com/titouanc/sublime-futhark/issues

**Comment by athas** [comment]
You should raise this issue on the repository in question.  It is not developed by the Futhark project itself, so we have no control over it.
