### ISSUE TITLE
Style checking Python programs in CI

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1894]
We have a bunch of Python programs in `tools/`, but where our Haskell code is closely scrutinized by such things as `hlint`, `ormolu`, and GHC itself, no such thing has been set up for Python.

I have no idea what kind of linters are commonly used for Python, but someone should investigate and set it up.

**Comment by kfl** [comment]
I recommend:

* `pep8` as style checker <https://pypi.org/project/pep8/> (a bit like `hlint`) 
* `black` as formatter <https://pypi.org/project/black/> (like `ormolu`)
* `mypy` as type checker <https://www.mypy-lang.org/> (but that's a bit of an investment)

I've *been* recommended `flake8` <https://github.com/pycqa/flake8>, but personally I've found it too big an investment compared to the gains.

**Comment by WilliamDue** [comment]
Thanks @kfl this is very helpful!
