### ISSUE TITLE
Incorrect results for `vjp` on OpenCL backend

### ISSUE THREAD

**Issue by nhey** [diku-dk/futhark#1895]
```futhark
import "lib/github.com/athas/vector/vspace"

-- Setup from my program.
module real = f32
module v = mk_vspace_3d real

type real = real.t
type vec3 = v.vector

def to_vec3 (xs: [3]real) = {x=xs[0], y=xs[1], z=xs[2]}
def map_2d f = map (map f)
def map_3d f = map (map_2d f)

def grad 'a (f: a -> real) (primal: a) = vjp f primal (real.i64 1)

let jacfwd [n][m] (f: [n][m]vec3 -> real) (x: [n][m]vec3): [n][m]vec3 =
  let v3 xs = unflatten_3d n m 3 xs |> map_2d to_vec3
  let tangent i = (replicate (n*m*3) 0 with [i] = 1) |> v3
  in tabulate (n*m*3) (\i -> jvp f x (tangent i)) |> v3


-- The function.
def fun atom_coords : real =
  let xs = flatten atom_coords
  -- "Random" reads are necessary (in the original program this reads an
  -- input of unknown pairs of indices, here the indexing is just nonsense):
  let dists = map2 (\i j -> v.norm (xs[i] v.- xs[j]))
                   (indices atom_coords)
                   (indices atom_coords |> reverse)
  in f32.sum dists


-- ==
-- entry: test_rev_ad
-- random input { [1][32][20][3]f32 }
-- auto output
entry test_rev_ad coords =
  map (grad fun) (map_3d to_vec3 coords)
  |> map_3d (\v -> [v.x,v.y,v.z])

-- ==
-- entry: test_fwd_ad
-- random input { [1][32][20][3]f32 }
-- auto output
entry test_fwd_ad coords =
  map (jacfwd fun) (map_3d to_vec3 coords)
  |> map_3d (\v -> [v.x,v.y,v.z])
```

(I cannot, for the life of me, reduce this program further, sorry).
My version of the compiler is at b9acc013a235d747525e343db1cea54d533ec212.

Changes that seem to make the error go away:
1. Removing the outer dimension from random input (and thus the map of `vjp`)
2. Reducing dimensions of sizes 32 and 20 too much.
3. Removing the random index dists calculation in fun.
4. I think, not using vectors (I tested too many variations at this point).

**Comment by athas** [comment]
Is the difference only when using the `opencl` backend, or also when using `c`?

**Comment by nhey** [comment]
Only when using `opencl`. Auto output asserts this right? I found the difference by testing the original program against a python implementation.

**Comment by athas** [comment]
`auto output` will check whether the output produced by the `opencl` backend matches what is produced by the `c` backend for the same entry point. That doesn't have anything to do with whether forward/reverse mode AD coincides.

**Comment by nhey** [comment]
Right. I have tested the two against the same input/output and the difference does not occur for `c`.

**Comment by athas** [comment]
I can reproduce on some machines, but not all.  Interesting.

**Comment by nhey** [comment]
The issue is not about mismatching results; it is definitely the reverse mode that is incorrect. Excuse the misleading title.

**Comment by nhey** [comment]
I also cannot reproduce on my local machine (though it has no dedicated GPU).

**Comment by athas** [comment]
If reverse mode is correct when using the C backend, then how can there be anything wrong with the AD pass itself?  I even notice nondeterministic results when using the GPU backend.  It is unlikely that AD can cause that; there is no way to express nondeterminism in the core language.  It's probably a bug in codegen.

**Comment by nhey** [comment]
By reverse mode being incorrect, I was referring to the output of the program using `vjp`. I'll edit the title to better reflect the issue.

**Comment by athas** [comment]
The program results in two GPU code versions being generated.  It is only the intragroup version that misbehaves.  Probably something related to intragroup accumulators - that is likely not a well tested code path.
