### ISSUE TITLE
Smuggling sizes through functions

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1903]
This program type-checks and works:

```Futhark
module m1 = {
  def f [n] (_: [n]bool -> bool) = n
}

def contrived (_: [10]bool) = true

entry main1 = m1.f contrived
```

`m1.f` uses a size that is only made available through a function.  Functions are "black box" and do not carry their sizes at runtime (unlike arrays), but this works because type inference can connect the size parameter `n` to the type of `contrived` (that is, the instantiation `n=>10` is used).

This program type-checks but does not work:

```Futhark
module m2 : {
  type^ t
  val x : bool -> t
  val f : t -> i64
} = {
  type^ t = []bool -> bool
  def x b = \(_: [10]bool) : bool -> b
  def f [n] (_: [n]bool -> bool) = n
}

entry main2 = m2.f (m2.x true)
```

Here the module ascription hides the fact that `f` actually has a size parameter, meaning that type checking is not instantiating anything when checking the expression `m2.f (m2.x true)`.  This would work if the size `n` was also the size of an array parameter (we call this a "constructive use", and means the array acts as a kind of witness), because we can fish out the size at run-time from the array shape, but functions do not (and *should not*) carry around the sizes of their parameter types.

@melsman Any ideas on this one?  I can think of a few ideas:

* Ban functions such as `f` that use a size only in a "non-constructive" manner.  We actually have similar restrictions elsewhere, so this is probably fine.  It means that definitions such as `def iiota: [n]i64 = iota n` that use "return type size polymorphism" would no longer work, but I'm not sure we ever agreed such definitions were desirable, and I'm almost certain no code actually uses them.  I was always a bit nervous about this bit of flexibility, and I don't think it was allowed in the original conception of the size type system.

* *If* this problem only occurs due to module ascriptions (I'm almost but not completely sure of that), then add some additional rules.  We *do* still want to allow module ascription to hide size parameters, as otherwise abstract size-lifted types become useless, but perhaps we could require that if you hide a size parameter, that size parameter must be used constructively (i.e. as an actual array size).

* Come up with a more complicated dynamic semantics that can make this work.  The programs above do actually work with the compiler (but not interpreter), because defunctorisation will add back the missing size parameters.  However, the whole point of the interpreter is to keep us honest about the fundamental simplicity of the language semantics, so this is a bit of a "semantics smell" to me.

**Comment by catvayor** [comment]
The problem with `m2` appears at monomorphisation:
When monomorphised, the `f` function takes a new argument which is the `n` it returns, but in `main2`, it has no way to know what to give as this argument, it then supposes that it means any value is fine, and gives `0i64`.

```haskell
inferSizeArgs :: [TypeParam] -> StructType -> StructType -> [Exp]
inferSizeArgs tparams bind_t t =
  mapMaybe (tparamArg (dimMapping bind_t t)) tparams
  where
    tparamArg dinst tp =
      case M.lookup (typeParamName tp) dinst of
        Just (SizeExpr (Var d _ _)) ->
          Just $ Var d (Info i64) mempty
        Just (SizeExpr (IntLit x _ _)) ->
          Just $ Literal (SignedValue $ Int64Value $ fromIntegral x) mempty
        _ ->
          Just $ Literal (SignedValue $ Int64Value 0) mempty ------------ there
```

The program is then 
```futhark
def f (n: i64) ((_: [n]bool -> bool)) : i64 =
  n

def x (b: bool) : [10]bool -> bool =
  \((_: [10]bool): [10]bool):bool ->
    b

entry main2 : i64 =
  f 0i64 (x true)
```
after monomorphisation.

I'm not sure, but I think this problem comes from `f` having the type `m2.t -> i64` in the body of `main2` until monomorphisation, and so the size variable is not unified during the typing, and never known to the monomorphisation module. I think we may solve the problem by doing a unification pass when type declaration are replaced, but I don't know how to manage existentials in this situation if someone manage to make one.

This particular case of monomorphisation is currently used in only one test (`tests/shapes/entry-lifted.fut`) because of the function `m.mk` having to allow any size for the `#bar` constructor. Note that again the function is in a module in which an ascription hide a size parameter, when removing it, such a function is not accepted because `main2` would be size-polymorphic in it's return type.

**Comment by athas** [comment]
I am reluctant to re-do type checking during monomorphisation.  I am increasingly of the belief that we should reject this program in the type checker; probably as part of module ascription.  The rule should be something like "you can only hide a size parameter if that size parameter is used constructively in a parameter".  Don't work on this; Martin and I will look at it.

**Comment by melsman** [comment]
I'm unsure what type `t` in `m2` represents - is it an existential type? In that case, I don't think `f` should match its specification, should it?

**Comment by athas** [comment]
There is nothing existential in `t` (depending on how you define "existential".)  Instead, the module ascription hides a size parameter, which turns `m2.f` into an instance of *higher rank polymorphism*.  We allow module ascription to hide size parameters (but not type parameters) because we can usually infer values for size parameters based on the actual parameters passed at run-time.  The exception is if the size is only used in a function: then we cannot infer them.

**Comment by athas** [comment]
I think the problem here may just be that we allow

```Futhark
type^ t = []bool -> bool
```

while the explicit

```Futhark
type^ t = ?[n].[n]bool -> bool
```

is rightly banned.

**Comment by catvayor** [comment]
It should not be just syntactic sugar ?

**Comment by athas** [comment]
Indeed, the former is supposed to mean the same as the latter, but currently it doesn't.  Likely because the former is actually the older notation.  I will fix it and hope it won't break too many programs.
