### ISSUE TITLE
futhark lsp: Prelude.undefined: Eglot times out on LSP crashing

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1907]
Opening a `.fut` file with the `Emacs` + `Eglot` + `Flymake` combo, it doesn't take long before `Eglot` stop responding after landing the cursor on a piece of code. The `*EGLOT events*` buffer reads a long log of seemingly normal event ending with
```
(:jsonrpc "2.0" :id 3 :method "textDocument/hover" :params
	  (:textDocument
	   (:uri "file:///home/user/test/test.fut")
	   :position
	   (:line 0 :character 26)))
[stderr] [Debug] ---> {"jsonrpc":"2.0","id":3,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///home/user/test/test.fut"},"position":{"line":0,"character":26}}}
[stderr] Got hover request: (Just "/home/user/test/test.fut",Position {_line = 0, _character = 26})
[stderr] futhark: Prelude.undefined
[stderr] CallStack (from HasCallStack):
[stderr]   error, called at libraries/base/GHC/Err.hs:74:14 in base:GHC.Err
[stderr]   undefined, called at src/Language/Futhark/Query.hs:114:25 in futhark-0.25.0-inplace:Language.Futhark.Query
[internal] (id:3) Mon Mar 27 08:00:28 2023:
(:timed-out :textDocument/hover :id 3 :params
	    (:textDocument
	     (:uri "file:///home/user/test/test.fut")
	     :position
	     (:line 0 :character 26)))
```
Which refers to the `undefined` at https://github.com/diku-dk/futhark/blob/b562f0c340748cfbd200ee823201bf727fc76270/src/Language/Futhark/Query.hs#L114 that was added at https://github.com/diku-dk/futhark/commit/2b94ea17a4f8e15a66b05e061db63bb228452fdc because of https://github.com/diku-dk/futhark/pull/1873

**Comment by athas** [comment]
This happened because we do not have tests for `futhark query` (and through that, the LSP).
