### ISSUE TITLE
Add more glossary terms

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1909]
I have begun work on a [glossary of terms](https://futhark.readthedocs.io/en/latest/glossary.html) that might be useful to new Futhark programmers.  I'll leave this issue open for a little while as invitation to suggest other terms that we might want to add.

**Comment by Munksgaard** [comment]
Great initiative!

Ideas off the top of my head: lifted types (`^`), coalescing, irregular vs regular parallelism

**Comment by athas** [comment]
> size coercions; they're also called shape coercions in [some places](https://futhark-lang.org/examples/shape-coercions.html). (Maybe they should be consistently named a single thing.)

Which name do you think is best?

**Comment by athas** [comment]
I can argue "size coercion" is better, since you can only change sizes of shapes, not ranks.  Hence, "shapes" don't change, only sizes do.

**Comment by athas** [comment]
Thanks!  I included most of your suggestions.  Exclusions:

* higher-order (type | function): if you don't know what a higher-order function is, then the Futhark glossary is the wrong thing to read.  And what is a higher-order type?
* (size | type) annotation: I kind of want to get away from this nomenclature, but maybe I'll change my mind.  (They are not *annotations*, they are *ascriptions*, and they are all ultimately *type ascriptions*.)
* coalescing: You mean GPU memory transaction implementation details?  What could we say about this that would be useful?  The compiler will *never* scream this word at you.

**Comment by zfnmxt** [comment]
>  And what is a higher-order type?

You tell me! https://github.com/diku-dk/futhark/blob/4d53cb450d7cb4fa4308d72f256c1a7f068a7d89/src/Language/Futhark/TypeChecker/Unify.hs#L929
