### ISSUE TITLE
Typo in reverse AD docs

### ISSUE THREAD

**Issue by clemisch** [diku-dk/futhark#1912]
On the [page](https://futhark-lang.org/examples/reverse-ad.html) for reverse AD, it says 

> jvp corresponds to differentiation by [reverse accumulation](https://en.wikipedia.org/wiki/Automatic_differentiation#Reverse_accumulation)

but should say

> **vjp** corresponds to differentiation by [reverse accumulation](https://en.wikipedia.org/wiki/Automatic_differentiation#Reverse_accumulation)

**Comment by athas** [comment]
Fixed, thanks.
