### ISSUE TITLE
Problem with unknown sizes arising from anonymous sizes in coercions

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1918]
Crashes the compiler:

```Futhark
type opt 't = #some t | #none

def main b (x: i64) =
  if b
  then #some (iota x)
  else #none :> opt ([]i64)
```

I think unknown sizes arising from coercions is a misfeature, and one we've already removed in #1897 I think.

**Comment by athas** [comment]
Crashes the interpreter, too.  #1917 was also a sum type bug.  I guess people are really starting to use them now.

**Comment by catvayor** [comment]
> one we've already removed in https://github.com/diku-dk/futhark/pull/1897 I think.

Still crash in #1897 after internalisation

**Comment by catvayor** [comment]
```futhark
def main b (x: i64) =
  if b
  then [iota x]
  else [] :> [0][]i64
```
I was expecting the same crash, but I got branches differing in type as the second one is considered as `[0]i64`, as if the anonymous size was removed

**Comment by athas** [comment]
Yeah, I'm fixing it.  It was a bit more subtle than expected.
