### ISSUE TITLE
This should type check

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1923]
```Futhark
def f [n] [m] 't (_: [n+m]t) = n * m

def main [n] (xs: [n]i32) =
  f (let xs' = filter (<3) xs
     in xs' ++ xs)
```

This contrived program will work once we simplify the handling of unknown sizes in the type checker, *but* that in return requires work on monomorphisation.

**Comment by melsman** [comment]
What is the result? My guess is zero, as an array of size k=n+m can always be decomposed into an array of size n=0 catenated with an array of size m...

**Comment by catvayor** [comment]
needs to be fully normalised
```futhark
def f [n] [m] 't (_: [n+m]t) = n * m

def main [n] (xs: [n]i32) =
  let [d] (xs': [d]i32) = filter (<3) xs
  let (tmp: [d+n]i32) = xs' ++ xs
  f tmp
```

**Comment by athas** [comment]
> What is the result? My guess is zero, as an array of size k=n+m can always be decomposed into an array of size n=0 catenated with an array of size m...

That's not how unification works.  Except in edge cases, the sizes of arrays are expressions of rigid variables, so you cannot just decompose them.  The program is only type correct if `f` is passed an array whose size is already some syntactical expression `a+b`.  The goal here is to ensure that `xs'` going out of scope does not eliminate that structure.

**Comment by melsman** [comment]
My point was that we may want to disallow functions like `f`. Adding a type cast may now change the semantics of a program, I presume...

**Comment by athas** [comment]
The underlying principle is this: we should type check anything that would type check if it had been written in ANF and with explicit binding of existentials.  Similarly, if a program type checks, the user should be able to turn it into that explicit form and still have it type check.

**Comment by athas** [comment]
Actually, maybe banning size parameters that are not used constructively would not be a big problem if they cause semantic headaches.  Looking over our usage examples, they don't really seem to occur outside of contrived test programs.
