### ISSUE TITLE
Unscoping of i64

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1924]
This version of `partition` does not work:

```Futhark
def partition [n] 'a (p: a -> bool) (as: [n]a): ?[k].([k]a, [n-k]a) =
  let p' x = if p x then 0 else 1
  let (as', is) = intrinsics.partition 2 p' as
  let q = is[0]
  in (take q as', drop q as')
```

The reason is that although the final tuple expression is indeed assigned type `([q]a, [n-q]a)`, when `q` then goes out of scope we weaken the type to `([k1]a, [k2]a)` for some fresh unknown sizes `k1,k2`.

I discussed this with @catvayor today and we reasoned that it might be fine to treat `i64`-typed variables going out of scope specially, and not turn the *entire* size expression in which they occur into an unknown size, but only the part actually going out of scope.  We argue that this is OK because `i64` really *is* a special type, as it is the only type that can be existentially quantified.

**Comment by catvayor** [comment]
types like `?[k].([k]a, [n-k]a)` should be only allowed if k is used constructively, right ?

**Comment by catvayor** [comment]
I think the typing can work well, but I have questions about the type of `intrinsics.partition`:
your program as the type `([d₁₅]a, [k - d₁₅]a)` (no k declared).
reading Prop.hs, I found the type of `intrinsics.partition` is `i64 -> (a -> i64) -> [n]a -> ?[m]([k]a, *[n]i64)`, where this k is coming from ?

**Comment by athas** [comment]
Uh, that looks like a bug in the type of the partition intrinsic.  I will fix it.

**Comment by athas** [comment]
Fixed.  I don't understand what you claim freezes the interpreter.

**Comment by catvayor** [comment]
```futhark
[0]> let p = \_ -> true
[1]> let as = iota 50
[2]> let p' x = if p x then 0 else 1i64
[3]> :t intrinsics.partition 2 p' as
partition 2 p' as : ([k]i64, [50]i64)
[4]> let (as', is) = intrinsics.partition 2 p' as
```
just let me without reply
