### ISSUE TITLE
Futhark repl sometimes crash

### ISSUE THREAD

**Issue by catvayor** [diku-dk/futhark#1929]
When running `futhark repl`, it sometimes crash with the error:
```
futhark: mmap 4096 bytes at (nil): Cannot allocate memory
futhark: Try specifying an address with +RTS -xm<addr> -RTS
fish: Job 1, 'futhark repl' terminated by signal SIGSEGV (Address boundary error)
```
This don't always arise, but in like 30% of runs (I've done 100 tests, it happened 31 times).
Also, it seems to never happen when piping input from a file

**Comment by athas** [comment]
When does this happen?  Just when `futhark repl` starts?  This looks like a Haskell RTS error: specifically, that it tries to map page zero.
