### ISSUE TITLE
test tags not working

### ISSUE THREAD

**Issue by Alexnortung** [diku-dk/futhark#1939]
I am creating a library in futhark and want to do some benchmarks and tests, I would like my benchmarks to not run when using test.

Following the [documentation](https://futhark.readthedocs.io/en/latest/man/futhark-test.html) I have created some benchmarks.

[`main.fut`](https://github.com/Alexnortung/sha256.fut/blob/e5c0f253f00a2e6a0ce8f905d8894c9bbfc5a1ee/lib/github.com/alexnortung/sha256.fut/main.fut#L50-L66)

```futhark
-- ==
-- tags { disable }
-- entry: multi_sha256
-- compiled random input { [500][30]u8 }
-- compiled random input { [1000][30]u8 }
-- compiled random input { [2000][30]u8 }
-- compiled random input { [3000][30]u8 }
-- compiled random input { [4000][30]u8 }
-- compiled random input { [10000][30]u8 }
-- compiled random input { [1000000][30]u8 }
-- compiled random input { [2000000][30]u8 }
-- compiled random input { [4000000][30]u8 }
-- compiled random input { [8000000][30]u8 }
-- compiled random input { [16000000][30]u8 }
-- compiled random input { [24000000][30]u8 }
-- compiled random input { [10][2000000]u8 }
```

However when running test on the file I get an error:

```
./lib/github.com/alexnortung/sha256.fut/main.fut:52:9:
   |
52 | -- tags { disable }
   |         ^^^^^
unexpected "{ dis"
expecting "input" or white space
```

I would expect it to handle the tags like the documentation states. Am I doing anything wrong?

## Meta:

repository: [Alexnortung/sha256.fut](https://github.com)
futhark version: 0.22.3 and updated to 0.24.3

**Comment by athas** [comment]
Tags apply to the entire program and can only be used in the first test block.  You can prefix your benchmark inputs with `no_test` and then pass `--exclude=no_test` to `futhark test`.  Perhaps the latter should be added as implicit behaviour.

**Comment by Alexnortung** [comment]
Ahh thanks, I guess I missed that. What do you mean by prefix? Prefix in the tags?

I have moved my benchmark tests to another file and it works fine :)
