### ISSUE TITLE
How to use futhark in haskell?

### ISSUE THREAD

**Issue by wujilingfeng** [diku-dk/futhark#1942]
Due to many limitations and other reasons of Futhark, I need to program in Haskell language. I would like to know how to use futalk perfectly in Haskell language.
Thank you very much!

**Comment by Munksgaard** [comment]
I think you best bet is to use something like [futhask](https://gitlab.com/Gusten_Isfeldt/futhask), which enables you to easily use a Futhark library from Haskell.

**Comment by athas** [comment]
Yes, futhask is the best solution for this.  Here is a [list of language bridges](https://futhark-lang.org/docs.html#bridges).

**Comment by wujilingfeng** [comment]
> I think you best bet is to use something like [futhask](https://gitlab.com/Gusten_Isfeldt/futhask), which enables you to easily use a Futhark library from Haskell.

Thanks. I'm learning it.
