### ISSUE TITLE
Where do I go for coding advise?

### ISSUE THREAD

**Issue by wstevick** [diku-dk/futhark#1951]
I'm used to procedural programming, and am having difficulty reworking my brain to think functionally. Is there a place where I can ask about solutions to specific programming problems? I'm hesitant to put my questions here, because it seems like this is for issues with the language, not the programmer.

Thank you

**Comment by Munksgaard** [comment]
Welcome to the functional world! There are lively discussions about Futhark on gitter/matrix (https://gitter.im/futhark-lang/Lobby) and to a lesser degree on #futhark on libera.chat.

**Comment by wstevick** [comment]
Thank you.

**Comment by athas** [comment]
Also, Futhark is largely a simplified subset of normal functional programming, so standard tutorials on programming in languages such as Haskell, F#, or OCaml are also useful.  The main difference is Futhark does not support recursion, which is usually taught as the fundamental primitive operation in functional programming.  In Futhark, the fundamental primitive is more like `map`.
