### ISSUE TITLE
Apparent bounds checking failure

### ISSUE THREAD

**Issue by Programmerino** [diku-dk/futhark#1952]
It's possible to read past the end of arrays without using unsafe, sometimes leading to segfaults. I tested it on the C backend on both 761c9def45029de4ce1d69114bdd89759e1d07af (current master) and `0.24.3` (latest release). My compiler is `gcc` version `13.1.1` and I am on x86-64 Linux.

I have two examples, the first one is simple but the returned value always seems to be `x` and I can't achieve a segfault with it:
```futhark
entry main (x: i64) =
    let is = flatten [[x], [x]]
    in
    is[999999999]
```
Output:
```bash
> futhark c bad.fut
> echo "0" | ./bad --entry-point main
0i64
```

Here is the second one:
```futhark
def helper inner outer =
    let is = flatten (map(\_ -> inner |> map id) outer)
    in
    is[999999999]

entry main (_: i64) = helper [(1i32, 0i32), (0, 0)] [(0, 0)]
```
Output:
```bash
> futhark c bad.fut
> echo "0" | ./bad --entry-point main
Segmentation fault (core dumped)
```

**Comment by athas** [comment]
The first one is benign, because the compiler realises that the output (if any) must be zero.  We still normally try to preserve failing checks, though.

The second one is a real problem and is likely due to a sloppy rewrite rule that throws away safety dependencies.
