### ISSUE TITLE
Why is there an error in using this method about reduce_by_index?

### ISSUE THREAD

**Issue by wujilingfeng** [diku-dk/futhark#1957]
I was reading the tutorial, and want to test the function of `reduce_by_index`

```
>a 
[0, 1, 2]
> b
[0, 0, 0]
> reduce_by_index b (+) 0 a a 
Cannot apply "reduce_by_index" to "b" (invalid type).
Expected: [k₁]a₀
Actual:   [range_dim₃]i64

Would consume variable "b", which is not consumable.
```

What's wrong about it?
There is no detailed introduction to this function,  I learned its signature through the interaction system, I would like to know the meaning of its third parameter.
Can you give me a standalone example?

**Comment by athas** [comment]
The third parameter is a neutral element for the `(+)` function.  This function is a variant of [hist](https://futhark-lang.org/examples/histograms.html) where the result is put in a pre-existing array.  You can see [here](https://futhark.readthedocs.io/en/latest/language-reference.html#in-place-updates) for a description of this idea, but unless you know you need it, I'd really just use `hist` instead.

**Comment by wujilingfeng** [comment]
> The third parameter is a neutral element for the `(+)` function. This function is a variant of [hist](https://futhark-lang.org/examples/histograms.html) where the result is put in a pre-existing array. You can see [here](https://futhark.readthedocs.io/en/latest/language-reference.html#in-place-updates) for a description of this idea, but unless you know you need it, I'd really just use `hist` instead.

So how to give a consumable parameter?

**Comment by athas** [comment]
Read the link above for a discussion about consumption, but I'd really recommend just avoiding this part of the language until you need it.  One way is to construct the array immediately in the expression:

    reduce_by_index [1,2,3] (+) 0 a a 

By neutral element I mean it in the [monoidal](https://en.wikipedia.org/wiki/Monoid) sense.  For `hist` the neutral element is also used to construct an initial array.

**Comment by athas** [comment]
Since there is no bug here, I will close the issue.

**Comment by wujilingfeng** [comment]
> Since there is no bug here, I will close the issue.

Thank you!
