### ISSUE TITLE
Entry point has an opaque type

### ISSUE THREAD

**Issue by wujilingfeng** [diku-dk/futhark#1974]
I want to write multiplication of sparse matrix
```

def myreduce (a: [](i32,f32)) (b:[](f32)) : f32= reduce (+) 0 ( map (\(i,j)->b[i]*j ) a)

entry s_mult_mat [m][n][k][l] (s:[m][n](i32,f32)) (a:[l][k]f32) : [m][k]f32= map (\x->map  (\y->myreduce x y  ) <| transpose a  ) s 
```
where  s is a sparse matrix and a is a dense matrix.
futhark throwed a warning
```
warning at algebra.fut:53:31-49:
  Entry point parameter

    ((s: [m][n](i32, f32)): [m][n](i32, f32))

  will have an opaque type, so the entry point will likely not be callable.
```
Do I have to use two matrices to represent s ?just like `s1:[m][n]i32  ` ,`s2:[m][n]f32?`

**Comment by athas** [comment]
Short answer: yes. You then `zip` them inside the entry point.

**Comment by wujilingfeng** [comment]
> Short answer: yes. You then `zip` them inside the entry point.

Thank you!

**Comment by wujilingfeng** [comment]
> Short answer: yes. You then `zip` them inside the entry point.

```
myfun  [m][n] (s1:[m][n]:i32 )  (s2:[m][n]:f32 ): [m][n](i32,f32)= map (\(a1,a2) -> zip a1 a2) (zip s1 s2)
```

**Comment by wujilingfeng** [comment]
> > Short answer: yes. You then `zip` them inside the entry point.
> 
> Like this?
> 
> ```
> myfun  [m][n] (s1:[m][n]:i32 )  (s2:[m][n]:f32 ): [m][n](i32,f32)= map (\(a1,a2) -> zip a1 a2) (zip s1 s2)
> ```
> 
> Is this writing correct? Is there no problem with efficiency?

Ok ,the correct way is 
```
map2 (\a1 a2->zip a1 a2) s1 s2
```
