### ISSUE TITLE
How up-to-date is the Language Reference

### ISSUE THREAD

**Issue by wstevick** [diku-dk/futhark#1976]
I'm working on a Tree Sitter grammar for Futhark, and I'm worried that the Language Reference isn't entirely accurate. For instance, it says that parametric modules may only take a single module as a parameter, but I know I've seen them use more. Also, there's a `"[" exp [".." exp] "..." exp "]"` line in the `atom` definition, which I've never seen before.

Would someone look over the Language Reference, and make sure that my grammar will be accurate if I follow it?

Thank you

**Comment by athas** [comment]
The grammar in the language reference is supposed to be up-to-date, but it's maintained manually and separately from the grammar definition used in the compiler itself, so inconsistencies can sneak in and there is no system in place to detect them.  I'll fix the ones you found and will fix any other errors you may find.
