### ISSUE TITLE
Interpreter error: array size not bound to a value.

### ISSUE THREAD

**Issue by WilliamDue** [diku-dk/futhark#2002]
## How to replicate the error.
The following piece of code throws an error when using the interpreter.
```fut
-- | file: error.fut
module type thing = {
  val n : i64
  val f : i64 -> [n / 2]i64
}

module mk_m(G: thing) = {
  def lex [m] (i : [m]i64) : [m][G.n / 2]i64 =
    map G.f i
}

module m = mk_m {
  def n : i64 = 2
  def f i = replicate (n / 2) i
}

def x = m.lex [1, 2, 3]

-- ==
-- entry: test
-- random input { } output { 6i64 }
entry test =
  flatten x |> i64.sum
```
The error thrown when testing using the interpreter is.
```
$ futhark test --no-terminal -i error.fut
error.fut:
Interpreting:
Entry point: test; dataset: :
Function failed with error:
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
n is not bound to a value.
-> #0  error.fut:17:9-24

CallStack (from HasCallStack):
  error, called at src/Language/Futhark/Interpreter.hs:654:7 in futhark-0.26.0-A0Goj3y9s36IgMdzTlFTzJ:Language.Futhark.Interpreter

0/1 passed.
```
While using the C backend `futhark test --no-terminal error.fut` throws no such error and results in `1/1 passed.`

When I change the function `lex` such that it has the type signature `lex : i64 -> [G.n / 2]i64` or `lex [m] : [m]i64 -> [m][G.n]i64`  the error disappears.

### Version
```
Futhark 0.26.0 (prerelease - include info below when reporting bugs)
git: 76025b85cc85370b2c3173a54f07b694b5a689c9
```

**Comment by athas** [comment]
The poor interpreter.  All these bugs are ultimately due to the module system resulting in sizes *in types* not being in scope at the top level, which was not a problem until our recent addition of full size-dependent types (which requires evaluation of expressions in types).
