### ISSUE TITLE
Scatter on same destination and source produces internal compiler error

### ISSUE THREAD

**Issue by nhey** [diku-dk/futhark#2007]
This wicked little program crashes the compiler. The error tells you exactly what you should know though.
```
def main [n] (xs: *[n]i64) = scatter xs (iota n) xs
```

**Comment by nhey** [comment]
Similar nonsense:
```
def main (xs: *[]i64) = scatter xs xs xs
```

**Comment by athas** [comment]
None of these should be type correct.  Probably a recent regression.
