### ISSUE TITLE
Parser does not allow literal patterns

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#2017]
According to the [language reference](https://futhark.readthedocs.io/en/stable/language-reference.html), Futhark allows [literals as patterns](https://futhark.readthedocs.io/en/stable/language-reference.html#grammar-token-pat_literal), meaning that the following code should be accepted:

```futhark
def foo 1 = 1
```
However, the current parser does not allow this: 

```
Error at program.fut:1:9-9:
Unexpected token: '1'
Expected one of the following: '='

If you find this error message confusing, uninformative, or wrong, please open an issue:
https://github.com/diku-dk/futhark/issues
```

[Playground link](http://playground.futhark-lang.org/061ca29734a67da9e5c079464ff35c45dad3e691da4dc9a25ade0fb4c68decf8)

**Comment by Munksgaard** [comment]
Wouldn't allowing literals in function definition patterns introduce ambiguity here:

```futhark
def a - 1 = 2
```

That could be interpreted both as an infix binding of the `-` operator or as a function `a` that matches only on the literal pattern `-1`.

**Comment by athas** [comment]
We just pick one of them, and since this would be rejected in the type checker anyway, the distinction is not important.
