### ISSUE TITLE
Why is it that the daily builds have linux, windows, and macOS versions, but the released version only has the linux version for download?

### ISSUE THREAD

**Issue by fenginsc** [diku-dk/futhark#2034]
Suggest a fix to provide other versions for download.
Thanks!

**Comment by fenginsc** [comment]
Ok, but I still prefer to download standalone binary packages, so I hope it's available for download!

**Comment by uxmal** [comment]
@fenginsc

**Comment by fenginsc** [comment]
> @fenginsc

What?
