### ISSUE TITLE
"Length" built-in isn't well-informed about compile-time constants

### ISSUE THREAD

**Issue by cpebble** [diku-dk/futhark#2036]
When working with compiled arrays, the following:

```futhark
def doesnt =
  let A = [2i64, 4, 6, 8]
  let A' = iota (length A)
  in zip A A'
```
Does not work with, emitting the following error:

> Error at iota.fut:5:12-14:
> Cannot apply "zip" to "A'" (invalid type).
> Expected: [4]b₇
> Actual:   [length A]i64
>
> Sizes "4" and "length A" do not match.

Since A is compiled, it has the obvious length of `4`. I cannot see why `length A` in this case shouldn't be aware that
1. A exists with a size 4
2. `length A` is 4
3. The 'type' [length A] must be of size [4]

I do understand this might be an antipattern code-wise however it trips up people new to the language.

I propose allowing `length A` to be optimized in the case of `A` being known at compile-time. In my reasoning, `length A` could be optimized just as `2 + x` can be optimized if `x` is known. My reasoning might very well be wrong though, so please do correct me

**Comment by athas** [comment]
Yes that's right; Futhark does not perform evaluation during type checking.  The type checker has no idea what `length` is - it is not a builtin function - and so it cannot be handled specially by the type checker.  The solution in this case is to use the `indices` function instead.  It is very rare that you want to use `length`, and if I were a braver man, I would propose that we just remove it outright.  Alternatively, it might be possible to add a few special cases to the error reporting that tries to detect cases like this and provide an explanation of what is wrong.

**Comment by FluxusMagna** [comment]
`length` is still useful for things like normalization in averages. Although it's usually just as convenient to use the size parameter from a type declaration, I think there are cases where it might still make sense in order to avoid too many explicit type declarations.

**Comment by athas** [comment]
Yes, that is why I am not brave enough to remove it.

**Comment by cpebble** [comment]
> length [...] is not a builtin function
My initial assumption was wrong then.

As @FluxusMagna mentions, it is convenient(and easier on the type system) when the size parameter is used. It also nudges developers towards using and understanding size parameters properly.
In truth i was not brave enough to suggest removal of `length` since i am new to the code-base. It does however seem to be redundant. At the very least i cannot reason a case where properly typed programs would need it.

What if `length` was replaced with the corresponding size param on the IR level, then it could be tested and moves could be made to deprecate it/inform the developer of the bad code pattern?

**Comment by sortraev** [comment]
May I suggest we change the homepage code example to `def average [n] (xs: [n]f64) = reduce (+) 0 xs / f64.i64 n` to reflect the fact that `length` is now ~~deprecated~~discouraged :smiling_face_with_tear:

**Comment by athas** [comment]
We can do that, but that use of `length` is actually just the (sensible) use that @FluxusMagna mentioned.  It is fine to use `length` for a number, but it is dubious to use it for a size.
