### ISSUE TITLE
Allow for records and tuples to be not opaque

### ISSUE THREAD

**Issue by dcz-self** [diku-dk/futhark#2071]
Records and tuples in entry points end up being impossible to instantiate:

>  Entry point parameter
>    ((foo: (u8, u16)): (u8, u16))
>  will have an opaque type, so the entry point will likely not be callable.

This is unexpected, creating a divergence between what can be called internally and externally, before even taking the wrapping language's capabilities into account.

The C ABI used in bindings allows at least a simple representation of records, while bindings to a language like Rust could conceivably interface with all of records, tuples, and sum types.

If the goal of opaque types is to let the user deliberately prevent the caller from modifying values (and e.g. messing up invariants), then I think a better way to do this would be to add a keyword to distinguish types meant to be opaque versus those which aren't, rather than assume all should.

**Comment by athas** [comment]
The goal is to not expose the internal representation of compound types to the outside world.  It is a critical part of the C API design that only a few known primitive types and pointers are exposed.  This significantly eases interaction with the FFIs of various languages.  The manifest (and C API) actually provides enough information for sufficiently smart bridges to transparently turn record/tuple-typed entry point parameters/results into something more ergonomic if desired, as the complete structure (and projection/construction functions) is provided.  But it is not something the Futhark compiler will do automatically.

**Comment by dcz-self** [comment]
I see now that the C side is documented here: https://futhark.readthedocs.io/en/stable/c-api.html#opaque-values . I guess I've been scared into thinking they are not instantiable by the compiler message.

On a quick look, the sum type is still not instantiable. Should I open a dedicated issue or keep it in this one? My general problem described in this one is no longer relevant.

**Comment by athas** [comment]
I agree the compiler warning is perhaps overly cautious.  Today it really mostly means "the generated C type will have a really nasty name".

Feel free to open a tracking issue for making a similar facility available for sum types.  It's not as easy as records, which is why we don't have it yet, but I don't think it's impossible to come up with an API.

**Comment by dcz-self** [comment]
I created an issue specifically for sum types: https://github.com/diku-dk/futhark/issues/2074
