### ISSUE TITLE
Compilation error : internal error anout dimensions

### ISSUE THREAD

**Issue by Alexandre-Da-Cunha-Guiborat** [diku-dk/futhark#2089]
Compilation error :

Type error after pass 'simplify':
In function entry_bench_rangeQuery2d_grid
When checking function body

In expression of statement
  {defunc_0_map_res_12821 : ({}, [d<{(/) n 2}>_11508]i64)}
in body of last case
In expression of statement
  {partition_res_r_13695 : ({}, [d<{(/) n 2}>_11508][64i64][j_m_i_11541]i64)}
2 indices given, but type of indexee has 3 dimension(s).

This error happens when compiling with a gpu backend such as opencl or cuda.

[rangeQuery2d_grid.txt](https://github.com/diku-dk/futhark/files/13969436/rangeQuery2d_grid.txt)

**Comment by athas** [comment]
Reduced test case:

```Futhark
entry main =
  map2 (\is vs -> scatter (replicate 20 (replicate 30 true)) is vs)
```
