### ISSUE TITLE
Documentation improvement for Prelude math functions

### ISSUE THREAD

**Issue by laurentpayot** [diku-dk/futhark#2122]
Hi, I’m new to Futhark and so far I’m loving it.

It took me a while to figure out how to use simple Prelude math functions such as [`abs`](https://futhark-lang.org/docs/prelude/doc/prelude/math.html#1240). I was getting an `unknown name` error when using `abs x`. Nowhere in the [book](https://futhark-book.readthedocs.io/en/latest/language.html) I could find the right way to use `abs`. I had to google Futhark examples to find out that `abs` has to be prefixed by the  type of its operand, such as `i32.abs myIntValue` and so.

It would be nice to add a note about that in the docs to prevent newcomers confusion. I would have done a PR if I wasn’t such a Futhark newbie :wink:

**Comment by athas** [comment]
Would it have been useful to add an [example](https://futhark-lang.org/examples.html) that discusses this?

**Comment by laurentpayot** [comment]
> Would it have been useful to add an [example](https://futhark-lang.org/examples.html) that discusses this?

Sure, but examples should illustrate the content of the docs, not be the docs.
It may be more appropriate to add a note about what Prelude is in the [Modules](https://futhark-book.readthedocs.io/en/latest/modules.html) section of the book, with a few examples.

**Comment by athas** [comment]
I added an example to the website and a small paragraph to the Futhark book (in the basic language chapter). I may add something to the module chapter eventually.
