### ISSUE TITLE
`futhark bench --skip-compilation` with non-server executable hangs indefinitely

### ISSUE THREAD

**Issue by sortraev** [diku-dk/futhark#2142]
I found that trying to use `futhark bench --skip-compilation` with a non-server executable causes `futhark-bench` to hang indefinitely. I don't know if it happens in other places where a server executable is expected (if any).

It's not a huge issue, but it took me a while scouring the source code before I found out why.

Example where `futhark-bench` hangs indefinitely:

```
$ ~/foo cat foo.fut
-- ==
-- input { 0i32 }
entry main (x: i32) = x
$ ~/foo futhark c foo.fut
$ ~/foo futhark bench --skip-compilation foo.fut
Reporting arithmetic mean runtime of at least 10 runs for each dataset (min 0.5s).
More runs automatically performed for up to 300s to ensure accurate measurement.

```

I'd say the minimum viable solution is to add a note such as "(must be compiled to server executable)" to the `futhark-bench` help string for `--skip-compilation`, but it'd be nice to be notified somehow. Is it possible to query a Futhark executable of whether it is a server executable?

**Comment by athas** [comment]
I don't mind adding a sentence to the documentation, but this is a somewhat exotic failure case that will only be encountered by compiler hackers. I don't think it's worth putting too much technical effort into it. Maybe we should just get entirely rid of non-server executables.

**Comment by sortraev** [comment]
> ... that will only be encountered by compiler hackers.

This is a good point that I had not thought about.

In any case, I noticed that `script`, `autotune`, and `literate` also have `--skip-compilation` flags.

> Maybe we should just get entirely rid of non-server executables.

Good idea! Could perhaps give a `--server` to the executable to allow both, if it's not too much overhead
