### ISSUE TITLE
Should we always round correctly on OpenCL?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#2155]
The OpenCL spec allows implementations to round single-precision floating point operations incorrectly. You have to pass `-cl-fp32-correctly-rounded-divide-sqrt` to the kernel compiler to make it round correctly.

Should we pass this option by default? From what I can determine, CUDA does the equivalent of passing this option by default, so it would harmonise behaviour between backends.

**Comment by laurentpayot** [comment]
I’m surprised to learn you can get different results with different platforms. That’s an issue  for me as I use a couple of different machines. So yes, personally, I’m for passing it by default with an option to opt it out.

**Comment by athas** [comment]
The performance difference can be quite dramatic in some cases on some GPUs, if you have workloads that are dominated by square root calculations (e.g. for Mandelbrot fractals). But it's equivalent to just passing `-ffast-math`-like options, which I am a bit wary of.

**Comment by laurentpayot** [comment]
> workloads that are dominated by square root calculations (e.g. for Mandelbrot fractals)

Really? When I was in high school (last century) I was playing with the Mandelbrot set on my 8 bit computer. I remember I was super happy to realize I could get rid of the square root operation simply by using an hard coded squared value (the "bailout") on the other side of the condition. Correct me if I’m wrong...

**Comment by athas** [comment]
Sure, I'm not saying that it's the best way to implement Mandelbrot fractals, I'm just using it as an example of a specific program in our benchmark suite that turned out to benefit from OpenCL's default of inaccurate-but-fast square roots on my MI100 GPU (but not on A100). I can imagine other programs that are similarly squareroot-heavy (nbody), but they also do plenty of other things, so the effect is not as pronounced.

If anyone is curious, I'm actually working on a systematic investigation of CUDA/OpenCL and HIP/OpenCL performance differences. I have these two graphs, where a higher number means that OpenCL is faster than CUDA or HIP respective:

![image](https://github.com/diku-dk/futhark/assets/55833/20881998-f6aa-4927-96b2-952b096c7a2e)


There are many root causes of the differences, some of which were surprising. The behaviour discussed in this issue is one of the latter, but it mostly affects benchmarks I would say are not "realistic".

**Comment by athas** [comment]
The generated code is essentially the same. The main difference is the choice of scan implementation, as well as a few minor details for certain histogram operators. I am certainly going to put in some work in order to try to minimise the differences, and one (relatively easy) one is covered by exactly this issue. (Unfortunately, here the solution is to make OpenCL slower by default, but such is life.)
