### ISSUE TITLE
Performance regression due to https://github.com/diku-dk/futhark/pull/2133

### ISSUE THREAD

**Issue by patrick-nicodemus** [diku-dk/futhark#2157]
On [this commit](https://github.com/b67a92183e2e6b4ea3ccc3f253e8f7f7a3723303iku-dk/futhark/issues), my Futhark source code takes 47 seconds  to compile. (I am using the multicore compiler, I have not checked yet if there are issues with other backends) On the next commit, https://github.com/diku-dk/futhark/commit/64235a1ace9b298970d65c09f79db41fa8ab3824, the same code takes 497 seconds to compile.

I have not yet thoroughly benchmarked the code with the old and new versions. It may be that the performance improvements with the compiled code are well worth the change. Nevertheless, going from a compile/debug cycle of 47 seconds per iteration to 497 seconds per iteration is really just brutal and unfortunate. Would it be possible to improve the performance of this portion of the code so that the compilation times are not so extreme?

Attached, please find the source code for my current project, the main executable is `unbalanced_gw.fut`.

[futhark.zip](https://github.com/user-attachments/files/16008586/futhark.zip)

**Comment by athas** [comment]
Only happens with the `multicore` backend (and the others that use the multicore optimisation pass). At least that should make it easy to isolate the bug.
