### ISSUE TITLE
How to compare two arrays for equality?

### ISSUE THREAD

**Issue by INIT-REF** [diku-dk/futhark#2165]
Hi all,
 
I'm just starting out with Futhark by solving Project Euler problems and I'm looking for the best/most simple/fastest way to compare two arrays of the same type (int or bool) for equality.

The compiler was so kind to inform me that "==" is not the way to do it, so given two arrays a and b  I'm using

`map2(\x y -> x == y) a b |> and`

for now. Is this ok or would you recommend something different?

Cheers,
Matthias

**Comment by athas** [comment]
That is how you do it. See also https://futhark-lang.org/examples/array-equality.html

It feels quite roundabout, but array comparison turns out to be fairly rare in most programs.
