### ISSUE TITLE
Feature Request: Splat / Rest Exprs for Records

### ISSUE THREAD

**Issue by iMplode-nZ** [diku-dk/futhark#2171]
If I have a large record, I'd like to be able to create a new record with some elements changed without having to write out all elements of the record.
For example,

```
let a = {
  x = 1.0,
  y = 1.0,
  z  = 1.0,
} in { x = 2.0, ..a }
```
should be equivalent to
```
let a = {
  x = 1.0,
  y = 1.0,
  z  = 1.0,
} in { x = 2.0, y = a.y, z = a.z }
```

It seems like this was a feature a while back according to https://futhark-lang.org/blog/2017-03-06-futhark-record-system.html, but it seems to have been dropped and the current documentation does not state an alternative except use of `with` statements, but I would prefer to avoid the shadowing that it provides.

**Comment by iMplode-nZ** [comment]
@athas huh, I suppose that does work. My issue with that is that I sometimes want to update multiple variables at once, but that's quite minor.

**Comment by athas** [comment]
You can chain `with`: `a with x = 1 with y = 2`.

**Comment by iMplode-nZ** [comment]
Alright thanks.
