### ISSUE TITLE
Express system dependencies in Cabal?

### ISSUE THREAD

**Issue by patrick-nicodemus** [diku-dk/futhark#2182]
I am not familiar with Haskell or Cabal, so I do not really know if it is possible to include system packages as dependencies somehow. 
However, I got the following error:
```
/usr/bin/ld.gold: error: cannot find -ltinfo
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
Error: cabal: Failed to build futhark-0.26.0 (which is required by exe:futhark
from futhark-0.26.0).
```
I was able to solve this easily by running `sudo apt-get install libtinfo-dev` from my system package manager but maybe you can put this dependency into Cabal somewhere or specify it in the readme?

**Comment by athas** [comment]
I don't think cabal has any way of specifying such dependencies beyond what it already does (this dependency comes from [haskeline](https://hackage.haskell.org/package/haskeline). Even if it did, cabal has no way to *install* those dependencies. At best it could report a better error message.

**Comment by athas** [comment]
The best I could come up with for handling this issue is [documenting the dependencies](https://futhark.readthedocs.io/en/latest/installation.html#dependencies).

**Comment by patrick-nicodemus** [comment]
I don't know how I missed that, sorry.
