### ISSUE TITLE
Add C# Backend

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#232]
Since DIKU is now using F# for teaching, we should have an F# backend for Futhark.  It might lead to some interesting projects.  I don't expect it to be very hard, but we must have answers for the following questions.
1. **Representation of mutable variables**.  For code generation, Futhark uses an imperative IL ([ImpCode](https://github.com/HIPERFIT/futhark/blob/master/src/Futhark/CodeGen/ImpCode.hs)) with free-form mutation of (typed) scalar variables.  While performance of ImpCode is not important when most of the runtime is spent in OpenCL, it would still be nice to have an efficient representation.  ImpCode uses scalar variables in a way that really suggests putting them in registers, while SML reference cells are heap-allocated IIRC.
2. **Representation of memory blocks**.  ImpCode uses raw memory blocks for managing arrays, although it does not do any pointer arithmetic.  Crucially, there is no primitive type associated with memory blocks - the same block can be used to store arrays of different types at different times.  We need a representation that can support the operation "read or write a scalar of type T at byte offset N".
3. **Interface to OpenCL**.  We need a thin wrapper that maps closely to the C API.

We managed to do this for Python of all things.  Surely F# will be easier.

**Comment by Athas** [comment]
For question 3, there is [OpenCL.Net](https://openclnet.codeplex.com/).  It seems reasonable.  Do we also need a C# backend, maybe?

**Comment by Athas** [comment]
A C# backend would be superior.  It is a better fit for ImpCode, and just as accessible.

**Comment by nestordemeure** [comment]
As an F# user, an easy way to produce F# modules from Futhark to produce optimized GPU code would be nice (and might give some visibility to your project, F# users are already familiar with a Futhark-like syntax which helps).

**Comment by Athas** [comment]
We are working on a compiler frontend that accepts programs in F# syntax (the idea being that you can write F# programs, with some restrictions, and debug them using normal F# tools, then compile them to Futhark, and then to C#).  Is an F# backend also necessary?  I was of the impression that it's quite easy to call C# from F#.

**Comment by nestordemeure** [comment]
Having a restriction of F# compiled by Futhark into an efficient library looks like the perfect scenario.

Using C# as a backend makes sense : 
- it is indeed easy to call from F# (the only drawback is that the functions you get are not currified and it is a minor drawback that can always be alleviated by a wrapper)
- it is faster than F# (the gap is not large but speed does matter here)

**Comment by athas** [comment]
Done by Mikkel in6c31673d14fc184c186c628d5c93d1e6c2b67e3c.
