### ISSUE TITLE
Why can't I run Futhark on my phone?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#237]
I have a OnePlus 3.  It clearly has a GPU, and probably supports OpenCL.  What needs to happen before I can run Futhark on my phone?

**Comment by nqpz** [comment]
On Fri, 23 Sep 2016 03:28:05 -0700, Troels Henriksen wrote:
> I have an OnePlus 3.  It clearly has a GPU, and probably supports
> OpenCL.  What needs to happen before I can run Futhark on my phone?

Can't you just remove Android and install Debian on it?

**Comment by kfl** [comment]
Well, we should start by integrating Futhark with the [Android NDK](https://developer.android.com/ndk/guides/index.html). Which means that we need some kind of Java/JNI interface.

Maybe something can get pilfered from the python integration.

**Comment by kfl** [comment]
However, Android does not officially support OpenCL. Although it possible to use it on some/many models.

Alas, it seems that on the model that @Athas mentions (the phone of champions) OpenCL is not supported (according to a [random source on the internet](https://github.com/Scandy-co/scandy-core-sdk/wiki/Supported-devices)).

**Comment by athas** [comment]
Phones are terrible; this is unlikely to happen before we have a WebGPU backend.

**Comment by Oblomov** [comment]
FWIW, assuming the phone has the adequate system libraries, it may be possible to run OpenCL programs without JNI inside a Linux environment such as Termux, see e.g. how this is done for [clinfo on Android](https://github.com/Oblomov/clinfo#android-support).
