### ISSUE TITLE
Write a machine learning library

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#309]
Here's some good inspiration: https://github.com/eriklindernoren/ML-From-Scratch

**Comment by kfl** [comment]
But there is no deep learning in that repo. You gotta have deep learning, that's the end of all ML. 

(deep learning aka Neural Networks, in particular recurrent NNs)

**Comment by fenollp** [comment]
Multiclass SVMs, HOG and Random Forests would be a great start!

Also a very efficient implementation of inference for smartphone backends, reading in Tensorflow protos could be interesting. But then where in the roadmap are GPUs like Mali?

**Comment by fenollp** [comment]
Maybe there is some collaboration to be done with https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/xla ?

**Comment by athas** [comment]
[This Haskell library](https://github.com/diffusionkinetics/open/tree/master/fuml) contains some simple things written in easily readable functional code.

**Comment by athas** [comment]
[This was done.](https://github.com/HnimNart/deeplearning)
