### ISSUE TITLE
Memory block merging

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#32]
Also known as "register allocation", but I picked a new one because people tend to get confused.  The idea is to use an algorithm very similar to register allocation to merge memory blocks and reduce copies and memory pressure.

**Comment by athas** [comment]
Wait, don't we technically have this now?

**Comment by Munksgaard** [comment]
Yes, I think this was covered by #1368

**Comment by Munksgaard** [comment]
Or, well, I guess it depends on what is meant by "memory block merging".

**Comment by athas** [comment]
Close enough, but maybe we should have a tracking issue for what remains to be done in terms of copy-elimination, or whatever it is we call it.
