### ISSUE TITLE
OpenGL Compute shader backend?

### ISSUE THREAD

**Issue by wvdschel** [diku-dk/futhark#346]
How feasible would it be to generate GLSL compute shaders from Futhark?

OpenGL is much more widely available and doesn't require installing special drivers to run, so it would be much easier to get up and running and redistribute software using Futhark with an OpenGL backend.

**Comment by Athas** [comment]
I think this would mostly be interesting because it would enable use of WebGL (both Windows and macOS seem to bundle OpenCL, as do proprietary GPU drivers for Linux).

I suspect it's feasible.  I looked into it a few times, but couldn't figure out how flexible GLSL is compared to OpenCL C.  Futhark does not require much, but the present code generators do require some flexibility about types - specifically that we have access to raw byte arrays.  Something similar to OpenCL local memory would also be necessary.

It would also be possible to replace a larger chunk of the code generation backend, which might not require the above, but I hope that is not necessary.

Generating code for OpenGL would likely involve a significant amount of technical hacking, but the conceptual divide should not be particularly large.

**Comment by wvdschel** [comment]
Mobile platforms are also not very welcoming to OpenCL: Google does not
provide OpenCL drivers (though many other device manufacturers do), and
Apple has a private OpenCL framework on iOS, which is not allowed to be
uaed by apps in their store, and just runs OpenCL on the CPU.

OpenGL can target all of these.

**Comment by Athas** [comment]
Well, I'm sold.  Now we just need a volunteer. :-)

Another quirk is that I'm not sure GLSL supports all the necessary primitive types (e.g. 16 bit integers).  But that can be emulated - pretty sure that's how OpenCL does it anyway.

**Comment by wvdschel** [comment]
I don't know Haskell, and don't have the time or desire to learn it, so don't look to me for help.

As far as I know, GLSL only has 32-bit integers (signed and unsigned variants).

**Comment by RasmusWL** [comment]
@wvdschel just out of curiosity, how come you are bringing this up? did you have a specific use case in mind? or was it more of a general observation, that Futhark could benefit from targeting GLSL?

**Comment by wvdschel** [comment]
@RasmusWL I get bored and have pipe dreams of what I could be making someday. I'm working on a pet project that could use GPU computing, and I enjoy Futhark for those tasks over manually worrying about the low level stuff all the time.

This project would also have to run on Android, so I started looking into OpenCL on Android. After a bit of testing on the devices I have access to (2012 Nexus 4, 2013 Nexus 7,  2015 Nexus 5X and 2016 ZenFone 3), I found out that only the ZenFone has OpenCL support out of the box, and the Nexus devices can have an OpenCL driver installed by unlocking the bootloader and flashing a Qualcomm package. I also found out OpenCL support is missing on many newer devices.

So I ended up concluding that there is no satisfactory support for OpenCL on Android, despite almost all of the devices having the required hardware, and the only way to get good GPU computing on Android is OpenGL ES 3.1 with compute shaders.

**Comment by RasmusWL** [comment]
@wvdschel cool, thanks for clarifying. I'm sure that @Athas has added a *writing an OpenGL backend* to the list of ambitious projects that could be done by students :smile:

**Comment by oleid** [comment]
I think it would make sense to target SPIR-V (*) these days, especially due to the tooling available. E.g. you can easily (**) use it from Vulkan, OpenGL, Metal you name it.

(*): https://www.khronos.org/opengl/wiki/SPIR-V
(**): https://github.com/KhronosGroup/SPIRV-Cross

**Comment by sebastien** [comment]
I'd be interested in using Futhark to implement parts of a geometry kernel that would run on the GPU in WebGL. Is there any plan to implement that feature?

**Comment by Athas** [comment]
Not any immediate plans.  From what we discovered, compute shader support is really spotty, and with enough quirks and differences compared to OpenCL that the engineering effort would be substantial (e.g, many primitive types may simply not work, and even multidimensional arrays seem a bit fragile).

**Comment by jarble** [comment]
@sebastien I wrote [a compiler](https://jarble.github.io/transpiler/javascript/js_transpiler/test_parser.html#%7B%22inputText%22%3A%22%5Cnlet%20add%20(a%3Ai32)%20(b%3Ai32)%3A%20i32%20%3D%5Cn%20%20%20%20a%2Bb%22%2C%22inputLang%22%3A%22futhark%22%2C%22outputLang%22%3A%22glsl%22%7D) that translates a small subset of Futhark to GLSL, but it's still a work-in-progress.

**Comment by athas** [comment]
We tried this recently, and it turns out to be hard to do properly.  Since OpenGL is slowly getting sunsetted and replaced with Vulkan and WebGPU, this will realistically not happen.
