### ISSUE TITLE
Should we add an implicit prelude?

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#380]
We have a growing basis library, but programmers are still responsible for manually `import`ing anything they want from it, including things like `/futlib/math` or `/futlib/array`.  In most languages, some of the most fundamental things are always available.  In Haskell, this is via the implicitly imported `Prelude` module.  In Futhark, a few functions (like `iota` and `replicate`) *are* implicitly available, via compiler hackery.  It is annoying to add more, and I'd honestly prefer to get rid of the ones we have, but I'm not yet brave enough to require an `import` to make `replicate` available.

The question is: should the Futhark compiler automatically add, to any program being compiled, imports of a few strategically chosen modules (or just a single module `prelude` that itself imports others)?  There are two downsides:

1. The initial environment becomes larger, and it may be less clear what is available.  Right now, the answer is "almost nothing", which is at least simple.
2. Due to the current compiler design, an import involves *parsing and type-checking every imported module*.  This means that we will have significant extra overhead for small programs that do not actually use the prelude (and currently have no imports).  For example, on my laptop, the time to parse and type check our entire test suite (700+ programs; most are trivial) rises from about 4.5s to 21s.  On the other hand, if you actually want to *compile and run* the programs, the relative time taken to parse and type-check is less important.  The time taken to run the entire test suite on one of our Xeon machines rises from 3m1s to 3m18s.  The time taken to run the benchmark suite would probably not change measurably.

**Comment by Athas** [comment]
As an example, these are definitions for `iota` and `replicate`:

```
let iota (n: i32) = [0..1..<n]

let replicate 't (n: i32) (x: t) = map (\_ -> x) (iota n)
```

**Comment by melsman** [comment]
Perhaps it is possible to give a conservative estimate that a program only
depends on a subset of the prelude files. The MLKit uses a dependency
analysis to avoid unnecessary import of symbol table information. The
'open' construct causes some problems in this respect and so does the
concept of identifier status (a value identifier can denote either a
constructor or a variable...)

ons. 19. jul. 2017 kl. 09.14 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Qata** [comment]
I'd be in favour of moving iota and replicate to a `Prelude`, and very sparingly adding new functions to `Prelude` when deemed necessary.

**Comment by Athas** [comment]
> The MLKit uses a dependency analysis to avoid unnecessary import of symbol table information.

Even knowing what is exported by the prelude, so that such analysis can be done, requires parsing and type-checking of the prelude, which is costly when you have a large amount of tiny programs.

The reason for this is that there is no persistent format for previously parsed/type-checked/internalised Futhark code. Creating such a format would require *substantial* work and add a lot of complexity to the frontend, so that would be an absolute last option. It would not even have an effect on the compilation time of non-trivial programs, where the vast majority of time is spent in the optimiser.

**Comment by melsman** [comment]
ons. 19. jul. 2017 kl. 10.26 skrev Troels Henriksen <
notifications@github.com>:

> The MLKit uses a dependency analysis to avoid unnecessary import of symbol
> table information.
>
> Even knowing what is exported by the prelude, so that such analysis can be
> done, requires parsing and type-checking of the prelude, which is costly
> when you have a large amount of tiny programs.
>
> The reason for this is that there is no persistent format for previously
> parsed/type-checked/internalised Futhark code. Creating such a format would
> require *substantial* work and add a lot of complexity to the frontend,
> so that would be an absolute last option. It would not even have an effect
> on the compilation time of non-trivial programs, where the vast majority of
> time is spent in the optimiser.
>

I'm suggesting something simpler! Let's assume, first, that the prelude
only exports a bunch of module identifiers. Then, all we need is a simple
map from these module identifiers to the files that implement each of them.
I'm now suggesting that we first parse the program  (no type checking) and
then run a simple conservative (due to open) dependency analysis to suggest
which parts of the prelude are required...

**Comment by Athas** [comment]
That would be simpler, but it has two (non-showstopper) problems:

1) Having the prelude define only modules precludes such things as `iota` and `replicate` from being in there.  In that case, I don't think much is won compared to requiring an explicit `import "/futlib/prelude"`.
2) It requires hard-wiring the module names (and their internal unique names) into the compiler.  The prelude is then no longer just some file.

**Comment by henrikurms** [comment]
Would it be possible to parse and type check the prelude when the compiler is compiled so it only has to be done once?

**Comment by Athas** [comment]
Yes, that is possible via Template Haskell, but we would need to define Lift instances for both AST and type checker output. This is much simpler than defining on-disk serialization formats, though. 

The big question is whether such complexity is worth it when the performance issue only crops up in extremely specialized circumstances. I doubt any real Futhark user would notice.

**Comment by Athas** [comment]
The branch [embedded-prelude](https://github.com/HIPERFIT/futhark/tree/embedded-prelude) shows the implementation cost of doing this.  About 180 lines (including comments and blank lines), of which at least 80 are mechanical boilerplate.  It's a judgement call whether this is an acceptable cost in complexity.  It's at least rather localised.

**Comment by melsman** [comment]
ons. 19. jul. 2017 kl. 11.36 skrev Troels Henriksen <
notifications@github.com>:

> That would be simpler, but it has two (non-showstopper) problems:
>
>    1. Having the prelude define only modules precludes such things as iota
>    and replicate from being in there. In that case, I don't think much is
>    won compared to requiring an explicit import "/futlib/prelude".
>
>
As for Standard ML, we could just have a small General library, which is
always opened and which, therefore, a program will always depend on.


>    1. It requires hard-wiring the module names (and their internal unique
>    names) into the compiler. The prelude is then no longer just some file.
>
>
Couldn't the compiler just read a "deps" file from the root of the prelude
directory...

**Comment by melsman** [comment]
søn. 23. jul. 2017 kl. 16.14 skrev Troels Henriksen <
notifications@github.com>:

> The branch embedded-prelude
> <https://github.com/HIPERFIT/futhark/tree/embedded-prelude> shows the
> implementation cost of doing this. About 180 lines (including comments and
> blank lines), of which at least 80 are mechanical boilerplate. It's a
> judgement call whether this is an acceptable cost in complexity. It's at
> least rather localised.
>

The problem with this approach is that it will become impossible to roll
your own alternative prelude without rebuilding the compiler...

**Comment by Athas** [comment]
> Couldn't the compiler just read a "deps" file from the root of the prelude directory...

Well, then the name of the "deps" file is magical.  Anyway, this is close to what I did in my experiment: the file "futlib/prelude.fut" (and the things it explicitly `import`s) defines the prelude.

> The problem with this approach is that it will become impossible to roll your own alternative prelude without rebuilding the compiler...

You can always just explicitly `import` some other module and treat that as your prelude.  It won't be implicitly available, and its contents won't be wired into the compiler, but those are not things that can be solved in general.  The only problem is that you may inadvertently depend on things defined by the default implicit prelude.  If this becomes an issue, surely we can come up with some mechanism for inhibiting it.

**Comment by Athas** [comment]
I added an implicit prelude a while ago.  Not sure why I didn't close this issue at the time.  Probably got distracted by the whole dissertation thing.
