### ISSUE TITLE
primes-flat.fut gives and internal compiler error

### ISSUE THREAD

**Issue by CamillaOlsen** [diku-dk/futhark#399]
The primes-flat.fut file in the /L2-Code/Primes folder (The one containing the recursive line 'primesFlat sq') for the PMPH 2017 course yields the compiler-error:

'Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'Inline and remove dead functions':
In function main
In expression of statement {i32 size_2511; [size_2511]i32 entry_result_2512}
Call of unknown function main_2074.'

When compiled with the futhark-c compiler as well as the futhark-opencl compiler. The corresponding template (The one without the recursive line 'primesFlat sq') does not give this error, so I suspect the recursion is at fault.

**Comment by Athas** [comment]
Can you provide the program?  I do not have access to the PMPH course.

**Comment by CamillaOlsen** [comment]
-- For Assignment 1, Task 3, Please implement the Flat-Parallel Version 
-- of prime numbers computation (sieve).
-- ==
-- compiled input { 30 } output { [2,3,5,7,11,13,17,19,23,29] }

import "/futlib/array"

-- The current implementation is dummy, i.e., produces garbage.
-- Your implementation should recognize all prime numbers less than n.
let primesFlat (n : i32) : []i32 =
  if n <= 8 then [2,3,5,7]
  else let sq= i32( f64.sqrt (f64 n) )
       let sq_primes = primesFlat sq
       ----------------------------------------
       -- ASSIGNMENT 1, Task 3: insert here your code
       -- that implements the flat-parallel version
       -- of prime-number computation (sieve). The
       -- code should compute the not_primes array  
       -- and its length mm.
       -- The two lines below are dummy, replace them as well!
       -- ...
       let not_primes = sq_primes
       let mm = (shape not_primes)[0]
       -- ...
       -- ... 
       -- This is how the implementation should end,
       -- i.e., the code remanining after flattening
       -- the nested maps.
       let zero_array = replicate mm 0
       let mostly_ones= map (\ x -> if x > 1 then 1 else 0) (iota (n+1))
       let prime_flags= scatter mostly_ones not_primes zero_array
       in  filter (\i -> unsafe prime_flags[i] != 0) (iota (n+1))

let main (n : i32) : []i32 = primesFlat n

**Comment by CamillaOlsen** [comment]
-- For Assignment 1, Task 3, Please implement the Flat-Parallel Version 
-- of prime numbers computation (sieve).
-- ==
-- compiled input { 30 } output { [2,3,5,7,11,13,17,19,23,29] }

import "/futlib/array"

-- The current implementation is dummy, i.e., produces garbage.
-- Your implementation should recognize all prime numbers less than n.
let primesFlat (n : i32) : []i32 =
  if n <= 8 then [2,3,5,7]
  else let sq= i32( f64.sqrt (f64 n) )
       let sq_primes = primesFlat sq
       ----------------------------------------
       -- ASSIGNMENT 1, Task 3: insert here your code
       -- that implements the flat-parallel version
       -- of prime-number computation (sieve). The
       -- code should compute the not_primes array  
       -- and its length mm.
       -- The two lines below are dummy, replace them as well!
       -- ...
       let not_primes = sq_primes
       let mm = (shape not_primes)[0]
       -- ...
       -- ... 
       -- This is how the implementation should end,
       -- i.e., the code remanining after flattening
       -- the nested maps.
       let zero_array = replicate mm 0
       let mostly_ones= map (\ x -> if x > 1 then 1 else 0) (iota (n+1))
       let prime_flags= scatter mostly_ones not_primes zero_array
       in  filter (\i -> unsafe prime_flags[i] != 0) (iota (n+1))

let main (n : i32) : []i32 = primesFlat n

**Comment by Athas** [comment]
Fixed in 0eeb306542e41801535a1b37102345b01cf47663.  The new version should be on the GPU cluster in an hour at the latest.
