### ISSUE TITLE
Primes-opt.fut yields internal compiler error

### ISSUE THREAD

**Issue by CamillaOlsen** [diku-dk/futhark#400]
The file primes-opt.fut from the PMPH 2017 course yields the following internal compiler error:

'Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
After internalisation:
In function primesOpt_2092
In expression of statement {i32 size_2410; [size_2410]i32 res_2411, i32 res_2412}
In expression of statement {i32 size_2445; [size_2445]i32 res_2446, i32 res_2447}
Inside the loop body
Type error:
not_primes_2449 was invalidly consumed.
Nothing can be consumed here.'

The offending file:
`-- Primes: Nested-Par Version
-- Since Futhark does not support irregular array,
-- we pad to the maximal allowed dimension.
-- ==
-- compiled input { 30 } output { [2,3,5,7,11,13,17,19,23,29] }

let primesOpt (n : i32) : ([]i32, i32) =
  if n <= 4 then ([2,3],2)
  else let sq= i32( f64.sqrt( f64(n) ) )
       let (sq_primes, sq_sz) = primesOpt sq
           -- composite = map (\ p -> let m = (n `div` p)
           --                      in  map (\ j -> j * p ) (drop 2 (iota (m+1)))
           --                 ) sqrt_primes
           -- not_primes = reduce (++) [] composite
       -- Morally, it should be the nested-parallel code above,
       -- but since Futhark does not support irregular arrays
       -- we write it as a loop nest in which we precompute 
       -- the total result size 
       let sizes = map (\ p -> n / p - 1 ) sq_primes
       let flat_size = reduce (+) 0 sizes
       let not_primes = replicate flat_size 0
       let cur_ind = 0
       let (not_primes, cur_ind) =
         loop (not_primes, cur_ind) for i < sq_sz do
            let p = sq_primes[i]
            let s = sizes[i]
            let not_primes = 
                loop(not_primes) for j < s do
                  let not_primes[cur_ind+j] = (j+2)*p
                  in  not_primes
            in  (not_primes, cur_ind + s)
       let zero_array = replicate flat_size 0
       let prime_flags = scatter (replicate (n+1) 1) not_primes zero_array 
       let prime_flags[0] = 0
       let prime_flags[1] = 0
       in  (filter (\i->unsafe prime_flags[i]!=0) (iota (n+1)), cur_ind)
       
let main (n : i32) : []i32 = let (res,_) = primesOpt n in res`

**Comment by Athas** [comment]
This will sound stupid, because it is, but the workaround is to replace `(not_primes)` (in the loop) with `not_primes`.

**Comment by Athas** [comment]
Fixed in db565d268ebbe9177865b1043afc111e2c881884.
