### ISSUE TITLE
Should we remove the old-style size annotations?

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#405]
For historical reasons, Futhark presently supports two ways of writing size annotations.  The old syntax uses a `#` to distinguish freshly bound sizes from sizes in scope:

```
let dotprod (xs: [#n]i32) (ys: [#n]i32) = ...
```

The new syntax uses explicit *size parameters*, akin to type parameters:

```
let dotprod [n] (xs: [n]i32) (ys: [n]i32) = ...
```

The old syntax is more concise, but has some problems:

  * A simple typo can change the meaning of a program:
    ```
    let dotprod (xs: [#n]i32) (ys: [n]i32) = ...
    ```
    Note the missing `#` on the size of `ys`.  This is now a reference to some variable `n` in scope.

  * The use feels a bit inconsistent.  Since sizes in a return type are not bound there, they do not have the `#` prefixed, even though it might look to be part of the same "declaration":
    ```
    let reverse 't (xs: [#n]t): [n]t = ...
    ```

    This works better with the new syntax, which also fits the syntax for type parameters:

    ```
    let reverse [n] 't (xs: [n]t): [n]t = ...
    ```

  * It does not work for value specs in module types.

Given these problems, is the concision of the old syntax enough to justify keeping it around?

**Comment by coancea** [comment]
I am for getting rid of the old syntax -- because it is prone to 
introducing logical errors
Cosmin

**Comment by melsman** [comment]
I also suggest we simplify and support only one syntax for size
abstraction...

**Comment by Athas** [comment]
Well then, looks like we're all in agreement.  Time to break everyone's code again.
