### ISSUE TITLE
Value of e (Euler's number) in Math-lib seems to be pi

### ISSUE THREAD

**Issue by kasperah** [diku-dk/futhark#415]
The title kind of says it all :) running the following code:

```
import "futlib/math"

let main () : (f32, f32) =
	let pi = f32.pi
	let e =  f32.e
	in (pi, e)
```

results in the following output:
```
3.141593f32
3.141593f32
```

**Comment by melsman** [comment]
... to me the title is quite confusing ;)

fre. 13. okt. 2017 kl. 10.47 skrev kasperah <notifications@github.com>:

**Comment by kasperah** [comment]
Ooops.. thanks :)

**Comment by Athas** [comment]
Fixed in bae97c52187ec5713f00ce08f1ca0b18bf9b2542.

**Comment by vsenko** [comment]
Looks like it's still there: https://github.com/diku-dk/futhark/blob/master/futlib/math.fut#L977

      let pi = f64 f64m.pi
      let e = f64 f64m.pi

**Comment by Athas** [comment]
Dammit.
