### ISSUE TITLE
Experiment with making the first stage of a scan a segmented reduction rather than a segmented scan

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#432]
One of the PMPH projects came up with this, and it seems like it would improve performance noticeably.

**Comment by Athas** [comment]
I realised this is not always a win.  Consider in general a `scanomap` taking as input *n* arrays, and where the scan operator itself operates on *m*-tuples.  Then our current implementation performs *n+3m* memory operations, where one based on a reduction performs *2n+m*.  Thus, using the reduction approach will actually perform more memory traffic when *2m<n*.  I'm not sure about the constant factors, but I suspect the reduction approach will fare better.

In any case, it's not a clear win.  Probably the compiler could have a simple heuristic to pick a strategy based on *m* and *n*, which are known statically.  Unfortunately, the kernel extractor does not actually how how many of the input arrays actually result in memory traffic - in particular, `iota` and `replicate` is often not simplified away until after kernel extraction.

**Comment by athas** [comment]
We'll come up with an even better way of making scans soon.
