### ISSUE TITLE
Report comprehensible error when OpenCL device does not support double-precision floats

### ISSUE THREAD

**Issue by RasmusKlett** [diku-dk/futhark#439]
I get the following error when trying to run programs using the power (**) operator:
```
 ./sample: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ./sample)
Warning: Device limits tile size to 22 (setting was 32)
Build log:
stringInput.cl:772:12: error: call to 'pow' is ambiguous
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:49:20: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:148:19: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1142:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1143:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1144:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1145:21: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1146:22: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1147:20: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1148:20: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1149:20: note: candidate function
/usr/lib/x86_64-linux-gnu/beignet//include/ocl_math.h:1150:20: no
./sample: sample.c:1593: OpenCL call
  build_opencl_program(prog, device, compile_opts)
failed with error code -2 (Device not available)
```
Note: The first two lines are always in the output, but other programs work anyway. I'm assuming they are unrelated to this problem.

A minimal example is:
```
let main (xs : []f64)  : []f64 =
    map (\x -> x**2.0) xs
```

Similar programs which DO work:
```
let main (xs : []f32)  : []f32 =
    map (\x -> x**(f32.f64 2.0)) xs
```
and:
```
default(f32)
let main (xs : []f32)  : []f32 =
    map (\x -> x**2.0) xs
```
and also:
```
let main (x : f64) = x**2.0
```

Although the simple map over f32 does work, my original use case where I encountered this was actually a map over f32. So the problem is not confined to f64, even though the minimal version of f32 map works.

My system:
Intel i7-5500U
XUbuntu 16.04
OpenCL: beignet-opencl-icd Version: 1.1.1-2 (installed from apt)

**Comment by Athas** [comment]
This is because your Intel GPU (nor any Intel GPU) does not support double precision floats.

**Comment by Athas** [comment]
Maybe we should do a check at startup and report a slightly more comprehensible error.  The compiler knows perfectly well whether your program uses `f64`s.

**Comment by RasmusKlett** [comment]
I would certainly have appreciated saving those hours of digging around ;)

I accidentally posted the issue before I was done writing. Does it make sense that I am still able to use power on f64 when not in a map?
My original use case was using pow on f32, and later converting those to f64. When I convert everything to f32 it works. This is kind of weird, but I guess it could be the case that pow becomes ambiguous in the presence of f64's, even though the pow is not being applied to f64.

**Comment by Athas** [comment]
Code outside of parallel sections run on the CPU, and can use double precision just fine.  The compiler may also in some cases be able to constant-fold all your double precision away (but don't count on it).
