### ISSUE TITLE
Uniformative error message.

### ISSUE THREAD

**Issue by thyrgle** [diku-dk/futhark#444]
I have been trying to use Futhark for an OEIS sequence which asks for numbers that satisfy the fractional part of (1024/1000)*n < 1/n. I wrote the following code:

```
let criterion (n: i32): bool = (((1024.0/1000.0)*n)%1.0) < (1.0/n)

let seq (n: i32): []i32 = filter criterion [1..n]

let main (n: i32): []i32 = seq n

```

And received the error message:

```
oeis.fut:3:49-3:49: Parse error.

If you find this error message confusing, uninformative, or wrong, please open an issue at https://github.com/diku-dk/futhark/issues.
```

It does tell me the issue is at the end of the third line, but I am still confused about what the issue is so I thought I would put this here.

**Comment by Athas** [comment]
The syntax for ranges is [1...n], not [1..n].  (This is so [1..<n]
contains the same number of characters.)

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I have added code to the parser so that the error message will say what the problem is.  Considering how many languages use `..`, this will not be a rare error.
