### ISSUE TITLE
Should we remove brackets from range syntax?

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#445]
I have realised that there is no syntactic reason to require brackets around a range literal:

    [1...10]

We might as well write it as:

    1...10

There is no ambiguity.  [Swift](https://developer.apple.com/swift/) does it this way.  Should we, too?  It is mostly a question of whether the brackets make it clear that an array is being produced.  Due to the low operator priority of `...`, many uses will still require parentheses:

    map f (1...10)

But others will not:

    loop x for i in 1...10 do ...

By a quick search in the benchmarks repository, we have 21 uses of range literals, and 11 of these will not require parentheses.

**Comment by RasmusWL** [comment]
I think it would be nice to keep them, not based on anything but my personal opinion

**Comment by Athas** [comment]
It appears that most languages (Rust, Swift, Ruby) use a notation without brackets.  Haskell seems a bit like the odd man out.

**Comment by Qata** [comment]
+1, there’s no need for them

**Comment by melsman** [comment]
+1 from me too...

fre. 22. dec. 2017 kl. 01.59 skrev Charlotte Tortorella <
notifications@github.com>:

**Comment by Athas** [comment]
I will remove the brackets once the block is over, so no student projects run into a sudden syntax change.

**Comment by Athas** [comment]
The block is over; change incoming.
