### ISSUE TITLE
A Futhark logo!

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#449]
We need a logo, because why not.  My girlfriend drew the silhouette of a hedgehog with Sonic-like spines.  Given the history of Futhark-related visuals, this seems an appropriate logo.  I traced the logo in Inkscape to obtain a vector version - a better approach would be to draw it from scratch using geometric primitives, but my skills are not sufficient for that.  This will do for now, unless someone has a better suggestion.

![futhark](https://user-images.githubusercontent.com/55833/34453010-98eaac72-ed4a-11e7-87f2-848c6e6d46be.png)

The logo is 3KiB in SVG format and can be used with any colour, and is legible at all sizes.  The only place I envision using it for now is in the header of the [website](https://futhark-lang.org).

**Comment by kfl** [comment]
I think that it is a nice logo.

What do you mean by drawing it from scratch using geometric primitives? Would you rather have a less "organic" feel to it?

**Comment by Athas** [comment]
I mean that the spikes are not the exact same shape, and the spacing between the spikes and the body is not perfectly consistent.

It's much better than my original draft, though, so I'm fine with its current state.

**Comment by Athas** [comment]
The logo is now in the README.  I'll see about getting it on the website, too.
