### ISSUE TITLE
Undefined symbols, linker command failed, warnings about format specifiers

### ISSUE THREAD

**Issue by luxint** [diku-dk/futhark#450]
I've compiled the linalg.fut module as a library with futhark-opencl --library linalg.fut, with went well, if I then try to compile the generated files with gcc linalg.c -o liblinalg.so -fPIC -shared I get warnings and error messages see below. (tried it also with other .fut files)

linalg.c:818:25: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                        block->size, ctx->cur_mem_usage_device);
                        ^~~~~~~~~~~
linalg.c:818:38: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                        block->size, ctx->cur_mem_usage_device);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:846:17: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                ctx->cur_mem_usage_device);
                ^~~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:878:25: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                        block->size, ctx->cur_mem_usage_local);
                        ^~~~~~~~~~~
linalg.c:878:38: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                        block->size, ctx->cur_mem_usage_local);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:899:17: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                ctx->cur_mem_usage_local);
                ^~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:931:25: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                        block->size, ctx->cur_mem_usage_default);
                        ^~~~~~~~~~~
linalg.c:931:38: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                        block->size, ctx->cur_mem_usage_default);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:952:17: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                ctx->cur_mem_usage_default);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:971:17: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                ctx->peak_mem_usage_device);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:973:17: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                ctx->peak_mem_usage_local);
                ^~~~~~~~~~~~~~~~~~~~~~~~~
linalg.c:975:17: warning: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Wformat]
                ctx->peak_mem_usage_default);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
12 warnings generated.
Undefined symbols for architecture x86_64:
  "_clBuildProgram", referenced from:
      _build_opencl_program in linalg-880123.o
  "_clCreateCommandQueue", referenced from:
      _setup_opencl in linalg-880123.o
  "_clCreateContext", referenced from:
      _setup_opencl in linalg-880123.o
  "_clCreateProgramWithSource", referenced from:
      _setup_opencl in linalg-880123.o
  "_clFinish", referenced from:
      _futhark_context_sync in linalg-880123.o
  "_clGetDeviceIDs", referenced from:
      _opencl_all_device_options in linalg-880123.o
  "_clGetDeviceInfo", referenced from:
      _setup_opencl in linalg-880123.o
      _post_opencl_setup in linalg-880123.o
      _opencl_all_device_options in linalg-880123.o
      _opencl_device_info in linalg-880123.o
  "_clGetPlatformIDs", referenced from:
      _opencl_all_device_options in linalg-880123.o
  "_clGetPlatformInfo", referenced from:
      _opencl_platform_info in linalg-880123.o
  "_clGetProgramBuildInfo", referenced from:
      _build_opencl_program in linalg-880123.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Athas** [comment]
Are you using a Futhark release?  I think I fixed those printf() warnings in Git recently.  They should be mostly harmless, though.

The linker error is because you also need to pass `-lOpenCL` to clang in order to link to the OpenCL library.  You are likely not the first who will encounter this issue, so I'll see about mentioning it explicitly in the documentation somewhere.

**Comment by Athas** [comment]
If you are on macOS, the option may be `-framework OpenCL`.  That's what `futhark-opencl` itself passes when `--library` is not used.

**Comment by luxint** [comment]
Thanks, adding -framework OpenCL worked.
Regarding the warnings, I checked out the GIT repository a couple of days ago and build from source as per installation instructions.

**Comment by Athas** [comment]
I guess I'll have to take a closer look at what goes wrong with those format strings.
