### ISSUE TITLE
2 internal compiler errors when running tests

### ISSUE THREAD

**Issue by luxint** [diku-dk/futhark#451]
Hi,

see below errors which I got when running: futhark-test tests --compiler=futhark-opencl --pass-option='-dAMD' --exclude no_open

Warning at tests/shapes/lambda-return.fut:22:7-22:7:
  Unused variable 'n'.
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/HIPERFIT/futhark/issues.
Cannot deal with existential memory block res_mem_2615 when expanding inside kernels.
CallStack (from HasCallStack):
  error, called at src/Futhark/Pass/ExpandAllocations.hs:197:15 in futhark-0.3.0-A6KhDlSVJpqBxpBKFDVwLj:Futhark.Pass.ExpandAllocations

Warning at tests/soacs/scan2.fut:20:40-20:40:
  Unused variable 'y_658'.
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'extract kernels':
In function main
In expression of statement {[size_2577][size_2578]f64 res_seq_scanned_2631,
 [num_groups_2617][size_2578]f64 res_group_sums_2632}
Type error:
In function main
In expression of statement {[size_2577][size_2578]f64 res_seq_scanned_2631,
 [num_groups_2617][size_2578]f64 res_group_sums_2632}
In expression of statement {[size_2577][size_2578]f64 result_2662, [size_2578]f64 result_2663}
Type error:
Variable scan_ne_right_shape_2590 referenced after being consumed.

**Comment by Athas** [comment]
You have a typo: it's `no_opencl`, not `no_open`.  I'm surprised we only have two failures, though.  I thought we had more that didn't work.
