### ISSUE TITLE
Permit randomly generated test data in futhark-test/futhark-benchmark

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#463]
We have `futhark-dataset` for generating random test data, but you are currently required to save the generated data as files.  This seems unnecessary.  The test stanza syntax should just support `futhark-dataset` directories instead.  This will save on disk consumption for benchmark programs where we the actual data is less important, and the size of the data is more important.

**Comment by RasmusWL** [comment]
For small datasets this would be fine, but for large datasets the time to *generate* the data was quite significant, so if you want to run a test multiple times, you will suffer from doing this :)

**Comment by Athas** [comment]
That could be solved by specifying a filename *and* a stanza for generating them.  `futhark-bench`/`futhark-test` will then generate the files in question only if they do not already exist.

**Comment by athas** [comment]
I propose the following syntax, by example:

```
random input { [10]i32 f32 [100]bool }
```

`futhark-test` and `futhark-bench` will automatically cache the generated file in a `data` subdirectory.  There may be some way to indicate a specific seed, possibly by saying `random(123)` or whatnot.  I think that can be left for later.

The missing piece: where do we indicate the bounds for the generated numbers?  That is pretty important.  Maybe a superior solution is to just insert the corresponding command line parameters for `futhark-dataset`.  (But we should not permit arbitrary shell commands, *only* `futhark-dataset`.)

Bikeshedding welcome.

**Comment by svip** [comment]
Couldn't we just add some brackets after each parameter to indicate bounds?

    random input { [10]i32<0..100> f32<-100.0..100.0> [100]bool }

And if you need it to be exclusive, you could flip the bracket?  I am unsure whether `<` and `>` have any meaning in the benchmark syntax.

As for seeds, what happens by default then?  Current time or a predefined seed?

**Comment by athas** [comment]
They do not.  However, what is the advantage over the following?

```
random input { --i32-bounds=0:100 -g [10]i32 --f32-bounds=-100=100 --bool-bounds=true:true -g [100]bool
```

While this is verbose, it has the benefit that you can copy it directly into a `futhark-dataset` invocation on the command line to try it out.

**Comment by svip** [comment]
Besides a lack of verboseness, I don't think it has any advantages.  Unfortunately, `<` and `>` have quite important meanings in a shell.  Doesn't `[` and `]` have some meaning?  Wouldn't `[10]i32` catch all files that end in "i32" and start with either 0 or 1?

**Comment by athas** [comment]
Yes, normally you'd quote it, but it is unlikely there will be any files with those names, so the shell lets them pass unmolested.  It has not been a problem yet.  Further, we will not literally spawn a shell here, but just launch `futhark-dataset` directly.

**Comment by svip** [comment]
Ah, I thought you meant your example had the advantage of the user being able to copy it directly into their own shell as parameters for calling `futhark-dataset`.

**Comment by athas** [comment]
It does.
