### ISSUE TITLE
Support arbitrary function preconditions

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#464]
I thought of a fairly straightforward way to implement arbitrary function preconditions efficiently.  In this scheme, a precondition is an arbitrary `bool`-typed expression.  It could be used to, for example, encode that an input array must not be empty:

```
let f (xs: []i32) with length xs > 0 = ...
```

(The syntax can be discussed.)  This is essentially a lightweight implementation of #24, and should be designed in such a way that it could eventually be extended to that.  This also looks like a good spot for the user to add annotations that are not really preconditions, but merely hints to the compiler.  For example, I would like to say

```
let f (xs: []i32) with sufficiently parallel (length xs) = ...
```

which hints to the compiler that it is never worth parallelising inside a parallel construct of span proportional to the size of `xs`.  Similarly, an annotation could be supported that some dimension is never worth parallelising.  This cuts down on the number of different versions generated by the gradual flattening algorithm, which reduces compile times, and speeds up autotuning of the parallelisation thresholds.

**Comment by Athas** [comment]
Instead of preconditions, we could just add a function `assert` of type `bool -> t -> t` (for any `t`), which semantically behaves like the identity function on the second argument, but makes the compiler insert a check of the first argument:

```
let f (xs: []i32) = let xs = assert (length xs > 0) xs in ...
```

It makes it less clear what is a function precondition and what is an internal sanity check, but it saves us from having to extend the language at all.

**Comment by RasmusWL** [comment]
That would easily expand to allowing postconditions :)

**Comment by Athas** [comment]
I will soon add such an `assert` construct.  It will be translated to a core language `Assert`.

**Comment by Athas** [comment]
Defining this as an ordinary function is rather annoying if we want to support good error messages (we do).  Can we think of a good syntax for an expression construct instead?  `x where x > 0`, which returns `x` or fails?  I would really prefer to do this at the expression level.

**Comment by Athas** [comment]
Maybe, to match `:` for type ascription, we could use `?`:

```
x ? x > 0
```

Or to be really wild, the right-hand side should be a function:

```
x ? (>0)
```

But that is probably not a good design.
