### ISSUE TITLE
Typo in pyopencl boiler plate

### ISSUE THREAD

**Issue by swilliam** [diku-dk/futhark#468]
def apply_size_heuristics(self, size_heuristics, sizes):
    for (platform_name, device_type, size, value) in size_heuristics:
        if sizes[size] == None \
           and self.platform.name.find(platform_name) >= 0 \
           and self.device.type == device_type:
               if type(value) == str:
ERROR ->>>                   size[size] = self.device.get_info(getattr(cl.device_info,value))
               else:
                   sizes[size] = value
    return sizes

should be sizes[size not size[size]

**Comment by Athas** [comment]
Good catch!  Wonder how that ever managed to run.
