### ISSUE TITLE
Factorial example from the website doesn't work

### ISSUE THREAD

**Issue by nh2** [diku-dk/futhark#469]
I'm using from https://futhark-lang.org/examples.html

```
let fact (n: i32): i32 = reduce (*) 1 [1...n]

let main (n: i32): i32 = fact n
```

on commit 6f777b711b4c773af8916ab3ecf57cede8f37e4f:

```
Type error at fact.fut:1:33-1:33:
Overloaded function * not defined for arguments of types i32, *[]i32
```

**Comment by Athas** [comment]
Oh sorry, the syntax for range literals literally changed yesterday - it's just `1...n` now, not `[1...n]`.  I will update the website.

**Comment by Athas** [comment]
Note you will still need parens here:

```
let fact (n: i32): i32 = reduce (*) 1 (1...n)
```

**Comment by nh2** [comment]
Thanks!
