### ISSUE TITLE
Permit operator sections everywhere

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#491]
Given

```
let map2 'a 'b [n] 'x (f: a -> b -> x) (as: [n]a) (bs: [n]a): [n]x =
  map (\(a, b) -> f a b) (zip as bs)
```

it would be nice if I could write

```
let vecadd (xs: []i32) (ys: []i32) = map2 (i32.+) xs ys
```

instead of

```
let vecadd (xs: []i32) (ys: []i32) = map2 (\(x: i32) (y: i32) -> x + y) xs ys
```

(Of course, `(+)` by itself would be even nicer, but that touches upon operator overloading - let's not go there for the moment.)

Currently this produces the error message "Operator sections are only permitted directly in applications.".

**Comment by ahovgaard** [comment]
I think this requires modifications to the internalizer as well. For example, `(i32.+) 1 2` will fail in `Futhark.Internalise.findFuncall` with "Invalid function expression in application: (i32.+)".

**Comment by Athas** [comment]
Why not have the monomorphiser turn all sections into lambdas, and then from lambdas into lifted functions?  Conceptually, an operator section is just a syntactic shortcut for a lambda.

**Comment by ahovgaard** [comment]
That's probably a good way to do it.
