### ISSUE TITLE
Internalisation error for higher order function

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#493]
This crashes the compiler:

```
let (<|) 'a '^b (f: a -> b) (x: a) = f x

let main (n: i32) (d: [][]i32) = replicate n <| d
```

```
futhark: Futhark.Internalise.internaliseIdent: asked to internalise non-prim-typed ident 'replicate_2514 of type {const:(), iota:()} at unknown location.
```

**Comment by Athas** [comment]
This might also be an internalisation bug - or at least a case of unclear requirements.  The defunctionaliser produces a binding such as:

```
let replicate_2518 (n_2344) =
  {n_2344, replicate_2515}
```

where

```
let replicate_2515 (n_1019) (x_1020) =
  map ((\(x_2517)->
          const_2514 x_1020 x_2517))
      (iota_1015 n_1019)
```

but the type annotation for `replicate_2515` in the binding of `replicate_2518` is a record `{const:(), iota:()}`, *not* a function (how could it be?).

**Comment by Athas** [comment]
I think I figured out what's going wrong (or at least, another problem): the monomorphiser does not deal with infix operators.  I'll try to fix it myself, to get some familiarity with the code.

**Comment by Athas** [comment]
Okay, the problem is definitely not the infix operator.  While there is a separate problem with infix operators (which I will try to solve), this problem persists if you rename `<|` to `h` or whatever.

**Comment by ahovgaard** [comment]
I will take a look at this now. I am aware that polymorphic infix operators are not yet handled properly in the monomorphizer, but I just didn't get around to it yet.

**Comment by Athas** [comment]
You may want to do a pull - I modified the pretty printer to print type annotations for parameters, which may make your job a little easier.

**Comment by ahovgaard** [comment]
I found the problem. When defunctionalizing a lambda, we currently just construct a record with an implicit field for each value in the closed-over environment. If one of those is a `DynamicFun` (first-order function), we instead need to construct an explicit field with its record closure as the expression and modify the environment to map to the corresponding `Lambda` static value rather than the `DynamicFun` static value.

**Comment by Athas** [comment]
Makes sense.  Good find!  You may want to pull again as my recent commit changed a few lines here and there (mostly related to infix operators, but you never know).
