### ISSUE TITLE
Full type inference for Futhark

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#503]
I think it is fairly easy to extend the infrastructure built by @ahovgaard to support full type inference (at least in the absence of in-place updates, which is fine by me).  If we simply handle un-annotated parameters by creating a new type variable, I think we will already be almost done.

The only problem is in the handling of our handful of built-in overloaded operators.  However, I think a solution is to change how we track substitutions in the type checker.  Currently the data structure looks like this:

```
type Substs = M.Map VName (TypeBase () (), SrcLoc)
```

I propose extending it to something like:

```
type Substs = M.Map VName TySubst
data TySubst = TySubst (TypeBase () ()) SrcLoc
             | TySubstOverloaded [TypeBase () ()] SrcLoc
```

Here a `TySubstOverloaded` indicates a type variable that can *only* be unified with one of the mentioned types.  For an operator like `+`, that would be i8, i16, i32, i64, u8, u16, u32, u64, f32, and f64.  This just needs a few more cases in the instantiation logic, plus some code when we look up overloaded operators to not just create a new type variable, but also insert a `TySubstOverloaded` substitution immediately.

One question is what to do about a function such as:

```
let add x y = x + y
```

Is this an error, because the type of `x` and `y` is ambiguous, or do we just fall back to `int` as a default?  I suggest the former.

**Comment by melsman** [comment]
Another possibility would be to contrain the type variables. A type
variable would then have associated with it an optional list of those base
types that it can be instantiated with...

**Comment by Athas** [comment]
Yes, that is essentially how `TypeSubstOverloaded` works, except that the "no constraints" case is represented by the type variable not being present in the substitution map at all.

**Comment by melsman** [comment]
The natural type for the type inference algorithm to give to `add` would
then be:

````
val add : \/'a :> [i32,f64]. 'a -> 'a -> 'a
````

The monomorphizer would then generate different copies for each type..

On Sun, Mar 11, 2018 at 11:11 PM, Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
This would make type overloading visible at the user level.  Is that not the path to a great deal of complexity?  Is that complexity worthwhile?

**Comment by melsman** [comment]
I'm not sure that we would be required to let the type slip to the user
level, which I don't think would be nice. But you're right, we wouldn't be
able to specify the type of add in a module type, which is fine with me....
I guess a conservative solution would be just to never quantify over such
constrained type variables...

**Comment by Athas** [comment]
I am playing with a design where a type variable (the ones we create when instantiating a type scheme) can be in four different states:

  * *Lifted unconstrained*, which can be instantiated with any (possibly functional) type.
  * *Unlifted unconstrained*, which can be instantiated with any non-functional type.
  * *Constrained*, which contains a list of (primitive, non-functional) types that the variable can be instantiated with.  Used for handling overloading.
  * *Fixed*, which is when we have a concrete substitution (which might of course be another type variable).

**Comment by Athas** [comment]
This also makes it easy to determine which variables in the type of a RHS of a `let`-binding must be closed over: it is those that are present in the substitution map.

**Comment by Athas** [comment]
I have done some initial work and pushed it to the type-inference branch: https://github.com/diku-dk/futhark/tree/type-inference

As expected, it was mostly a matter of extending @ahovgaard's substitution maps in the type checker.  Nothing downstream had to be modified.  I do not yet handle overloaded operators, but the following program type checks, which pleases me greatly:

```
let main x =
  let apply f x = f x
  in apply (apply (i32.+) x) x
```

My type errors are barely acceptable.  At least they tend to point to the right source locations, but they leak internal names.  I will handle that last.

**Comment by Athas** [comment]
This program can now type check:

```
let main x = x + 2
```

And so can this:

```
let main x = (\y -> x + y) 2
```

But this is intentionally a type error, because the type is ambiguous:

```
let add x y = x + y
```

This is different from Standard ML, which as I recall will default to `int`.  I think it is better to raise an error on ambiguities.  There is no tax on type annotations.

Progress has been faster after I started reading the MLkit and MosML source code for inspiration.  I still suspect this will be quite buggy in the first release, though.

**Comment by Athas** [comment]
It is almost ready, and I will merge soon.  There are still a lot of limitations (inference is not possible for in-place updates, records/tuples, or `unzip`), but in these cases one can just insert type annotations, so it's not a big deal.  I want to get it in master so we can start debugging.  I really want it to be stable for the 0.4 release.  The type error messages become slightly worse, unfortunately.
