### ISSUE TITLE
Defunctionaliser does not handle shadowing correctly

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#509]
There are a number of places where the defunctionaliser constructs records by using `baseName`s as the keys.  This is dangerous when closing over an environment that contains multiple variables with the same `baseName`, as we will end up throwing some of the record fields away.  At the moment I am having a lot of trouble finding a small reproducible base case, but it happens in some large problems.  The symptom is usually an error in the internaliser, because the program produced by the defunctionaliser is ill-typed.  One way of seeing this is to add the following function to the defunctionaliser:

```
mfromList :: (Ord k, Pretty k, Pretty v) => [(k,v)] -> M.Map k v
mfromList kvs = if nub (map fst kvs) /= map fst kvs then
                  error ("Would shadow: " ++ pretty kvs)
                else M.fromList kvs
```

and then use `mfromList` in place of `M.fromList` everywhere.

**Comment by Athas** [comment]
Also, I should mention that I'm not even sure that the problem is closures - all I know is that the defunctionaliser will sometimes construct record types that are smaller than they should be.  @ahovgaard, can you think of any obvious solution?

**Comment by Athas** [comment]
In general, I would caution against generating code that uses `RecordFieldImplicit`, since the generated record field names never contain the unique identifier.  Only user code should use that (and we will of course have to maintain it, but that should not cause problematic shadowing).

**Comment by Athas** [comment]
The problem is both.  We should always use field names that include the unique name (`nameFromString . pretty` is a good way to generate those), and we should never generate implicit record literals.

**Comment by ahovgaard** [comment]
I can try to take a look at this now. Do you have an example of a program that fails?

**Comment by Athas** [comment]
Yes, but you will not like it.  It is a modification of the large Heston benchmark to use more higher-order functions, and comprises four files and heavy use of the module system: http://sigkill.dk/junk/heston-broken/

`futhark heston32.fut` should fail.  This one will test your debugging skills.  One potential wrinkle is that since modules are involved, it *might* be a bug in the module system as well.  I find that highly unlikely, however.

**Comment by Athas** [comment]
Apart from using the module system (which I think is a red herring), the most characteristic aspect of the Heston benchmark is heavy use of records and local functions.

**Comment by ahovgaard** [comment]
I'm not exactly sure how to solve this. However, when I change the case for `Lambda` to only produce explicit record fields with names obtained using `nameFromString . pretty`, and also update `typeFromEnv` to construct a type from a `LambdaSV` environment with unique names constructed in the same way, I get a different error: `lookupConstant: unsign_1612 failed`

**Comment by Athas** [comment]
Anders Kiel Hovgaard <notifications@github.com> writes:

> I'm not exactly sure how to solve this. However, when I change the
> case for `Lambda` to only produce explicit record fields with names
> obtained using `nameFromString . pretty`, and also update
> typeFromEnv` to construct a type from a `LambdaSV` environment with
> unique names constructed in the same way, I get a different error:
> lookupConstant: unsign_1612 failed`

Yes, I did the same.  This issue is due to the handling of BinOp being
wrong.  I have (locally) modified BinOp handling to just turn it into an
Apply, so the logic will be the same.  This reveals yet another (final!)
issue about uniqueness, which is similar to what I have seen before, so
I believe I can resolve it.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
A starting point is definitely to ensure commonality between binary operators and ordinary application.  @ahovgaard, could you use this definition in Defunctionalise.hs, and then fix the resulting errors?

```
-- We handle BinOps by turning them into ordinary function applications.
defuncExp (BinOp qn (Info il) (e1, Info pt1) (e2, Info pt2) (Info (pts, ret)) loc) =
  defuncExp $ Apply (Apply (Var qn (Info (il, pt1:pt2:pts, ret)) loc)
                     e1 (Info (diet pt1)) (Info (pt2:pts, ret)) loc)
                    e2 (Info (diet pt2)) (Info (pts, ret)) loc
```

After this change, the defunctionaliser produces incorrect code on some relatively simple programs (like [this one](https://github.com/diku-dk/futhark/blob/master/tests/higher-order-functions/binop2.fut)) - probably a bug in the handling of intrinsic functions in the general handling of applications (intrinsics almost never occur outside of `BinOp`s, so it is not unsurprising that a few bugs remain).  I will take a break from this now.

**Comment by Athas** [comment]
If it makes things consistent, we could also just make the monomorphiser switch all `BinOp` nodes to `Apply` nodes, just like how it already handles operator sections.

**Comment by Athas** [comment]
Also, you may want to pull - I just fixed a prettyprinter bug that caused me to waste an hour looking for the wrong thing (missing parentheses around function arguments).

**Comment by ahovgaard** [comment]
The problem with intrinsic functions in applications is easily fixed. It currently doesn't defunctionalize the argument expressions and the problem has not shown up yet, since most intrinsic functions are infix operators. However, the problem with uniqueness remains.

**Comment by Athas** [comment]
I can fix the uniqueness problem.  Just put your code on a branch somewhere, and I'll take a look.

**Comment by ahovgaard** [comment]
It's on the `higher-order-functions` branch now.

**Comment by Athas** [comment]
This got fixed.
