### ISSUE TITLE
Turn map into a function

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#518]
`map` is currently a language construct, not a function.  This means, among other things, that you can't do `map (map f) xss`.  There is a `map1` function in the basis library that can be used instead, but it feels ugly.  The main reason `map` remains a language construct is that it can accept multiple input arrays, as in `map f x y z`.  However, the compiler will currently warn if you do so.  There are also some quirks around aliasing, but I'd rather get rid of those anyway - none of our benchmarks make use of it.

There is no doubt that `map` will *eventually* become a normal function, as part of my general crusade against language constructs.  Deus vult.  The only question is whether it should happen *before* the next release (in a week), or after.  Opinions?

**Comment by kfl** [comment]
My vote is for `map` to be a function as soon as possible.
