### ISSUE TITLE
Shape annotation on function type parameter interferes with result

### ISSUE THREAD

**Issue by ahovgaard** [diku-dk/futhark#535]
It would be interesting to support shapes in function types, but it may cause problems if the same shape is used in other value parameters of order zero or used as a term-level variable. Most likely, a shape occurring in a function type should not be used as a term variable (unless, maybe if it was used in a order 0 parameter first so that the shape could actually be determined).

In the following program, the shape on the return type of `g` causes the shape `n` to have value 0 and `length` to return 0 regardless of its input.
```
let f [n] (g: i32 -> [n]i32) (xs: [n]i32) = (g (length xs), n)
let main (xs: []i32) = f iota xs  -- n is always 0
```
It executes as follows:
```
$ echo "[1,2,3]" | ./shapes 
empty(i32)
0i32
```

**Comment by ahovgaard** [comment]
Perhaps somewhat related. Dependency between parameter values and shapes actually kind of works in the source language now. This will fail if not `n = length xs`:
```
let main (n: i32) (xs: [n]i32) = xs
```

**Comment by Athas** [comment]
The defunctionaliser produces this:

```
let length_3091 [n_2841] ((_: [n_2841]i32)): i32 =
  n_2841
let f_3092 : {length_3091:()} =
  {length_3091={}}
let iota_1340 ((n_1341: i32)): *[]i32 =
  [0i32..1i32..<n_1341]
let iota_2911 ((n_2912: i32)): *[n_2912]i32 =
  iota_1340 n_2912
let lifted_3093 [n_3085] {length_3091=(length_3091: ())} ((g_3086: {iota_1340:()})): {g_3086:{iota_1340:()},
                                                                                      length_3091:(),
                                                                                      n_3085:i32} =
  {n_3085=n_3085, g_3086=g_3086, length_3091=length_3091}
let lifted_3094 [n_2841] {} ((_: [n_2841]i32)): i32 =
  n_2841
let lifted_3095 {} ((n_1341: i32)): *[]i32 =
  [0i32..1i32..<n_1341]
let lifted_3096 {iota_1340=(iota_1340: ())} ((n_2912: i32)): *[]i32 =
  (lifted_3095 iota_1340 n_2912)
entry main_3089 ((xs_3090: []i32)): ([]i32, i32) =
  let {n_3085=(n_3085: i32), g_3086=(g_3086: {iota_1340:()}),
       length_3091=(length_3091: ())} = (lifted_3093 f_3092 {iota_1340={}}) in
  let (xs_3087: [n_3085]i32) = xs_3090 in
  ((lifted_3096 g_3086 ((lifted_3094 length_3091 xs_3087))), n_3085)
```

The problem is that the function `lifted_3093` takes a shape parameter that is not fixed by any of its value parameters.  The internaliser will turn that into a zero (probably it should terminate with an error instead).  I suspect the reason is that the shape parameter handling I implemented is confused by shapes in negative position in parameter types.

**Comment by Athas** [comment]
Maybe that function should be prevented by the type checker.  What would be the result of a partial application that fixes only the first parameter?  What would the constraint be?  Impossible to say.

**Comment by Athas** [comment]
I am increasingly convinced that `f` is an abomination that the type checker should not permit to live.  The absurdity is clear if you spell out the lambdas:

```
let f = \[n] (g: i32 -> [n]i32) -> \(xs: [n]i32) -> (g (length xs), n)
```

What's that supposed to mean?

**Comment by ahovgaard** [comment]
It could mean that `g`, if applied, must return an array of the same length as `xs`. But I agree that it's not clear how this is supposed to work in general. Other examples, like the following, simply make no sense:
```
let f' [n] (g: i32 -> [n]i32) : i32 = n
```
This will just return 0. At least until we implement some kind of support for shape annotations in functions, I think it would make most sense if the annotation on `g` is ignored, so that `f'` will fail with "size parameter not used in value parameter", or let all such annotations cause an error.

Regarding the meaning of `f`. If we apply the kind of translation that we discussed previously, we could translate it to something like the following, which I think works fine:
```
let f [n] (g: i32 -> []i32) (xs: [n]i32) =
  let g' (x: i32) = g x : [n]i32
  in (g' (length xs), n)
```

**Comment by Athas** [comment]
But at the point where `g` is provided, `xs` is not known.  From the functions point of view, it is not even in scope!  I think we should definitely refine the type checker such that it forbids uses of shape parameters until that shape parameter has been in positive position at least once.  I am pretty sure that is how dependently typed programming languages handle implicit parameters, too.
