### ISSUE TITLE
Change type error message

### ISSUE THREAD

**Issue by clonest1ck** [diku-dk/futhark#543]
When getting a type error it currently only states something like "Couldn't match type `i32' with type `i8'." which can be confusing and lead to an increased amount of time when debugging if you are unsure about which type it is supposed to be and which you have (accidentally) placed there instead. A message like "couldn't match given type x with expected type y" would be more intuitive.

**Comment by Athas** [comment]
Agreed.  But in the general Hindley-Milner setting, is there a good way to really know which is the expected and which is the actual type?  E.g. consider an `if` expression whose branches return different types.  I wonder how GHC does it.
