### ISSUE TITLE
Invalid consumption after internalization of very simple program

### ISSUE THREAD

**Issue by ahovgaard** [diku-dk/futhark#544]
```
let main =
  ((\x -> x) <-< (\x -> x)) [1,2,3]
```
This program fails with the following error message:
```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
After internalisation:
In function lifted_3198
Type error:
x_3213 was invalidly consumed.
Nothing can be consumed here.
```
It looks like the defunctionalizer may be producing invalid uniqueness type annotations on the lifted function:
```
let lifted_3198 {g_2863=(g_2863: ()),
                 f_2864=(f_2864: ())} ((x_2865: []i32)): *[]i32 =
  let (x_3187: []i32) = (let (x_3189: []i32) = x_2865 in
                         x_3189) in
  x_3187
```

**Comment by Athas** [comment]
Interesting.  It is because `[1,2,3]` has a unique type, which then gets substituted into the lambda bodies.  I think we should remove uniqueness when constructing the environment we use when defunctionalising the body of a static lambda.

**Comment by Athas** [comment]
Oh, interesting - the problem is specifically that sometimes we call `matchPatternSV` with a pattern that contains non-unique types but a StaticVal that contains unique types, and we propagate the uniqueness from the StaticVal.  That is clearly a bug.
