### ISSUE TITLE
Defunctionalisation can remove shape annotations

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#548]
Consider this program:

```
let iota (n: i32): [n]i32 =
  0..1..<n

let main (is: []i32) (m: i32) =
  map (\i -> map (+i) (iota m)) is
```

After monomorphisation it looks like this:

```
let map_3200 [n_308] ((f_310: i32 -> []i32)) ((as_311: [n_308]i32)): *[n_308][]i32 =
  map (f_310)
      as_311
let map_3201 [n_308] ((f_310: i32 -> i32)) ((as_311: [n_308]i32)): *[n_308]i32 =
  map (f_310)
      as_311
let iota_3186 ((n_3187: i32)): [n_3187]i32 =
  [0..1..<n_3187]
entry main_3190 ((is_3191: []i32)) ((m_3192: i32)): *[][]i32 =
  map_3200 (\(i_3195: i32)->
              map_3201 (\(x_3202: i32)->
                          x_3202
                          intrinsics_0.+_271 i_3195) (iota_3186 m_3192)) is_3191
```

Note the function `iota_3186` that contains a shape annotation in its return type.  After defunctionalisation, the program looks like this:

```
let map_3200 : () =
  {}
let map_3201 : () =
  {}
let iota_3186 ((n_3187: i32)): [n_3187]i32 =
  [0..1..<n_3187]
let lifted_3204 {} ((n_3187: i32)): *[]i32 =
  [0..1..<n_3187]
let lifted_3206 [n_308] {f_310=(f_310: {i_3195:i32})} ((as_311: [n_308]i32)): *[]i32 =
  map (\(x_3205: i32)->
         let {i_3195=(i_3195: i32)} = f_310 in
         let (x_3202: i32) = x_3205 in
         intrinsics_0.+_271 x_3202 i_3195)
      as_311
let lifted_3207 {iota_3186=(iota_3186: ()), m_3192=(m_3192: i32),
                 map_3201=(map_3201: ())} (i_3195: i32): *[]i32 =
  (lifted_3206 {f_310={i_3195=i_3195}} ((lifted_3204 iota_3186 m_3192)))
let lifted_3208 [n_308] {f_310=(f_310: {iota_3186:(), m_3192:i32,
                                        map_3201:()})} ((as_311: [n_308]i32)): *[][]i32 =
  map (\(x_3203: i32)->
         (lifted_3207 f_310 x_3203))
      as_311
entry main_3190 ((is_3191: []i32)) ((m_3192: i32)): *[][]i32 =
  (lifted_3208 {f_310=({iota_3186={}, m_3192=m_3192,
                        map_3201=map_3201})} is_3191)
```

While `iota_3186` is still present, it is not used.  Instead, the defunctionaliser has generated a `lifted_3204` that does not contain a return shape annotation.

While this does not affect functional correctness, it does impact which optimisations that the compiler can carry out.  I'm not sure why it happens but it should be fixed.

**Comment by Athas** [comment]
The problem appears to be that the closure environment for a `LambdaSV` contains things that are not really part of the closure (global variables and names).  This means that the `DynamicFun` for `iota_3186` degenerates into a `LambdaSV`, and these are inlined/lifted when applied (so return type shape annotations vanish).

**Comment by ahovgaard** [comment]
I think this stems from the changes made to fix issue #493. This problem was not as prominent before we changed SOACs to be library functions, because they would be handled specially before and in this case, the program would be mostly unchanged by defunctionalization. Now the defunctionalizer will see the variable `iota` in the lambda as a free variable and because it is a dynamic functions, its static value will be converted to a `LambdaSV`. This is necessary if the dynamic function is a local function with free variables or is partially applied.

**Comment by Athas** [comment]
But don't DynamicFuns degenerate to LambdaSVs anyway if they are partially applied somewhere?

**Comment by ahovgaard** [comment]
Yes they do. I think the only case where this conversion, from `DynamicFun` to environment record and `LambdaSV`, is necessary is when a lambda refers to a local dynamic function that needs to escape its scope. Perhaps, we just need to somehow check if the dynamic function is defined at top-level or in some local scope.

**Comment by Athas** [comment]
Yes, that's also what I ended up surmising.  I'll see if I can hack something together.  As another solution, would it be possible for LambdaSVs to carry around an (optional) return type declaration, or does that not make sense?

**Comment by ahovgaard** [comment]
I think that would also be an option, but it would be nice to avoid creating new lifted functions for every single library function that occurs in a lambda.
