### ISSUE TITLE
Possibly an error in the v0.6.1 on the gpu-machines

### ISSUE THREAD

**Issue by kasperah** [diku-dk/futhark#566]
I have tested some code using latest official version on GitHub `Futhark 0.6.0 git: f02b066 (Wed Jun 13 07:31:28 2018 +0200)`, and everything runs fine. 

Preparing some benchmarks I tested the code on the gpu-machines (gpu01 and 02) and got some unexpected results.  The gpu's are running  `Futhark 0.6.1, git: 78f937f (Thu Jun 7 23:37:39 2018 +0200)`. 

The unexpected result came when running 
```
[blk486@a00332 fut_genfft]$ futhark-test --compiler=futhark-pyopencl planner.fut 
planner.fut:
Entry point: t_get_factor; dataset: #0 ("4i32 2i32"):
Running compiled program:
Running ./planner -e t_get_factor:
validating test result:
planner.fut.actual and planner.fut.expected do not match:
Value 0 expected array of shape [], got [1]
```
As the result explains, the result should be a tuple `(i32, i32, i32)` but for some reason the output is  `(i32, [i32], i32)`.

If you want to check for yourself, you can run the current version of `planner.fut` in [fut_genfft](https://github.com/diku-dk/fut_genfft)

**Comment by Athas** [comment]
I can't reproduce this on `gpu01`.  Just in case something is really going on, I have updated the Futhark installation on all the machines.

Does this also happen with the non-Python compilers?

**Comment by kasperah** [comment]
No, just the pyopencl one. 

Just tested it again on gpu02 and it is working as expected now. Thanks!

**Comment by kasperah** [comment]
Seems the error has returned. When runnning `futhark-test --nobuffer --compiler=futhark-pyoopencl planner.fut` on either gpu01 or gpu02, I get
```
planner.fut:
Entry point: t_get_factor; dataset: #0 ("4i32 2i32"):
Running compiled program:
Running ./planner -e t_get_factor:
validating test result:
planner.fut.actual and planner.fut.expected do not match:
Value 0 expected array of shape [], got [1]
```
Some how, futhark-test compiles the output  as `get_factor -> ([i32], [i32], i32)` when it should be `get_factor -> (i32, i32, i32)`. It is only when running futhark-test and does seem affect compiling the code using futhark-pyopencl (although I have not tried running the compiled python-code). 

Final note, is that this is only happening on the gpu-machines and not on my own. Do not know if it is important, but the the python versions are different: I am running `Python 2.7.15rc1`, and the gpu's are running `Python 2.7.5`

**Comment by Athas** [comment]
Still can't reproduce this on gpu01-diku-apl.  Could you send me the compiled planner.py that fails?

**Comment by Athas** [comment]
Guess it's just `planner`, really.

**Comment by kasperah** [comment]
Strange. Here's the file including .expected and .actual. 


[planner.zip](https://github.com/diku-dk/futhark/files/2107266/planner.zip)

**Comment by Athas** [comment]
Which exact revision of planner.fut and the Futhark compiler are you using?  The MD5-sum does not match what I get.

**Comment by Athas** [comment]
When I run that program, I get these results:

```
$ echo 4 2 | ./planner -e t_get_factor
1i32
2i32
2i32
```

Maybe you are using a different version of Numpy?  I get:

```
$ python
>>> import numpy
>>> numpy.version.version
'1.13.1'
```

**Comment by Athas** [comment]
Looks like the globally installed Numpy on those machines is 1.7.1.  Try doing a `pip install --user numpy`.

**Comment by kasperah** [comment]
Will do

**Comment by kasperah** [comment]
installed a newer numpy on gpu02, as you suggested, and seems to have fixed it. I will close this issue - thanks!
