### ISSUE TITLE
Type error after pass 'simplify' for assigning to a slice

### ISSUE THREAD

**Issue by pepijndevos** [diku-dk/futhark#573]
I tried to update a complete array in-place, rather than creating a new variable.
```
entry test (a: [8]f32) : *[8]f32 =
  let a = copy a
  let a[:] = map id a
  in a
```
But this produces the following error:
```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'simplify':
In function test_3278
When matching
   {[8i32]f32 letwith_dst_3420}
with
   replicate([1i32], lw_val_correct_shape_3419)
Pattern {[8i32]f32 letwith_dst_3420} cannot match value of type {[1i32][8i32]f32}.
```

**Comment by Athas** [comment]
There is a compiler bug here, but even when it's fixed, this will still not run fully in-place.  The compiler will merely make a copy of `a`, and then overwrite the original `a` with it.  Improving *that* is tracked in #461.
