### ISSUE TITLE
Expose metadata in generated C code

### ISSUE THREAD

**Issue by pepijndevos** [diku-dk/futhark#576]
When writing generic FFI code, I faced the following challenges, which required some fragile introspection.

 * There is no easy way to get a list of all entry points. I resolve them at run-time currently.
 * There is no easy way to get a list of all datatypes and their corresponding `new`, `free`, etc. functions. I currently iterate over all functions and pattern-match on their names. There is no easy way to tell if a type is opaque or not, except that the above pattern-matching loop finds only `free`.
 * There is no easy way to know the length of the return value of `shape`. Either pattern-match on the name, or extract from the number of arguments to `new`.
 * There is no easy way to know which parameters are inputs or outputs. I used an heuristic based on their type (`struct * *` or `numeric *`)

Introspection is also used to determine the argument types of each entry point, and to determine the type of argument to `new`. But I think this is fine. So the following information would be really helpful.

For entry points
 * a list of all entry points
 * the number of output arguments (or make inputs const, so it's clear from the type signature)

For data types
 * a list of all types
 * a list of their functions
 * their dimension
 * their inner type (optional, can be easily inferred from `new` type signature)
 * if they are opaque (optional, can be easily inferred from functions)

These could be implemented as an array of structs with function pointers. I think the Linux kernel declares modules like this. The only odd one in this "API" is `new`, which takes a different number of arguments depending on the dimension. Strings are also workable. Even JSON or comments would work, but maybe not as nice.

**Comment by Athas** [comment]
I'm not sure what form this information should take at the C level.  For example, a list of entry point function pointers is not very useful, since they would all have to be variadic functions returning `int`.  Is that really useful?  Would it be more useful to have their names as strings (and information about their number of arguments)?

For the type information, would it be sufficient to have a list of all array types (each with rank and base type), and a list of all opaque types?    The functions available can be inferred from that.

**Comment by pepijndevos** [comment]
I'm internally divided on this subject. For Python, strings are great, as you can just `ffi.new(string)` the types and `getattr(lib, string)` the functions. So in the case of Python, a list of strings of entry points an data types is sufficient and even convenient. Your suggestion seems reasonable.

But I can imagine wanting to write a FFI in a more static language. The ultimate in discoverability is, can I write a C program that gets the first entry point, generates data in the correct shape, and calls it?

Using an imaginary API that uses arrays as arguments, one could write something like the following (guaranteed to not work and be incomplete and a bad idea):

```
typedef struct {
  int rank;
  char[2048] type; // gotta have space for the opaques
  char[32] itemtype; // NULL = opaque
  int (*free)(futhark_context*, void*)
  void* (*new)(futhark_context*, void*, int*) // takes array now
  int* (*shape)(futhark_context*, void*)
  int (*values)(futhark_context*, void*, void*)
} dtype;

typedef struct {
  char[256] name;
  int (*fun)(futhark_context*, void*, void*); // arrays of in/output
  int outc;
  int inc;
  dtype* outputs;
  dtype* inputs;
} entrypoint;

dtype[] types = {
  {2, "f32_id", "float",
    &futhark_free_f32_2d, 
    &futhark_new_f32_2d, 
    &futhark_shape_f32_2d, 
    &futhark_values_f32_2d},
  {0, "shtesnhtoeshntshnt", NULL,
    &futhark_free_ftusoetnsoetns, 
    NULL, 
    NULL, 
    NULL},
  {0, "float", NULL, NULL, NULL, NULL, NULL}
  NULL};

entrypoint[] entrypoints = {
  {"futhark_magic", &futhark_magic, 2, 2,
    {types[0], types[2]}
    {types[1], types[0]}
  },
  NULL};

// Usage

entrypoint e = entrypoints[0];
printf("calling %s", e.name);
void[e.outc]* out;
void[e.inc]* in;
for (i=0; i<e.inc; i++) {
  if (e.inputs[i].new != NULL) {
    int[e.inputs[i].rank] shape;
    // loop over rank to make array of junk or whatevs
    in[i] = e.outputs[i].new(ctx, data, shape);
  } else {
    in[i] = 4; // chosen by fair dice roll
  }
}
```

**Comment by Athas** [comment]
The API operates entirely in terms of pointers (except the error return codes), so the specific types are less important.  Representing functions as strings is fine when using `dlopen()`.  I can easily change the array creation functions to take the dimensions as an array of integers, if you think it will make a meaningful difference.

I rather like the interface you're sketching there, although I'd probably define `dtype` as a union to distinguish between primitives, arrays, and opaques.  I will probably take a swing at implementing it (although likely not for a week or two).

**Comment by pepijndevos** [comment]
The `// loop over rank to make array of junk or whatevs` is where it all falls down though. To fully close the gap in C, you'd have to manually dispatch on itemtype (maybe should be an enum). Adding a field with `sizeof(float)` may help allocating a bucket of bytes of the right size, which is the closest you can get I think.

Having `void*` arrays as input and output arguments goes a bit far maybe. It's an interesting thought experiment how generic your C code can be, but in practice it'll be annoying to work with for non-ffi users. And, usually you don't have any business calling a function unless you know what to pass it already.

I do think shape as an array is reasonable, because it makes a nice uniform API for all types.

Regardless of this metadata, I think it's good practice to mark input arguments `const`, which already solves some fragile hacks, I hope.

**Comment by Athas** [comment]
I have made the following two changes:

* Input parameters are now `const`.

* All entry point functions are prefixed with `futhark_entry_`.

All the other information can be inferred.  For constructing type-safe wrappers for higher-level languages, something like [SWIG](http://www.swig.org/) should be usable.  Can I close this issue now?

**Comment by pepijndevos** [comment]
I'll update my FFI wrapper later this week, and report back if I find any large stumbling blocks, or else close the issue. Thanks!

**Comment by pepijndevos** [comment]
It seems numeric types are not marked `const` yet. But more importantly... CFFI seems to just ignore the `const` modifier, so that part did not turn out as I hoped.

Maybe the interwebs know: https://stackoverflow.com/questions/51161844/how-can-i-get-the-const-modifier-of-a-cffi-function-in-python

The entry points worked out nicely though, allowing me to create wrapper functions once during initialization and offload a bit of the work away from runtime.

My code for detecting output arguments for now still looks like this
```python
if arg_t.kind == 'pointer' and (arg_t.item.kind == 'primitive' or arg_t.item.kind == 'pointer')
```

**Comment by Athas** [comment]
Do you have access to the parameter names?  Otherwise it wouldn't be a big deal to put the information there directly; it's just nicer if it can be inferred robustly somehow.

**Comment by pepijndevos** [comment]
I've not found a way yet. The docstring contains the following, so without name and without const.
```
int futhark_entry_test3(struct futhark_context *, struct futhark_i32_1d * *, struct futhark_i32_1d *);
```
I've been using `ffi.typeof` to get the type information, which is the same. No names, no const.

**Comment by pepijndevos** [comment]
Well, the hack works. So I'll close this, as I don't see an easy, low-maintenance, low-effort way to improve this.
