### ISSUE TITLE
Permit lifted abstract types in module types

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#577]
@melsman, I will need your help to design this.

Should we just define a `type^` spec to to along with `type`, or what do you think?  We can probably get away with just using the same rules as for lifted type parameters.

**Comment by melsman** [comment]
The eqtype specs in SML works in the different direction. There, type-specs
("type t") specify all possible types and eqtype-specs specify a subset of
all types (chose that support equality). In Futhark, we somehow have the
opposite situation with lifted types being the general concept - I somehow
think that we should change the type specs to be "type t", meaning that t
can stand for any type, and "btype t", meaning that t can stand only for
base types (i.e., non-function types). Also notice that when an abstract
type is referenced in an array context (e.g., []t), it should then be
required that t is specified as a btype...

man. 2. jul. 2018 kl. 23.07 skrev Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
I think whatever syntax we pick for abstract module types should resemble the syntax for type parameters.  There is no point in inconsistency (and certainly none in making them backwards).

> Also notice that when an abstract type is referenced in an array context (e.g., []t), it should then be required that t is specified as a btype...

Yes, of course.  The same rules as for type parameters.

**Comment by Athas** [comment]
I talked a bit with Martin and came up with something resembling a design.

A module type may contain a *lifted* type spec (none of us like the name) of the form:

```
type ^t
```

Otherwise it is said to be non-lifted.  When matching a module with a module type, a type `t` only matches a *non-lifted* type spec if `t` is guaranteed to be of order zero.  Any type may match a lifted abstract type.  The reverse rule applies to type parameters on the type spec.  E.g:

```
{ type t = i32 -> i32 } : { type ^t } -- ok
{ type t = i32 -> i32 } : {type t } -- not ok
{ type t 'a = a } : { type t 'a } -- ok
{ type t 'a = a } : { type t '^a } -- not ok
```

There are undoubtedly interesting implementation and soundness issues we have not given due consideration.

**Comment by Athas** [comment]
Here's a tricky case:

```
module m = \(p: {type ^a}) -> ({ type t = p.a } : { type t })
```

This should not pass the type checker, because there is no guarantee that `p.a` is a zeroth-order type.  However, this requires a little more information than our module ascription function has available at the moment; specifically it needs to look up the abstract type `p.a` to figure out its liftedness.
