### ISSUE TITLE
Adding a package manager

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#592]
It is time to add a package manager.  [I wrote some notes about it](https://futhark-lang.org/blog/2018-07-20-the-future-futhark-package-manager.html).

**Comment by melsman** [comment]
What exact problems should be solved by having a package manager? Here are
some questions:

What if baz requires foo@v1.0.0? Should "futhark-pkg get" also download
nested dependencies?

Do you envision that Futhark compilers should make calls to "futhark-pkg
get" if an imported module is not present in the appropriate directory?

Should it be possible to specify which compiler version a package version
depends on?

Do you envision a stack-like tool on top of futhark-pkg that takes care of
also downloading a proper version of Futhark.

søn. 22. jul. 2018 kl. 21.23 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> What if baz requires foo@v1.0.0? Should "futhark-pkg get" also download
> nested dependencies?

Yes.

> Do you envision that Futhark compilers should make calls to "futhark-pkg
> get" if an imported module is not present in the appropriate directory?

No.

> Should it be possible to specify which compiler version a package version
> depends on?

No.

> Do you envision a stack-like tool on top of futhark-pkg that takes care of
> also downloading a proper version of Futhark.

No.

The package manager will not be a build tool, and will not have any
particular integration with the compiler.  This may change in the
future.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I'm keeping my work on a separate branch: https://github.com/diku-dk/futhark/tree/futhark-pkg

It is shaping up really well.

**Comment by Athas** [comment]
The package manager is essentially functional now.  I have made two deviations from my original plans:

* Package paths now include the major version (e.g. `github.com/athas/foo@v2`), and it is possible for a package to depend on multiple major versions of the same package (because they are technically *different* packages with distinct package paths).  This turned out to be much cleaner to reason about, and has nice properties for the dependency solver.
* When creating a package, the local directory structure must mirror exactly the package path.  E.g. when defining a package called `github.com/athas/foo@v2`, you will need a Git repository that contains a directory `lib/github.com/athas/foo@v2`.  It took me a while to accept this, but it really is necessary.  Many languages (e.g. Java) have similar restrictions, so at least it is not unheard of.

**Comment by Athas** [comment]
There is [documentation here](http://futhark.readthedocs.io/en/latest/package-management.html).  I think the design has become quite nice and understandable.  Once I have written some larger packages (I'm thinking Sobol and maybe the least-squares optimiser) and some integration tests, I will close this issue.

**Comment by Athas** [comment]
I have written a useful package: https://github.com/Athas/distance

Seems to work nicely, although it did uncover a bug where it would delete the user's code on `futhark-pkg sync`.  Guess that's why I try it out on myself first.

**Comment by athas** [comment]
I have set up an automated system ([futhark-docbot](https://github.com/diku-dk/futhark-docbot)) that automatically publishes documentation of known packages, browseable [here](https://futhark-lang.org/pkgs) (yet unstyled). Once it gets a little more polish, it should enable discoverability of Futhark packages.  It's beginning to look like a real programming language!

**Comment by athas** [comment]
I have extracted the least-squares solver from the Heston benchmark and constructed an [lmdif](https://github.com/diku-dk/lmdif) package.

**Comment by kfl** [comment]
A tiny bit of bike-shedding: For Futhark I don't think that it's a good idea to follow `vgo`'s design in when it comes to version selection. That is, taking the minimum (oldest) version possible.

Instead, think it should pick tge maximum (newest) version possible.

I'd argue that picking the maximum version is the most intuitive, based on my experience with various sane(-ish) package managers `vgo`, `cargo` and `npm` in particular. However, I also recognise that it is a qualitative judgement.

Still, for a young eco-system as Futhark I think it makes more sense to default to the newest version.

**Comment by athas** [comment]
This is a part of the `dep` solver: [solver.go](https://github.com/golang/dep/blob/master/gps/solver.go).  It is 1381 lines of code.  The entire `gps` directory is over 20000 source lines of code, and that is just the solver algorithm, not all of `dep`.  I don't know if this implementation is correct.  I know that I will *never know* whether it is correct.

This is the entirety of the `futhark-pkg` solver: [Solve.hs](https://github.com/diku-dk/futhark/blob/master/src/Futhark/Pkg/Solve.hs).  It is 121 lines of code.  I don't know whether it's correct.  It probably is not.  But I am confident that eventually it *will* be correct, and that I will know it is correct.

It would not be hard to modify `futhark-pkg` to use maximum versions (probably even less code, since there is then no solving at all).  However, maximum versions are only practical if packages can specify upper version bounds, and then you are back in SAT.

If no version number is given, `futhark-pkg add` will always add the newest version of the package.  Similarly, `futhark-pgk upgrade` will upgrade all version bounds to the most recent.  On the happy path, this is equivalent to a package manager that picks maximum versions.  On the unhappy path, if someone has broken compatibility, this will give you a bad build (and you can then roll back the upgrade).  This is similar to a conventional package manager.  The only difference is that in a conventional package manager, you can insert upper bounds to avoid the bad version.  But that is not what you want - if compatibility is broken, then that version should simply be marked invalid, and a new (compatible) version released.  It is more important that you quickly figure out that this is the case, than you spend time fighting with a complex package manager.

Speaking of complexity, Futhark cannot possibly sustain a complex package manager.  It is a [https://futhark-lang.org/blog/2018-06-18-designing-a-programming-language-for-the-desert.html](desert language), and its package manager must survive in the same climate (only it's harsher still, since people find it fun to learn languages, but *nobody finds it fun to learn package managers*).

The only non-erroneous situation where a SAT-solving package manager is superior to a minimum-version package manager is the exotic case where you have many packages with both upper and lower bound, *and a solution even exists* that allows them all to coexist.

And in the very worst case, if all my thoughts on this are wrong, then the package solver is completely orthogonal to the rest of `futhark-pkg`,  and it would be perfectly feasible to replace it with a 20k SLOC SAT-solving heuristic monstrosity that nobody knows whether is correct.  I'd rather try the simple thing first.

**Comment by kfl** [comment]
There are two issues:

* The version selection feature

* The difficulty of implementation

That Go is a poor choice for implementing a SAT solver, shouldn't be used as an argument for which features that a futhark package manager should have. A reasonably performant SAT-solver shouldn't take 20k SLOC to implement. The relevant (back-tracking based) [solver for Rust's cargo](https://github.com/rust-lang/cargo/blob/8b5aec111926d1d03d2da32dd494e0fff073f870/src/cargo/core/resolver/mod.rs) is ~1000 lines of heavily commented code. I would dare to say that it's only slightly harder to comprehend than your `Solve.hs`.
