### ISSUE TITLE
Bug in incremental flattening

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#593]
This program makes incremental flattening produce an invalid program:

```
let main (xss: [][]i32) (ys: []i32) =
  let (as, bs) = unzip2 (map2 (\xs y -> (y, i32.sum (map (+y) xs))) xss ys)
  in (i32.sum as, bs)
```

The problem is the identity-mapped parameter `y`.  This is a reduced case of something that occurs in the Heston benchmark.

**Comment by RasmusWL** [comment]
Is this a bug in my code then? :blush: -- what do mean by _incremental flattening_?

**Comment by Athas** [comment]
No, this has nothing to do with you.  Incremental flattening is the new dataset-sensitive code kernel extraction.
