### ISSUE TITLE
'copy' should work on non-arrays

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#604]
Consider this program:

```
let swap 't (i: i32) (j: i32) (xs: *[]t) =
  let xs_i = xs[i]
  let xs[i] = xs[j]
  let xs[j] = xs_i
  in xs

let main (xs: *[][]i32) = swap 0 1 xs
```

The `swap` function is actually ill-typed, because the `xs_i` value aliases the `xs` array, and hence it cannot be used after `xs` is consumed.  The normal solution would be to use `copy`, but that won't fly, as we defined `copy` to take an array as argument!  Clearly it should take any type as argument.  Specifically, we currently have this type for `copy`:

```
val copy [n] 't: [n]t -> [n]t
```

And I want this one:

```
val copy 't: t -> *t
```

(There is probably a free theorem stating that this can only be the `copy` function.)  However, this type is not well-formed, as we only permit the uniqueness asterisk immediately preceding an array type.  I don't think that restriction is necessary for soundness, so we might as well remove it.

**Comment by melsman** [comment]
Should the copy function maintain sharing or should all memory addresses in
the result value be unique?

søn. 5. aug. 2018 kl. 00.22 skrev Troels Henriksen <notifications@github.com

**Comment by athas** [comment]
There should be no sharing.
