### ISSUE TITLE
Request for "In-Place Updates" code sample clarification

### ISSUE THREAD

**Issue by vsenko** [diku-dk/futhark#607]
The "Parallel Programming in Futhark" book contains an ["In-Place Updates" section](https://futhark-book.readthedocs.io/en/latest/language.html#in-place-updates) and there is a code sample:

    let fib (n: i32): []i32 =
      -- Create "empty" array.
      let arr = replicate n 0
      -- Fill array with Fibonacci numbers.
      in loop (arr) for i < n-2 do
           let arr[i+2] = arr[i] + arr[i+1]
           in arr

As far as I understand, the next couple of paragraphs imply that the code sample is not efficient enough because it does not utilize "In-Place Updates" feature.

Could someone, please, provide a code sample of a similar efficient implementation that will utilize the "In-Place Updates" feature.

**Comment by athas** [comment]
No, that one is efficient (`let arr[i] = ...` is exactly an in-place update).  I will clarify in the text that this is what is happening.

**Comment by athas** [comment]
Is it clearer now?

**Comment by vsenko** [comment]
Yes, thank you!
