### ISSUE TITLE
blur.fut example doesn't compile

### ISSUE THREAD

**Issue by flokli** [diku-dk/futhark#609]
I wanted to toy around with futhark (0.6.2) and wanted to run the `blur.fut` example from the website:

```
wget https://futhark-lang.org/static/blur.fut
futhark-pyopencl --lib blur.fut
```

However, it seems to not work:

```
Error at blur.fut:12:8-18:18:
Couldn't match expected type `(a0, b1)' with actual type `*[](f32, f32, f32)'.
When matching type
  [](a0, b1)
with
  *[][](f32, f32, f32)
```

Other examples inside the repo seem to work.

**Comment by athas** [comment]
How embarrassing.  Fixed.

This has happened more than once.  I have now enabled CI for the website so we can catch these quickly in the future.  (Although I expect the language will not break compatibility so much in the future.)
