### ISSUE TITLE
Found futhark-test output confusing

### ISSUE THREAD

**Issue by einar-io** [diku-dk/futhark#630]
At least two students found

    futhark-test lssp.fut
    0 failed, 1 passed, 3 cases run.

confusing, because the numbers do not add up.

Suggestion: Add clarifying units

    futhark-test lssp.fut
    0 test file(s) failed, 1 test file(s) passed, 3 test cases run.

**Comment by athas** [comment]
@zfnmxt I think you were the last one to go near this.  Fancy having another go?

**Comment by zfnmxt** [comment]
Sure. I've actually already fixed it; just never got around to polishing it.

**Comment by zfnmxt** [comment]
Fixed by 8d88228.
