### ISSUE TITLE
Rust language backend?

### ISSUE THREAD

**Issue by novacrazy** [diku-dk/futhark#640]
Would it be reasonable to add a Rust target/runtime? With or without OpenCL.

I'm calling OpenCL Futhark routines from Rust, and there is some issues and redundancy in the C runtime and the Rust language, such as panics (which in Rust can automatically includes backtraces), data structures and threading/locks, among other things.

In fact, the `exit` part of `panic` in the C runtime can actively cause issues and corrupt data, such as killing other running threads, abandoning non-flushed open files, network activity, etc.. I'm currently working on a way to automatically replace the C code before compile and replace the Futhark runtime `panic` function with something that triggers a Rust callback and kills the thread, rather than exiting the application, which combined with running Futhark FFI calls in another sacrificial thread could allow the Rust program to be aware of errors and continue running.

However, that is a huge pain, obviously. Safety may not be a concern for C or Python, but it is in Rust.

The [OCL crate](https://github.com/cogciprocate/ocl/) provides varying OpenCL abstraction levels to build upon.

Rust also natively supports tuples, arrays of tuples, tuples of arrays, and so forth, so opaque data types may not be necessary.

**Comment by novacrazy** [comment]
I'm willing to do what I can to assist. Haskell isn't my thing, but I can help write the Rust library boilerplate for `futhark/rts/`.

**Comment by athas** [comment]
I don't think a Rust backend *as such* is a good idea.  Backends do carry a maintenance cost, and ossify the compiler, so we want to have them only where they give a lot of return on investment (.NET/Java because they cover a lot of languages), or are strategically important (Python, to demonstrate accessibility).  The problem is that the C runtime contains a lot of subtle stuff (like the memory allocator) that are not much fun to rewrite.  As the runtime inevitably grows more sophisticated (for example, when we start doing multi-device concurrency), I really don't want to change the code for many different backends.  The inevitable consequence would likely be that other backends will fall behind and become buggy.

Instead, I think we should try to make it more convenient to access the C backend from other languages, and Rust seems like a good candidate!  Specifically:

* We should stop using `panic()`, except in extreme cases (and I'm not even sure what those should be).  It is definitely the intention that the C backend produces code that is a friendly neighbour, but we are not there yet.  It used to be even worse than it currently is, so at least we are making progress.

* We should write a tool that can automatically construct an idiomatic Rust wrapper for calling the generated C code.  The inspiration is [futhark-pycffi](https://github.com/pepijndevos/futhark-pycffi), which does exactly this for Python (and makes me wonder whether the Python backend should even be kept around forever).

(A completely different option might be to primarily have a Rust backend rather than C, but the world is not ready.)

**Comment by novacrazy** [comment]
It's interesting you bring up the memory allocator, which appears to be a (relatively) simple freelist/arena style allocator with some workarounds built-in. Recently I've been doing some research into Vulkan/DX12 memory models, and I/we may be able to port parts of the [gfx-memory](https://github.com/gfx-rs/gfx-memory) allocator for use with OpenCL, since they appear to work very similarly. I can try to work on that as a separate crate that integrates with the `ocl` crate I mentioned above. Then integrating that into the runtime would be as simple as a `Cargo.toml` entry.

Furthermore, perhaps create a modular memory allocation system like:

```c
typedef int32_t error_code;

struct futhark_allocation_function_ptrs {
    error_code (*malloc)(uint64_t, void**);
    error_code (*free)(void*);
    // ...
};
```

and a similar modular interface for the OpenCL allocator, allowing the user to provide their own implementation:

```c
struct futhark_opencl_allocator_function_ptrs {
    // user-defined code, creates a new allocator and gives back a pointer to it
    error_code (*new_allocator)(void** /*allocator_ptr*/);
    // user-defined code, deletes an allocator previously created with `new_allocator`
    error_code (*delete_allocator)(void* /*allocator*/);
    error_code (*alloc_block)(void* /*allocator*/, /*...*/);
    error_code (*free_block)(void* /*allocator*/, /*...*/);
    // ...
};
```

Furthermore, a similar system to the OpenCL allocator may be used for locks/mutexes:

```c
struct futhark_thread_function_ptrs {
    error_code (*alloc_lock)(void** /*lock_ptr*/);
    error_code (*free_lock)(void* /*lock*/);
    error_code (*acquire_lock)(void* /*lock*/);
    error_code (*release_lock)(void* /*lock*/);
    // ...
};
```

with default implementations for both using regular C stuff:

```c
struct futhark_allocation_function_ptrs* futhark_default_allocation_function_ptrs();
struct futhark_opencl_allocator_function_ptrs* futhark_default_opencl_allocator_function_ptrs();
struct futhark_thread_function_ptrs* futhark_default_thread_function_ptrs();
```

There really isn't a downside to this style of API when used with FFI. A proper error system is a *Must*, though. Return codes work well enough for C and I can wrap those easily in Rust, just no `panic`/`exit`.

I was also considering the idea of passing callback functions as error or trace callbacks to public API methods, but to get any real use out of that would require either global state (on either side of the API), or an *extra* context argument for those callbacks. So yeah, not very eloquent in C, but I'm still tossing the idea out there. Perhaps global (to the Futhark context) callbacks for errors or tracing would be a good idea, though.

```c
typedef void (*futhark_callback)(error_code, const char*);

error_code futhark_context_assign_error_callback(struct futhark_context* ctx, void* cb_context, futhark_callback cb);
error_code futhark_context_assign_trace_callback(struct futhark_context* ctx, void* cb_context, futhark_callback cb);
```

I assume the host code would keep track of that `cb_context` pointer long enough to outlive the Futhark usage.

Overall, I believe such an API would also work well with Go and other C-ABI-ish languages.

The only unsolved problem is the opaque types, as Rust and other modern languages do have tuples or some equivalent. However, that's probably not *too* much of an issue in practice, but it is still an issue.

Also, my function pointer syntax is a little rusty (no pun intended), so I apologize for any mistakes.

**Comment by novacrazy** [comment]
Custom CPU allocation routines: Some languages have their own allocators. For example, Rust is usually built with jemalloc, which is incompatible with the `malloc` of the system C ABI. Providing that to Futhark would probably reduce headaches somewhere along the line or improve performance by not using two allocators in the same process.

Custom OpenCL allocator: More or less a "Why not?". Most users will probably be fine with the default. It was just a suggestion and doesn't have to be a priority until needed for something weird.

Another point that I was trying to account for in the error system was thread-safety, although that brings up a good point for the whole runtime. How well would the current implementation work if called at the same time from another thread? Or a dozen other threads, all queuing up work? Work to the same or different kernels/entry points?

**Comment by athas** [comment]
The entry points are thread safe (via internal locking), but the error state probably is not.  I don't think it's a good idea to use the same Futhark context from multiple threads, but it will not break Futhark itself - it just might be confusing.  Assigning a single worker thread responsible for managing the Futhark context might be a better design (but I have zero experience using Futhark in a multithreaded program, so I may be wrong).

**Comment by novacrazy** [comment]
This is kind of going off-track a little from Rust, but it would be great for Futhark to support concurrent kernel evaluation on hardware that supports it, using multiple command queues. That's my primary intent with multi-threaded invocations. On modern hardware it's legitimately hard to just keep the cores *fed* properly with data, so having multiple queues running concurrently (again, on supporting hardware), could result in greater performance all around. The less time the GPU is idle the better.

A great example is a path-tracing engine (what I intend to use Futhark for). Many tiles could use the same entry point, but concurrently. It would be more scalable to determine the number of tiles dynamically from the CPU as the rendering goes on, rather than requiring that info up-front if I were to split the tiles from Futhark code itself. If the GPU is being underutilized, extra tile invocation threads could be spawned.

**Comment by athas** [comment]
I agree!  That would be pretty cool and is definitely on the (long term) plan.  I suspect the best way to make it work is to be able to create "sub-contexts" that each have their own command queue, but permit you to pass data between them (so they need to use the same memory allocation and profiling guts, for example).  Conceptually and technically it is not difficult; all it takes is a small bit of hacking.

Generally, I'm OK with adding complexity if it is needed - for example, the pluggable allocation mechanisms you mentioned above.  However, while complexity can always be added, it is hard to remove once in place.  Hence, I prefer to have concrete usage cases in mind (as in, a specific program that *right now* could be improved), as this also helps us getting the design right in the first place.

**Comment by athas** [comment]
The best solution is to construct a range of Rust macros that make it easy to call the C code generated by the Futhark compiler.  This is WIP here: https://github.com/Erk-/rust-futhark
