### ISSUE TITLE
Why do we use <- in 'with' expressions?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#650]
An in-place update in Futhark is written `a with [i] <- x`.  A record update is written `a with f <- x`.  A module type refinement is written `mt with a = b`.  My question is this: should we switch to `=` everywhere?  It would create a nice symmetry.  We would still keep `<-` around as a deprecated synonym for a while.

**Comment by nqpz** [comment]
I think I might find it confusing to have `=` used for in-place updates and record updates. For example, would this code be valid?
```
let a' = a with [i] = x
...
```
Having two equality signs on the same line just feels a bit weird. Maybe I would skim this and read the `with` as a second `let` and think I'm doing two assignments, the second one setting the value of some strange variable `[i]`.

I actually like the visual difference between `=` and `<-`. If symmetry is an issue, maybe it would be better to change the use of `with` in module type refinements. It could be `where` instead?

**Comment by athas** [comment]
Writing `let a' = a with [i] = x` would be possible but pointless, as we have the recommended shorthand form `let a[i] = x` (which *also* does not use `<-`!).  Those kinds of issues should be solved with linters, I think.  It's currently possible to write
```
let a' = let a[i] = x in a
```
but that has not caused us to redesign the syntax.

**Comment by nqpz** [comment]
Right. I think my point still slightly stands with record updates, but I don't think stand-alone let expressions like
```
let a' = a with f = x
```
would occur very often, so I don't really see a problem with the proposal from the user point of view.

**Comment by athas** [comment]
I guess it would also be a valid solution to change module type refinement to use `<-`.

**Comment by athas** [comment]
[*Futhark Presents!*](https://github.com/diku-dk/futhark-presents) is the program that currently makes the most use of record updates.  Here's a sample function:

```
entry start_nbody [h][w] (s: state [h][w]): state [h][w] =
  let background = most_common_colour s.image
  let bodies = bodies_from_image background s.image
  in s with bodies <- bodies
       with background <- background
       with offset <- length s.bodies / 2
       with reverting <- false
```

And here is how it would look with equal signs instead:

```

entry start_nbody [h][w] (s: state [h][w]): state [h][w] =
  let background = most_common_colour s.image
  let bodies = bodies_from_image background s.image
  in s with bodies = bodies
       with background = background
       with offset = length s.bodies / 2
       with reverting = false
```

**Comment by athas** [comment]
After discussion with Martin and Cosmin we have decided to move to `=`.
