### ISSUE TITLE
Should we stop embedding the pre-parsed/typechecked prelude?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#653]
There is a module in the Futhark compiler, `Language.Futhark.Futlib.Builtin`, which takes a lot of time to compile.  The reason is that this module uses Template Haskell to parse and type-check the implicit prelude (which is fast) and then constructs an AST representing the result which is embedded into the compiler binary (this is slow).  The result is that we save about 100ms when compiling a Futhark program, because we don't have to re-typecheck the prelude.

The heavy weight of this module has two main disadvantages:

* Waiting for it to compile is annoying.  However, when working on the frontend, the `builtinBasis` can be set to `emptyBasis`, which disables the embedding.
* Our CI tools (in particularly Travis) sometimes crash when compiling this module, because it takes more memory than the virtual machines are allotted.

This second point is the most dire to me.  In particular, it means I am reluctant to add more functions to the prelude (or more annotations/information to our AST), because it will increase memory usage and compile times yet more.  It seems wrong to me that these concerns should drive language and compiler evolution.

Most real use of the compiler does not benefit from this facility, as the rest of the compilation takes orders of magnitude longer anyway.  The main beneficiary is interactive type checking in Emacs (but maybe 100ms doesn't matter here anyway), as well as type-checking many programs at once.  For example, without this facility, type-checking our entire test suite takes about 24s on my machine, compared to 2s with the embedded prelude.

Thoughts?

**Comment by melsman** [comment]
Are there alternatives? How about serialising the ast to disk or to a byte
stream, which can then be deserialised when futhark is invoked?

fre. 19. okt. 2018 kl. 15.23 skrev Troels Henriksen <
notifications@github.com>:

**Comment by athas** [comment]
* I tried that (with an admittedly imperfect serialisation scheme).  It's as slow as just re-typechecking.
* It would make installing Futhark more complex (now there are data files and search paths to worry about), which is unacceptable.

**Comment by melsman** [comment]
You are probably right. Alternatively, one could have a more complex
two-level compilation scheme (for the compiler itself). The first generated
compiler would have an empty prelude, but it can be used to generate a
Haskell source file with an embedded serialised ast. This file can then be
included in the second-level compilation... But if deserialisation is slow
then...

fre. 19. okt. 2018 kl. 19.12 skrev Troels Henriksen <
notifications@github.com>:

**Comment by athas** [comment]
That is essentially what Template Haskell does.  The thing that takes time is to pass the resulting gigantic AST through GHCs ordinary compiler passes.  If we embed it as a serialised byte string, then it takes a lot of time to deserialise it at run-time.

**Comment by athas** [comment]
It is very unlikely that we will find a non-heroic way of speeding up the current embedding.  I've already spent quite a while thinking about it, and trying out alternatives.  The only thing that remains is to speed up GHC itself, but that is definitely in the category of "heroic".

Thus, the only thing that remains for us to do is to decide whether the current cost in complexity, compiler build time, and CI fragility offsets the small decrease in compilation time.

**Comment by melsman** [comment]
Simplicity in the approach has a high weight, I would argue...

søn. 21. okt. 2018 kl. 08.54 skrev Troels Henriksen <
notifications@github.com>:
