### ISSUE TITLE
tabulate_3d error

### ISSUE THREAD

**Issue by tpolakovic** [diku-dk/futhark#659]
The tabulate_3d function currently doesn't work because of a typo in

` map1 (f >-> tabulate_2d m n) (iota n)`

which should be instead:

` map1 (f >-> tabulate_2d m n) (iota o)`

so that the output matches `*[n][m][o]a`.

**Comment by athas** [comment]
I think the `o` should be the second argument to `tabulate_2d`.  Do you want to make a pull request, or should I fix it?

**Comment by tpolakovic** [comment]
You're right. I'll do the pull request.

**Comment by athas** [comment]
Fixed in #660.
