### ISSUE TITLE
Module type does not fit actual type

### ISSUE THREAD

**Issue by TheBlackKoala** [diku-dk/futhark#696]
module intEq : MonoidEq = {type t = i32
                           let add = (+)
                           let mul= (*)
                           let eq = (i32.==)
                           let ne= 0 }

let a = [[intEq.ne,2i32],[3,4]]

Couldn't match expected type `intEq.t' with actual type `i32'.
When matching type
  intEq.t
with
  i32

Am i doing some horribly wrong with module types or is there a bug somewhere?
I can see that intEq.t is exactly i32 but yet it will not match?
I am using the type monoidEq to define things in a nice manner in a sparse matrix library and i can't seem to be allowed to test it because of an error that looks exactly like this.

**Comment by athas** [comment]
*You* may be able to see that `intEq.t` is `i32`, but the compiler cannot, since you are hiding the module with the module type `MonoidEq`, which has an opaque type `t`.  Try this instead:

```
module intEq : (MonoidEq with t = i32) = ...
```

**Comment by TheBlackKoala** [comment]
That worked! Thank you!
