### ISSUE TITLE
The type checker should not permit type abbreviations with unused size parameters

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#699]
We don't permit this in function definitions anyway, and it would have prevented the initial issues in #698.

Maybe I can talk with @melsman about permitting some kind of singleton values eventually, because it might be useful to encode some sizes in types that do not strictly correspond to array sizes.

**Comment by melsman** [comment]
yes - I presume such "phantom size variables" can sometimes be useful...

**Comment by athas** [comment]
I realised that we already support this via arrays of unit values: `[n]()`.  Since these contain no information apart from their size, the compiler will/should compile them to an integer.
