### ISSUE TITLE
Some piping can make the compiler throw errors.

### ISSUE THREAD

**Issue by TheBlackKoala** [diku-dk/futhark#701]
this works:
  let b = unflatten 3 2 <| iota 6
  let mat = coord.fromDense b

this does not:
  let b = coord.fromDense <| unflatten 3 2 <| iota 6

with the error:
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
After internalisation:
In function lifted_0_f_5539
A unique tuple element of return value of function lifted_0_f_5539 is aliased to some other tuple component.

**Comment by athas** [comment]
Can I see your full program? Which version of the compiler are you using?

**Comment by TheBlackKoala** [comment]
Futhark 0.7.0
git: c1e4bf2 (Wed Sep 12 21:42:12 2018 +0200)

module spCoordSized(M: MonoidEq) = {
  type matrix [x][y]= { Inds : [](i32,i32), Vals : []M.t, _x : [x]u8 , _y : [y]u8}

let fromList ((x,y) : (i32,i32)) (l : []((i32,i32),M.t)) : matrix [x][y]=
  let (inds,vals) = unzip l
  in {Inds = inds, Vals = vals, _x=(replicate x (u8.i32 0)), _y=(replicate y (u8.i32 0))}

--General solution
let fromDense [m][n] (dense : [m][n]M.t) =
  let inds = flatten <| map (\i -> map (\j -> (i,j)) (iota n)) <| iota m
  let denseInds = zip inds <| flatten dense
  let listVals = filter (\(_,v) -> ! (M.eq v M.zero)) denseInds
  in fromList (m,n) listVals

let empty (x:i32) (y:i32) : matrix[x][y]= {Inds = [], Vals = [], _x=(replicate x (u8.i32 0)), _y=(replicate y (u8.i32 0))}

-- in another file:
module intEq : (MonoidEq with t=i32) = {type t = i32
                                        let add = (+)
                                        let mul= (*)
                                        let eq = (i32.==)
                                        let zero= 0i32 }

--module coord = spCoord(intEq)
module coord = spCoordSized(intEq)

let test15 =
  let a = coord.empty 3 2
  let mat = coord.fromDense <| unflatten 3 2 <| iota 6
  --let b = unflatten 3 2 <| iota 6
  --let mat = coord.fromDense b

The part of the code that is commented out works but the current throws an error in the compiler (used in some other actions but that is what fizes it).
If you want i can upload the whole files but that should be all that is actually used.

**Comment by athas** [comment]
You are using an old compiler.  I believe this bug is fixed at least in HEAD.

**Comment by TheBlackKoala** [comment]
Yep it works in the lastest version.
