### ISSUE TITLE
Compiler vs interpreter - "array" sizes

### ISSUE THREAD

**Issue by TheBlackKoala** [diku-dk/futhark#702]
When running the following program with futarki i get an error (as expected) but when i compile and run the program i get a result.
The test file (coord is the module being used with i32)
let test19 =
  let a = unflatten 3 2 <| iota 6
  let mat = coord.fromDense a
  let b = coord.empty 3 2
  let res = coord.mul b b

from the module:
let mul [x][y][z] (mat0 : matrix[x][y]) (mat1 : matrix[y][z]) : matrix[x][z] =
  mulFun mat0 mat1 (M.mul) (M.add)

type matrix [x][y]= { Inds : [](i32,i32), Vals : []M.t, _x : [x]u8 , _y : [y]u8}

and yes i replicate 0 to the _x and _y arrays to indicate the sizes which the interpreter catches but the compiler seems oblivious to.

**Comment by athas** [comment]
This is not terribly unexpected.  The compiler is at liberty to aggressively remove dead code, including these dummy arrays, which may turn nonterminating programs into terminating ones.

**Comment by athas** [comment]
This kind of stuff has been resolved with the adoption of size types.
