### ISSUE TITLE
Bug in reduce_by_index with tuples on OpenCL

### ISSUE THREAD

**Issue by nqpz** [diku-dk/futhark#715]
This program fails to validate on the OpenCL backend:
```
-- Test reduce_by_index on array of tuples where part of the tuple is not
-- recomputed.
-- ==
-- input {
--   5
--   [1, 3, 1]
--   [4, 1, 3]
--   [5, 6, 7]
-- }
-- output {
--   [-1, 3, -1, 1, -1]
--   [-1, 7, -1, 6, -1]
-- }

-- This is 'min', but with auxiliary information carried along with the result.
let operator ((x0, y0): (i32, i32)) ((x1, y1): (i32, i32)): (i32, i32) =
  if x0 != -1 && (x1 == -1 || x0 < x1)
  then (x0, y0)
  else (x1, y1)

let main [n] (m: i32) (is: [n]i32) (vs0: [n]i32) (vs1: [n]i32): ([m]i32, [m]i32) =
  let ne = (-1, -1)
  let dest = replicate m ne
  let vs = zip vs0 vs1
  in unzip (reduce_by_index dest operator ne is vs)
```

It should compute:
```
[-1, 3, -1, 1, -1]
[-1, 7, -1, 6, -1]
```
But it computes:
```
[-1, 7, -1, 6, -1]
[-1, 7, -1, 6, -1]
```
I think this is a pretty silly use of `reduce_by_index`, but the C backend handles it correctly.

I can probably look into it (I just have to figure out where to look).

**Comment by athas** [comment]
The atomic update is implemented [here](https://github.com/diku-dk/futhark/blob/master/src/Futhark/CodeGen/ImpGen/Kernels/Base.hs#L299) (you want the general case).  The bug might however also be in some of the supporting kernels for the `reduce_by_index` (notably a segmented reduction at the end).  Hard to say!  Fun to debug.  Enjoy!

**Comment by athas** [comment]
The atomic update itself looks good to me (but do verify), so it must be something that happens later.

**Comment by athas** [comment]
Simpler program that reproduces the problem; it has nothing to do with `reduce_by_index` specifically:

```
let main (b: bool) (n: i32) =
  let (xs, ys) = if b
                 then (replicate n 0, replicate n 0)
                 else (replicate n 1, replicate n 1)
  let xs[0] = 42
  in (xs, ys)
```

Rather, it is an error in CSE.
