### ISSUE TITLE
Name clash between #define macro and a double variable in a generated OpenCL code

### ISSUE THREAD

**Issue by wojciechpawlak** [diku-dk/futhark#722]
We use the latest code version of futhark (commit: 3891fb66d7a54ce717d7ffa5ddd03b5f2d00c124) as of 8th March 12:00:
`Futhark 0.10.0
git: ac88c9f (Sun Feb 10 22:03:44 2019 +0100)`

We compile https://github.com/HIPERFIT/lsmc/blob/master/opt/lsmc_f64.fut with 
`futhark opencl .\lsmc_f64.fut -o .\bin\lsmc_f64-opencl.exe` without errors.

However, we experience a following error when we run it with `echo 0 1 80.0 90.0 0.4167 0.05 0.3 100000 100 | .\bin\lsmc_f64-opencl.exe -pNVIDIA`:

` OpenCL call
  build_opencl_program(prog, device_option.device, compile_opts)
failed with error code -2 (Device not available)
`

We dump the out put to the attached file [error.txt](https://github.com/diku-dk/futhark/files/2945577/error.txt).

See the errors at lines 260-293:
```
<kernel>:11558:12: error: expected parameter declarator
    double x_69432;
           ^
<kernel>:1083:26: note: expanded from macro 'x_69432'
#define x_69432 (squot32(8 + (sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup
_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622))))) - 1), sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624),
 squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622)))))))
                         ^
<kernel>:11558:12: error: expected ')'
<kernel>:1083:26: note: expanded from macro 'x_69432'
#define x_69432 (squot32(8 + (sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup
_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622))))) - 1), sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624),
 squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622)))))))
                         ^
<kernel>:11558:12: note: to match this '('
<kernel>:1083:25: note: expanded from macro 'x_69432'
#define x_69432 (squot32(8 + (sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup
_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622))))) - 1), sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624),
 squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622)))))))
                        ^
<kernel>:11558:12: error: conflicting types for 'squot32'
    double x_69432;
           ^
<kernel>:1083:18: note: expanded from macro 'x_69432'
#define x_69432 (squot32(8 + (sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup
_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622))))) - 1), sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624),
 squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622)))))))
                 ^
<kernel>:161:23: note: previous definition is here
static inline int32_t squot32(int32_t x, int32_t y)
                      ^
<kernel>:11563:17: error: expression is not assignable
        x_69432 = *(__global double *) &res_mem_69859[ltid_61019 * 8];
        ~~~~~~~ ^
```

We run the `.\bin\lsmc_f64-opencl.exe --dump-opencl ker.cl` and attach the dumped OpenCL kernel file [ker.txt](https://github.com/diku-dk/futhark/files/2945656/ker.txt).

There is a macro definition at line 1083:
`
#define x_69432 (squot32(8 + (sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622))))) - 1), sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622)))))))
`
which is used then as an int in line 14553:
`
    for (int32_t i_54678 = 0; i_54678 < x_69432; i_54678++) {
`

and a variable declaration at line 11558:
`
double x_69432;
`
which is used then as a double in lines 11563, 11564 and 11567.

We remove the error by changing the name of the macro definition and its use, to any other non-conflicting name, and loading the manually-edited OpenCL kernel file:
`echo 0 1 80.0 90.0 0.4167 0.05 0.3 100000 100 | .\bin\lsmc_f64-opencl.exe -pNVIDIA --load-opencl ker.cl`

**Comment by athas** [comment]
I cannot reproduce this.  Are you using a modified lsmc_f64.fut?

**Comment by athas** [comment]
I also cannot find the line you reference in the `ker.txt` you have linked.  Line 1083 of `ker.txt` contains the following:

```
#define x_6943333 (squot32(8 + (sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622))))) - 1), sext_i64_i32(sext_i32_i64(test_examplezigroup_sizze_54622) * smax64(1, smin64(sext_i32_i64(test_examplezimax_num_groups_54624), squot64(8 + (sext_i32_i64(test_examplezigroup_sizze_54622) - 1), sext_i32_i64(test_examplezigroup_sizze_54622)))))))
```
