### ISSUE TITLE
-D causing Floating point exception (core dumped) ... probably division by zero

### ISSUE THREAD

**Issue by coancea** [diku-dk/futhark#725]
Program "lsmc_f64" compiled with

FUTHARK_INCREMENTAL_FLATTENING=1 futhark opencl lsmc_f64.fut

and run with:

echo "0i32 1i32 80.0f64 90.0f64 0.4167f64 0.05f64 0.3f64 1000000i32 100i32" | ./lsmc_f64 --default-tile-size=16  --size=main.suff_intra_par_12=50000000  --size=main.suff_intra_par_14=50000000  --size=main.suff_intra_par_20=50000000  --size=main.suff_intra_par_22=50000000  --size=main.suff_intra_par_24=50000000  --size=main.suff_intra_par_27=50000000  --size=main.suff_intra_par_4=50000000  --size=main.suff_intra_par_8=50000000  --size=main.suff_outer_par_11=50000000  --size=main.suff_outer_par_13=50000000  --size=main.suff_outer_par_19=50000000  --size=main.suff_outer_par_21=50000000  --size=main.suff_outer_par_23=50000000  --size=main.suff_outer_par_26=50000000  --size=main.suff_outer_par_3=50000000  --size=main.suff_outer_par_7=50000000  --size=main.suff_outer_redomap_25=50000000 -D

**Comment by athas** [comment]
I think this is fixed now.
