### ISSUE TITLE
Change header guards to not use #pragma once

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#747]
#744 added header guards using `#pragma once`, which was great.  A small snag is that when we construct command line executables, we manually insert the generated header in the .c file, `#pragma once` and all.  Some C compilers warn about `#pragma once` outside of headers.  There are plenty of other spurious warnings issued for the code we generate, so fixing this is not urgent, but it would be nice to do so.

A good fix would involve plumbing through the name of the original `.fut` file from the CLI frontends to the code generator, and use that to generate a normal `#ifdef`/`#define` header guard.  We might eventually also consider using this to generate the public names, rather than just prefixing them all with `futhark_`, but that requires more thought.

**Comment by mxxo** [comment]
I think this bad boy is ready 😎
