### ISSUE TITLE
List comprehensions

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#749]
I want to translate some list comprehensions from Haskell into Futhark, but I'm not sure if Futhark has this feature yet:

`z = [i*2|i<-[1,2,3]]`

 In Haskell, it is also possible to define list comprehensions with multiple generators:

`z = [i*j*2|i<-[1,2,3],j<-[4,5,6]]`

Would it be possible to translate these list comprehensions into Futhark [using maps or for-loops](https://futhark-lang.org/examples.html)?

**Comment by athas** [comment]
Yes, that's a `map`:

```
map (\i -> i*2) [1,2,3]
```

**Comment by kfl** [comment]
And your second example can be written as (warning untested futhark code ahead):

```
let z = flatten (map (\i -> map (\j -> i*j*2) [4,5,6]) [1,2,3])
```

Things get a bit more dicey if you include guards, then you need a more general `flatten`.
