### ISSUE TITLE
Removing support for size parameters in non-function patterns

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#751]
Currently we permit code like the following:

```
let main [n] (xs: [n]i32): i32 =
  let [num_even] xs': [num_even]i32 = filter even xs
  in num_even
```

This binds `num_even` at the same point that `xs'` is bound.  We do not have a single non-test program that uses this.  Similarly, this is permitted:

```
loop [n] (i, ys : [n]i32) = (0, xs) while length n > 1 do
...
```

Again, this is not really used anywhere.

I don't think this feature has any soundness problems, but it is annoying to implement.  The current implementation likely has several problems, and it's only the obscurity of the feature that means they haven't cropped up.  Without this, you'd have to use `length` instead.  There's also a few invariants that you'd not be able to express directly, like requiring that some existentially-sized array is square:

```
let [n] (xs: [n][n]i32) = ...
```

This would now have to be the somewhat more awkward:

```
let xs = ...
let n = length xs
let (xs: [n][n]i32) = xs
```

(Alternatively, you can define a utility function:

```
let must_be_square [n] 't (xs: [n][n]t): [n][n]t = xs
```
)

However, let me emphasize that we've had this feature for years, and *nobody has ever done this that I know of*.

I'd like to remove this feature to simplify the language.  Firstly to make it smaller and easy to keep in the programmer's head.  Secondly, because with the work I'm doing on statically checking size annotations, these size binders become even more awkward to implement.

**Comment by athas** [comment]
@melsman, what do you think?

**Comment by melsman** [comment]
I've only used size-bindings for universal quantification in function
bindings... I would say that you should just get rid of the other forms, if
no one uses them...

ons. 15. maj 2019 kl. 21.23 skrev Troels Henriksen <notifications@github.com

**Comment by coancea** [comment]
I do not have a strong opinion on this, but I know that Wojciech is using
it quite aggressively in his Futhark endeavors , and he found it quite 
useful
for debugging purposes.

Cosmin
