### ISSUE TITLE
Removing size parameters from lambdas

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#752]
This issue is motivated similarly to #751, but is a bit more thorny, so I'd appreciate input.  In particular from @melsman and @coancea, but all are welcome to join the fun.

In Futhark, we currently support size parameters (but not arbitrary type parameters) in lambda abstractions:

```
\[n] (xs: [n]i32) : [n]i32 -> ...
```

This is a fairly obscure feature, but it *is* used - specifically, in conjunction with `stream_map` and `stream_red`.  To quote OptionPricing.fut:

```
  let sobol_mat = stream_map (\[chunk] (ns: [chunk]i32): [chunk][sobvctsz]f32  ->
                                sobolChunk dir_vs (unsafe ns[0]) chunk)
                             (iota num_mc_it)
```

This works fine as long as size annotations are just glorified assertions rather than really tying into the type system.  However, it starts causing trouble when we want to verify them in the type checker, because these lambda-bound size parameters are really a form of higher-rank polymorphism, while Futhark's type system is generally built around rank-1 polymorphism.  In principle, the type of `stream_map` should be something like:

```
val stream_map [n] 'a 'b : (forall c . [c]a -> [c]b) -> [n]a -> b
```

But this is not valid Futhark syntax - we have no `forall`, and I'm not particularly inclined to introduce it.  The current type is:

```
val stream_map [n] 'a 'b : ([]a -> []b) -> [n]a -> [n]b
```

So the fact that the functional argument must be size-preserving is not visible.  Introducing higher-rank polymorphism just to encode this requirement seems a bit like overkill.  I'd much rather give it a type like this:

```
val stream_map [n] 'a 'b : (f : (c: i32) -> [c]a -> [b]b) -> [n]a -> [n]b
```

The difference is that the chunk size is now passed as an explicit named parameter `c`, and the chunk array then has a type dependent on `c`.  This also reflects that size parameters are really more of a notational convenience - the *real* underlying calculus uses explicit parameters (and originally, this was also the design that Cosmin was pushing IIRC).  (This type is not valid at the moment, but it is comparatively *much* simpler to support than full higher-ranked polymorphism for lambdas.)

The stream in OptionPricing would then have to be written as:

```
  let sobol_mat = stream_map (\(chunk: i32) (ns: [chunk]i32): [chunk][sobvctsz]f32  ->
                                sobolChunk dir_vs (unsafe ns[0]) chunk)
                             (iota num_mc_it)
```

There is not really any loss in clarity.  The only loss is that you cannot pass in a "normal" named function that uses size parameters.  Considering how rare streams are in Futhark programs, I feel this is a minor drawback.

**Comment by wojciechpawlak** [comment]
In reference to #751, that is closed now and to follow up on Cosmin's reply https://github.com/diku-dk/futhark/issues/751#issuecomment-493045135:

I am not quite sure if I use the exact functionality, that you mention here.  See lines 674-678 in https://github.com/HIPERFIT/lsmc/blob/1cece14de4714fc1aae200579d5f50e646a15b7b/nvidia/lsmc_nvidia.fut or below.

```
let do_run
    (num_timesteps: i32)
    (num_paths: i32)
...
let paths : [num_paths][num_timesteps]real = generate_paths samplesT S0 dt r sigma computeGbmNormalStep
let Sst_2d : [num_timesteps][num_paths]real = transpose paths
let cashflows : [num_paths]real = map payoff Sst_2d[num_timestepsm1] -- the last column contains the discounted payoffs
  
let (svds : [num_timesteps][SLOTS]real, all_out_of_the_moneys : [num_timesteps]i32) = prepare_svd Sst_2d is_in_the_money min_in_the_money CHUNK
...
```

It turned quite helpful during debugging to check exact array sizes and shapes returned by various functions. The compiler did not catch these as sizes are known first at runtime and it ended up in runtime errors. Thanks to these type and size checks I could trace (still at runtime) where exactly the size is wrong in the nested functions.

**Comment by athas** [comment]
I've kept array size annotations - those are simple, useful, and have an obvious behaviour.  The feature I removed in #751 is so obscure that I'm not sure Cosmin even knew about it, so he was confused about what I was talking about.

**Comment by athas** [comment]
I talked to Cosmin about this, and he is fine with removing size parameters from lambdas.  Unless someone (@melsman?) comes up with a very good argument against, I'm going to remove them soon.

**Comment by athas** [comment]
Removed in 03a625840ba062bd81f4443844cd8b73c2d22922.
