### ISSUE TITLE
CUDA-specific compiler option "--nvrtc-option" is not recognised

### ISSUE THREAD

**Issue by wojciechpawlak** [diku-dk/futhark#753]
While compiling with cuda backend, I wanted to experiment and change the default gpu-architecture the CUDA code is compiled to by passing `--nvrtc-option "--gpu-architecture=compute_70"`. It is, though, not recognized by the latest nightly build of futhark as of today.

```
$ futhark cuda -o ./bin/lsmc_nvidia-cuda.exe lsmc_nvidia.fut --nvrtc-option "--gpu-architecture=compute_70"
Junk argument: lsmc_nvidia.fut
Unrecognised argument: --nvrtc-option
Unrecognised argument: --gpu-architecture=compute_70
Usage: futhark cuda options... program
...
```

I found that this argument to `futhark cuda` should be available in the documentation, see here:
https://futhark.readthedocs.io/en/latest/usage.html#cuda-specific-options

**Comment by athas** [comment]
It is a run-time option, not compile-time.  You have to pass it to the executable generated by `futhark cuda`.

**Comment by wojciechpawlak** [comment]
> It is a run-time option, not compile-time. You have to pass it to the executable generated by `futhark cuda`.

Right! Thanks for this note. I was also puzzled at first, because nvrtc is used. This is CUDA's runtime compilation engine. Let's close the issue.
