### ISSUE TITLE
Switch/case statements

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#756]
In many functional programming languages, it's possible to define "case" statements:
```
case x of
    0 => 0
    | 1 => 1
    | _ => x+1
```
I searched Futhark's documentation, but didn't find any examples of "switch" or "case" statements. Does Futhark already have this feature, or will it be implemented in a future version of the language?

**Comment by athas** [comment]
It exist in an undocumented form, with this syntax:

```
match x
case 0 -> 0
case 1 -> 1
case _ -> x+1
```

It's undocumented because it's tied to @zfnmxt's in-progress work on sum types.  However, I doubt the syntax will change, so feel free to use it.
