### ISSUE TITLE
futhark on jetson nano --stack setup fails

### ISSUE THREAD

**Issue by jxxcarlson** [diku-dk/futhark#764]
Trying to set up futhark on jetson nano.   I posted my comments on 

   https://github.com/diku-dk/futhark/issues/729

further stuff, if any, will be posted here.  

Briefly, there is the below when I do `stack ghci` of `stack build`:

```
Error: Plan construction failed.

Warning: Build failed, but trying to launch GHCi anyway
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: futhark

Warning: Didn't find expected autogen file: /home/jxxcarlson/futhark/.stack-work/dist/aarch64-linux/Cabal-2.4.0.1/build/autogen/cabal_macros.h

Warning: Didn't find expected autogen file: /home/jxxcarlson/futhark/.stack-work/dist/aarch64-linux/Cabal-2.4.0.1/build/futhark/autogen/cabal_macros.h
GHCi, version 8.6.2: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package aeson
    (use -v for more information)
```

And curioulsy enough ghc-8.6.2 is installed:

```
ls ~/.stack/programs/aarch64-linux/ghc-8.6.2/bin/
ghc  ghc-8.6.2  ghci  ghci-8.6.2  ghc-pkg  ghc-pkg-8.6.2  haddock  haddock-ghc-8.6.2  hp2ps  hpc  hsc2hs  runghc  runghc-8.6.2  runhaskell
```

As a final check, inside the `futhark` directory, I did

```
jxxcarlson@jetson:~/futhark$ stack ghc hello.hs
Linking hello ...
```

Weird, all.

**Comment by athas** [comment]
Interesting!  I have a Jeston Nano that has been gathering dust on my desk for the past month, and this looks like a good excuse to try it out.  I'll take a shot and see what I can find out.

**Comment by athas** [comment]
Looks like NVIDIA decided to not include a microSD-card, so I won't be able to look at this before Monday.  Until then, my advice is to look for general advice on using `stack` on ARM64.  Futhark is totally unremarkable as a Haskell program, so it should not be more difficult to use with `stack` than anything else is.

**Comment by jxxcarlson** [comment]
Yes, it is entirely an nVIDIA problem.  There are many sloppy things is their release of the OS for the Jetson Nano, most of which I have solved.  No hurry!

**Comment by athas** [comment]
I have my Jetson Nano running now.  Where did you find an aarch64 version of Stack?

**Comment by athas** [comment]
Oh, the installer works.  Cool.

**Comment by athas** [comment]
How did you manage to get Stack to install GHC 8.6.2, though?  Mine says it knows nothing about the platform and asks me to install manually.

**Comment by jxxcarlson** [comment]
I believe that I put the line `resolver: ghc-8.6.2` in `stack.yaml` and then did `stack setup`.  If I have time, I will get another sd card and do it all from the start, keeping notes.

**Comment by athas** [comment]
Well, that's definitely why plan construction fails.  The plain `ghc` resolvers don't have any packages, and the user gets the pleasure of manually adding a list of everything to `stack.yaml`.

I'm building myself now, but I'm surprised at how rickety it is.  I thought GHC on ARM would be a lot smoother.  I'll write a guide if I get it working.

(Alternatively, since the Futhark compiler outputs a single portable `.c` file, it might be easier to compile the Futhark program on another machine, move the `.c` file to the Jetson, and then compile to a binary.)

**Comment by jxxcarlson** [comment]
I will give that a tr,  Thanks!

**Comment by jxxcarlson** [comment]
Shall I close this? Not a futhark issue.  NVIDIA has indeed been pretty sloppy with this. Hope it will get better.

**Comment by athas** [comment]
Yes.  I think I'll still write a blog post about this mess.

**Comment by jxxcarlson** [comment]
A blog post would be most welcome!

**Comment by athas** [comment]
[Blog post](https://futhark-lang.org/blog/2019-06-22-futhark-on-nvidia-jetson.html)
