### ISSUE TITLE
Defining "subclasses" of modules

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#768]
I'm trying to define a module that "inherits" functions from another module, but I'm not sure if this is possible yet.

It seems that it isn't possible to define functions in a module type, so this example won't compile:
```
module type Int32Adder = {
   val add: t -> t -> t
   let add a b = a+b
}

module AddInt32 : Int32Adder = {
	let sub a b = a-b
}
```

It seems that modules can't be "ascribed" to other modules, so this won't work either:
```
module Int32Adder = {
    let add a b = a+b
}

module AddInt32 : Int32Adder = {
    let sub a b = a-b
}
```

It's possible to copy functions from another module, but this requires each function to be specified individually:

```
module Int32Adder = {
    let add a b = a+b
}
module AddInt32 = {
    let sub a b = a-b
    let add a b = Int32Adder.add a b
}
```

Is there any other way to define a module that "inherits" functions from another module?

**Comment by athas** [comment]
You can `open` the old module inside the new:

```
module Int32Adder = {
    let add a b = a+b
}
module AddInt32 = {
    let sub a b = a-b
    open Int32Adder
}
```

It's not really inheritance, but it makes straightforward to extend other modules (although things are more tricky when abstract types are involved).  For module types there is `include`, which serves a similar purpose.

**Comment by jarble** [comment]
I [searched the documentation](https://futhark.readthedocs.io/en/latest/search.html?q=%22module+type%22+%22include%22), but it doesn't describe the `include` syntax for module types. I suppose it might be written like this, but I'm not sure if this syntax is correct:
```
module type Int32Adder = {
  val add: t -> t -> t
}

module type AddInt32 = {
  val sub: t -> t -> t
  include Int32Adder
}
```
Is it possible for module types to "inherit" from other module types in this way?

**Comment by athas** [comment]
That syntax is correct.  The module system is not very well documented unfortunately, but [the grammar for module type expressions](https://futhark.readthedocs.io/en/latest/language-reference.html#module-type-expressions) does mention `include`.

**Comment by jarble** [comment]
I'm writing a compiler that translates TypeScript classes and interfaces into Futhark, so this syntax could be very useful.
