### ISSUE TITLE
Sequential C# backend missing FutharkConfigLoadTuning

### ISSUE THREAD

**Issue by alexander-myltsev** [diku-dk/futhark#772]
I'm compiling with:
```
futhark csharp fact.fut
csc failed with code 1:
Microsoft (R) Visual C# Compiler version 2.8.2.62916 (2ad4aabc)
Copyright (C) Microsoft Corporation. All rights reserved.

fact.cs(42,53): error CS0103: The name 'FutharkConfigLoadTuning' does not exist in the current context
fact.cs(42,81): error CS0103: The name 'Cfg' does not exist in the current context
```

How to fix this? Should I copy files with `FutharkConfigLoadTuning` and `Cfg` class from somewhere?

**Comment by athas** [comment]
No, this looks like a simple oversight - the sequential C# backend (like the sequential Python backend) is not exercised properly in our CI setup for some reason, so it appears it was broken at one point.  Should be an easy fix.
