### ISSUE TITLE
Using generics with trigonometric functions

### ISSUE THREAD

**Issue by jarble** [diku-dk/futhark#775]
I'm trying to use some trigonometric functions in a generic function, but this example won't compile:

`let sin_cos 't (a:t) = (math.sin a) + (math.cos a)`

Does Futhark's documentation explain how to import and use these built-in trigonometric functions?

**Comment by athas** [comment]
You can't do it that way - Futhark does not have operator overloading, except for a small handful of built-in operators (`+` etc).  You need to either use a concrete type:

```
let sin_cos (a:f32) = f32.sin a + f32.cos a
```

Or define the function inside a parametric module, which you then instantiate multiple times with whatever types you want:

```
module m (P: real) = {
  let sin_cos (a: P.t) = P.(sin a + cos a)
}

module m_f32 = m f32
module m_f64 = m_f64
```
