### ISSUE TITLE
Build Issue with latest Stack - Thread blocked in an STM transaction

### ISSUE THREAD

**Issue by mratsim** [diku-dk/futhark#781]
Just so you know, futhark is also affected by https://github.com/haskell/haskell-ide-engine/issues/1328.

system: Archlinux with stack 1.9.3.1. stack install crashes with `Thread blocked in an STM transaction` after downloading `ghc-tinfo6-8.2.2`

**Comment by athas** [comment]
What a weird issue.  But is there anything Futhark can do about it?  I guess you could always build with `cabal` instead.

**Comment by mratsim** [comment]
Yeah, I don't think you can do anything except providing alternative build instructions that don't use stack.

It's probably widespread, and Archlinux is updates packages pretty fast so hopeefully there will be an upstream solution sooner rather than later. I'll close then.

**Comment by athas** [comment]
[Looks like the solution is to use Stack 2.1.1 or newer.](https://github.com/haskell/haskell-ide-engine/pull/1338)

**Comment by mratsim** [comment]
I confirm that it solved my issue.
