### ISSUE TITLE
Nim and Futhark

### ISSUE THREAD

**Issue by develooper1994** [diku-dk/futhark#789]
There is a language like futhark. It is nim. Nim language also generate optimized c/c++ code. but nim aims to general purpose language. Futhark generates parallel executable code. These languages can cooparate with each others in my opinion

**Comment by athas** [comment]
I don't see how Nim and Futhark are particularly similar, except their choice of code generation target ([which is a big family](https://github.com/dbohdan/compilers-targeting-c)).  Futhark is accessible to any language that can call C, which Nim can easily do.  What other form of cooperation could exist?

**Comment by mratsim** [comment]
same question and answer on Nim side, linked thread https://github.com/nim-lang/Nim/issues/11843
