### ISSUE TITLE
Dependency required: tinfo

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#804]
Compiling Futhark on a relatively fresh Ubuntu 18.04 install I got the following error towards the end:

```
/usr/bin/ld.gold: error: cannot find -ltinfo
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
Completed 121 action(s). 

--  While building package futhark-0.13.0 using:
      /home/munksgaard/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.0.0_ghc-8.8.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.0.0 build lib:futhark exe:futhark --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

It was easily fixed by installing the tinfo library (`sudo apt install libtinfo-dev`), but it perhaps it should be mentioned in the installation documentation. I assume that `build-essential` is also required, but I already had that installed.

**Comment by athas** [comment]
Yes.  Although that package is called different things on different systems (but is fairly common, so I think most people already have it installed for other reasons).  I think there's also a requirement on libgmp.  Ought to be documented.
