### ISSUE TITLE
Is it possible to suppress emitting primitive atomic operations?

### ISSUE THREAD

**Issue by mt-caret** [diku-dk/futhark#806]
For the past few days, I've been trying to compile the OpenCL kernels that Futhark emits with Xilinx's SDAccel compiler. The main problem I'm encountering so far is the lack of support for atomic operations (e.g. `atomic_add`) on SDAccel's part (see https://forums.xilinx.com/t5/SDAccel/atomic-inc-needed/m-p/859822#M2115, https://forums.xilinx.com/t5/SDAccel/XOCC-fails-with-atomic-functions/td-p/857170). Is it possible in principle to compile Futhark to kernels that don't rely on these operations, and if so, how would one go about it?

**Comment by athas** [comment]
Most programs don't need atomics (IIRC, it's only if you use `reduce_by_index`), so in principle I could make the code generator not emit the stubs unless they are necessary.  We already do something similar for handling `double`, which some GPUs do not support.  Would that be good enough?

**Comment by mt-caret** [comment]
Thanks for the quick response!

> Most programs don't need atomics (IIRC, it's only if you use reduce_by_index)

Hmm, that's odd. I tried compiling this basic example (taken from <https://futhark-lang.org/examples/fact.html>) and I got [this kernel](https://gist.github.com/mt-caret/4c71b16f731ac75a352db0fd2ce5341c) containing `atomic_add`s.

```
let fact (n: u64): u64 = reduce (*) 1 (1...n)

let main (n: u64): u64 = fact n
```

**Comment by athas** [comment]
Oh yeah, we started using them for a few other things. Sadly, it's not viable to change that. I doubt those reduction kernels would run well on an FPGA anyway.

**Comment by mt-caret** [comment]
Ah, that's unfortunate.
