### ISSUE TITLE
Linux dependency for opencl backends

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#807]
As far as I can tell, the futhark user guide doesn't mention the fact that the user will need to install an opencl backend in order to successfully run `futhark opencl` on linux. For instance, on my Intel pc (that doesn't actually have a GPU) running Ubuntu 18.04, I need to install `beignet-dev` in order to successfully compile the dotprod.fut example from the second chapter of futhark book using `futhark opencl dotprod.fut`.

On a related note, it seems like Intel has released another library to replace beignet on newer CPUs (https://github.com/intel/compute-runtime)

**Comment by athas** [comment]
I think this requirement is fairly obvious, but I guess I can document it.
