### ISSUE TITLE
ICE: Cannot parse values from 'input block contents'

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#808]
```
$ cat foo.fut
-- futhark test cannot handle (-1) in the input
-- ==
-- entry: input_is_minus_one
-- input { (-1) }
-- output { 0 }
entry input_is_minus_one (x: i32): i32 =
  0

$ futhark test foo.fut
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
foo.fut:5:2:
  |
5 |  output { 0 }
  |  ^
Cannot parse values from 'input block contents'

CallStack (from HasCallStack):
  error, called at src/Futhark/Test.hs:398:17 in futhark-0.13.0-4S1TmArFtlq737rsEmwsMo:Futhark.Test
```

The reverse (output being `(-1)`) also fails.

**Comment by Munksgaard** [comment]
Besides being an ICE, the error message is confusing, as the error is caused by the `input` line.

**Comment by athas** [comment]
The input blocks do not use term syntax, they use value syntax.  In particular, parentheses are not allowed.

You're right about the error locations being out of whack.  You're welcome to take a look at [the test spec parser](https://github.com/diku-dk/futhark/blob/master/src/Futhark/Test.hs) and see if you can figure out what's going on.  It's written with standard Megaparsec.
