### ISSUE TITLE
ICE when benchmarking commented out function

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#819]
I encountered an ICE when benchmarking code with a commented out function. I managed to simplify it to this minimal example: (the blank line is important)
```
-- ==

-- ==
--entry:0
--0
```
When trying to run `futhark bench`, the following error occurs:
```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
seam-carve.fut:5:1:
  |
5 | <empty line>
  | ^
unexpected end of input
expecting "input" or white space

CallStack (from HasCallStack):
  error, called at src/Futhark/Test.hs:412:29 in futhark-0.14.0-LNpKAxefDnf9AJXzkAlGqr:Futhark.Test
```
I am running the nightly version:
```
Futhark 0.14.0
git: 098083d (Fri Dec 6 12:45:11 2019 +0100)
```

**Comment by athas** [comment]
Thanks for the report.  The test stanza parser is still a bit too temperamental when it comes to parse errors, I see.
