### ISSUE TITLE
Could not compile to cuda, fresh docker container

### ISSUE THREAD

**Issue by benjaminhmtan** [diku-dk/futhark#820]
Tried to compile one of the samples to cuda and this error came up. On a fresh docker container, I installed cuda toolkit 10.2 after building futhark.

Thanks in advance!

```
futhark cuda lss.fut
gcc failed with code 1:
lss.c:8:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
```

**Comment by athas** [comment]
Does plain `nvcc` or `gcc` that includes `cuda.h` work?  Futhark doesn't take any special care to feed the C compiler any include flags, so you need to set up any necessary environment variables yourself.  On many systems, the CUDA headers (and other libraries) end up in `/usr/local/cuda`, which is not on the default include path.  I find that it's often necessary to set something like:

```
LIBRARY_PATH=/usr/local/cuda/lib64:
LD_LIBRARY_PATH=/usr/local/cuda/lib64/
CPATH=/usr/local/cuda/include
```

**Comment by benjaminhmtan** [comment]
The include paths were not in CPATH. I can compile with cuda now. Thanks!

**Comment by athas** [comment]
I have [added mention of this to the documentation now](https://futhark.readthedocs.io/en/latest/man/futhark-cuda.html#environment).  In a bit of an obscure place, but I'm not sure where else to put it.
