### ISSUE TITLE
Should we move to 0-indexed tuples?

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#821]
In Futhark, components of a tuple can be accessed using the same dot notation as with records: foo.1, foo.2. In contrast to arrays, which are 0-indexed, tuple components are numbered from 1. While Dijkstra argues convincingly and correctly for the benefits of 0-indexing, he does so in the context of ranges, which does not apply to tuple indexing. In Futhark, there is no way to perform arithmetic on a tuple index. They must always be constants, because they are really just names that look like numbers. Thus the reasoning behind the inconsistency: 0-indexing is used for arrays because it has benefits when doing index calculations, while 1-indexing is used for tuples because it is the more familiar ordering outside of programming.

Yet, I cannot help but wonder whether we got this one wrong. How many programmers are going to accidentally access the wrong field in a tuple, because they are used to thinking 0-indexed? We are not even particularly consistent: Futhark numbers OpenCL devices starting from 0 (because that’s what OpenCL itself does), and our test runner also numbers test cases from 0.  Actually, *everything* except tuples is 0-indexed.

The cost of changing this is obvious: every single Futhark program that uses dot notation for tuples must be modified.  While conversion is mechanical and can be automated with a simple script, there is still a cost.  I'm not sure how widespread tuple indexing is in the wild.  Our benchmark suite contains 110 uses out of about 17000 lines of code (also counting dependencies), but all of these were added by me.

@henglein, any advice?

**Comment by RasmusWL** [comment]
One idea for mitigate making this change (besides statically telling you your index is out of bounds): For the foreseeable future, the compiler could show a warning about 0-indexing that must be acknowledged if it encounters any tuple indexing in a file (and keep track of which files warning has been acknowledged for).

I've seen the pattern for acknowledgement in some emacs packages, that made breaking changes in how you configure them. When upgraded, it would show the warning for how to adapt your config, until you actively acknowledge that you have done so.

Personally, I feel 0-indexing sounds like a good path forward :+1:

**Comment by Oblomov** [comment]
Oh yeah,

    OPTION TUPLE BASE 0

**Comment by athas** [comment]
Well, Cosmin *does* call Futhark a "functional FORTRAN"...

Maybe `IMPLICIT NONE` could be used for disabling type inference.

**Comment by athas** [comment]
@munksgaard says 0-indexed tuples are better, so I will make this change for the next release.

Rust does it that way, too.

**Comment by athas** [comment]
An incomplete but useful script for doing the conversion automatically:

```
#!/bin/sh
#
# Automatically turn tuple-indexing from being 1-based to 0-based.  I
# am lazy, so this only works for tuples with less than 10 components
# (it doesn't recognise .10 or above).
#
# On macOS, replace 'sed' with 'gsed'.
#
# This script does not handle 'with' expressions or explicit record
# statements, but I don't think those are frequently used with tuples.

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file or directory>"
    exit 1
fi

find $1 -name \*.fut -exec sed -E \
     -e 's/([^0-9.])\.1/\1.0/g' \
     -e 's/([^0-9.])\.2/\1.1/g' \
     -e 's/([^0-9.])\.3/\1.2/g' \
     -e 's/([^0-9.])\.4/\1.3/g' \
     -e 's/([^0-9.])\.5/\1.4/g' \
     -e 's/([^0-9.])\.6/\1.5/g' \
     -e 's/([^0-9.])\.7/\1.6/g' \
     -e 's/([^0-9.])\.8/\1.7/g' \
     -e 's/([^0-9.])\.9/\1.8/g' \
     -i {} \;
```
