### ISSUE TITLE
ICE during reference dataset generation

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#822]
Code:
```
-- ==
-- entry: a
-- input { 0 0 } auto output
entry a (b: u8, c: u8) = 0
```
Error:
```
$ futhark bench ice.fut 
Compiling ice.fut...
futhark: user error (Reference dataset generation failed with exit code 1 and stderr:
./ice: Cannot read input #0 of type (u8, u8)
)
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
thread blocked indefinitely in an MVar operation
```
Version:
```
Futhark 0.14.0
git: 0abf01a (Mon Dec 30 23:44:48 2019 +0100)
```
-----
I also get a similar error with:
```
-- ==
-- entry: a
-- input { 0 } auto output
entry a (b: u8) = 0
```
which is:
```
./ice: Error when reading input #0 of type u8 (errno: Success).
```
It's probably the same bug, but the error messages are slightly different, so I thought I'd mention it.

**Comment by athas** [comment]
The error message is still not particularly illuminating.  For the first program, the main issue is that entry points should not accept tuples, because the input block syntax will not allow them.

For the second program, the issue is that the input block contents are of type `i32`, not `u8`.
