### ISSUE TITLE
Tighten package bounds on Hackage

### ISSUE THREAD

**Issue by vmchale** [diku-dk/futhark#824]
Various bounds are failing on the CI matrix, viz. https://matrix.hackage.haskell.org/#/package/futhark/0.13.2/ghc-8.8.1@1576494226

I think a constraint `megaparsec < 8.0.0` would fix the latest release at least :)

Thanks!

**Comment by athas** [comment]
Are you using the `futhark` package as a dependency?  I don't think I can recommend that - I don't put any effort into keeping the internal API stable.  If you're just compiling it, doesn't the [cabal.project.freeze](https://github.com/diku-dk/futhark/blob/master/cabal.project.freeze) take care of pinning the dependencies?

**Comment by athas** [comment]
Anyway, I added a revision for the `megaparsec` bound.
