### ISSUE TITLE
Typed numeric literals in random input test cases

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#825]
Trying to test the following code with `futhark test test.fut`:
```
-- ==
-- entry: a
-- random input { 0u8 } auto output
entry a (i: u8) = 0
```
results in this error:
```
Reference dataset generation failed with exit code 1 and stderr:
./test: binary-input: Expected scalar of type u8 but got scalar of type i32.
```
Looking in `data`, I see two files: `0i32.in` and `u8.in`. It seems like `0u8` is parsed as `0 u8` (an `i32` zero and a random `u8`) instead of a `u8` zero.

Version:
```
Futhark 0.14.0
git: 5006ca6 (Tue Jan 7 00:01:48 2020 +0100)
```

**Comment by athas** [comment]
Typed literals aren't supposed to work in random blocks, but I guess there is not really any good reason why.  I can add support for that.
