### ISSUE TITLE
futhark autotune doesn't allow files without main

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#830]
It seems like `futhark autotune` doesn't allow working on files that don't have a `main` function:

```futhark
-- ==
-- entry: foo
-- compiled random input { [10]f32 }
-- auto output
entry foo (xs: []f32): []f32 = xs
```

```
$ futhark autotune foo.fut
Compiling foo.fut...
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
user error (Program does not have a 'main' entry point with datasets.)
```

Given that we can run the program just fine (with `--entry-point`) and that both `futhark bench` and `futhark test` work, this seems like a strange restriction.

**Comment by athas** [comment]
I don't think this restriction is there for a good reason; I just never bothered to finish the implementation.
