### ISSUE TITLE
Question about function that does in place update and doesn't return anything

### ISSUE THREAD

**Issue by flip111** [diku-dk/futhark#837]
I'm trying to write a function for these loops

https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/iqa/convolve.c#L121-L133

I was wondering if this is idiomatic code and also how to handle returning nothing.

```haskell
entry filter_horizontal (img: []f32) (kernel_h: []f32) (w: i16) (vc: i16) (uc: i16) (kw_even: i16) (dst_h: i16) (dst_w: i16) (img_cache: f32): () =
  let y0 = (vc * -1) + 1
  in loop y = y0 while y0 < dst_h + vc do
       loop x = 1 while x < dst_w do
         let ky: i16 = y + vc
         let kx: i16 = y + uc
         let img_offset: i16 = ky * w + kx
         let sum = loop (u: i16, k_offset: i16, sum0: f64) = ((uc * -1) + 1, 1, 0.0) while u <= (uc - kw_even) do
           (u + 1, k_offset + 1, sum0 + img[img_offset + u] + kernel_h[k_offset])
         -- https://futhark.readthedocs.io/en/latest/language-reference.html#in-place-updates
         -- img_cache[img_offset] = (float)(sum * scale);
         x + 1
       y + 1
     ()
```

```
Error at convolve_loops.fut:15:1-1: unexpected end of file.
If you find this error message confusing, uninformative, or wrong, please open an issue at https://github.com/diku-dk/futhark/issues.
```

Maybe in place across function boundary is not possible and copy should always happen?

**Comment by athas** [comment]
In a pure functional language it doesn't make sense to return nothing.  Futhark's in-place updates are not *semantic* (you cannot observe them), but *operational*.  All they do is make things faster (and complain when it can't).  I'm not completely sure what you're trying to do here, but if you really want to do in-place updates, here's an example corresponding to your program:

```
entry filter_horizontal (img: []f32) (kernel_h: []f32) (w: i16) (vc: i16) (uc: i16) (kw_even: i16) (dst_h: i16) (dst_w: i16) (scale: f32) (img_cache: *[]f32): *[]f32 =
  let y0 = (vc * -1) + 1
  let (_, img_cache) =
    loop (y, img_cache) = (y0, img_cache) while y0 < dst_h + vc do
      let (_, img_cache) =
        loop (x, img_cache) = (1, img_cache) while x < dst_w do
          let ky: i16 = y + vc
          let kx: i16 = y + uc
          let img_offset: i16 = ky * w + kx
          let (u, k_offset, sum) =
            loop (u: i16, k_offset: i16, sum0: f32) = ((uc * -1) + 1, 1, 0.0) while u <= (uc - kw_even) do
              (u + 1, k_offset + 1, sum0 + img[i32.i16 img_offset + i32.i16 u] + kernel_h[i32.i16 k_offset])
          let img_cache[i32.i16 img_offset] = (sum * scale)
          in (x + 1, img_cache)
      in (y + 1, img_cache)
  in img_cache
```

I had to add a few variables and some type conversions to make it work out.  But note that writing code like that (with sequential `loop`s) negates the point of Futhark, since there will be no parallelism.  I don't know what this program is supposed to compute, but it looks like it is really computing a 2D array (which you do with flattened indexing), where each individual element can be computed independently.

**Comment by flip111** [comment]
How could i rewrite the code to independently compute each element? Especially the outer loop seems to be independent of previous results and should be embarrassingly parallel from what i understand.

**Comment by athas** [comment]
Use one of the parallel constructs, like `map` and `tabulate` (the latter is just a wrapper around `map`).

Both of the two outer loops look parallel to me.

Conceptually, it looks like what you are doing is updating a rectangular portion of a potentially larger array.

**Comment by flip111** [comment]
I don't know what this code is doing. But it's taking a lot of time on the CPU (measured and flamegraph). I was hoping to put a unit test of input/output around this little section of the code and then see if the same can be written in futhark for a speed up. I'll be looking into map and tabulate thank you

**Comment by flip111** [comment]
For my information ... i was looking around the manual specifically the [language reference](https://futhark.readthedocs.io/en/latest/language-reference.html). Is there a section that would tell me to prefer using map? From the names of the chapters i didn't get i could find this useful information about map there:

```
    1. Installation
    2. Basic Usage
    4. Package Management
    5. C Porting Guide
    6. Futhark Compared to Other Functional Languages
    7. Hacking on the Futhark Compiler
    8. Binary Data Format
```

**Comment by athas** [comment]
The reference manual is not intended as a language introduction.  [Parallel Programming in Futhark](https://futhark-book.readthedocs.io/en/latest/), although incomplete, is a better way of learning the language.
