### ISSUE TITLE
Add option to navigate the call stack on breakpoints in the repl

### ISSUE THREAD

**Issue by he-la** [diku-dk/futhark#840]
It would be useful to be able to navigate up and down the call stack when stopping on a breakpoint, similar to gdb's `where` and `frame X` commands. This would also allow writing small helper functions for conditional breakpoints etc.

Perhaps `:where` and `:frame X` might be good choices for the command names to stick with the familiar gdb naming scheme?

**Comment by athas** [comment]
This was technically quite easy to add, but I only tested it lightly.  Do tell me if something doesn't work as it should.
