### ISSUE TITLE
IO exception in futhark dataset bounds

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/futhark#849]
Hi,

I get unhandled IO exceptions when formatting the bounds incorrectly when using `futhark dataset`:

```
$ futhark dataset --i32-bounds=
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
Invalid bounds: 
CallStack (from HasCallStack):
  error, called at src/Futhark/CLI/Dataset.hs:119:24 in futhark-0.14.1-8oXojRzfhtLFtoaoYiTOWB:Futhark.CLI.Dataset
```

I am using `Futhark 0.14.1` installed with `brew install futhark`

**Comment by emilmasoumi** [comment]
The bounds are not specified: `--T-bounds=<min:max>`. 
For example: `futhark dataset --i32-bounds=0:8`. Also make sure to actually generate the Futhark 
data array by adding: `-g [n]T`. For example: `futhark dataset --i32-bounds=0:8 -g [4]f32`.

**Comment by Unigurd** [comment]
Yeah, I know. I just accidentally mistyped the bounds and got an error message that told me to report it.
Specifying the bounds incorrectly also results in the same error. `futhark dataset --i32-bounds=0-8`, for example.

**Comment by athas** [comment]
Thanks for the report!  The compiler definitely should not crash after emitting the error message.  Will fix.
