### ISSUE TITLE
Beginner issue ...

### ISSUE THREAD

**Issue by eimfach** [diku-dk/futhark#851]
I have following Futhark code:

```
-- vector * vector
let dotprod (u: []f32) (v: []f32): f32 =
  reduce (+) 0.0 (map2 (*) u v)

-- vector * matrix
let lvecmul u b =
  map (\rowOfTrB -> dotprod u rowOfTrB)
    (transpose b)

-- matrix * matrix
entry matmul a b =
  map(\rowOfA -> lvecmul rowOfA b) a

entry sigmoid (x: []f32) =
  divide 1.0 (add (exp (negate x)) 1.0)
```
complete file: https://gist.github.com/eimfach/60ff703d86d51a06601cb2e763900ee3

which I compile to python code with `futhark pyopencl --library GPU.fut`

Now when I run my calculations I get this error:

Traceback (most recent call last):
  File "test.py", line 102, in <module>
    trainAndTest(n)
  File "test.py", line 58, in trainAndTest
    n.train(inputs, targets)
  File "/Users/xx/Documents/workspaces/my-notebooks/neural-network/neuralnetworkopencl.py", line 53, in train
    final_inputs = gpu_api.matmul(self.who, hidden_outputs)
 File "/Users/xx/Documents/workspaces/my-notebooks/neural-network/gpu.py", line 3739, in matmul
    sizze_6231 = np.int32(b_mem_6772_ext.shape[1])
IndexError: tuple index out of range

```
 File "/Users/xx/Documents/workspaces/my-notebooks/neural-network/gpu.py", line 3739, in matmul
    sizze_6231 = np.int32(b_mem_6772_ext.shape[1])
IndexError: tuple index out of range
```
Were gpu.py is the generated library code from Futhark.

Could someone give me a hint or an idea what is going on ? Thanks a lot !

**Comment by athas** [comment]
Unfortunately, the Python output code does not perform particularly friendly error checking of its argument types.  My guess is that you are passing `matmul` an argument that isn't a matrix.  What does neuralnetworkopencl.py look like?

**Comment by eimfach** [comment]
Hi @athas many thanks for this language btw, it is really really cool and super handy ! Awesome work !

Yes right, I was/am using vectors instead of matrices (still for `multiply2` and `add2` where I need to implement the version for matrices)

 ... really a beginner to this stuff, math experience way lower, but I understand for example creating a dot product of two matrices ... 

Also I am not sure how to implement a multiplication function like for (numpy.array * numpy.array), like in the base (working) implementation of the network [in this file](https://github.com/eimfach/my-notebooks/blob/b21fd4a82b7276a762c2ffcb4c5898f00686faf4/neural-network/neuralnetwork.py#L56)

- The current migration of the neural network (neuralnetworkopencl.py) is [here](https://github.com/eimfach/my-notebooks/blob/master/neural-network/neuralnetworkopencl.py)

- [My current Futhark API](https://github.com/eimfach/my-notebooks/blob/master/neural-network/GPU.fut)

- [My repo containing all files](https://github.com/eimfach/my-notebooks/tree/master/neural-network)

**Comment by athas** [comment]
It looks like `self.who` becomes a vector on neuralnetworkopencl.py line 74, and `self.wih` on line 78 (since `add2` is vector addition).  This causes a crash when you later try to treat them as matrices.  Pretty unfortunate that the generated code doesn't detect this.

**Comment by eimfach** [comment]
Okay I think I have solved it. I just mapped those numpy functionalities I needed to my Futhark API...

My use case: I am using the MSNIST datasets to detect handwriting.
I moved some remaining numpy.array conversions in my `train` method to a batch before the training even starts. I am trying to move all my training data into gpu memory before hand...

You can see my test suite here:

https://github.com/eimfach/my-notebooks/blob/1e9254848090f506097e78a80de79228c91eb52a/neural-network/test.py#L38

To create gpu arrays from numpy arrays beforehand, I have this function in my Futhark API:

```
entry arr (x: [][]f32) =
  x
```
Does that approach makes sense ?
[See an example:](https://github.com/eimfach/my-notebooks/blob/1e9254848090f506097e78a80de79228c91eb52a/neural-network/test.py#L59)

The allocation for 60,000 MNIST Datasets (the training data) takes 129.17 seconds ... even worse, the training takes 222.33 seconds... whereas with pure numpy it takes about 50s to complete it all over.

**Comment by athas** [comment]
How big are the matrices?  Futhark is not particularly optimised for writing small primitives that are then composed in another language, since the compiler cannot optimise across entry points.  Ideally, you'd put most of the `train` method in a single Futhark function.  But even with the current code, it should be able to do better than that.

**Comment by athas** [comment]
Also, where do you see that the Intel Iris 550 has 1536MiB of memory?  [This page](https://www.notebookcheck.net/Intel-Iris-Graphics-550.149937.0.html) suggests 64MiB.  If you're going by what `clinfo` reports, then it's probably just listing your system RAM, for the reason that Intel GPUs will transparently swap to CPU memory once their (tiny) internal memory fills up.  This is *extremely* slow.  Intel GPUs are actually pretty fast at computation, but they are hampered by very little fast memory.

**Comment by eimfach** [comment]
Thanks for the troubleshooting ! :) I understand what you are referring to, that I only have 64MiB Memory ... the 1,5 GiB RAM is definitely Main Memory ...

> Futhark is not particularly optimised for writing small primitives that are then composed in another language, since the compiler cannot optimise across entry points. 

Okay, good to know, I moved the whole training logic to a [new Futhark module](https://github.com/eimfach/my-notebooks/blob/17d8afc43e3accb4ab6dbbe66db15473805eab4d/neural-network/GPUTraining.fut#L157) where I have only one entry (the main) function, which does the whole network training process.

> How big are the matrices?

(as of numpy.ndarray.size tells me)

- Size of Weights Matrix for input layer to hidden layer: 156800
- Size of Weights Matrix for hidden layer to output layer: 2000
- Size of Training Input Matrix: 784
- Size of Training Target Matrix: 10

> Me: I am trying to move all my training data into gpu memory before hand...

I dropped that functionality. It will create the initial numpy arrays for input and target matrices (sizes: 784 and 10) on each training call entry (60,000 of them). The Weight Matrices reside as members in the network object where the type is as given by the first training call to Futhark. So those matrices stay in gpu memory, I guess.

[Updated neuralnetworkopencl.py](https://github.com/eimfach/my-notebooks/blob/df4a8f72cd88981076bcfc1d84ae8699af016b55/neural-network/neuralnetworkopencl.py#L47)

- The whole training time for the MNIST data now went from 222.33s to about 180-200s (which is still very slow), where the GPU load is about 15% +/- 2%.

- Do you think it is exceeding the 64MiB eDRAM (going to system RAM) and does that maybe create the bottleneck ?

---

I also tested the training with a very small subset of the MNIST data, 100 entries.
- The GPU training takes about: 0.33s
- The CPU training takes about: 0.075s

**Comment by eimfach** [comment]
- Also, I have no command `clinfo`

**Comment by eimfach** [comment]
#### Further Testing

I just ran the test suite on windows 10 with an radeon rx 480 8GB of VRAM and it took 125s in average

**Comment by athas** [comment]
I tried running your code (I assume `test.py` is the entry point) on my own GPU, and a single call of `train` takes 1187.00μs with the `pyopencl` backend.  You seem to be doing *tons* of these sequentially.  The `pyopencl` backend has significant overhead for many small operations (a single `train` call is 9 kernel launches), so this is not very good (it's 272.70μs with the `opencl` backend`).

It may be worth it to increase the batch-size to decrease the granularity of the parallel operations.  This will also help with the transmission costs, as right now you will be constantly ferrying relatively small arrays between the GPU and CPU.

**Comment by eimfach** [comment]
Ah yes, I see. 

Yes, I now realized that I compute the updated weights of the network with 60,000 datasets sequentially. It doesn't make sense to compute sequentially on a GPU I guess. I need to utilize the power of parallel computing right ? Do you think it would be better to pass those datasets to the training method in Futhark ? The problem is also that the training for each dataset relies on the previous training to improve the network.

So my imagination looks like this:

```
let main (lr: f32) (wih: [][]f32) (who: [][]f32) (inputs: [][]f32) (targets: [][]f32) (data: [][]f32) =

-- map over 60,000 data sets
  -- do the training
```

As I said the training results build upon each other. I wonder of how this implementation would be optimized by the Futhark compiler, if at all ...

**Comment by athas** [comment]
I don't think you can fit 60000 data sets all at once.  I am not very experienced with machine learning, but [when a student worked on neural networks in Futhark](https://github.com/HnimNart/deeplearning), most networks needed at least a hundred data sets at a time to saturate the GPU.  In practice, I think people just try various sizes in an ad-hoc manner until they find something that seems to run well.  Of course, you have the extra constraint of a tiny GPU, so who knows what it'll look like.

Having an outer `map` over all the data sets is fine.  Handling (regular) nested parallelism is exactly what the Futhark compiler is built for.

**Comment by eimfach** [comment]
I have this code now:

```
let train (lr: f32) (wih: [][]f32) (who: [][]f32) (inputs: [][]f32) (targets: [][]f32) : ([][]f32, [][]f32) =

let main (lr: f32) (wih: [][]f32) (who: [][]f32) (data: []([][]f32, [][]f32)) : ([][]f32, [][]f32) =
  reduce (\(inputs, targets) (uwih, uwho) -> train lr uwih uwho inputs targets ) (wih, who) data
```

where reduce should return a tuple: (updated_wih, updated_who) which is ([][]f32, [][]f32)

The compiler is telling me:

```
Warning at GPUTraining.fut:180:1-181:96:
  Entry point parameter
  
    ((data: []([][]f32, [][]f32)): []([][]f32, [][]f32))
  
  will have an opaque type, so the entry point will likely not be callable.
```

**Comment by athas** [comment]
Unpack it into multiple arrays and use `zip`/`unzip` to give it whatever form you need.  These operations are free.  You can [also define a type abbreviation to give the opaque type a known name](https://futhark.readthedocs.io/en/latest/usage.html#general-concerns), but that's more fiddly.

**Comment by eimfach** [comment]
I can't find a reference in the docs for `zip`

**Comment by athas** [comment]
[Here.](https://futhark-lang.org/docs/doc/futlib/zip.html#365)

**Comment by eimfach** [comment]
Okay I guess this should be okay then:

```
let main (lr: f32) (wih: [][]f32) (who: [][]f32) (inputs: [][][]f32) (targets: [][][]f32) : ([][]f32, [][]f32) =
  reduce (\(cinputs, ctargets) (uwih, uwho) -> train lr uwih uwho cinputs ctargets ) (wih, who) (zip inputs targets)
```

I get an AssertionError: Error: Row shape of input array does not match shape of neutral element

**Comment by eimfach** [comment]
btw is the accumulator of the reduce function the first or second parameter (a->b->b **or** b->a->b)

**Comment by athas** [comment]
The shape of `wih` must be the shape of the elements of `inputs`,  and similarly for `who` and `targets`.

But that construction will get you in trouble anyway.  How is training a reduction?  Seems to me that should just be a `map`.  There is no "accumulator" in a reduction, since it's supposed to be given an associative function (otherwise no parallelism is possible and it's just a fold).

**Comment by eimfach** [comment]
I think map does not solve what I need, in the end I need two matrices (which are the updated wih and who matrices). Each update builds upon each other ...

It looks like so:

training with initial weights and data 1 -> update weights -> training with updated weights and data 2 -> update weights -> training with updated weights and data 3 ... 
...
training with updated weights and data 60,000 -> last update weights
...

**Comment by athas** [comment]
This is becoming a question about how to do batched training in machine learning, which is outside my area of expertise.  I guess you compute an error independently for each dataset (`map`), and then sum them or something (some form of `reduce` I guess).  I really don't know.
