### ISSUE TITLE
Blurred testing results

### ISSUE THREAD

**Issue by eimfach** [diku-dk/futhark#852]
I have following code:

```
-- vector * vector
let dotprod (u: []f32) (v: []f32): f32 =
  reduce (+) 0.0 (map2 (*) u v)

-- vector * matrix
let lvecmul u b =
  map (\rowOfTrB -> dotprod u rowOfTrB)
    (transpose b)

-- matrix * matrix
-- ==
-- entry: matmul
-- input { [[0.014f32, 0.056f32, -0.032f32], [0.045f32, 0.032f32, -0.067f32]] [[0.01f32], [0.01f32], [0.01f32]] }
-- output { [[0.00038f32], [0.0001f32]] }
entry matmul a b =
  map(\rowOfA -> lvecmul rowOfA b) a
```

If I replace the output with `-- output { [[0.00038f32], [0.0008f32]] }` or `-- output { [[0.00038f32], [0.001f32]] }` the test just passes ... (?)

Then I changed it to `-- output { [[0.00038f32], [0.01f32]] }` and finally it is complaining: `Value (0,1) expected 1.0e-2f32, got 1.0e-4f32`

**Comment by athas** [comment]
`futhark test` uses a small epsilon when comparing floating-point values.  [Looks like it's hardcoded to 0.2%.](https://github.com/diku-dk/futhark/blob/master/src/Futhark/Test/Values.hs#L555-L556)

**Comment by eimfach** [comment]
Okay, does it mean that there is no way to be exact testing floats ? Maybe it would be better to opt-in this epsilon, instead of being it implicit... just an idea...

**Comment by athas** [comment]
You definitely need this epsilon in practice, since many floating-point operations (e.g. transcendental functions) do not produce 100% identical results on different platforms.  In particular, GPUs often cut corners.
