### ISSUE TITLE
Bug report: Internal compiler error.

### ISSUE THREAD

**Issue by Ulrik-dk** [diku-dk/futhark#856]
I have isolated the minimally reproductive example, of an internal compile-error, to this code-snippet: https://github.com/Ulrik-dk/error-snippet/blob/master/example.fut

When I compile with `futhark c example.fut` I get the following error-message:
![image](https://user-images.githubusercontent.com/30180650/75058721-cfda9080-54db-11ea-9775-f3dd2ba023c7.png)

I think I can probably find a workaround, but I thought I'd let you know about it.

**Comment by athas** [comment]
I cannot reproduce with the Git version of Futhark.  Which version are you using?

**Comment by Ulrik-dk** [comment]
0.13.0
git: e50d964

**Comment by Ulrik-dk** [comment]
With version 0.14.1, I now get a type-error instead. Thank  you!
