### ISSUE TITLE
Source has non-unique type

### ISSUE THREAD

**Issue by reversefold** [diku-dk/futhark#868]
This may be a misunderstanding on my side but I'm having problems trying to loop over a 2d array and set values on it. I'm wanting to pass a bitmap into an entry method and set each pixel value with the result of another method call. I've reduced this to just the loops and the setting and I'm still getting an error about the source's type not being unique.
```
entry render [width] [height] (
    pixels: [height][width][4]i8
) =
    loop y = 0 for y < height
    do loop x = 0 for x < width
        do pixels with [y, x] = [0, 0, 0, 0]
```

```
[0]> :load unique_error.fut
Loading unique_error.fut
Error at unique_error.fut:6:12-44:
Source "pixels" has type [height][width][4]i8 , which is not unique.
```

**Comment by athas** [comment]
You need to change the type of `pixels` to be `*[num_pixels][4]i8`.  This will let you change it.  See [this section](https://futhark.readthedocs.io/en/latest/language-reference.html#in-place-updates).

However, note that the loop you've written is completely sequential.  It's likely not what you really want.

**Comment by reversefold** [comment]
Thanks, I've gotten a version of this simple code to compile:
```
entry render [width] [height] (
    pixels: *[height][width][4]i8
) =
    loop (pixels) for y < height
    do let row = pixels[y]
    in loop (pixels) for x < width
        do pixels with [y, x] = [0, 0, 0, 0]
```

But if this would run sequentially then it doesn't really help. What would I have to do to make this use-case run in parallel? I've gotten some other code working with `map`, `reduce` and such but only when it's returning its value.

A naive attempt to parallelize this with map causes the original error about uniqueness again:
```
entry renderp [width] [height] (
    pixels: *[height][width][4]i8
) =
    map (\y ->
        map (\x ->
            pixels with [y, x] = [0, 0, 0, 0]
        ) 0...width
    ) 0...height
```

```
[0]> :load unique_error.fut
Loading unique_error.fut
Error at unique_error.fut:6:13-45:
Source "pixels" has type [height][width][4]i8 , which is not unique.
```

If I try to create the bitmap it loads but then says that the entry point won't be callable due to an opaque type:
```
entry renderpm (width: i32, height: i32): [][][4]i8 =
    map (\y ->
        map (\(x): [4]i8 ->
            [i8.i32(x), i8.i32(y), 0i8, 0i8]
        ) (iota width)
    ) (iota height)
```

```
[0]> :load unique_error.fut
Loading unique_error.fut
Warning at unique_error.fut:1:1-6:19:
  Entry point parameter

    ((width: i32): i32, (height: i32): i32)

  will have an opaque type, so the entry point will likely not be callable.
```

If I try to make the width and height size parameters I get an error about return values not being allowed to be size-polymorphic. It seems like returning an array of a non-constant size is not allowed.

**Comment by athas** [comment]
If you just want to turn `pixels` into an all-zero array, then use two nested `map`s:

```
entry renderp [width] [height] (
    pixels: [height][width][4]i8
) =
    map (\y ->
        map (\x ->
            0
        ) (0..<width)
    ) (0..<height)
```

Note the use of `0..<height` instead of `0...height` - you want an exclusive upper bound here.  There is a prelude function `tabulate_3d` for handling this common pattern:

```
entry renderp [width] [height] (
    pixels: [height][width][4]i8
) =
    tabulate_2d height width (\_ _ -> 0)
```

For `renderpm`, the problem is that you've written a function that takes a *single* argument that happens to be a tuple.  In most cases the difference doesn't matter, but it is significant for entry points.  Write it like this instead:

```
entry renderpm (width: i32) (height: i32): [][][4]i8 =
    map (\y ->
        map (\(x): [4]i8 ->
            [i8.i32(x), i8.i32(y), 0i8, 0i8]
        ) (iota width)
    ) (iota height)
```

**Comment by reversefold** [comment]
The setting to 0 was just as an example, I have a function which I want to call which does rendering based on the x/y coordinate.

Ah yes, thanks for reminding me of `0..<x`, I'd forgotten that.

And thanks for the pointer on the parameter syntax. It's easy to get confused since the tuple syntax makes the functions appear to be just like functions in many other languages and works just fine.

The first two examples you gave don't seem to do anything with `pixels`, they just create an unrelated 2d list. With your help I got the version that returns a newly created bitmap working but I'm curious what it would take to make the version that passes in the bitmap work. Trying to go back to using `with` in the map version of the function still gives the same uniqueness error:

```
entry renderp [width] [height] (
    pixels: [height][width][4]i8
) =
    map (\y ->
        map (\x ->
            pixels with [y, x] = [i8.i32(x), i8.i32(y), 0i8, 0i8]
        ) (0..<width)
    ) (0..<height)
```

```
[5]> :load unique_error.fut
Loading unique_error.fut
Error at unique_error.fut:14:21-73:
Source "pixels" has type [height][width][4]i8 , which is not unique.
```

Is there a way to set this up with a passed-in array that will run in parallel?
```

**Comment by athas** [comment]
In-place updates are an exotic and rarely used feature.  You definitely don't need them for this.  Just do

```
entry renderp [width] [height] (
    pixels: [height][width][4]i8
) =
    map (\y ->
        map (\x ->
            [i8.i32(x), i8.i32(y), 0i8, 0i8]
        ) (0..<width)
    ) (0..<height)
```

I usually also recommend using small tuples (or even 32-bit integers) instead of small arrays for [reasons described here](https://futhark-lang.org/blog/2019-01-13-giving-programmers-what-they-want.html).

As an example, [this is the equivalent loop in a ray tracer I wrote](https://github.com/athas/raytracinginoneweekendinfuthark/blob/master/raytracer.fut#L246-L251).

**Comment by reversefold** [comment]
Sure...but why would I pass pixels into that function at all? It's useless to pass in that array if all that it's using it for is the width and height. If the "right way" to do this kind of thing in futhark is to generate the array then I can use that but it would also be helpful to be able to update an existing bitmap.

**Comment by athas** [comment]
You're right, just pass in the sizes.  Futhark is a pure language, so there is no way to do observable updates of an existing bitmap.  You can use in-place updates or `scatter` to get the operational effect of an update (performance-wise), but in most cases there is no point, and it's more awkward.

What I do when I write graphics programs with a Futhark component is to use Futhark to generate bitmaps as arrays, and then I have a wrapper program that uses SDL or whatnot to actually blit it to where it's necessary.  Usually I just have Futhark compute a full screen image.  See [Lys](https://github.com/diku-dk/lys) for an example.
