### ISSUE TITLE
internaliseTypeM: cannot handle function type: i32 -> i32

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/futhark#873]
The following program crashes the compiler:

```
type^ myType = #myVal (i32 -> i32)

let main = 
    match ((\m   -> #myVal (\_ -> m)) 0 : myType)
    case #myVal m -> m 1
```

The error message I get is:
```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
internaliseTypeM: cannot handle function type: i32 -> i32
CallStack (from HasCallStack):
  error, called at src/Futhark/Internalise/TypesValues.hs:130:7 in futhark-0.15.1-8dc5e22932fcde1138d5774b2faa37f0a12ed2b06c2c6636e477094642c93005:Futhark.Internalise.TypesValues
```

I use Futhark 0.15.1, just updated via brew, and I compile with `futhark c`.
Should the example code be valid Futhark or should it just result in a proper error message?

**Comment by athas** [comment]
What is `myType`?

**Comment by Unigurd** [comment]
Sorry, it was on the same line as the three backticks, and so didn't show.

**Comment by athas** [comment]
That program should be OK.  I'll take a look...

**Comment by athas** [comment]
Looks like the defunctionaliser is forgetting to rewrite the payloads of sum type annotations sometimes (although the actual definitions are handled correctly).  Shouldn't be a difficult fix.  Thanks for reporting it!

**Comment by Unigurd** [comment]
No problem. Thanks for fixing it :)

**Comment by athas** [comment]
`brew install --HEAD futhark` should get you the fix on macOS (but it'll take at least half an hour to compile, unless your machine is much faster than mine).
