### ISSUE TITLE
REPL crashes when attempting to destructure pair in let binding.

### ISSUE THREAD

**Issue by porcuquine** [diku-dk/futhark#875]
I wasn't sure whether destructuring assignments were supported in Futhark, so I tested in the REPL. This caused it to crash.

I'm using v0.15.1.

UPDATE: output makes it look like I'm actually inadvertently using 0.16.0.

```
[0]> let (a, b) = (1, 2) in (b, a)
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
eval: nonsensical type for integer literal: t₀
CallStack (from HasCallStack):
  error, called at src/Language/Futhark/Interpreter.hs:803:10 in futhark-0.16.0-Jq3IKZrcS5U55wTFYq323q:Language.Futhark.Interpreter

Process futhark exited abnormally with code 1
```

**Comment by athas** [comment]
Destructuring assignments don't work at top-level (but they do everywhere else).  But this REPL crash is due to a stupid bug I introduced recently and fixed in https://github.com/diku-dk/futhark/commit/61d8dde0c0a450e3892e94011c6293f811642dc8.

**Comment by porcuquine** [comment]
Ah right, I knew it worked in general — but it was failing at top-level in a module. I think you are saying this (but not the crash) is expected behavior, so I will work around.
