### ISSUE TITLE
Error:: unknown type name '__uint128_t'

### ISSUE THREAD

**Issue by kewp** [diku-dk/futhark#883]
I'm trying to compile on Windows

It's a fresh install. I used the procedure in the docs, i.e. `git clone etc`, `stack update`, `stack setup`, `stack build`. I had to change `stack.html` to use `haskell.compiler.ghc883` to get the build to work.

```
c:\Users\karl\tst>futhark c linear.fut -o prog.exe
gcc failed with code 1:
prog.exe.c: In function 'futrts_mul_hi64':
prog.exe.c:2059:5: error: unknown type name '__uint128_t'; did you mean '__int128'?
     __uint128_t aa = a;
     ^~~~~~~~~~~
     __int128
prog.exe.c:2060:5: error: unknown type name '__uint128_t'; did you mean '__int128'?
     __uint128_t bb = b;
     ^~~~~~~~~~~
     __int128
prog.exe.c:2062:20: warning: right shift count >= width of type [-Wshift-count-overflow]
     return aa * bb >> 64;
                    ^~


If you find this error message confusing, uninformative, or wrong, please open an issue at
https://github.com/diku-dk/futhark/issues.
```

**Comment by athas** [comment]
Which version of GCC are you using?

**Comment by athas** [comment]
And are you on a 32-bit system?  GCC should support __uint128_t even in very old versions, but only when compiling for 64-bit.

**Comment by kewp** [comment]
It's a 64 bit machine. I do have my own GCC on the path (32bit) but I thought Stack uses it's own version?

**Comment by kewp** [comment]
Hmmm. I see there is another GCC that Haskell Platform setup. I removed mine and it works now.
