### ISSUE TITLE
Internal compiler error (unhandled IO exception).

### ISSUE THREAD

**Issue by porcuquine** [diku-dk/futhark#887]
I got the following error and am duly reporting:

```
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
`LVec.get` is not bound to a value.
CallStack (from HasCallStack):
  error, called at src/Language/Futhark/Interpreter.hs:613:10 in futhark-0.16.0-Jq3IKZrcS5U55wTFYq323q:Language.Futhark.Interpreter

Process futhark exited abnormally with code 1
```

LVec is a module representing a static vector (https://github.com/athas/vector/tree/master/lib/github.com/athas/vector). I don't know which line of my program led to this, so I can't include it here.

**Comment by athas** [comment]
Can you point me at your entire program, then?  Somewhere along the way in the interpreter a module forgets its contents, but it's a bit tricky to pin down why.

Does it also fail with the compiler?

**Comment by porcuquine** [comment]
As it turns out, it does fail with the compiler. (I now know that this error is triggered on line 521 or 528: https://github.com/porcuquine/fut-ff/blob/master/lib/github.com/porcuquine/fut-ff/field.fut

It wasn't until I fixed the last type error when refactoring to static vectors that it happened, so I hadn't tried the compiler yet. (It also compiles fast.)

**Comment by athas** [comment]
I cannot reproduce, neither on `master` or the `static-vectors` branch of that repository.  Could you give an exact command that fails?

**Comment by athas** [comment]
Ah, I see it now, at least in the REPL.

**Comment by porcuquine** [comment]
It happens when I try to load the file into the REPL from an emacs buffer using C-c C-l (futhark-comint-load-file).

**Comment by athas** [comment]
But it only fails in the REPL, right?  That's important, because it means the root issue might just be an interpreter bug, and not because the type checker inserts the wrong annotations for modules or something.

**Comment by porcuquine** [comment]
That is the only place I have seen the problem, yes.

**Comment by athas** [comment]
Yeah, it's something about how the interpreter (mis)handles qualified parentheses.  It's this one that fails:

```
M.((LVec.get i a) + (LVec.get i b) + carry)
```

**Comment by athas** [comment]
Actually it's even simpler; looks like the interpreter simply screws up nested module that are not actually declared inline:

```
module type has_x = {
  val x : i32
}

module has_x = {
  let x = 1
}

module type has_has_x = {
  module has_x : has_x
}

module has_has_x = {
  module has_x = has_x
}

let main = has_has_x.has_x.x
```

**Comment by athas** [comment]
No, wait, it does need the parens:

```
let main = has_has_x.(has_x.x)
```
