### ISSUE TITLE
futhark pkg issue with gitlab

### ISSUE THREAD

**Issue by melsman** [diku-dk/futhark#899]
I believe there is a mistake in the extraction of files from gitlab zip-files. There seems to be a mistake in the pkgtest:

The directory `pkgtests/lib.16/gitlab.com/athas/fut-gitlab` should contain a file `gitlab.fut` with the content
```
let gitlab = (1, 0, 1)
``` 
The problem seems to be that the zip-file contains paths where the semantic version is prefixed with a `v`...

Here is the content of the zip-file fetched from gitlab:
```
curl -L -o fut-gitlab-v1.0.1.zip https://gitlab.com/athas/fut-gitlab/-/archive/v1.0.1/fut-gitlab-v1.0.1.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1482  100  1482    0     0  21152      0 --:--:-- --:--:-- --:--:-- 21171
bash-3.2$ unzip -qql fut-gitlab-v1.0.1.zip
        0  09-22-2018 08:37   fut-gitlab-v1.0.1/
       43  09-22-2018 08:37   fut-gitlab-v1.0.1/README.md
       49  09-22-2018 08:37   fut-gitlab-v1.0.1/futhark.pkg
        0  09-22-2018 08:37   fut-gitlab-v1.0.1/lib/
        0  09-22-2018 08:37   fut-gitlab-v1.0.1/lib/gitlab.com/
        0  09-22-2018 08:37   fut-gitlab-v1.0.1/lib/gitlab.com/athas/
        0  09-22-2018 08:37   fut-gitlab-v1.0.1/lib/gitlab.com/athas/fut-gitlab/
       23  09-22-2018 08:37   fut-gitlab-v1.0.1/lib/gitlab.com/athas/fut-gitlab/gitlab.fut
```

The `futhark pkg` code (Info.hs, line 235) assumes that the paths are of the form `fut-gitlab-1.0.1/lib/...`...

**Comment by athas** [comment]
Nice catch!  And quite shameful that I screwed up the tests.  At least a fix is easy.
