### ISSUE TITLE
Provide statically linked releases and nightlies

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#910]
[I figured out how to build static `futhark` binaries](https://github.com/diku-dk/futhark/blob/master/default.nix).  This is what we should put in our tarballs!  Using Nix on CI might also relieve some dependency constraints.

**Comment by flip111** [comment]
Great idea !

**Comment by athas** [comment]
This is now done on Azure, although I expect to be chasing problems for a while.  The statically linked binaries are much smaller (when compressed) than the old dynamically linked ones.  Check the size of the nightly tarball here: https://futhark-lang.org/releases/
