### ISSUE TITLE
Can we use this thing from OCaml?

### ISSUE THREAD

**Issue by UnixJunkie** [diku-dk/futhark#916]
I saw that you have something for Python users.
But, not everybody likes the snake. :)

**Comment by Munksgaard** [comment]
Futhark can create [C libraries](https://futhark-book.readthedocs.io/en/latest/interoperability.html#calling-futhark-from-c). I think your best option would be to FFI to that as part of your build process. As far as I'm aware, this is also the preferred method for other languages that don't have specific Futhark frontends, like Rust.

**Comment by UnixJunkie** [comment]
Ok, fair enough.
I'll keep that in mind for the future.
Thanks for the pointer!

**Comment by Munksgaard** [comment]
You're welcome, thank you for checking out Futhark!
