### ISSUE TITLE
Distribute in different ways and select optimal code at run-time

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#92]
This is the main hybrid optimisation technique.  As a demonstration, let us consider the fully fused matrix multiplication program:

```
fun {[[int,n_0],n_0]} main(int n_0, int m_1, [[int,m_1],n_0] x_2,
                           [[int,n_0],m_1] y_3) =
  -- transpose_4 aliases y_3
  let {[[int,m_1],n_0] transpose_4} = rearrange((1, 0), y_3) in
  let {[[int,n_0],n_0] res_54} =
    map(n_0,
        fn {[int,n_0]} (i_21; [int,m_1] not_curried_22) =>
          let {[int,n_0] res_52} =
            map(n_0,
                fn {int} (i_33; [int,m_1] x_34) =>
                  let {int res_50} =
                    redomap(m_1,
                            fn {int} (i_40; int x_41, int y_42) =>
                              let {int res_43} = x_41 + y_42 in
                              {res_43},
                            fn {int} (i_44; int x_45, int x_46, int y_47) =>
                              let {int res_48} = x_46 * y_47 in
                              let {int res_49} = x_45 + res_48 in
                              {res_49},
                            {0}, not_curried_22, x_34) in
                  {res_50},
                transpose_4) in
          {res_52},
        x_2) in
  {res_54}
```

When distributing and extracting kernels from this, we have a significant choice to make - do we sequentialise the `redomap` or not?  If we do, then we gain extra parallelism (corresponding to `m_1`), but we also use more memory (again by a factor of `m_1`).  If `n_0 * n_0` is already "sufficient parallelism" (by some metric of sufficiency), then paying for the extra parallelism is wasteful (this is exactly how flattening typically goes wrong).  But in some cases (probably rarely in the case of matrix multiplication) it's perfectly reasonable to pay a little memory to expose some more parallelism!  Hence, the Futhark compiler should generate both versions of the code, and at runtime determine whether enough parallelism is present to prefer the one with sequentialised redomap, or whether we need as much parallelism as we can get.

Note that it's not as pressing to consider sequentialising the second `map`, as we don't pay a memory cost for leaving it parallel, even if we do end up with excess parallelism.  Also - preserving some of the nested structure can make other coalescing transformations easier to do (not too sure about this; we optimise fine on flat kernels).

**Comment by Athas** [comment]
For example, exposing the full parallelism when multiplying two 2000x2000 matrices results in an intermediate array of eight billion elements (this is also the number of kernel threads).

This is bad for many reasons, and not only because Futhark currently uses 32-bit integers to track array sizes (but that is pretty bad too).

**Comment by Athas** [comment]
Sadly, I cannot find any input size for which it is more efficient to parallelise the inner `redomap` in matrix multiplication.  We will have to find another program that demonstrates the validity of both approaches.

**Comment by Athas** [comment]
One reason may be that we don't have segmented reductions, and that is pretty much what ends up being the final step.  I am going to put off working on this until we have a test program where it matters for performance.

**Comment by athas** [comment]
This is done by incremental flattening.
