### ISSUE TITLE
Invalid opencl kernel code generated (define spans multiple lines)

### ISSUE THREAD

**Issue by zeebo** [diku-dk/futhark#922]
Using the pyopencl backend, some kernel code was generated with this define:

```c
    #define ldim_11603 (squot32(add32(61, sub32(smin32(61, grid_model_newzisegmap_group_sizze_11475),
                        1)), smin32(61,
                                    grid_model_newzisegmap_group_sizze_11475)))
```

Since there's no escapes on the newlines, it parses incorrectly.

This happens on both v0.15.3 and v0.15.4. I don't have a small reproducer, but I can work on that if necessary.

**Comment by athas** [comment]
No, that's not necessarily, I think this one will be easy to fix.

**Comment by athas** [comment]
I am 99% sure this is fixed now.  Could you check just to be certain?

**Comment by zeebo** [comment]
Sorry for the delay. I double checked and it worked. Thanks :+1:
