### ISSUE TITLE
Pattern matching related bug?

### ISSUE THREAD

**Issue by bryal** [diku-dk/futhark#923]
Hi again. I seem to have encountered a bug in `match` where depending on the body of a case, the match may skip over to the default case even if it should really enter that branch. No error message, and again, we couldn't manage to reduce it, sorry.

The non-working code can be found in branch `match-bug` of our repo, https://gitlab.com/JoJoZ/futhark-tracer/-/tree/match-bug.

Context: It's a ray tracer, and one can specify the camera to also act as a transmitter. The transmitter can be either `#flash`, `#scanning`, or `#none`, and for debugging purposes we create a "normal" light for the `#flash` case, an extremely powerful white light for the `#scanning` case, and an extremely powerful red light for the `#none` case. The camera transmitter variable is set to `#scanning`.

Expected behaviour:
1. Run the program (make run)
2. Press the `M` key to activate accumulation
3. See the screen turn white, since `gen_transmitter` enters the `#scanning` case and creates a bright white light.

Actual behaviour:
Do the same as above, but see the screen turn completely red, as if `gen_transmitter` enters the `#none` case and creates a red light, even though the transmitter variable is `#scanning`.

The following diff makes `gen_transmitter` behave as expected, i.e. create a bright white light as it should. The two versions of the function should be completely equivalent as far as I can tell.

```
modified   src/camera.fut
@@ -70,19 +70,15 @@ let get_ray (cam: camera) (wh: vec2) (ji: vec2) (rng: rnge): ray =
             vec3.- origin)
 
 let gen_transmitter (n_sectors: i32) (c: camera) (r: ray): [n_sectors]light =
-  match c.transmitter
-  case #flash { radius, emission } ->
-    let tris = disk c.origin (cam_dir c) radius n_sectors
-    let to_light (t: triangle): light = #arealight
-      (#diffuselight { geom = #triangle t, emission })
-    in map to_light tris
-  case #scanning { radius, theta=_, emission } ->
-    let tris = disk c.origin r.dir radius n_sectors
-    let to_light (t: triangle): light = #arealight
-      (#diffuselight { geom = #triangle t, emission })
-    in map to_light tris
-  case #none ->
-    let tris = disk c.origin (cam_dir c) 0.0 n_sectors
-    let to_light (t: triangle): light = #arealight
-      (#diffuselight { geom = #triangle t, emission = spike_spectrum 600 10000 })
-    in map to_light tris
+  let (dir, radius, emission) =
+    match c.transmitter
+    case #flash { radius, emission } ->
+      (cam_dir c, radius, emission)
+    case #scanning { radius, theta=_, emission } ->
+      (r.dir, radius, emission)
+    case #none ->
+      (cam_dir c, 0.0, spike_spectrum 600 10000)
+  let tris = disk c.origin dir radius n_sectors
+  let to_light (t: triangle): light = #arealight
+    (#diffuselight { geom = #triangle t, emission })
+  in map to_light tris
```

The following diff also "fixes" the issue, in that the `#scanning` case is now entered as expected, but we really want to use `r.dir` and not `cam_dir c` -- they are not quite the same.

```
modified   src/camera.fut
@@ -77,7 +77,7 @@ let gen_transmitter (n_sectors: i32) (c: camera) (r: ray): [n_sectors]light =
       (#diffuselight { geom = #triangle t, emission })
     in map to_light tris
   case #scanning { radius, theta=_, emission } ->
-    let tris = disk c.origin r.dir radius n_sectors
+    let tris = disk c.origin (cam_dir c) radius n_sectors
     let to_light (t: triangle): light = #arealight
       (#diffuselight { geom = #triangle t, emission })
     in map to_light tris
```

**Comment by athas** [comment]
This is truly mysterious.  I've not seen a bug like this before.  Since the version that moves the `map` out of the `case` branches both works and is faster for other reasons, I'll probably not spend too much time on this bug in the short term.

**Comment by athas** [comment]
It works with the `c` backend, so it's not a problem in the early parts of the compiler.  That's a relief.

**Comment by athas** [comment]
While I fixed the immediate problem, I still think something else is going wrong, as one of the GPU kernels seem to enter an infinite loop, but I don't know whether it's a compiler bug.  That kernel contains several nested `while` loops (so I guess it's the BVH traversal).

**Comment by bryal** [comment]
Interesting. Can confirm the previously bugged code works for me now!
