### ISSUE TITLE
Error with sum types and anonymous sizes

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/futhark#927]
I find the compiler will not unify an anonymous size of an array with some constant if the array is stored in a sum type. In the following example,  ``fine`` will compile just fine, while ``error`` will not.

````
type sometype 'a = #someval a

let fine  (_ : i32) : []i32 = []
let error (_ : i32) : sometype ([]i32) = #someval []
````

Here is the error message I get:
````
Error at bug.fut:7:3-19 :
Function body does not have expected type.
Expected: i32 -> (#someval []i32)
Actual:   t₀ -> t₁

Dimensions "0" and "" do not match.
When matching types of constructor "someval".
When matching return types.

If you find this error message confusing, uninformative, or wrong, please open an issue at
https://github.com/diku-dk/futhark/issues.
````

I am using Futhark 0.16.0, downloaded as by the instructions [here](https://github.com/diku-dk/futhark/issues/873#issuecomment-600637724).

**Comment by athas** [comment]
This type-checks for me.  I suspect your Futhark is slightly outdated (0.16.0 just means its an unreleased version newer than 0.15.1).

**Comment by Unigurd** [comment]
Whoops, I think I was a bit too lazy when checking those test cases. They type check for me as well. This variation however still generates an error message similar to the one posted above: 
````
let error : i32 -> sometype ([]i32) = \_ -> #someval []
````
I did update Futhark.

**Comment by athas** [comment]
Thanks for the report!
