### ISSUE TITLE
commit-id and LICENSE files missing in latest releases

### ISSUE THREAD

**Issue by mbloms** [diku-dk/futhark#932]
Release 0.15.4 and current nightly build by user nixbld (which I guess means you started using nix) lacks the `LICENSE` and `commit-id` files. I used both these in my AUR packaging scripts and they are very useful to have in the package. Could you make nix include them?

[1] https://futhark-lang.org/releases/futhark-0.15.4-linux-x86_64.tar.xz
[2] https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
[3] https://aur.archlinux.org/packages/futhark-nightly/

**Comment by athas** [comment]
Sure, that should be possible.  I actually left them out because I thought nobody would really use them anyway (at least the commit-id), but it appears I was wrong!

**Comment by mbloms** [comment]
Knowing `commit-id` is very useful when installing nightly with a package manager. I include it in the package version.
```
micke@Wrynn ~> pacman -Qi futhark-nightly 
Name            : futhark-nightly
Version         : 0.15.0.r3df95a0-1
Description     : A data-parallel functional programming language
Architecture    : x86_64
URL             : https://github.com/diku-dk/futhark
Licenses        : ISC
Groups          : None
Provides        : futhark
Depends On      : ncurses5-compat-libs  zlib  gmp
Optional Deps   : opencl-headers: opencl support
                  ocl-icd: opencl support
                  opencl-driver: opencl support [installed]
Required By     : None
Optional For    : None
Conflicts With  : futhark
Replaces        : None
Installed Size  : 63,32 MiB
Packager        : Mikael Blomstrand <kmbloms@gmail.com>
Build Date      : fre 14 feb 2020 12:24:38
Install Date    : tis 21 apr 2020 13:17:23
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

This way I know `futhark-nightly-0.15.0.r3df95a0` is different from `futhark-nightly-0.15.0.rf92a5ee`.

**Comment by mbloms** [comment]
Actually what would be even more convenient would be to have `commit-id` contain the output of `git describe --long --tags`. That format is compatible with git so that it can be used instead of a simple hash, but it is makes for much better version id's than simple hashes.
```
$ git describe --tags --long
v0.15.4-29-g791b5dc71
```

**Comment by athas** [comment]
The tarballs now contain `LICENSE` and `commit-id`, with the latter containing the output of `git describe --tags --long`.  I won't change the released tarballs, but the new nightly is ready, and I plan another proper release within a few days anyway.

**Comment by mbloms** [comment]
Perfect :ok_hand:
