### ISSUE TITLE
More informative futhark bench output

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#947]
I think the current `futhark bench` output format elides useful information and is simultaneously too verbose.  I suggest a new format (without changing the actual collection method or the `--json` output, so all derived tooling willstill work).

Old:

```
dataset data/small.in:     4614.30μs (avg. of 10 runs; RSD: 0.05)
```

New:

```
data/small.in:     <MIN>μs 4614.30μs <MAX>μs (RSD: 0.05)
```

That is, show both the minimum and maximum runtimes, as well as the average.  Rust bolds the average to make it more visible.  An alternative format could be:

```
data/small.in:     4614.30μs (min: ...; max: ...; RSD: 0.05)
```

**Comment by flip111** [comment]
Have a look at http://www.serpentine.com/criterion/tutorial.html such output would also be interesting.

**Comment by athas** [comment]
I like criterion's measuring methodology, but I've never been a fan of its very verbose output.  I like having one data point on every line.
