### ISSUE TITLE
This does not fuse as expected

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#953]
```
let main [n] (xs: [n]i32): [n]i32 =
  let num x = x&1
  let pairwise op (a1,b1) (a2,b2) =
    (a1 `op` a2, b1 `op` b2)
  let bins = xs |> map num
  let flags = bins |> map (\x -> if x == 0 then (1,0) else (0,1))
  let offsets = scan (pairwise (+)) (0,0) flags
  let f bin (a,b) = match bin
                    case 0 -> a-1
                    case 1 -> (last offsets).0+b-1
  let is = map2 f bins offsets
  in scatter (copy xs) is xs
```

This program produces a `map`, `scan`, and `scatter`.  It should just be a `scan` and `scatter`.

The root cause is that fusion treats `Copy` as a `map`, which is then horizontally fused with the `scan`.  I'm not sure what the best solution is.  Maybe just disabling horizontal fusion for `Copy`.

**Comment by flip111** [comment]
What was the solution you settled on?

**Comment by athas** [comment]
No longer fusing `copy` at all.
