### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by TobiasRoikjer** [diku-dk/futhark#985]
The lack of syntax highlighting on GitHub and editors makes it hard to get into Futhark. I have looked into obtaining syntax highlighting on GitHub for .fut files. One way is to get linguistic, the GitHub formatter and parser, to see .fut as another programming language, e.g. Ada. It works only sporadically and sometimes you have to refresh the page many times for it to highlight (yea... I don't understand it either). You can see it at [my fork](https://github.com/TobiasRoikjer/futhark/blob/syntax-highlighting/examples/rosettacode/for.fut). I don't know if Ada is the right language, but placing a `.vimrc` file with the contents

```
vim: set syntax=Ada:
vim: set filetype=Ada:
```
gives that results.

Secondly, is there some easy way of obtaining the CFG to create a syntax highlighter for e.g. IntelliJ?

  - [ ] - Show syntax highlighting for Futhark on GitHub
  - [ ] - Create syntax highlighting for editors

**Comment by athas** [comment]
Regarding GitHub, [there is an upstream pull request](https://github.com/github/linguist/pull/4842).  For other editors, that's already in progress.  To my knowledge, there are syntax definitions for Emacs, Vim, gedit, Atom, and VS Code.  I have no idea how good they are (except for the Emacs mode, which I use myself).

I'm not sure what you mean by CFG.  There is an [EBNF description of the grammar](https://futhark.readthedocs.io/en/latest/language-reference.html), which should be sufficient.

**Comment by TobiasRoikjer** [comment]
> Regarding GitHub, there is an upstream pull request. For other editors, that's already in progress. To my knowledge, there are syntax definitions for Emacs, Vim, gedit, Atom, and VS Code. I have no idea how good they are (except for the Emacs mode, which I use myself).

That sounds great. An intellij plugin seems like to only main editor not supported then!

> I'm not sure what you mean by CFG. There is an EBNF description of the grammar, which should be sufficient.
BNF yea, not CFG :) 

It seems like both of these things are handled! I'll close the issue

**Comment by Munksgaard** [comment]
For reference, here is the syntax highlighting for Atom: https://github.com/Alhadis/language-etc/blob/master/grammars/futhark.cson, which may or may not be used as the basis for syntax highlighting in other editors.
