### ISSUE TITLE
reverse >-> reverse returns garbage

### ISSUE THREAD

**Issue by Unigurd** [diku-dk/futhark#992]
The following program yields nonsense.
```
let main : []i32 -> []i32 = reverse >-> reverse
```
The first element is the same as for the input list, but the rest is buggy when compiled. Works in the repl.
I am using Futhark 0.15.8.

An example:
```
$ echo [1,2,3,4] | ./rev-rev
[1i32, 0i32, 33i32, 0i32]
```

**Comment by athas** [comment]
What in tarnation!  At least it looks like it's not about the function composition.
